force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Organisations</relationshipLabel>
    <relationshipName>Organisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Refund_Id__c.field-meta.xml
<CustomField>
    <fullName>Refund_Id__c</fullName>
    <description>This Field is Use to store the refund Id of the Stripe. If Refund request has been submitted by the customer.</description>
    <label>Refund Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Stripe_fees__c.field-meta.xml
<CustomField>
    <fullName>Stripe_fees__c</fullName>
    <label>Stripe fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Stripe_Payout_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Payout Id</label>
    <referenceTo>Stripe_Payout_Log__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/recordTypes/Payment_Transaction.recordType-meta.xml
<RecordType>
    <fullName>Payment_Transaction</fullName>
    <active>true</active>
    <label>Payment Transaction</label>
</RecordType>

force-app/main/default/objects/Payment__c/recordTypes/Refund.recordType-meta.xml
<RecordType>
    <fullName>Refund</fullName>
    <active>true</active>
    <label>Refund</label>
</RecordType>

force-app/main/default/objects/Stripe_Payout_Log__c/Stripe_Payout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object will store the Payout logs whenever the payout is created in the stripe.</description>
    <label>Stripe Payout Log</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Stripe Payout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Payout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Stripe Payout Logs</relationshipLabel>
    <relationshipName>Stripe_Payout_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This Field will store the Status of the payout object in stripe.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unprocessed</fullName>
                <default>true</default>
                <label>Unprocessed</label>
            </value>
            <value>
                <fullName>Processed in SF</fullName>
            </value>
            <value>
                <fullName>Posted in Sage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Stripe_Payout_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Id__c</fullName>
    <description>This Field will store the Stripe Payout Id from the Stripe</description>
    <label>Stripe Payout Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FetchBalanceTransactionsQueueable.cls
public class FetchBalanceTransactionsQueueable implements Queueable, Database.AllowsCallouts {
    private String stripePayoutId;
    private String starting_afterId = '';
    private Id payoutId;
    private Integer limitOfRecords;
    private String apiKey;
    private Stripe_Payout_Log__c payoutObj;
    private Id paymentTransactionRcTypeId = Schema.SObjectType.Payment__c.getRecordTypeInfosByDeveloperName().get('Payment_Transaction').getRecordTypeId();
    private Id refundPaymentRcTypeId = Schema.SObjectType.Payment__c.getRecordTypeInfosByDeveloperName().get('Refund').getRecordTypeId();
    
    //Constructor used first to invoke queueable
    public FetchBalanceTransactionsQueueable(Id payoutId, Integer limitOfRecords){
        this.payoutId = payoutId;
        List<Stripe_Payout_Log__c> stripePayoutLogList = [SELECT Id, Stripe_Payout_Id__c, Organisation__r.Country__r.Stripe_Secret_Key__c, Status__c FROM Stripe_Payout_Log__c WHERE Id=: payoutId];

        if(stripePayoutLogList != NULL && stripePayoutLogList.size()>0){
            this.payoutObj = stripePayoutLogList[0];
            this.stripePayoutId = stripePayoutLogList[0].Stripe_Payout_Id__c;
            this.apiKey = stripePayoutLogList[0].Organisation__r.Country__r.Stripe_Secret_Key__c;
        }
        this.limitOfRecords = limitOfRecords;
    }
    
    //Constructor used to chain jobs, accepts last id of limited retrieved records
    public FetchBalanceTransactionsQueueable(Id payoutId, Integer limitOfRecords, String starting_afterId){
        this.payoutId = payoutId;
        List<Stripe_Payout_Log__c> stripePayoutLogList = [SELECT Id, Stripe_Payout_Id__c, Organisation__r.Country__r.Stripe_Secret_Key__c, Status__c FROM Stripe_Payout_Log__c WHERE Id=: payoutId];
        if(stripePayoutLogList != NULL && stripePayoutLogList.size()>0){
            this.payoutObj = stripePayoutLogList[0];
            this.stripePayoutId = stripePayoutLogList[0].Stripe_Payout_Id__c;
            this.apiKey = stripePayoutLogList[0].Organisation__r.Country__r.Stripe_Secret_Key__c;
        }
        this.limitOfRecords = limitOfRecords;
        this.starting_afterId = starting_afterId;
    }
    
    public void execute(QueueableContext context){
        System.debug('apiKey '+apiKey);
        if(String.isNotBlank(apiKey)){
            System.debug('apiKey '+apiKey);
            String baseurl = 'https://api.stripe.com';
            String transactionUrl = baseurl+'/v1/balance_transactions';
            
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            if(starting_afterId != ''){
                request.setEndpoint(transactionUrl+'?payout='+stripePayoutId+'&limit='+limitOfRecords+'&starting_after='+starting_afterId);
                System.debug('called with starting after id');
            }
            else{
                request.setEndpoint(transactionUrl+'?payout='+stripePayoutId+'&limit='+limitOfRecords);
                System.debug('called without starting after id');
            }
            request.setMethod('GET');
            
            Blob headerValue = Blob.valueOf(apiKey);
            String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
            request.setHeader('Authorization', authorizationHeader);
            
            HttpResponse response = http.send(request);
            System.debug('response '+response.getBody());
            System.debug(response.getStatusCode());
            if(response.getStatusCode() == 200){
                String respStr = response.getBody();
                respStr = cleanJson(respStr);
                BalanceTransactionWrapper balTransaction = (BalanceTransactionWrapper) System.JSON.deserialize(respStr, BalanceTransactionWrapper.class);
                system.debug('@@balTransaction'+balTransaction);
                
                if(balTransaction != NULL && balTransaction.data != null){ //if any record exists
                    String endingObjId = balTransaction.data.get(balTransaction.data.size()-1).id; //store last object's id for future use
                    Map<String, Decimal> mapTransactionToFee = new Map<String, Decimal>();
                    Map<String, Decimal> mapRefundToFee = new Map<String, Decimal>();
                    
                    for(DataWrapper data: balTransaction.data){
                        if(data.source != null && data.stripeType != null){
                            Map<String, Decimal> mapTypeToFee = new Map<String, Decimal>();
                            if(data.stripeType == 'charge'){
                                if(data.fee > 0){ //stripe fee must always be negative in this case
                                    data.fee = data.fee * -1;
                                }
                                
                                Decimal fee = data.fee/100;
                                mapTransactionToFee.put(data.source, fee);
                            }
                            else if(data.stripeType == 'refund'){
                                if(data.fee < 0){ //stripe fee must always be positive in this case
                                    data.fee = data.fee * -1;
                                }
                                
                                Decimal fee = data.fee/100;
                                mapRefundToFee.put(data.source, fee);
                            }
                        }
                    }
                    
                    //update Payment records on the basis of source, as received from http response
                    if(!mapTransactionToFee.isEmpty() || !mapRefundToFee.isEmpty()){
                        List<Payment__c> paymentList = [SELECT Id, Stripe_Payout_Id__c, Stripe_fees__c, Transaction_ID__c, RecordTypeId, Refund_Id__c FROM Payment__c WHERE (Transaction_ID__c IN: mapTransactionToFee.KeySet() OR Refund_Id__c IN: mapRefundToFee.KeySet()) AND (RecordTypeId =: paymentTransactionRcTypeId OR RecordTypeId =: refundPaymentRcTypeId)];
                        System.debug(paymentList);
                        if(paymentList != NULL && paymentList.size()>0){
                            for(Payment__c paymentObj: paymentList){
                                paymentObj.Stripe_Payout_Id__c = payoutId;
                                if(!mapTransactionToFee.isEmpty() && mapTransactionToFee.containsKey(paymentObj.Transaction_ID__c)){
                                    paymentObj.Stripe_fees__c = mapTransactionToFee.get(paymentObj.Transaction_ID__c);
                                }
                                else if(!mapRefundToFee.isEmpty() && mapRefundToFee.containsKey(paymentObj.Refund_Id__c)){
                                    paymentObj.Stripe_fees__c = mapRefundToFee.get(paymentObj.Refund_Id__c);
                                }
                            }
                            
                            update paymentList;
                        }
                    }
                    
                    if(balTransaction.has_more){ //if more records exist
                        //Chain another job that will fetch records after the last record retrieved
                        System.enqueueJob(new FetchBalanceTransactionsQueueable(payoutId, limitOfRecords, endingObjId));
                    }
                    else{
                        System.debug('has more false');
                        payoutObj.Status__c = 'Processed in SF';
                        System.debug(payoutObj);
                        update payoutObj;
                    }
                }
            }
        }
    }
    
    //this method is used to correct JSON such that it can be deserialized with apex
    public static String cleanJson(String json){
        json = json.replaceAll('"currency":', '"stripeCurrency":');
        json = json.replaceAll('"type":', '"stripeType":');
        
        return json;
    }
    
    public class BalanceTransactionWrapper{
        public List<DataWrapper> data;
        public Boolean has_more;
    }
    
    public class DataWrapper{
        public String id;
        public Decimal amount;
        public String stripeCurrency;
        public String description;
        public Decimal fee;
        public List<FeeDetailsWrapper> fee_details;
        public String source;
        public String stripeType;
    }
    
    public class FeeDetailsWrapper{
        public Decimal amount;
        public String stripeCurrency;
        public String description;
        public String stripeType; 
    }
}