force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Referral_Discount__c/Referral_Discount__c.object-meta.xml
<CustomObject>
    <label>Referral Discount</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Discount__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Discount__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Referral Discounts</relationshipLabel>
    <relationshipName>Referral_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Discount__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Discount__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <label>Default</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral_Discount__c/fields/Discount_Amount_Referee__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount_Referee__c</fullName>
    <description>This field is used to store discount amount of referee</description>
    <inlineHelpText>To work out the price without GST you have to divide the amount by 1. (Tax Rate) i.e. 1.07. E.g. ($214/1.07=$200)</inlineHelpText>
    <label>Discount Amount (Referee)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Referral_Discount__c/fields/Discount_Amount_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount_Referrer__c</fullName>
    <description>This field is used to store the Discount amount of Referrer</description>
    <inlineHelpText>To work out the price without GST you have to divide the amount by 1. (Tax Rate) i.e. 1.07. E.g. ($214/1.07=$200)</inlineHelpText>
    <label>Discount Amount (Referrer)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestSpecialReferralDiscountBatchSheduler.cls
/*
Name        :        TestSpecialReferralDiscountBatchSheduler
Date        :       12 Aug 2020
Author      :       
Description :       It is a Test Class for specialReferralDiscountBatchSheduler and specialReferralDiscountBatch
*/
@isTest
public class TestSpecialReferralDiscountBatchSheduler {
    @testSetup
    private static void setupMethod(){
        Country__c country = new Country__c();
        country.Name = 'SGD';
        country.Country_Name__c = 'India';
        country.Tax_Rate__c = 7.0;
        country.Currency_Code__c = 'SGD';
        country.Student_Policies_Template_Id__c = 'test';
        country.Stripe_Base_Url__c = 'www.test.com';
        country.Stripe_Publishable_Key__c = 'ABC';
        country.Stripe_Secret_Key__c = 'deede';
        insert country;
        
        Referral_Discount__c referral_discount = new Referral_Discount__c();
        referral_discount.Name = 'Special. Referral (SG)';
        referral_discount.Discount_Amount_Referrer__c = 93.46;
        referral_discount.Discount_Amount_Referee__c = 93.46;
        referral_discount.Start_Date__c = system.today();
        referral_discount.End_Date__c = Date.newInstance(2020,09,15);
        referral_discount.Country__c = country.Id;
        referral_discount.Default__c = 'No';
        referral_discount.Active__c = 'Yes';
        insert referral_discount;
        
        
        
    }
    @isTest
    private static void unitTest1(){
        Referral_Discount__c referral_discount = [SELECT id,name,Discount_Amount_Referrer__c,Discount_Amount_Referee__c,Start_Date__c,End_Date__c
                                                  ,Country__c,Default__c,Active__c from Referral_Discount__c LIMIT 1];
        Test.startTest();
        specialReferralDiscountBatch obj = new specialReferralDiscountBatch();
        Database.executeBatch(obj);
        referral_discount.Start_Date__c = system.today() - 2;
        referral_discount.End_Date__c = system.today() - 1;
    }
    @isTest
    private static void unitTest2(){
        Referral_Discount__c referral_discount = [SELECT id,name,Discount_Amount_Referrer__c,Discount_Amount_Referee__c,Start_Date__c,End_Date__c
                                                  ,Country__c,Default__c,Active__c from Referral_Discount__c LIMIT 1];
        Test.startTest();
        
        referral_discount.Start_Date__c = system.today() - 2;
        referral_discount.End_Date__c = system.today() - 1;
        update referral_discount;
        specialReferralDiscountBatch obj = new specialReferralDiscountBatch();
        Database.executeBatch(obj);
        specialReferralDiscountBatchSheduler sheduler = new specialReferralDiscountBatchSheduler();
        sheduler.execute(null);
        
    }
}