force-app/main/default/objects/Case/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <formula>IF(Text(Enrolment__r.Effective_Date__c) = NULL ,&apos;&apos;,CASE(
  MOD( Enrolment__r.Effective_Date__c - DATE( 1900, 1, 7 ), 7 ),
  0, &quot;Sun&quot;,
  1, &quot;Mon&quot;,
  2, &quot;Tue&quot;,
  3, &quot;Wed&quot;,
  4, &quot;Thur&quot;,
  5, &quot;Fri&quot;, 
  &quot;Sat&quot;
)+&apos;, &apos;+ Text(Day(Enrolment__r.Effective_Date__c)) +&apos; &apos;+CASE(
  MONTH( Enrolment__r.Effective_Date__c),
  1, &quot;Jan&quot;,
  2, &quot;Feb&quot;,
  3, &quot;Mar&quot;,
  4, &quot;Apr&quot;,
  5, &quot;May&quot;,
  6, &quot;Jun&quot;,
  7, &quot;Jul&quot;,
  8, &quot;Aug&quot;,
  9, &quot;Sep&quot;,
  10, &quot;Oct&quot;,
  11, &quot;Nov&quot;,
  &quot;Dec&quot;
)+&apos; &apos;+ Text(Year(Enrolment__r.Effective_Date__c)) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Effective Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Add &apos;Duplicate&apos; and &apos;Enquiry Lost&apos; on Nov 4th to capture more Statistic
These values will be used in Pardot going forward
Requested By: Alex and Yunshi</description>
    <label>Sales Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Trial Requested</fullName>
            </value>
            <value>
                <fullName>Trial Booked</fullName>
            </value>
            <value>
                <fullName>Trial Cancelled</fullName>
            </value>
            <value>
                <fullName>Trial No Show</fullName>
            </value>
            <value>
                <fullName>Trial Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Enquiry Lost</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Package_Name__c.field-meta.xml
<CustomField>
    <fullName>Package_Name__c</fullName>
    <formula>Package__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Status__c</fullName>
    <label>Advance Action Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Type__c</fullName>
    <label>Advance Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Enrolment Change</fullName>
            </value>
            <value>
                <fullName>Centre Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <label>Lesson</label>
</RecordType>

force-app/main/default/classes/ComplimentaryCreditExpiryBatch.cls
/*
    Name : ComplimentaryCreditExpiryBatch
    Desription :  a.	Identify all those Complimentary Credit  whose makeup credit is expiry soon 
                    b. In case of withdrawal, all complimentary credit will expire on the last lesson date
    Author : Nishi Jain
    Date : 25-Feb-2021
*/
global with sharing class ComplimentaryCreditExpiryBatch implements Database.Batchable<sObject>,database.stateful,Database.AllowsCallouts{
    global Date complimentaryEffectiveDate;
    global ComplimentaryCreditExpiryBatch (date complimentaryEffectiveDate){
       this.complimentaryEffectiveDate = complimentaryEffectiveDate;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Credit_Apply_date__c, Credit_Expiry_date__c, Credit_Reason__c, Enrolment__c, Teacher_Name__c, Parent__c, Available_credit_Min__c,
                                            Package_Name__c, Is_Active__c, Name, Id,Enrolment__r.stage__c,Enrolment__r.Type__c,
                                            Enrolment__r.Package_Process_Status__c,Enrolment__r.Package_Process_Type__c,Enrolment__r.effective_Date__c
                                            FROM Complementary_Credit__c 
                                            WHERE  Parent__c != null
                                            And Credit_Expiry_date__c != null 
                                            And Credit_Apply_date__c != null
                                        ]);
                                
    }
    
    global void execute(Database.BatchableContext BC, List<Complementary_Credit__c> listOfComplementaryCredit){
        Set<String> setOfParentIds = new Set<String>();
        for(Complementary_Credit__c objComplementaryCredit : listOfComplementaryCredit){
                setOfParentIds.add(objComplementaryCredit.Parent__c);
        }
        Map<String, Boolean> mapOfActiveParent = new Map<String, Boolean>();
        mapOfActiveParent = checkParentHasMultipleEnrolments(setOfParentIds, complimentaryEffectiveDate);
        Map<String, Date> mapOfParentCancelEnrolment  = getParentCancelEnrolmentsDate(setOfParentIds);
        system.debug('listOfComplementaryCredit'+listOfComplementaryCredit);
        system.debug('mapOfActiveParent'+mapOfActiveParent);
        system.debug('mapOfParentCancelEnrolment'+mapOfParentCancelEnrolment);
        for(Complementary_Credit__c objComplementaryCredit : listOfComplementaryCredit){
            system.debug('mapOfParentCancelEnrolment'+mapOfParentCancelEnrolment.containsKey(objComplementaryCredit.Parent__c));
            system.debug('mapOfParentCancelEnrolment'+mapOfParentCancelEnrolment.get(objComplementaryCredit.Parent__c));
            if(!mapOfActiveParent.containsKey(objComplementaryCredit.Parent__c) && mapOfParentCancelEnrolment.containsKey(objComplementaryCredit.Parent__c)){
                objComplementaryCredit.Credit_Expiry_date__c = mapOfParentCancelEnrolment.get(objComplementaryCredit.Parent__c);
            }
            if(objComplementaryCredit.Is_Active__c && objComplementaryCredit.Credit_Expiry_date__c != null && objComplementaryCredit.Credit_Expiry_date__c <=  complimentaryEffectiveDate){
                objComplementaryCredit.Is_Active__c = false;
            }else if(!objComplementaryCredit.Is_Active__c && objComplementaryCredit.Credit_Apply_date__c != null && objComplementaryCredit.Credit_Apply_date__c <=  complimentaryEffectiveDate){
                objComplementaryCredit.Is_Active__c = true;
            }
        }
        update listOfComplementaryCredit;

    }

    //check that the Parent Has other Enrolments or Not
    public static Map<String, Boolean> checkParentHasMultipleEnrolments(Set<String> parentIds, Date lastDate){
        Map<String, Boolean> mapOfParentActiveEnrolment = new Map<String, Boolean>();
        Boolean flag = false;
        Set<String>  enrolTypes = New Set<String>{ConstantsClass.enrolRegularStatus,ConstantsClass.enrolGroupType};
        for(Enrolment__c enrolObj : [SELECT Id, Parent__c FROM Enrolment__c
                                        WHERE Parent__c IN :parentIds 
                                        AND ((Stage__c = :ConstantsClass.enroledStatus 
                                                AND Type__c In: enrolTypes
                                                AND (Package_Process_Type__c != :ConstantsClass.enrollmentProcessCancelType 
                                                    OR Effective_Date__c > :lastDate)
                                                )
                                            )]){
            mapOfParentActiveEnrolment.put(enrolObj.Parent__c, TRUE);
        }
        return mapOfParentActiveEnrolment;
    }

    //check that the Parent Has other Enrolments or Not
    public static Map<String, Date> getParentCancelEnrolmentsDate(Set<String> parentIds){
        Map<String, Date> mapOfParentCancelEnrolment = new Map<String, Date>();
        Boolean flag = false;
        Set<String>  enrolstage = New Set<String>{ConstantsClass.enroledStatus,'Cancelled'};
        Set<String>  enrolTypes = New Set<String>{ConstantsClass.enrolRegularStatus,ConstantsClass.enrolGroupType};
        for(Enrolment__c enrolObj : [SELECT Id, Parent__c,Effective_Date__c FROM Enrolment__c
                                        WHERE Parent__c IN :parentIds 
                                        AND Type__c In:enrolTypes
                                        AND  Stage__c In: enrolstage
                                        AND Package_Process_Type__c = :ConstantsClass.enrollmentProcessCancelType 
                                        and Effective_Date__c != null
                                        order by Effective_Date__c desc
                                    ]){
                                        if(!mapOfParentCancelEnrolment.containsKey(enrolObj.Parent__c)){
                                            mapOfParentCancelEnrolment.put(enrolObj.Parent__c, enrolObj.Effective_Date__c);
                                        }
        }
        return mapOfParentCancelEnrolment;
    }

    global void finish(Database.BatchableContext BC){
   
    }
}