force-app/main/default/objects/Case/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Add &apos;Duplicate&apos; and &apos;Enquiry Lost&apos; on Nov 4th to capture more Statistic
These values will be used in Pardot going forward
Requested By: Alex and Yunshi</description>
    <label>Sales Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Trial Requested</fullName>
            </value>
            <value>
                <fullName>Trial Booked</fullName>
            </value>
            <value>
                <fullName>Trial Cancelled</fullName>
            </value>
            <value>
                <fullName>Trial No Show</fullName>
            </value>
            <value>
                <fullName>Trial Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Enquiry Lost</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Trial_No_Show_Date__c.field-meta.xml
<CustomField>
    <fullName>Trial_No_Show_Date__c</fullName>
    <label>Trial No Show Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrialNoShowTaskSchedulerTest.cls
/*
Name        :        TrialNoShowTaskSchedulerTest
Date        :        21,22 April 2019
Author      :        Karan Singh Soni
Description :        It is the test class of TrialNoShowTaskScheduler.
*/

@isTest
public class TrialNoShowTaskSchedulerTest {
    public Static testMethod void invokeTrialNoShowTaskScheduler(){
         Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        User usr = new User(LastName = 'Singh',
                            FirstName='Karan',
                            Alias = 'Singh',
                            Email = 'Karan1.liveston@asdf.com',
                            Username = 'Karan1.liveston@asdf.com',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US'
                           );
        
        insert usr;
        System.runAs(usr){
            Case objCase=testUtil.createCase(false);
            objCase.RecordTypeId=Schema.SObjectType.case.getRecordTypeInfosByName().get(ConstantsClass.caseSalesEnqRecTypeName).getRecordTypeId();
            objcase.Stage__c='Trial No Show';
            objCase.Status='Open';
            objcase.Trial_No_Show_Date__c=system.today().addDays(-2);
            objCase.Enrolment__c=testUtil.createEnrolment(true).id;
            objCase.OwnerId=usr.Id;
            insert objcase;
            
           TrialNoShowTaskScheduler objTrialNoShow = new TrialNoShowTaskScheduler();
            objTrialNoShow.execute(Null);
        }
        
    }
    
    public Static testMethod void invokeTrialNoShowTaskScheduler2(){
         Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        User usr = new User(LastName = 'Singh',
                            FirstName='Karan',
                            Alias = 'Singh',
                            Email = 'Karan1.liveston@asdf.com',
                            Username = 'Karan1.liveston@asdf.com',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US'
                           );
        
        insert usr;
        System.runAs(usr){
            Case objCase=testUtil.createCase(false);
            objCase.RecordTypeId=Schema.SObjectType.case.getRecordTypeInfosByName().get(ConstantsClass.caseSalesEnqRecTypeName).getRecordTypeId();
            objcase.Stage__c='Trial No Show';
            objCase.Status='Open';
            objcase.Trial_No_Show_Date__c=system.today().addDays(-4);
            objCase.Enrolment__c=testUtil.createEnrolment(true).id;
            objCase.OwnerId=usr.Id;
            insert objcase;
            
           TrialNoShowTaskScheduler objTrialNoShow = new TrialNoShowTaskScheduler();
            objTrialNoShow.execute(Null);
        }
        
    }
    public Static testMethod void invokeTrialNoShowTaskScheduler3(){
         Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        User usr = new User(LastName = 'Singh',
                            FirstName='Karan',
                            Alias = 'Singh',
                            Email = 'Karan1.liveston@asdf.com',
                            Username = 'Karan1.liveston@asdf.com',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US'
                           );
        
        insert usr;
        System.runAs(usr){
            Case objCase=testUtil.createCase(false);
            objCase.RecordTypeId=Schema.SObjectType.case.getRecordTypeInfosByName().get(ConstantsClass.caseSalesEnqRecTypeName).getRecordTypeId();
            objcase.Stage__c='Trial No Show';
            objCase.Status='Open';
            objcase.Trial_No_Show_Date__c=system.today().addDays(-7);
            objCase.Enrolment__c=testUtil.createEnrolment(true).id;
            objCase.OwnerId=usr.Id;
            insert objcase;
            
           TrialNoShowTaskScheduler objTrialNoShow = new TrialNoShowTaskScheduler();
            objTrialNoShow.execute(Null);
        }
        
    }
     public Static testMethod void invokeTrialNoShowTaskScheduler4(){
         Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        User usr = new User(LastName = 'Singh',
                            FirstName='Karan',
                            Alias = 'Singh',
                            Email = 'Karan1.liveston@asdf.com',
                            Username = 'Karan1.liveston@asdf.com',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US'
                           );
        
        insert usr;
        System.runAs(usr){
            Case objCase=testUtil.createCase(false);
            objCase.RecordTypeId=Schema.SObjectType.case.getRecordTypeInfosByName().get(ConstantsClass.caseSalesEnqRecTypeName).getRecordTypeId();
            objcase.Stage__c='Trial No Show';
            objCase.Status='Open';
            objcase.Trial_No_Show_Date__c=system.today().addDays(-10);
            objCase.Enrolment__c=testUtil.createEnrolment(true).id;
            objCase.OwnerId=usr.Id;
            insert objcase;
            
           TrialNoShowTaskScheduler objTrialNoShow = new TrialNoShowTaskScheduler();
            objTrialNoShow.execute(Null);
        }
        
    }
}