force-app/main/default/objects/Employee_Work_Week__c/Employee_Work_Week__c.object-meta.xml
<CustomObject>
    <label>Employee Work Week</label>
    <nameField>
        <displayFormat>EW-{0000}</displayFormat>
        <label>Employee Work Week No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Work Week</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Work_Week__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee, Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Work Week</relationshipLabel>
    <relationshipName>Employee_Work_Week</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Working_Days_in_a_Week__c.field-meta.xml
<CustomField>
    <fullName>Working_Days_in_a_Week__c</fullName>
    <formula>IF(ISPICKVAL(Monday__c,&apos;Full Day&apos;),1,IF(ISPICKVAL(Monday__c,&apos;Half Day&apos;),0.5,0))
+
IF(ISPICKVAL(Tuesday__c,&apos;Full Day&apos;),1,IF(ISPICKVAL(Tuesday__c,&apos;Half Day&apos;),0.5,0))
+
IF(ISPICKVAL(Wednesday__c,&apos;Full Day&apos;),1,IF(ISPICKVAL(Wednesday__c,&apos;Half Day&apos;),0.5,0))
+
IF(ISPICKVAL(Thursday__c,&apos;Full Day&apos;),1,IF(ISPICKVAL(Thursday__c,&apos;Half Day&apos;),0.5,0))
+
IF(ISPICKVAL(Friday__c,&apos;Full Day&apos;),1,IF(ISPICKVAL(Friday__c,&apos;Half Day&apos;),0.5,0))
+
IF(ISPICKVAL(Saturday__c,&apos;Full Day&apos;),1,IF(ISPICKVAL(Saturday__c,&apos;Half Day&apos;),0.5,0))
+
IF(ISPICKVAL(Sunday__c,&apos;Full Day&apos;),1,IF(ISPICKVAL(Sunday__c,&apos;Half Day&apos;),0.5,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Working Days in a Week</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EmployeeWorkWeekTrigerHandler.cls
public class EmployeeWorkWeekTrigerHandler{

    /*  Employee Work Week - Functionality Description - Create Rostering record when a Employee Work Week record create/Update.*/
    Id employeeRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Employee').getRecordTypeId();
    List<Employee_Work_Week__c> newList = new List<Employee_Work_Week__c >();
    Map<Id,Employee_Work_Week__c> oldMap = new Map<Id,Employee_Work_Week__c>();
    Integer rosteringForNumberofMonth = 3;
    
    public void EmployeeWorkWeekAfterInsert(){
        newList = (List<Employee_Work_Week__c>) trigger.new;
        oldMap = (Map<Id,Employee_Work_Week__c>)trigger.oldMap;
        EmployeeWorkWeekRosteringSetup();
    }
    public void EmployeeWorkWeekAfterUpdate(){
        newList = (List<Employee_Work_Week__c>) trigger.new;
        oldMap = (Map<Id,Employee_Work_Week__c>)trigger.oldMap;
        EmployeeWorkWeekRosteringSetup();
    }
    public void EmployeeWorkWeekAfterDelete(){
        newList = (List<Employee_Work_Week__c>) trigger.old;
        oldMap = null;
        EmployeeWorkWeekRosteringSetup();
    }
    public void EmployeeWorkWeekAfterUnDelete(){
        newList = (List<Employee_Work_Week__c>) trigger.new;
        oldMap = null;
        EmployeeWorkWeekRosteringSetup();
    }
    
    
    public void EmployeeWorkWeekRosteringSetup(){
        Set<Id> accountIdSet = new Set<Id>();
        // Pre process of data
        for(Employee_Work_Week__c eww : newList){
            if((oldMap == null || oldMap != null && (oldMap.get(eww.Id).Effective_Date__c != eww.Effective_Date__c || oldMap.get(eww.Id).Working_Days_in_a_Week__c != eww.Working_Days_in_a_Week__c))){
                accountIdSet.add(eww.Employee__c);
            }
        }
        if(!accountIdSet.isEmpty()){
            Id jobId = Database.executeBatch(new EmployeeRosteringBatch(accountIdSet, rosteringForNumberofMonth), 200);
        }
    }
}