force-app/main/default/objects/Stripe_Payout_Log__c/Stripe_Payout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object will store the Payout logs whenever the payout is created in the stripe.</description>
    <label>Stripe Payout Log</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Stripe Payout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Payout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This Field will store the Status of the payout object in stripe.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unprocessed</fullName>
                <default>true</default>
                <label>Unprocessed</label>
            </value>
            <value>
                <fullName>Processed in SF</fullName>
            </value>
            <value>
                <fullName>Posted in Sage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FetchBalanceTransactionsScheduler.cls
/*
Name        :    FetchBalanceTransactionsScheduler
Date        :    18 October 2019
Author      :
Description :    Schedule FetchBalanceTransactionsQueueable to run daily at 12 AM.
*/


global class FetchBalanceTransactionsScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        for(Stripe_Payout_Log__c payoutObj: [SELECT Id FROM Stripe_Payout_Log__c WHERE Status__c = 'Unprocessed']){
            System.enqueueJob(new FetchBalanceTransactionsQueueable(payoutObj.Id, 200));
        }
    }   
}