force-app/main/default/objects/Leave_Entitlement__c/Leave_Entitlement__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Entitlement__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leave Entitlement</relationshipLabel>
    <relationshipName>Leave_Entitlement</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Leave_Entitlement__c/fields/Paid_Leave__c.field-meta.xml
<CustomField>
    <fullName>Paid_Leave__c</fullName>
    <label>Paid Leave</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Entitlement__c/fields/Remaining_Paid_Leaves__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Paid_Leaves__c</fullName>
    <formula>Paid_Leave__c +  Carry_forward_Paid_Leave__c + Additional_Paid_Leaves__c -  Used_Paid_Leaves__c</formula>
    <label>Remaining Paid Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Entitlement__c/fields/Remaining_Sick_Leaves__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Sick_Leaves__c</fullName>
    <formula>Sick_Leave__c - Used_Sick_Leaves__c</formula>
    <label>Remaining Sick Leaves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Entitlement__c/fields/Sick_Leave__c.field-meta.xml
<CustomField>
    <fullName>Sick_Leave__c</fullName>
    <label>Sick Leave</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Entitlement__c/fields/Used_Paid_Leaves__c.field-meta.xml
<CustomField>
    <fullName>Used_Paid_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Paid Leaves</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Entitlement__c/fields/Used_Sick_Leaves__c.field-meta.xml
<CustomField>
    <fullName>Used_Sick_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Sick Leaves</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeaveSummaryController.cls
/*
Name        :    LeaveSummaryController
Date        :    11 September 2019
Author      :    
*/

public class LeaveSummaryController{
    @AuraEnabled
    public static Leave_Entitlement__c getCurrentLeaveEntitlement(String recId){
        List<Leave_Entitlement__c> leaveEntList = [SELECT Id, Paid_Leave__c, Used_Paid_Leaves__c, Remaining_Paid_Leaves__c, Sick_Leave__c, Used_Sick_Leaves__c, Remaining_Sick_Leaves__c FROM Leave_Entitlement__c WHERE Start_Date__c <= TODAY AND End_Date__c >= TODAY AND Employee__c =: recId LIMIT 1];
        
        if(leaveEntList != NULL && leaveEntList.size()>0){
            return leaveEntList[0];
        }
        return null;
    }
}