force-app/main/default/objects/Salary_Detail__c/Salary_Detail__c.object-meta.xml
<CustomObject>
    <label>Salary Detail</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>Salary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salary Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Salary_Detail__c/fields/Basic_Salary__c.field-meta.xml
<CustomField>
    <fullName>Basic_Salary__c</fullName>
    <label>Basic Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Salary_Detail__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee, Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salary Details</relationshipLabel>
    <relationshipName>Salary_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalaryDetailTriggerTest.cls
@isTest
public class SalaryDetailTriggerTest {
    @isTest
    public static void test(){
        Account acc =new Account();
        acc.Name = 'test';
        insert acc;

        Salary_Detail__c sal = new Salary_Detail__c();
        sal.Basic_Salary__c = 123;
        sal.Employee_Name__c = acc.id;
        //sal.Effective_Date__c = system.today();
        insert sal;
        
        sal.Basic_Salary__c=1234;
        sal.Effective_Date__c = system.today().addDays(2);
        update sal;
        

        try {
            Salary_Detail__c sal1 = new Salary_Detail__c();
            sal1.Basic_Salary__c = 123;
            sal1.Employee_Name__c = acc.id;
            sal1.Effective_Date__c = system.today().addDays(2);
            insert sal1;
        } catch (DMLException e) {
            //System.assert(e.getMessage().contains('expected message'), 'message=' + e.getMessage());
        }
        
    }
}