force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Total_Deposit_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposit_Value__c</fullName>
    <label>Total Deposit Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Inv-Item-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Is_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Is_Deposit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deposit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateInvoiceAmountClass.cls
public class UpdateInvoiceAmountClass {
	
    public static void sumInvoiceLineAmount(List<Invoice_Line_Item__c> invList){
        // This trigger is updating the total Deposit Value on enrolment with the sum of amount on Invoice line item when isdeposit is true and status not = to (void,Cancelled)
        List<Enrolment__c> enrolList = new List<Enrolment__c>();
        set<Id> enrolId = new set<Id>();
        for(Invoice_Line_Item__c invObj:[select Id,Is_Deposit__c,Invoice__r.Status__c,Name,Invoice__c,Enrolment__c from Invoice_Line_Item__c where id in:invList]){
            if(invObj.Enrolment__c != null){
               enrolId.add(invObj.Enrolment__c); 
            }
        }
        system.debug('enrolId'+enrolId);
        List<Enrolment__c> enrolMentList = [Select Id,Total_Deposit_Value__c,(select Amount__c from Invoice_Line_Items__r where  (Invoice__r.Status__c !='Void' and Invoice__r.Status__c !='Cancelled') AND Is_Deposit__c =true) from Enrolment__c where Id in:enrolId];
        if(enrolMentList.size()>0){
            for(Enrolment__c enrObj:enrolMentList){
                system.debug('enrObj'+enrObj);
                decimal val =0;
                for(Invoice_Line_Item__c InvLineObj:enrObj.Invoice_Line_Items__r){
                    val += InvLineObj.Amount__c == null ? 0 :InvLineObj.Amount__c;
                }
                enrObj.Total_Deposit_Value__c=val;
                enrolList.add(enrObj);
            }
        }
        system.debug('enrolList'+enrolList);
        if(enrolList.size()>0){
            Update enrolList;
        }
        
        
    }
    
    public static void deleteInvoiceLineAmount(list<Invoice_Line_Item__c> invList){
          // This trigger is reducing  the total Deposit Value on enrolment with the  amount on Invoice line item when isdeposit is true and status not = to (void,Cancelled)
        List<Enrolment__c> enrolList = new List<Enrolment__c>();
        
        set<Id> enrolId = new set<Id>();
        for(Invoice_Line_Item__c inlineObj:invList){
            if(inlineObj.Enrolment__c != null){
                enrolId.add(inlineObj.Enrolment__c);
            }
        }
        system.debug('enrolIddelete'+enrolId);
        List<Enrolment__c> enrolMentList = [Select Id,Total_Deposit_Value__c,(select Amount__c from Invoice_Line_Items__r where  (Invoice__r.Status__c !='Void' and Invoice__r.Status__c !='Cancelled') AND Is_Deposit__c =true) from Enrolment__c where Id in:enrolId];
        if(enrolMentList.size()>0){
            for(Enrolment__c enrObj:enrolMentList){
                decimal val =0;
                for(Invoice_Line_Item__c InvLineObj:enrObj.Invoice_Line_Items__r){
                    val += InvLineObj.Amount__c == null ? 0 :InvLineObj.Amount__c;
                    //val += InvLineObj.Amount__c == null ? 0 :InvLineObj.Amount__c;
                   // enrObj.Total_Deposit_Value__c -=invList[0].Amount__c== null? 0 : invList[0].Amount__c;
                }
                enrObj.Total_Deposit_Value__c=val;
                enrolList.add(enrObj);
            }
        }
        system.debug('enrolListdelete'+enrolList);
        if(enrolList.size()>0){
            Update enrolList;
        }
    }
}