force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Delivery_Charges__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Charges__c</fullName>
    <description>this field for piano rental for manage customer Delivery charges</description>
    <label>Delivery Charges (2-way)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Selling_price__c.field-meta.xml
<CustomField>
    <fullName>Selling_price__c</fullName>
    <description>this field for piano rental for manage customer piano Selling Price</description>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stair_Charges__c.field-meta.xml
<CustomField>
    <fullName>Stair_Charges__c</fullName>
    <label>Stair Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Enrolment</fullName>
            </value>
            <value>
                <fullName>Studio Booking</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Inv-Item-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Is_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Is_Deposit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deposit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ConfirmRentalPurchaseControllerTest.cls
/*
Name        :        ConfirmRentalPurchaseControllerTest
Date        :        17 March 2020
Author      :        Jatin
Description :        It is the test class of ConfirmRentalPurchaseController.
*/
@isTest
public class ConfirmRentalPurchaseControllerTest {
    @testSetup
    private static  void createData(){
        PianoRentalTestHelper.createPianoRentalData();
    }
    private static testMethod void testRentalSummary(){
        List<Enrolment__c> lstEnrolments = [SELECT Id FROM Enrolment__c limit 1];
        lstEnrolments[0].Delivery_Charges__c = 50;
        lstEnrolments[0].Stair_Charges__c = 5;
        lstEnrolments[0].Selling_price__c = 100;
        
        update lstEnrolments[0];
        
        test.startTest();
        PageReference pageRef = Page.ConfirmRentalPurchasePage; // Add your VF page Name here
        pageRef.getParameters().put('Id',lstEnrolments[0].id);
        Test.setCurrentPage(pageRef);
        ConfirmRentalPurchaseController objController = new ConfirmRentalPurchaseController();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(201,'{ "id": "msFYActMfJHqNTKH8YSvF1", "status": "document.uploaded", "name": "API Sample Document from PandaDoc Template", "date_created": "2018-08-02T08:42:13.836022Z", "date_modified": "2018-08-02T08:42:13.836022Z", "expiration_date": null, "uuid": "msFYActMfJHqNTKH8YSvF1" }'));
        objController.signAgreement();
        objController.isSignAgreement();
        objController.waitAgreement();
        objController.sendAgreement();
        objController.createSession();
        test.stopTest();
        objController.signAgreementRentalPurchase(lstEnrolments[0].id);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'{"paid": true}'));
        objController.getPaymentForInvoices();
        objController.createAttachmentForEmail();
    }
    //for insert Current month rental invoice testMethod
    private static testMethod void testRentalSummary2(){
        List<Enrolment__c> lstEnrolments = [SELECT Id FROM Enrolment__c limit 1];
        List<Invoice_Line_Item__c>lstInvoiceLineItems = [SELECT Is_Deposit__c,Invoice__r.Status__c,Enrolment__c,Invoice__r.Invoice_Type__c,Invoice__r.Due_Date__c
                                                         from Invoice_Line_Item__c
                                                         Where Enrolment__c =: lstEnrolments[0].id
                                                        ];
        List<Invoice__c>lstInvoice = new List<Invoice__c>();
        lstInvoiceLineItems[0].Is_Deposit__c = true;
        lstInvoiceLineItems[0].Amount__c =100;
        lstInvoiceLineItems[0].Invoice__r.Status__c = 'Paid';
        lstInvoiceLineItems[0].Invoice__r.Invoice_Type__c =ConstantsClass.recurringInvoiceType;
        
        lstInvoice.add(lstInvoiceLineItems[0].Invoice__r);
        update lstInvoice;
        
        lstEnrolments[0].Delivery_Charges__c = 50;
        lstEnrolments[0].Stair_Charges__c = 5;
        lstEnrolments[0].Selling_price__c = 100;
        
        update lstEnrolments[0];
        PageReference pageRef = Page.ConfirmRentalPurchasePage; 
        pageRef.getParameters().put('Id',lstEnrolments[0].id);
        Test.setCurrentPage(pageRef);
        ConfirmRentalPurchaseController objController = new ConfirmRentalPurchaseController();
        objController.createInvoiceViaCard();
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'{"paid": true}'));
        objController.getPaymentForInvoices();
        test.stopTest();
        objController.createAttachmentForEmail();
        
    }
    private static testMethod void testRentalSummary3(){
        List<Enrolment__c> lstEnrolments = [SELECT Id FROM Enrolment__c limit 1];
        List<Invoice_Line_Item__c>lstInvoiceLineItems = [SELECT Is_Deposit__c,Invoice__r.Status__c,Enrolment__c,Invoice__r.Invoice_Type__c,Invoice__r.Due_Date__c
                                                         from Invoice_Line_Item__c
                                                         Where Enrolment__c =: lstEnrolments[0].id
                                                        ];
        List<Invoice__c>lstInvoice = new List<Invoice__c>();
        lstInvoiceLineItems[0].Is_Deposit__c = true;
        lstInvoiceLineItems[0].Amount__c =100;
        lstInvoiceLineItems[0].Invoice__r.Due_Date__c = System.today().addMonths(-2);
        lstInvoiceLineItems[0].Invoice__r.Status__c = 'Paid';
        lstInvoiceLineItems[0].Invoice__r.Invoice_Type__c =ConstantsClass.recurringInvoiceType;
        
        lstInvoice.add(lstInvoiceLineItems[0].Invoice__r);
        update lstInvoice;
        
        lstEnrolments[0].Delivery_Charges__c = 50;
        lstEnrolments[0].Stair_Charges__c = 5;
        lstEnrolments[0].Selling_price__c = 100;
        
        update lstEnrolments[0];
        PageReference pageRef = Page.ConfirmRentalPurchasePage; 
        pageRef.getParameters().put('Id',lstEnrolments[0].id);
        Test.setCurrentPage(pageRef);
        ConfirmRentalPurchaseController objController = new ConfirmRentalPurchaseController();
        objController.createInvoiceViaCard();
        
        lstInvoice.clear();
        lstInvoiceLineItems[0].Is_Deposit__c = true;
        lstInvoiceLineItems[0].Amount__c =100;
        lstInvoiceLineItems[0].Invoice__r.Due_Date__c = System.today();
        lstInvoiceLineItems[0].Invoice__r.Status__c = 'Paid';
        lstInvoiceLineItems[0].Invoice__r.Invoice_Type__c =ConstantsClass.recurringInvoiceType;
        
        lstInvoice.add(lstInvoiceLineItems[0].Invoice__r);
        update lstInvoiceLineItems[0];
        update lstInvoice;
        objController = new ConfirmRentalPurchaseController();
        objController.createInvoiceViaCard();
        
    }
}