force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Piano_Pickup_date__c.field-meta.xml
<CustomField>
    <fullName>Piano_Pickup_date__c</fullName>
    <description>this field for piano rental for manage customer after  Termination then we get Piano Pickup date</description>
    <label>Piano Pickup date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <description>this field for piano rental for manage customer Termination reason</description>
    <label>Termination Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not needed anymore</fullName>
            </value>
            <value>
                <fullName>Moving out of SG</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Termination_Reason_others__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason_others__c</fullName>
    <description>this field for piano rental for manage customer Termination other reason</description>
    <label>Termination Reason (others)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Termination_request_date__c.field-meta.xml
<CustomField>
    <fullName>Termination_request_date__c</fullName>
    <description>this field for piano rental for manage customer Termination requested date</description>
    <label>Termination request date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TerminateRentalSummaryControllerTest.cls
/**
* Name: TerminateRentalSummaryControllerTest
* Author: Jatin
* Date : 16-March-2020
* Description: this class Used to test TerminateRentalSummaryController controller class
*/
@isTest
public class TerminateRentalSummaryControllerTest {
    
    @testSetup
    private static  void createData(){
        PianoRentalTestHelper.createPianoRentalData();
    }
    //if isButton = true;
    private static testMethod void testSubmitTerminateRentalSummaryRequest1(){
        list<Enrolment__c> lstEnrolments = [SELECT Id, Termination_request_date__c,Piano_Pickup_date__c,
                                            Termination_Reason__c,Termination_Reason_others__c
                                            FROM Enrolment__c
                                           ];
        
        for(Enrolment__c objEnrollment :lstEnrolments) {
            objEnrollment.Termination_request_date__c = System.today().addDays(30);
            objEnrollment.Termination_Reason__c = 'Others'; 
        }
        update lstEnrolments;
        Test.StartTest(); 
        PageReference pageRef = Page.TerminationSummaryPage; 
        pageRef.getParameters().put('enrolmentId', String.valueOf(lstEnrolments[0].Id));
        Test.setCurrentPage(pageRef);
        Test.StopTest();
        TerminateRentalSummaryController objController = new TerminateRentalSummaryController();
        TerminateRentalSummaryController.submitTerminateRentalSummaryRequest(string.valueOf(lstEnrolments[0].Id), string.valueOf(lstEnrolments[0].Termination_request_date__c),
                                                                             string.valueOf(lstEnrolments[0].Piano_Pickup_date__c), string.valueOf(lstEnrolments[0].Termination_Reason__c),
                                                                             string.valueOf(lstEnrolments[0].Termination_Reason_others__c),true);
    }
    //if isButton = false;
    private static testMethod void testSubmitTerminateRentalSummaryRequest2(){
        list<Enrolment__c> lstEnrolments = [SELECT Id, Termination_request_date__c,Piano_Pickup_date__c,
                                            Termination_Reason__c,Termination_Reason_others__c
                                            FROM Enrolment__c
                                           ];
        
        for(Enrolment__c objEnrollment :lstEnrolments) {
            objEnrollment.Termination_request_date__c = System.today().addDays(30);
            objEnrollment.Termination_Reason__c = 'Others'; 
            objEnrollment.Stage__c = 'Piano Termination In-Progress';
        }
        update lstEnrolments;
        Test.StartTest(); 
        PageReference pageRef = Page.TerminationSummaryPage; 
        pageRef.getParameters().put('enrolmentId', String.valueOf(lstEnrolments[0].Id));
        Test.setCurrentPage(pageRef);
        Test.StopTest();
        
        TerminateRentalSummaryController objController = new TerminateRentalSummaryController();
        
        TerminateRentalSummaryController.submitTerminateRentalSummaryRequest(string.valueOf(lstEnrolments[0].Id), string.valueOf(lstEnrolments[0].Termination_request_date__c),
                                                                             string.valueOf(lstEnrolments[0].Piano_Pickup_date__c), string.valueOf(lstEnrolments[0].Termination_Reason__c),
                                                                             string.valueOf(lstEnrolments[0].Termination_Reason_others__c),false);
    }
    private static testMethod void testTerminateRentalSummary() {
        list<Enrolment__c> lstEnrolments = [SELECT Id, Termination_request_date__c,Piano_Pickup_date__c,
                                            Termination_Reason__c,Termination_Reason_others__c
                                            FROM Enrolment__c
                                           ];
        
        for(Enrolment__c objEnrollment :lstEnrolments) {
            objEnrollment.Termination_request_date__c = System.today();
            objEnrollment.Piano_Pickup_date__c = System.today();
            
        }
        TerminateRentalSummaryController.getTerminateRentalSummary(string.valueOf(lstEnrolments[0].Id),string.valueOf(lstEnrolments[0].Termination_request_date__c),
                                                                   string.valueOf(lstEnrolments[0].Piano_Pickup_date__c),string.valueOf(lstEnrolments[0].Termination_Reason__c),
                                                                   string.valueOf(lstEnrolments[0].Termination_Reason_others__c));
    }
    
}