force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Lesson_Day__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Day__c</fullName>
    <description>Weekly Appointment Day</description>
    <label>Lesson Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Promotional_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Period_End_Date__c</fullName>
    <label>Promotional Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Termination_request_date__c.field-meta.xml
<CustomField>
    <fullName>Termination_request_date__c</fullName>
    <description>this field for piano rental for manage customer Termination requested date</description>
    <label>Termination request date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Inv-Item-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription Line Item</label>
    <referenceTo>Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <formula>IF(NOT(ISBLANK(Subscription_Line_Item__c)),
        Subscription_Line_Item__r.Enrolment__r.Teacher__r.FirstName +&apos; &apos;+Subscription_Line_Item__r.Enrolment__r.Teacher__r.LastName,
     IF(NOT(ISBLANK(Booking__c)),
         Booking__r.Teacher_Account__r.FirstName+&apos; &apos;+Booking__r.Teacher_Account__r.LastName,
         &apos;&apos;
     )
)</formula>
    <label>Teacher</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Unit_Fee__c.field-meta.xml
<CustomField>
    <fullName>Unit_Fee__c</fullName>
    <inlineHelpText>One session fee</inlineHelpText>
    <label>Unit Fee</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegularInvoiceHandler.cls
/*
    Name            :    RegularInvoiceHandler
    Date            :    28th March 2019
    Author          :    Arpit Vijayvergiya
    Description     :    


*/
public class RegularInvoiceHandler implements PackageProcessInterface{
    private Subscription_Line_Item__c objSubLineItem;
    private Date firstDate;
    private Date lastDate;
    public RegularInvoiceHandler(Subscription_Line_Item__c objSubLineItem,Date firstDate,Date lastDate){
        this.objSubLineItem = objSubLineItem;
    	this.firstDate = firstDate;
        this.lastDate = lastDate;
    } 
    
    public List<Invoice_Line_Item__c> createInvoiceLineItem(Invoice__c objInvoice,Map<String,List<Date>> mapOfDates){
        List<Invoice_Line_Item__c> listOfInvoiceLineItems = new List<Invoice_Line_Item__c>();
        // Jatin: 28-jan-2020: for manage rental invoice amount
        if(objSubLineItem.Enrolment__r.recordtype.Name == ConstantsClass.enrollmentInstrumentRecTypeName){
            Date effectiveDate = objSubLineItem.Enrolment__r.Termination_request_date__c;  
            if(effectiveDate != NULL && effectiveDate >= firstDate && effectiveDate <= lastDate){
                Decimal rentalTotalAmount = effectiveDate.day() * ( objSubLineItem.Amount__c /  date.daysInMonth(effectiveDate.year(), effectiveDate.month()));
                system.debug(rentalTotalAmount);
                Invoice_Line_Item__c invLineItm = PackageUpgradeController.createInvoiceLineItem(objInvoice.id,objSubLineItem,rentalTotalAmount,
                                                                objSubLineItem.Enrolment__r.Package__c,False,objSubLineItem.Enrolment__r.Teacher__c);
                invLineItm.Remarks__c = 'Final Piano Rental';
                listOfInvoiceLineItems.add(invLineItm);
            }else{
                Invoice_Line_Item__c invLineItm = PackageUpgradeController.createInvoiceLineItem(objInvoice.id,objSubLineItem,objSubLineItem.Amount__c,
                                                                objSubLineItem.Enrolment__r.Package__c,False,objSubLineItem.Enrolment__r.Teacher__c);
                invLineItm.Remarks__c = 'Piano Rental';
                listOfInvoiceLineItems.add(invLineItm);
            }
         }else{
            Date effectiveDate = objSubLineItem.Enrolment__r.Promotional_Period_End_Date__c;       
            if(effectiveDate != NULL && effectiveDate >= firstDate && effectiveDate <= lastDate &&
            String.isNotBlank(objSubLineItem.Enrolment__r.Lesson_Day__c) && 
            mapOfDates.containsKey(objSubLineItem.Enrolment__r.Lesson_Day__c)){
                Integer noOfLessonToBeBilled = 0;
                List<Date> listOfDates = mapOfDates.get(objSubLineItem.Enrolment__r.Lesson_Day__c);
                if(listOfDates.size() == 5){
                    listOfDates.remove(4);
                }
                for(Date objDate : listOfDates){
                    if(objDate > effectiveDate){
                        noOfLessonToBeBilled += 1;
                    } 
                }
                if(noOfLessonToBeBilled > 0){
                    Decimal lessonCharge = noOfLessonToBeBilled *  objSubLineItem.Enrolment__r.Package__r.Unit_Fee__c;
                    listOfInvoiceLineItems.add(PackageUpgradeController.createInvoiceLineItem(objInvoice.id,objSubLineItem,lessonCharge  ,objSubLineItem.Enrolment__r.Package__c,False,objSubLineItem.Enrolment__r.Teacher__c)); 
                }   
            }else{
                Invoice_Line_Item__c invLineItm = PackageUpgradeController.createInvoiceLineItem(objInvoice.id,objSubLineItem,objSubLineItem.Amount__c,
                                                                objSubLineItem.Enrolment__r.Package__c,False,objSubLineItem.Enrolment__r.Teacher__c);
                listOfInvoiceLineItems.add(invLineItm);
            }   
         }
        return listOfInvoiceLineItems;
    }

}