force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Actual_Delivery_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Delivery_Date_Time__c</fullName>
    <description>this field for piano rental for manage customer actual Delivery datetime after sign panda doc</description>
    <label>Actual Delivery Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Extra_Stairs__c.field-meta.xml
<CustomField>
    <fullName>Extra_Stairs__c</fullName>
    <description>this field for piano rental for manage customer additional stairs according to packer</description>
    <label>Extra Stairs</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/No_of_Stairs__c.field-meta.xml
<CustomField>
    <fullName>No_of_Stairs__c</fullName>
    <description>this field for piano rental for manage customer number of stairs</description>
    <label>No. of Stairs</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stair_Charges__c.field-meta.xml
<CustomField>
    <fullName>Stair_Charges__c</fullName>
    <label>Stair Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateExtraStairsChargesCtrlTest.cls
/**
* Name: GenerateExtraStairsChargesCtrlTest
* Author: Jatin
* Date : 16-March-2020
* Description: this class Used to test GenerateExtraStairsChargesCtr controller class
*/
@isTest
public class GenerateExtraStairsChargesCtrlTest {
    @testSetup
    private static void createData(){
        PianoRentalTestHelper.createPianoRentalData();
        
        
    }
    private static testMethod void testUpdateEnrollment(){
        List<Enrolment__c> lstEnrolments = [SELECT Id FROM Enrolment__c LIMIT 1];
        List<Invoice__c> lstInvoice = [SELECT Id,status__c FROM Invoice__c where status__c =: ConstantsClass.paidStatus  limit 1 ];
        lstEnrolments[0].Stage__c = 'Piano Rental Active';
        lstEnrolments[0].Actual_Delivery_Date_Time__c = System.now();
        lstEnrolments[0].Extra_Stairs__c = 20;
        lstEnrolments[0].No_of_Stairs__c = 20;
        lstEnrolments[0].Stair_Charges__c =40;
        UPDATE lstEnrolments;
        
        
        ApexPages.StandardController objStandarCon = new ApexPages.StandardController(lstEnrolments[0]);
        GenerateExtraStairsChargesCtrl objController = new GenerateExtraStairsChargesCtrl(objStandarCon);
        objController.invoiceId = lstInvoice[0].Id;
        objController.getPaymentForInvoices();
        objController.createAttachmentForEmail();
        objController.generateExtraStairsCharges();
        System.debug('!!lstInvoice'+lstInvoice.size());
        GenerateExtraStairsChargesCtrl.insertPdfAndSendEmail(lstInvoice[0].id);
        
        System.assertEquals(true,objController.errorString == 'getPaymentForInvoices');
        
        
    }
}