force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Status__c</fullName>
    <label>Advance Action Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Type__c</fullName>
    <label>Advance Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Enrolment Change</fullName>
            </value>
            <value>
                <fullName>Centre Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PackageProcessHandler.cls
/*    
        Name            :    PackageProcessHandler
        Date            :    28th March 2019
        Author          :    Arpit Vijayvergiya
        Description     :    This is handler class for package Proccessing.

*/
public class PackageProcessHandler{
    public Invoice__c objInvoice;
    public List<PackageProcessInterface> listOfPackageProcess;
    
    public PackageProcessHandler(Invoice__c objInvoice , List<Subscription_Line_Item__c> listOfSubLineItems, Date firstDate,Date LastDate){
        listOfPackageProcess = new List<PackageProcessInterface>();
        this.objInvoice = objInvoice;
        String pendingStatus = ConstantsClass.enrollmentProcessPendingStatus;
        String upgradeType = ConstantsClass.enrollmentProcessUpgradeType;
        String downgradeType = ConstantsClass.enrollmentProcessDowngradeType;
        String cancelType = ConstantsClass.enrollmentProcessCancelType;
        String enromentChangeType = ConstantsClass.enrollmentProcessChanged; 
        String enromentChangeCenterType = ConstantsClass.enrollmentProcessChangedCenter; 
        for(Subscription_Line_Item__c objSubLineItems : listOfSubLineItems){
            if(String.isNotBlank(objSubLineItems.Enrolment__c) && String.isNotBlank(objSubLineItems.Enrolment__r.Package_Process_type__c)
                && String.isNotBlank(objSubLineItems.Enrolment__r.Package_Process_Status__c) && 
                objSubLineItems.Enrolment__r.Package_Process_Status__c == pendingStatus && objSubLineItems.Enrolment__r.effective_date__c != NULL &&
                  (/*objSubLineItems.Enrolment__r.effective_date__c >= firstDate &&*/ objSubLineItems.Enrolment__r.effective_date__c <= lastDate)){
                if(objSubLineItems.Enrolment__r.Package_Process_type__c == upgradeType){
                    listOfPackageProcess.add(new PackageUpgradeController(objSubLineItems));
                }else if(objSubLineItems.Enrolment__r.Package_Process_type__c == downgradeType){
                    listOfPackageProcess.add(new PackageDowngradeController(objSubLineItems));
                }else if(objSubLineItems.Enrolment__r.Package_Process_type__c == cancelType){
                    listOfPackageProcess.add(new PackageCancellationController(objSubLineItems));
                }else if(objSubLineItems.Enrolment__r.Package_Process_type__c == enromentChangeType){
                    listOfPackageProcess.add(new EnrolmentChangeHandler(objSubLineItems));
                }else if(objSubLineItems.Enrolment__r.Package_Process_type__c == enromentChangeCenterType){
                    listOfPackageProcess.add(new EnrolmentChangeCenterHandler(objSubLineItems));
                }
            }else{
                // this is for normal invoiceType
                listOfPackageProcess.add(new RegularInvoiceHandler(objSubLineItems,firstDate,lastDate));
            }
        }
    }
}