force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Package_Fee__c.field-meta.xml
<CustomField>
    <fullName>Package_Fee__c</fullName>
    <label>Package Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Item.recordType-meta.xml
<RecordType>
    <fullName>Item</fullName>
    <active>true</active>
    <description>Select this record type to setup package for Item Rental/Sell</description>
    <label>Item</label>
</RecordType>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Plan_Package__c.field-meta.xml
<CustomField>
    <fullName>Plan_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan/Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PackageFeeBatch.cls
/*
        Name           :    PackageFeeBatch
        Date           :    04/25/2019
        Description    :    This batch class update amount on all Subscription Line Item when amount is changed on the package
*/
global class PackageFeeBatch implements Database.Batchable<sObject>,database.stateful{
    global DateTime startTime;
    global integer noOfRecords;
    global Set<String> setOfPackIds;
    
    global PackageFeeBatch (Set<String> setOfPackIds){
        noOfRecords  = 0;
        startTime = system.now();
        this.setOfPackIds = setOfPackIds;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id,Amount__c,Plan_Package__c,Plan_Package__r.Package_Fee__c FROM Subscription_Line_Item__c WHERE Plan_Package__c IN: setOfPackIds]);                                
    }
    
    global void execute(Database.BatchableContext BC, List<Subscription_Line_Item__c> listOfLineItems){
        noOfRecords += listOfLineItems.size();
        for(Subscription_Line_Item__c objLineItem : listOfLineItems){
            objLineItem.Amount__c =  objLineItem.Plan_Package__r.Package_Fee__c; 
            
        }
        
        UPDATE listOfLineItems;
    }
    global void finish(Database.BatchableContext BC){
        BillingUtility.createBatchLog('PackageFeeBatch',startTime,system.now(),noOfRecords);
    }
}