force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Camp_Days__c.field-meta.xml
<CustomField>
    <fullName>Camp_Days__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp class  for select customer Camp Day</description>
    <label>Camp Days</label>
    <referenceTo>Camp_Days__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Break</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Hours in-lieu</fullName>
            </value>
            <value>
                <fullName>Recital</fullName>
            </value>
            <value>
                <fullName>Contract Programme</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>5th Lesson</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp__c/Camp__c.object-meta.xml
<CustomObject>
    <description>this object for manage camp class</description>
    <label>Camp</label>
    <nameField>
        <label>Camp  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>this field for camp class for manage camp Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/Camp_Day_Teachers__c.object-meta.xml
<CustomObject>
    <description>this object manage Camp Days related Teachers</description>
    <label>Camp Day Teachers</label>
    <nameField>
        <displayFormat>CampDayTeacher-{0000}</displayFormat>
        <label>Camp Day Teachers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Camp Day Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Camp_Day__c.field-meta.xml
<CustomField>
    <fullName>Camp_Day__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field lookup of camp day object</description>
    <label>Camp Day</label>
    <referenceTo>Camp_Days__c</referenceTo>
    <relationshipLabel>Camp Day Teachers</relationshipLabel>
    <relationshipName>Camp_Day_Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Camp_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Camp_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for manage camp teachers</description>
    <label>Camp Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camp Day Teachers</relationshipLabel>
    <relationshipName>Camp_Day_Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Days__c/Camp_Days__c.object-meta.xml
<CustomObject>
    <description>this object  for manage camp days</description>
    <label>Camp Days</label>
    <nameField>
        <label>Camp day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camp Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Days__c/fields/Camp_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Camp_End_Time__c</fullName>
    <description>this field for camp days for manage Camp End Time</description>
    <label>Camp End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Name__c.field-meta.xml
<CustomField>
    <fullName>Camp_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Camp Name</label>
    <referenceTo>Camp__c</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Camp_Start_Time__c</fullName>
    <description>this field for camp days for manage Camp Start Time</description>
    <label>Camp Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Camp_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp days for manage Camp Teacher</description>
    <label>Camp Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Dates_Of_The_Camp__c.field-meta.xml
<CustomField>
    <fullName>Dates_Of_The_Camp__c</fullName>
    <description>this field for camp days for manage Dates Of The Camp</description>
    <label>Dates Of The Camp</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/No_of_Students_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>No_of_Students_Enrolled__c</fullName>
    <description>this field for camp days for manage camp No. of Students Enrolled</description>
    <label>No. of Students Enrolled</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>this field for camp days for manage camp Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampDayTeacherTriggerTest.cls
/**
* Name: CampDayTeacherTriggerTest
* Author: Jatin
* Date : 13-March-2020
* Description: this class Used to test CampDayTeacherTriggerTest Trigger
*/
@isTest
public class CampDayTeacherTriggerTest {
    @testSetup
    private static void createData() {
        CampEnrolmentTestHelper.createCampData();
    }
    
    // if camp is active and teacher is Active Status
    //  we update teacher records in 'InActive' then check 'PlaceHolder'bookings are Deleted or not
    private static testMethod void testCampTeacherUpdateInActiveStatus() {
        
        list<Camp__c> lstCamps = [SELECT Id, Status__c FROM Camp__c WHERE status__c =: ConstantsClass.campActiveStatus and Name='Test Camp3'];
        list<Camp_Days__c> lstCampDays = [ SELECT id,Status__c, Camp_Name__c, Camp_Start_Time__c, Camp_End_Time__c, Dates_Of_The_Camp__c, No_of_Students_Enrolled__c 
                                          FROM Camp_Days__c 
                                          where Camp_Name__c =: lstCamps[0].id 
                                          and Status__c =:ConstantsClass.campDaysActiveStatus
                                          Order by Dates_Of_The_Camp__c];
        List<Camp_Day_Teachers__c> listOfCamp_Day_Teachers = [Select id,Camp_Teacher__c,Camp_Day__c
                                                              from Camp_Day_Teachers__c
                                                              where Camp_Day__r.Camp_Name__c =: lstCamps[0].id
                                                              AND Camp_Day__c =:lstCampDays[1].id
                                                              And Status__c =:ConstantsClass.campTeacherActiveStatus];
        System.debug('!!before'+listOfCamp_Day_Teachers);
        system.assert(listOfCamp_Day_Teachers.size() == 1); 
        test.startTest();
        List<Booking__C> listofBooking = [Select id ,Camp_Days__c,Teacher_Account__c,Camp_Days__r.Camp_Name__c, Booking_date__C from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() > 0); 
        System.debug('!!before'+listofBooking);
        for(Camp_Day_Teachers__c objCamp_Day_Teachers : listOfCamp_Day_Teachers){
            objCamp_Day_Teachers.Status__c = ConstantsClass.campTeacherInActiveStatus;
        }
        update listOfCamp_Day_Teachers;
        
        listofBooking = [Select id,Camp_Days__c,Teacher_Account__c,Camp_Days__r.Camp_Name__c, Booking_date__C from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        System.debug('!!after'+listofBooking);
        system.assert(listofBooking.size() == 0,''+listofBooking); 
        test.stopTest();
    }
    
     // if camp is Inactive and teacher is Active Status
    //  we update teacher records in 'InActive' then check 'PlaceHolder'bookings are Deleted or not
    private static testMethod void testCampTeacherUpdateInActiveStatus2() {
        
        list<Camp__c> lstCamps = [SELECT Id, Status__c FROM Camp__c WHERE status__c !=: ConstantsClass.campActiveStatus and Name='Test Camp1'];
        list<Camp_Days__c> lstCampDays = [ SELECT id,Status__c, Camp_Name__c, Camp_Start_Time__c, Camp_End_Time__c, Dates_Of_The_Camp__c, No_of_Students_Enrolled__c 
                                          FROM Camp_Days__c 
                                          where Camp_Name__c =: lstCamps[0].id 
                                          and Status__c =:ConstantsClass.campDaysActiveStatus
                                          Order by Dates_Of_The_Camp__c];
        List<Camp_Day_Teachers__c> listOfCamp_Day_Teachers = [Select id,Camp_Teacher__c,Camp_Day__c
                                                              from Camp_Day_Teachers__c
                                                              where Camp_Day__r.Camp_Name__c =: lstCamps[0].id
                                                              And Status__c =:ConstantsClass.campTeacherActiveStatus];
        test.startTest();
         List<Booking__C> listofBooking = [Select id from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() == 0); 
        for(Camp_Day_Teachers__c objCamp_Day_Teachers : listOfCamp_Day_Teachers){
            objCamp_Day_Teachers.Status__c = ConstantsClass.campTeacherInActiveStatus;
        }
        update listOfCamp_Day_Teachers;
        listofBooking = [Select id from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() == 0); 
        test.stopTest();
    }
    
     // if camp is active and teacher is Inactive Status
    //  we update teacher records in 'Active' then check 'PlaceHolder'bookings are created or not
    private static testMethod void testCampTeacherUpdateActiveStatus() {
        
        list<Camp__c> lstCamps = [SELECT Id, Status__c FROM Camp__c WHERE status__c =: ConstantsClass.campActiveStatus and Name='Test Camp3'];
        list<Camp_Days__c> lstCampDays = [ SELECT id,Status__c, Camp_Name__c, Camp_Start_Time__c, Camp_End_Time__c, Dates_Of_The_Camp__c, No_of_Students_Enrolled__c 
                                          FROM Camp_Days__c 
                                          where Camp_Name__c =: lstCamps[0].id 
                                          and Status__c =:ConstantsClass.campDaysActiveStatus
                                          Order by Dates_Of_The_Camp__c];
        List<Camp_Day_Teachers__c> listOfCamp_Day_Teachers = [Select id,Camp_Teacher__c,Camp_Day__c
                                                              from Camp_Day_Teachers__c
                                                              where Camp_Day__r.Camp_Name__c =: lstCamps[0].id
                                                              And Status__c !=:ConstantsClass.campTeacherActiveStatus];
        test.startTest();
        for(Camp_Day_Teachers__c objCamp_Day_Teachers : listOfCamp_Day_Teachers){
            objCamp_Day_Teachers.Status__c = ConstantsClass.campTeacherActiveStatus;
        }
        update listOfCamp_Day_Teachers;
        
        List<Booking__C> listofBooking = [Select id from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() > 0); 
        test.stopTest();
    }
    // if camp is Inactive and teacher is also Inactive Status
    // if we update teacher records in 'Active' then check 'PlaceHolder'bookings are created or not
    private static testMethod void testCampTeacherUpdateActiveStatus2() {
        
        list<Camp__c> lstCamps = [SELECT Id, Status__c FROM Camp__c WHERE status__c !=: ConstantsClass.campActiveStatus and Name='Test Camp1'];
        list<Camp_Days__c> lstCampDays = [ SELECT id,Status__c, Camp_Name__c, Camp_Start_Time__c, Camp_End_Time__c, Dates_Of_The_Camp__c, No_of_Students_Enrolled__c 
                                          FROM Camp_Days__c 
                                          where Camp_Name__c =: lstCamps[0].id 
                                          and Status__c =:ConstantsClass.campDaysActiveStatus
                                          Order by Dates_Of_The_Camp__c];
        List<Camp_Day_Teachers__c> listOfCamp_Day_Teachers = [Select id,Camp_Teacher__c,Camp_Day__c
                                                              from Camp_Day_Teachers__c
                                                              where Camp_Day__r.Camp_Name__c =: lstCamps[0].id
                                                              And Status__c !=:ConstantsClass.campTeacherActiveStatus];
        test.startTest();
        for(Camp_Day_Teachers__c objCamp_Day_Teachers : listOfCamp_Day_Teachers){
            objCamp_Day_Teachers.Status__c = ConstantsClass.campTeacherActiveStatus;
        }
        update listOfCamp_Day_Teachers;
        List<Booking__C> listofBooking = [Select id from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() == 0); 
        test.stopTest();
    }
   
     // if camp is active and teacher is Inactive Status
    //  we Delete or undelete teacher records in 'Active' then check 'PlaceHolder'bookings are created or not
    private static testMethod void testCampTeacherDeleteOrUndeleteActiveStatus() {
        
        list<Camp__c> lstCamps = [SELECT Id, Status__c FROM Camp__c WHERE status__c =: ConstantsClass.campActiveStatus and Name='Test Camp3'];
        list<Camp_Days__c> lstCampDays = [ SELECT id,Status__c, Camp_Name__c, Camp_Start_Time__c, Camp_End_Time__c, Dates_Of_The_Camp__c, No_of_Students_Enrolled__c 
                                          FROM Camp_Days__c 
                                          where Camp_Name__c =: lstCamps[0].id 
                                          and Status__c =:ConstantsClass.campDaysActiveStatus
                                          Order by Dates_Of_The_Camp__c];
        List<Camp_Day_Teachers__c> listOfCamp_Day_Teachers = [Select id,Camp_Teacher__c,Camp_Day__c
                                                              from Camp_Day_Teachers__c
                                                              where Camp_Day__r.Camp_Name__c =: lstCamps[0].id
                                                              And Status__c =:ConstantsClass.campTeacherActiveStatus];
        test.startTest();
       Delete listOfCamp_Day_Teachers;
         List<Booking__C> listofBooking = [Select id from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() == 0); 
        undelete listOfCamp_Day_Teachers;
        listofBooking = [Select id from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() > 0); 
        test.stopTest();
    }
    
     // if camp is active and teacher is Inactive Status
    //  we update teacher records in 'Active' then check 'PlaceHolder'bookings are created or not
    private static testMethod void testCampTeacherUpdateCampDayId() {
        
       list<Camp__c> lstCamps = [SELECT Id, Status__c FROM Camp__c WHERE status__c =: ConstantsClass.campActiveStatus and Name='Test Camp3'];
        list<Camp_Days__c> lstCampDays = [ SELECT id,Status__c, Camp_Name__c, Camp_Start_Time__c, Camp_End_Time__c, Dates_Of_The_Camp__c, No_of_Students_Enrolled__c 
                                          FROM Camp_Days__c 
                                          where Camp_Name__c =: lstCamps[0].id 
                                          and Status__c =:ConstantsClass.campDaysActiveStatus
                                          Order by Dates_Of_The_Camp__c];
        List<Camp_Day_Teachers__c> listOfCamp_Day_Teachers = [Select id,Camp_Teacher__c,Camp_Day__c
                                                              from Camp_Day_Teachers__c
                                                              where Camp_Day__r.Camp_Name__c =: lstCamps[0].id
                                                              AND Camp_Day__c =:lstCampDays[1].id
                                                              And Status__c =:ConstantsClass.campTeacherActiveStatus];
        test.startTest();
        List<Booking__C> listofBooking = [Select id,Camp_Days__c,Teacher_Account__c,Camp_Days__r.Camp_Name__c, Booking_date__C from Booking__c 
                                          where Camp_Days__c =:listOfCamp_Day_Teachers[0].Camp_Day__c
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() > 0); 
        for(Camp_Day_Teachers__c objCamp_Day_Teachers : listOfCamp_Day_Teachers){
            objCamp_Day_Teachers.Camp_Day__c = lstCampDays[0].id;
        }
        update listOfCamp_Day_Teachers;
        
       listofBooking = [Select id,Camp_Days__c,Teacher_Account__c,Camp_Days__r.Camp_Name__c, Booking_date__C from Booking__c 
                                          where Camp_Days__c =:lstCampDays[1].id
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() == 0); 
        listofBooking = [Select id,Camp_Days__c,Teacher_Account__c,Camp_Days__r.Camp_Name__c, Booking_date__C from Booking__c 
                                          where Camp_Days__c =:lstCampDays[0].id
                                          AND status__c =: ConstantsClass.scheduledStatus
                                          AND Category__c =: ConstantsClass.bookingCategoryCamp
                                          AND Teacher_Account__c =:listOfCamp_Day_Teachers[0].Camp_Teacher__c];
        system.assert(listofBooking.size() > 0); 
        test.stopTest();
    }
    
}