force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Enrolment_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Email_Date__c</fullName>
    <label>Enrolment Email Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExpireEnrolmentBooking.cls
global class ExpireEnrolmentBooking implements  Database.Batchable<sObject>{
	Private String PendingEnrolment= ConstantsClass.PendingEnrolment;
    
    global Database.QueryLocator start(Database.BatchableContext bc){ 
       integer noOfDay = (integer.valueOf(System.Label.Enrolment_expiry_period)/24);
        DateTime myDateTime = system.Now().addDays(-noOfDay);
        String query = 'Select Id,Status__c,Enrolment__r.Stage__c,Enrolment__c From Booking__c Where Enrolment__r.Stage__c =:PendingEnrolment AND Enrolment__r.Enrolment_Email_Date__c <=:myDateTime';
		      
        return Database.getQueryLocator(query); 
    }
    global void execute (Database.BatchableContext bc ,List<sObject> recordsList){
        System.debug('Execute-------'+recordsList.size());
        List<Booking__c> bookList = new List<Booking__c>();
        List<Enrolment__c> enrList = new List<Enrolment__c>();
        set<Id> bkgId = new set<Id>();
        set<Id> enrId = new set<Id>();
        List<Booking__C> records = (List<Booking__c>)recordsList;
        system.debug('records'+records);
        for(Booking__C bkg:records ){
            if(bkg.Status__c =='Blocked'){
                bkgId.add(bkg.Id);
            }
            enrId.add(bkg.Enrolment__c);
        }
        for(Enrolment__c enrLst :[select Id,Stage__c from Enrolment__c where Id in:enrId]){
            enrLst.stage__c='Attended';
            enrList.add(enrLst);
        }
        bookList=[Select Id from Booking__c where Id in:bkgId];
        system.debug('bookList'+bookList);
        if(bookList.size()>0){
            delete bookList; 
        }
        system.debug('enrList'+enrList);
        if(enrList.size()>0)
            update enrList;
        
        }
    global void finish(Database.BatchableContext bc){
        System.debug('----Finish');
    }
}