force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Lesson_Type__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Type__c</fullName>
    <label>Lesson Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Centre</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingFileDeleteBatchTest.cls
@isTest
public class BookingFileDeleteBatchTest {
    @testSetup 
    static void setup() {
        List<Booking__c> bookingList = new List<Booking__c>();
        for (Integer i=0;i<5;i++) {
            date mydate = Date.parse('2'+i+'/06/2020');
            bookingList.add(new Booking__c(Booking_Date__c= mydate, Lesson_Type__c='Online'));
        }
        insert bookingList;
    }
    
    static testmethod void test() {        
        Test.startTest();
        BookingFileDeleteBatch batchCls = new BookingFileDeleteBatch();
        Database.executeBatch(batchCls);
        Test.stopTest();
    }
}