force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Camp_Days__c.field-meta.xml
<CustomField>
    <fullName>Camp_Days__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp class  for select customer Camp Day</description>
    <label>Camp Days</label>
    <referenceTo>Camp_Days__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Break</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Hours in-lieu</fullName>
            </value>
            <value>
                <fullName>Recital</fullName>
            </value>
            <value>
                <fullName>Contract Programme</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>5th Lesson</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <description>This formula field is use for displaying name of center on booking object</description>
    <formula>Opportunity__r.Account.Name</formula>
    <label>Center Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
            <value>
                <fullName>Audition</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Group Class</fullName>
            </value>
            <value>
                <fullName>Group Lesson</fullName>
            </value>
            <value>
                <fullName>Piano Viewing</fullName>
            </value>
            <value>
                <fullName>Busy / Place holder</fullName>
                <isActive>false</isActive>
                <label>Busy / Place holder</label>
            </value>
            <value>
                <fullName>Notice</fullName>
                <isActive>false</isActive>
                <label>Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp__c/Camp__c.object-meta.xml
<CustomObject>
    <description>this object for manage camp class</description>
    <label>Camp</label>
    <nameField>
        <label>Camp  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>this field for camp class for manage camp Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/Camp_Day_Teachers__c.object-meta.xml
<CustomObject>
    <description>this object manage Camp Days related Teachers</description>
    <label>Camp Day Teachers</label>
    <nameField>
        <displayFormat>CampDayTeacher-{0000}</displayFormat>
        <label>Camp Day Teachers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Camp Day Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Camp_Day__c.field-meta.xml
<CustomField>
    <fullName>Camp_Day__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field lookup of camp day object</description>
    <label>Camp Day</label>
    <referenceTo>Camp_Days__c</referenceTo>
    <relationshipLabel>Camp Day Teachers</relationshipLabel>
    <relationshipName>Camp_Day_Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Camp_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Camp_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for manage camp teachers</description>
    <label>Camp Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camp Day Teachers</relationshipLabel>
    <relationshipName>Camp_Day_Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>this field manage teacher camp end time</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <description>this field manage teacher camp start time</description>
    <label>Start time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Days__c/Camp_Days__c.object-meta.xml
<CustomObject>
    <description>this object  for manage camp days</description>
    <label>Camp Days</label>
    <nameField>
        <label>Camp day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camp Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Name__c.field-meta.xml
<CustomField>
    <fullName>Camp_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Camp Name</label>
    <referenceTo>Camp__c</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Camp_Start_Time__c</fullName>
    <description>this field for camp days for manage Camp Start Time</description>
    <label>Camp Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Camp_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp days for manage Camp Teacher</description>
    <label>Camp Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Dates_Of_The_Camp__c.field-meta.xml
<CustomField>
    <fullName>Dates_Of_The_Camp__c</fullName>
    <description>this field for camp days for manage Dates Of The Camp</description>
    <label>Dates Of The Camp</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>this field for camp days for manage camp Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/Teacher_Working_Hour__c.object-meta.xml
<CustomObject>
    <label>Teacher Working Hour</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Teacher Working Hour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Working Hours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teacher_Working_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Working_Day__c.field-meta.xml
<CustomField>
    <fullName>Working_Day__c</fullName>
    <label>Working Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
            <value>
                <fullName>Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/campTriggerHelper.cls
/*
    Name    : campTriggerHelper 
   date: 29-Feb-2020
   author: jatin
   description : this triggerhelper for creating Placeholder for all camp teachers for the duration. This should be done once the camp is activated.
    
*/
public with sharing class campTriggerHelper {
    // 19-Feb-2020:create placeholer type booking for camp teachers
    public static void createCampTeachersPlaceholder(Map<string,Camp__c> mapOfCamp) {
        List<Booking__c> listOfCampTeachersPlaceholder = new List<Booking__c>();
        if(mapOfCamp != null && mapOfCamp.size() >= 0){
            
            List<Camp_Days__c> listOFCampDays =  [SELECT  Dates_Of_The_Camp__c,Camp_Start_Time__c,
                                                    Status__c, Camp_Name__c, Id, Name,
                                                    (select Camp_Teacher__c,End_Time__c,Start_time__c,Status__c,Camp_Day__c
                                                        FROM Camp_Day_Teachers__r
                                                        where Status__c =:ConstantsClass.campTeacherActiveStatus) 
                                                    FROM Camp_Days__c
                                                    WHERE Camp_Name__c in:mapOfCamp.keySet()
                                                    AND Status__c =: ConstantsClass.campDaysActiveStatus];
            if(listOFCampDays != null && listOFCampDays.size() > 0){
                set<string> campTeacherIds = new set<string>();
                Set<string> campDays = new set<string>();
                map<string,set<id>> mapOfCampTeacherDays = new map<string,set<id>>();
                map<id,Camp_Day_Teachers__c> mapOfCampTeachers = new  map<id,Camp_Day_Teachers__c>();
                for(Camp_Days__c campDayObj : listOFCampDays){
                    mapOfCampTeachers = new  map<id,Camp_Day_Teachers__c>();
                    //System.debug('!!campDayObj'+campDayObj);
                    if(campDayObj.Camp_Day_Teachers__r!= null && campDayObj.Camp_Day_Teachers__r.size() > 0){
                        mapOfCampTeachers = new  map<id,Camp_Day_Teachers__c>(campDayObj.Camp_Day_Teachers__r);
                        for(Camp_Day_Teachers__c campDayTeachersObj  : mapOfCampTeachers.values()){
                            campTeacherIds.Add(campDayTeachersObj.Camp_Teacher__c);
                        }
                    }
                    campDays.add(DateTime.newInstance(campDayObj.Dates_Of_The_Camp__c, campDayObj.Camp_Start_Time__c).format('E'));
                    mapOfCampTeacherDays.put(campDayObj.Camp_Name__c +'-'+campDayObj.Dates_Of_The_Camp__c,
                    mapOfCampTeachers.keySet());
                }  
                map<string,list<Teacher_Working_Hour__c>> mapOfTeacherWorkingHours = new map<string,list<Teacher_Working_Hour__c>>();
                if(campTeacherIds != null && campDays != null && campTeacherIds.size() > 0 && campDays.size() > 0) 
                        mapOfTeacherWorkingHours = CampClassUtilityController.getTeacherWorkingHoursList(campTeacherIds,campDays,''); 
                
                        
                for(Camp_Days__c objCampDays : listOFCampDays){
                   // system.debug('--objCampDays ----'+objCampDays.name);
                    //system.debug('--objCampDays.Camp_Day_Teachers__r ----'+objCampDays.Camp_Day_Teachers__r);
                    if(objCampDays.Camp_Day_Teachers__r!= null && objCampDays.Camp_Day_Teachers__r.size() > 0){
                        listOfCampTeachersPlaceholder.AddAll(createPlaceholderForCampClass(objCampDays.Camp_Day_Teachers__r,DateTime.newInstance(objCampDays.Dates_Of_The_Camp__c, objCampDays.Camp_Start_Time__c),
                                                            mapOfCamp.get(objCampDays.Camp_Name__c),mapOfTeacherWorkingHours,mapOfCampTeacherDays ));
                    }
                }
                if(listOfCampTeachersPlaceholder != null && listOfCampTeachersPlaceholder.size() >0){
                    insert listOfCampTeachersPlaceholder;
                }
                system.debug('listOfCampTeachersPlaceholder'+listOfCampTeachersPlaceholder);
            }
        }
    }

    // 19-Feb-2020:creating Placeholder for all camp teachers for the duration. This should be done once the camp is activated.
    Public static List<Booking__c> createPlaceholderForCampClass(List<Camp_Day_Teachers__c> campDayTeachersList,dateTime campDate,Camp__c objCamp,
                                                                    map<string,list<Teacher_Working_Hour__c>> mapOfTeacherWorkingHours,
                                                                    map<string,set<id>> mapOfCampTeacherDays ){
        Booking__c placeholderObj = new Booking__c();
        String campLessonRecId =  Schema.SObjectType.Booking__c.getRecordTypeInfosByName().get(ConstantsClass.bookingRecordsTypeCampLesson).getRecordTypeId();    
                
        List<Booking__c> placeholderList = new List<Booking__c>();
        set<id> campDateTeacherIds = new set<id>();
        if(mapOfCampTeacherDays.containsKey(objCamp.Id+'-'+campDate.date())){
            campDateTeacherIds = mapOfCampTeacherDays.get(objCamp.Id+'-'+campDate.date());
        }
     //  system.debug('campDateTeacherIds'+campDateTeacherIds);
        for(Camp_Day_Teachers__c campDayTeachersObj : campDayTeachersList){
            //system.debug('campDateTeacherIds.contains(campDayTeachersObj.id)'+campDateTeacherIds.contains(campDayTeachersObj.id));
                if(campDateTeacherIds.contains(campDayTeachersObj.id)){
                  //  system.debug('mapOfTeacherWorkingHours.containsKey(campDayTeachersObj.Camp_Teacher__c)'+mapOfTeacherWorkingHours.containsKey(campDayTeachersObj.Camp_Teacher__c));
                    if(mapOfTeacherWorkingHours.containsKey(campDayTeachersObj.Camp_Teacher__c)){
                        string centerId = '';
                        for(Teacher_Working_Hour__c techWorkSchObj: mapOfTeacherWorkingHours.get(campDayTeachersObj.Camp_Teacher__c)){
                          //  system.debug('techWorkSchObj.Working_Day__c'+techWorkSchObj.Working_Day__c);
                           // system.debug('campDate.format(E)'+campDate.format('E'));
                            
                            if(techWorkSchObj.Working_Day__c.equalsIgnoreCase(campDate.format('E'))){
                                centerId = techWorkSchObj.Center_Name__c;
                            }
                            //system.debug('centerId'+centerId);
                        }
                        if(string.isNotBlank(centerId)){
                            placeholderObj = CampClassUtilityController.createCampBooking('','',campDate.date(),campDayTeachersObj.End_Time__c,campDayTeachersObj.Start_time__c,
                                                                                    centerId,'','',campDayTeachersObj.Camp_Day__c,
                                                                                    campDayTeachersObj.Camp_Teacher__c);
                            placeholderObj.Type__c = ConstantsClass.typeBusy;
                            placeholderObj.status__c = ConstantsClass.scheduledStatus;
                            placeholderObj.remarks__c = objCamp.Name + '.';
                            placeholderObj.recordTypeId = campLessonRecId;
                            placeholderObj.Category__c = ConstantsClass.bookingCategoryCamp;
                            placeholderList.add(placeholderObj);
                        }
                    }
                }
            }
        
        system.debug('placeholderList'+placeholderList);
        return placeholderList;
        
    }

    // 19-Feb-2020: delete all active camp teacher 'placeholder' type  bookings if camp is deleted or canceled
    public static void deleteCampTeachersPlaceholder(Map<string,Camp__c> mapOfCamp) {
        List<Booking__c> listOfCampTeachersPlaceholder = new List<Booking__c>();
        if(mapOfCamp != null && mapOfCamp.size() >= 0){
            set<string> teacherIds = new  set<string>();
            map<string,Set<String>> campDaysTeachers = new  map<string,Set<String>>();
            List<Camp_Days__c> listOFCampDays =  [SELECT  Dates_Of_The_Camp__c,
                                                    Status__c, Camp_Name__c, Id, Name,
                                                    (select Camp_Teacher__c,End_Time__c,Start_time__c,Status__c,Camp_Day__c
                                                        FROM Camp_Day_Teachers__r
                                                        where Status__c =:ConstantsClass.campTeacherActiveStatus) 
                                                    FROM Camp_Days__c
                                                    WHERE Camp_Name__c in:mapOfCamp.keySet()
                                                    AND Status__c =: ConstantsClass.campDaysActiveStatus];
                                                    system.debug('listOFCampDays'+listOFCampDays);
            if(listOFCampDays != null && listOFCampDays.size() > 0){
                for(Camp_Days__c objCampDays : listOFCampDays){
                    if(objCampDays.Camp_Day_Teachers__r!= null && objCampDays.Camp_Day_Teachers__r.size() > 0){
                        set<string> campTeacherIds  = new set<string>();
                        for(Camp_Day_Teachers__c campDayTeachersObj :objCampDays.Camp_Day_Teachers__r){
                            teacherIds.add(campDayTeachersObj.Camp_Teacher__c);
                            campTeacherIds.add(campDayTeachersObj.Camp_Teacher__c);
                        }
                        if(objCampDays.Dates_Of_The_Camp__c != null){
                            campDaysTeachers.put(objCampDays.id,campTeacherIds);
                        }
                    }
                }
                List<Booking__c> listOfDeleteBooking = new List<Booking__c>();
                //system.debug('teacherIds'+teacherIds);
               // system.debug('campDaysTeachers'+campDaysTeachers);
                // get placeholder type bookings and then we check camp days and related teacher is found then we deleted this bookings
                Map<string,List<Booking__c>> mapOfCampDayBooking = getCampDayPlaceholderBooking(teacherIds,campDaysTeachers.keySet(),mapOfCamp.keySet());
               // system.debug('mapOfCampDayBooking'+mapOfCampDayBooking);
                for(string campDayId : mapOfCampDayBooking.keySet()){
                    List<Booking__c> listOfBooking = mapOfCampDayBooking.get(campDayId);
                    for(Booking__c objBooking:listOfBooking){
                        if(campDaysTeachers.containsKey(objBooking.Camp_Days__c)){
                            set<string> campTeacherIds  = campDaysTeachers.get(objBooking.Camp_Days__c);
                            if(campTeacherIds.contains(objBooking.Teacher_Account__c)){
                                listOfDeleteBooking.add(objBooking);
                            }
                        }
                    }
                }
                system.debug('listOfDeleteBooking'+listOfDeleteBooking);
                if(listOfDeleteBooking != null && listOfDeleteBooking.size() >0){
                    delete listOfDeleteBooking;
                }
                
            }
        }
    }

    // 19-Feb-2020: for get camp days place holder bookings for related teacher and camp_days id 
    // return map of dates and related date wise bookings
    public static Map<string,List<Booking__c>> getCampDayPlaceholderBooking(set<string> teacherIds,Set<String> campDaysIds,set<string> campIds){
        Map<string,List<Booking__c>> mapOfCampDayBooking = new Map<string,List<Booking__c>>();
        List<Booking__c> listOfPlaceholderBooking = new List<Booking__c>();
        if(teacherIds != null && campDaysIds != null && campIds != null && campIds.size() > 0 && campDaysIds.size() > 0 &&  teacherIds.size() > 0 )
        for(Booking__c objBooking: [Select Id,Camp_Days__c,Booking_Date__c,Teacher_Account__c FROM Booking__c
                where Teacher_Account__c In : teacherIds
                AND  recordType.Name  =:ConstantsClass.bookingRecordsTypeCampLesson
                //AND Camp_Id__c In : campIds
                AND Camp_Days__c In : campDaysIds
                AND Type__c =: ConstantsClass.typeBusy
                AND status__c =: ConstantsClass.scheduledStatus
                AND Category__c =: ConstantsClass.bookingCategoryCamp]){
                    listOfPlaceholderBooking = new List<Booking__c>();
                    if(mapOfCampDayBooking.containsKey(objBooking.Camp_Days__c)){
                        listOfPlaceholderBooking = mapOfCampDayBooking.get(objBooking.Camp_Days__c);
                    }
                    listOfPlaceholderBooking.add(objBooking);
                    mapOfCampDayBooking.put(objBooking.Camp_Days__c,listOfPlaceholderBooking);
        }
        return mapOfCampDayBooking;
    }
}