force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Online_Lesson_Passcode__c.field-meta.xml
<CustomField>
    <fullName>Online_Lesson_Passcode__c</fullName>
    <label>Online Lesson Passcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Online_Lesson_URL__c.field-meta.xml
<CustomField>
    <fullName>Online_Lesson_URL__c</fullName>
    <label>Online Lesson URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/MeetingRestApi.cls
@RestResource(urlMapping='/meetingservice/*')

global class MeetingRestApi {  
    @HttpGet
    global static Booking__c getBooking() {
       RestRequest req = RestContext.request;
        String bookingId = req.params.get('id');
        Booking__c bookingObj = new Booking__c();
        bookingId = '%'+bookingId+'%';
        bookingObj = [SELECT Online_Lesson_URL__c, Online_Lesson_Passcode__c, Id FROM Booking__c Where Online_Lesson_URL__c like:bookingId limit 1];
        return bookingObj;  
    }   
}