force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Camp_Days__c.field-meta.xml
<CustomField>
    <fullName>Camp_Days__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp class  for select customer Camp Day</description>
    <label>Camp Days</label>
    <referenceTo>Camp_Days__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Camp_Id__c.field-meta.xml
<CustomField>
    <fullName>Camp_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp class for manage select customer Camp name</description>
    <label>Camp Id</label>
    <referenceTo>Camp__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Break</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Hours in-lieu</fullName>
            </value>
            <value>
                <fullName>Recital</fullName>
            </value>
            <value>
                <fullName>Contract Programme</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>5th Lesson</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <description>This formula field is use for displaying name of center on booking object</description>
    <formula>Opportunity__r.Account.Name</formula>
    <label>Center Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
            <value>
                <fullName>Audition</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Group Class</fullName>
            </value>
            <value>
                <fullName>Group Lesson</fullName>
            </value>
            <value>
                <fullName>Piano Viewing</fullName>
            </value>
            <value>
                <fullName>Busy / Place holder</fullName>
                <isActive>false</isActive>
                <label>Busy / Place holder</label>
            </value>
            <value>
                <fullName>Notice</fullName>
                <isActive>false</isActive>
                <label>Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp__c/Camp__c.object-meta.xml
<CustomObject>
    <description>this object for manage camp class</description>
    <label>Camp</label>
    <nameField>
        <label>Camp  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>this field for camp class for manage camp Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/Camp_Day_Teachers__c.object-meta.xml
<CustomObject>
    <description>this object manage Camp Days related Teachers</description>
    <label>Camp Day Teachers</label>
    <nameField>
        <displayFormat>CampDayTeacher-{0000}</displayFormat>
        <label>Camp Day Teachers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Camp Day Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Camp_Day__c.field-meta.xml
<CustomField>
    <fullName>Camp_Day__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field lookup of camp day object</description>
    <label>Camp Day</label>
    <referenceTo>Camp_Days__c</referenceTo>
    <relationshipLabel>Camp Day Teachers</relationshipLabel>
    <relationshipName>Camp_Day_Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Camp_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Camp_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for manage camp teachers</description>
    <label>Camp Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camp Day Teachers</relationshipLabel>
    <relationshipName>Camp_Day_Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>this field manage teacher camp end time</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <description>this field manage teacher camp start time</description>
    <label>Start time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Days__c/Camp_Days__c.object-meta.xml
<CustomObject>
    <description>this object  for manage camp days</description>
    <label>Camp Days</label>
    <nameField>
        <label>Camp day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camp Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Name__c.field-meta.xml
<CustomField>
    <fullName>Camp_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Camp Name</label>
    <referenceTo>Camp__c</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Camp_Start_Time__c</fullName>
    <description>this field for camp days for manage Camp Start Time</description>
    <label>Camp Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Camp_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp days for manage Camp Teacher</description>
    <label>Camp Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Dates_Of_The_Camp__c.field-meta.xml
<CustomField>
    <fullName>Dates_Of_The_Camp__c</fullName>
    <description>this field for camp days for manage Dates Of The Camp</description>
    <label>Dates Of The Camp</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>this field for camp days for manage camp Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/Teacher_Working_Hour__c.object-meta.xml
<CustomObject>
    <label>Teacher Working Hour</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Teacher Working Hour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Working Hours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teacher_Working_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Working_Day__c.field-meta.xml
<CustomField>
    <fullName>Working_Day__c</fullName>
    <label>Working Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
            <value>
                <fullName>Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampDayTeacherTriggerHelper.cls
/*
    Name    : CampDayTeacherTriggerHelper 
   date: 4-Mar-2020
   author: jatin
   description : this triggerhelper for creating Placeholder for all camp teachers for the duration. 
                    
    
*/
public with sharing class CampDayTeacherTriggerHelper {
    // 4-Mar-2020:create placeholer type booking for camp teachers if camp status is active then we are createing otherwise not
    public static void createCampTeachersPlaceholder(Map<string,Camp_Day_Teachers__c> mapOfActiveCampTeachers) {
        List<Booking__c> listOfCampTeachersPlaceholder = new List<Booking__c>();
        if(mapOfActiveCampTeachers != null && mapOfActiveCampTeachers.size() >= 0){
            
            List<Camp_Day_Teachers__c> listOFCampDaysTeachers =  [select Camp_Teacher__c,End_Time__c,Start_time__c,Status__c,Camp_Day__c,Camp_Day__r.Camp_Name__r.Name,
                                                                    Camp_Day__r.Camp_Name__c,Camp_Day__r.Dates_Of_The_Camp__c,Camp_Day__r.Camp_Start_Time__c
                                                                    FROM Camp_Day_Teachers__c
                                                                    where Id In: mapOfActiveCampTeachers.keySet()
                                                                    And Camp_Day__r.Camp_Name__r.Status__c =: ConstantsClass.campActiveStatus];
          //  system.debug('listOFCampDaysTeachers'+listOFCampDaysTeachers);
            if(listOFCampDaysTeachers != null && listOFCampDaysTeachers.size() > 0){
                set<string> campTeacherIds = new set<string>();
                Set<string> campDays = new set<string>();
                map<string,id> mapOfCampTeacherDays = new map<string,id>();
                map<id,Camp_Day_Teachers__c> mapOfCampTeachers = new  map<id,Camp_Day_Teachers__c>();
                for(Camp_Day_Teachers__c campDayTeacherObj : listOFCampDaysTeachers){
                    campTeacherIds.add(campDayTeacherObj.Camp_Teacher__c);
                    campDays.add(DateTime.newInstance(campDayTeacherObj.Camp_Day__r.Dates_Of_The_Camp__c, campDayTeacherObj.Camp_Day__r.Camp_Start_Time__c).format('E'));
                    mapOfCampTeacherDays.put(campDayTeacherObj.id +'-'+campDayTeacherObj.Camp_Day__r.Dates_Of_The_Camp__c,
                    campDayTeacherObj.Camp_Teacher__c);
                }  
                map<string,list<Teacher_Working_Hour__c>> mapOfTeacherWorkingHours = new map<string,list<Teacher_Working_Hour__c>>();
                if(campTeacherIds != null && campDays != null && campTeacherIds.size() > 0 && campDays.size() > 0) 
                        mapOfTeacherWorkingHours = CampClassUtilityController.getTeacherWorkingHoursList(campTeacherIds,campDays,''); 
                
                        
                for(Camp_Day_Teachers__c campDayTeacherObj : listOFCampDaysTeachers){
                        listOfCampTeachersPlaceholder.AddAll(createPlaceholderForCampDayTeacher(campDayTeacherObj,
                                                            DateTime.newInstance(campDayTeacherObj.Camp_Day__r.Dates_Of_The_Camp__c, campDayTeacherObj.Camp_Day__r.Camp_Start_Time__c),
                                                            mapOfTeacherWorkingHours,mapOfCampTeacherDays ));
                }
                if(listOfCampTeachersPlaceholder != null && listOfCampTeachersPlaceholder.size() >0){
                    insert listOfCampTeachersPlaceholder;
                }
               // system.debug('listOfCampTeachersPlaceholder'+listOfCampTeachersPlaceholder);
            }
        }
    }

    // 19-Feb-2020:creating Placeholder for all camp teachers for the duration. This should be done once the camp is activated.
    Public static List<Booking__c> createPlaceholderForCampDayTeacher(Camp_Day_Teachers__c campDayTeacherObj,dateTime campDate,
                                                                    map<string,list<Teacher_Working_Hour__c>> mapOfTeacherWorkingHours,
                                                                    map<string,id> mapOfCampTeacherDays ){
        Booking__c placeholderObj = new Booking__c();
        String campLessonRecId =  Schema.SObjectType.Booking__c.getRecordTypeInfosByName().get(ConstantsClass.bookingRecordsTypeCampLesson).getRecordTypeId();    
                
        List<Booking__c> placeholderList = new List<Booking__c>();
        string campTeacherId ;
        if(mapOfCampTeacherDays.containsKey(campDayTeacherObj.Id+'-'+campDate.date())){
            campTeacherId = mapOfCampTeacherDays.get(campDayTeacherObj.Id+'-'+campDate.date());
        }
        //system.debug('campTeacherId'+campTeacherId);
        if(string.isNotBlank(campTeacherId)){
          //  system.debug('mapOfTeacherWorkingHours.containsKey(campDayTeacherObj.Camp_Teacher__c)'+mapOfTeacherWorkingHours.containsKey(campDayTeacherObj.Camp_Teacher__c));
            if(mapOfTeacherWorkingHours.containsKey(campDayTeacherObj.Camp_Teacher__c)){
                string centerId = '';
                //system.debug('mapOfTeacherWorkingHours.get(campDayTeacherObj.Camp_Teacher__c)'+mapOfTeacherWorkingHours.get(campDayTeacherObj.Camp_Teacher__c));
            
                for(Teacher_Working_Hour__c techWorkSchObj: mapOfTeacherWorkingHours.get(campDayTeacherObj.Camp_Teacher__c)){
                   // system.debug('techWorkSchObj.Working_Day__c'+techWorkSchObj.Working_Day__c);
                   // system.debug('campDate.format(E)'+campDate.format('E'));
                    
                    if(techWorkSchObj.Working_Day__c.equalsIgnoreCase(campDate.format('E'))){
                        centerId = techWorkSchObj.Center_Name__c;
                    }
                }
               // system.debug('centerId'+centerId);
                if(string.isNotBlank(centerId)){
                    placeholderObj = CampClassUtilityController.createCampBooking('','',campDate.date(),campDayTeacherObj.End_Time__c,campDayTeacherObj.Start_time__c,
                                                                            centerId,'',/*campDayTeacherObj.Camp_Day__r.Camp_Name__c*/'',campDayTeacherObj.Camp_Day__c,
                                                                            campDayTeacherObj.Camp_Teacher__c);
                    placeholderObj.Type__c = ConstantsClass.typeBusy;
                    placeholderObj.status__c = ConstantsClass.scheduledStatus;
                    placeholderObj.remarks__c = campDayTeacherObj.Camp_Day__r.Camp_Name__r.Name + '.';
                    placeholderObj.recordTypeId = campLessonRecId;
                    placeholderObj.Category__c = ConstantsClass.bookingCategoryCamp;
                    placeholderList.add(placeholderObj);
                }
            }
        }
            
        
       // system.debug('placeholderList'+placeholderList);
        return placeholderList;
        
    }

    // update camp placeholder bookings if camp day teacher not change status they change other fields 
    public static void UpdateCampTeachersPlaceholder(Map<string,Camp_Day_Teachers__c> mapOfUpdateNewCampTeacher,Map<string,Camp_Day_Teachers__c> mapOfUpdateOldCampTeacher){
        map<string,Set<String>> mapOfupdateOldCampDayTeacher = new  map<string,Set<String>>();
        set<string> campTeacherIds  = new set<string>();
        set<string> teacherIds = new  set<string>();
       // system.debug('!!mapOfUpdateNewCampTeacher'+mapOfUpdateNewCampTeacher);
        // system.debug('!!mapOfUpdateOldCampTeacher'+mapOfUpdateOldCampTeacher);
        Map<Id,Camp_Day_Teachers__c> mapOfNewCampDaysTeachers =  new Map<Id,Camp_Day_Teachers__c>([select Camp_Teacher__c,End_Time__c,Start_time__c,Status__c,Camp_Day__c,
                                                            Camp_Day__r.Camp_Name__c,Camp_Day__r.Dates_Of_The_Camp__c,Camp_Day__r.Camp_Start_Time__c
                                                            FROM Camp_Day_Teachers__c
                                                            where Id In:mapOfUpdateNewCampTeacher.keySet()
                                                            And Camp_Day__r.Camp_Name__r.Status__c =: ConstantsClass.campActiveStatus]);
        //system.debug('!!mapOfNewCampDaysTeachers'+mapOfNewCampDaysTeachers);
        //system.debug('mapOfUpdateOldCampTeacher'+mapOfUpdateOldCampTeacher);
        for(Camp_Day_Teachers__c objCampTeacher : mapOfUpdateOldCampTeacher.values()){ 
            if(mapOfupdateOldCampDayTeacher.containsKey(objCampTeacher.Camp_Day__c)){
                campTeacherIds = mapOfupdateOldCampDayTeacher.get(objCampTeacher.Camp_Day__c);
            }
            campTeacherIds.add(objCampTeacher.id);
            mapOfupdateOldCampDayTeacher.put(objCampTeacher.Camp_Day__c,campTeacherIds);
            teacherIds.add(objCampTeacher.Camp_Teacher__c);
        }
    //   system.debug('!!mapOfupdateOldCampDayTeacher'+mapOfupdateOldCampDayTeacher);
        if(mapOfupdateOldCampDayTeacher != null && mapOfupdateOldCampDayTeacher.size() >= 0){
            List<Booking__c> listOfPlaceholderBooking = getAllCampDayPlaceholderBooking(teacherIds,mapOfupdateOldCampDayTeacher.keySet());
           // system.debug('!!listOfPlaceholderBooking'+listOfPlaceholderBooking);
            if(listOfPlaceholderBooking != null && mapOfNewCampDaysTeachers != null && mapOfNewCampDaysTeachers.size() > 0 &&  listOfPlaceholderBooking.size() > 0){
                for(Booking__c objBooking:listOfPlaceholderBooking){
                    if(mapOfupdateOldCampDayTeacher.containsKey(objBooking.Camp_Days__c)){
                        for(string campDayTeacherId : mapOfupdateOldCampDayTeacher.get(objBooking.Camp_Days__c)){
                            if(mapOfNewCampDaysTeachers.containsKey(campDayTeacherId)){
                                if(mapOfNewCampDaysTeachers.get(campDayTeacherId).Start_time__c != null)
                                    objBooking.Start_Time__c = mapOfNewCampDaysTeachers.get(campDayTeacherId).Start_time__c;   
                                if(mapOfNewCampDaysTeachers.get(campDayTeacherId).End_Time__c != null)
                                    objBooking.End_Time__c = mapOfNewCampDaysTeachers.get(campDayTeacherId).End_Time__c;
                                if(mapOfNewCampDaysTeachers.get(campDayTeacherId).Camp_Day__r.Dates_Of_The_Camp__c != null)
                                    objBooking.Booking_Date__c = mapOfNewCampDaysTeachers.get(campDayTeacherId).Camp_Day__r.Dates_Of_The_Camp__c; 
                                if(string.isNotBlank(mapOfNewCampDaysTeachers.get(campDayTeacherId).Camp_Day__c))
                                    objBooking.Camp_Days__c = mapOfNewCampDaysTeachers.get(campDayTeacherId).Camp_Day__c;
                                /*if(string.isNotBlank(mapOfNewCampDaysTeachers.get(campDayTeacherId).Camp_Day__r.Camp_Name__c))
                                    objBooking.Camp_Id__c = mapOfNewCampDaysTeachers.get(campDayTeacherId).Camp_Day__r.Camp_Name__c; */
                            }
                        }
                    }
                }
            }
           // system.debug('!!listOfPlaceholderBooking'+listOfPlaceholderBooking);
            if(listOfPlaceholderBooking != null && listOfPlaceholderBooking.size() >0){
                update listOfPlaceholderBooking;
            }
        }
    }
    // 4-mar-2020: delete all active camp teacher 'placeholder' type  bookings if campteacher  is deleted or change status 
    public static void deleteCampTeachersPlaceholder(map<string,Set<String>> mapOfCancelledCampTeacher) {
        List<Booking__c> listOfCampTeachersPlaceholder = new List<Booking__c>();
        //system.debug('mapOfCancelledCampTeacher'+mapOfCancelledCampTeacher);
        if(mapOfCancelledCampTeacher != null && mapOfCancelledCampTeacher.size() >= 0){
            set<string> teacherIds = new  set<string>();
            for(string campDayId :  mapOfCancelledCampTeacher.keySet()){
                teacherIds.addAll(mapOfCancelledCampTeacher.get(campDayId));
            }
            List<Booking__c> listOfDeleteBooking = new List<Booking__c>();
           // system.debug('teacherIds'+teacherIds);
            //system.debug('mapOfCancelledCampTeacher'+mapOfCancelledCampTeacher);
            // get placeholder type bookings and then we check camp days and related teacher is found then we deleted this bookings
            Map<string,List<Booking__c>> mapOfCampDayBooking = getCampDayPlaceholderBooking(teacherIds,mapOfCancelledCampTeacher.keySet());
           // system.debug('mapOfCampDayBooking'+mapOfCampDayBooking);
            if(mapOfCampDayBooking != null && mapOfCampDayBooking.size() > 0){
                for(string campDayId : mapOfCampDayBooking.keySet()){
                    List<Booking__c> listOfBooking = mapOfCampDayBooking.get(campDayId);
                    for(Booking__c objBooking:listOfBooking){
                        if(mapOfCancelledCampTeacher.containsKey(objBooking.Camp_Days__c)){
                            set<string> campTeacherIds  = mapOfCancelledCampTeacher.get(objBooking.Camp_Days__c);
                            if(campTeacherIds.contains(objBooking.Teacher_Account__c)){
                                listOfDeleteBooking.add(objBooking);
                            }
                        }
                    }
                }
            }
          //  system.debug('listOfDeleteBooking'+listOfDeleteBooking);
            if(listOfDeleteBooking != null && listOfDeleteBooking.size() >0){
                delete listOfDeleteBooking;
            }
                
        }
    }
// 4-mar-2020: for get camp days place holder bookings for related teacher and camp_days id 
    // return map of dates and related date wise bookings
    public static List<Booking__c> getAllCampDayPlaceholderBooking(set<string> teacherIds,Set<String> campDaysIds){
        List<Booking__c> listOfPlaceholderBooking = new List<Booking__c>();
        if(teacherIds != null && campDaysIds != null && campDaysIds.size() > 0 &&  teacherIds.size() > 0 ){
         listOfPlaceholderBooking  = [Select Id,Camp_Days__c,Booking_Date__c,Teacher_Account__c FROM Booking__c
                where Teacher_Account__c In : teacherIds
                AND  recordType.Name  =:ConstantsClass.bookingRecordsTypeCampLesson
                AND Camp_Days__c In : campDaysIds
                AND Camp_Days__r.Camp_Name__r.Status__c =: ConstantsClass.campActiveStatus
                AND Type__c =: ConstantsClass.typeBusy
                AND status__c =: ConstantsClass.scheduledStatus
                AND Category__c =: ConstantsClass.bookingCategoryCamp];
            return listOfPlaceholderBooking;
        }
        return listOfPlaceholderBooking;
    }
    // 4-mar-2020: for get camp days place holder bookings for related teacher and camp_days id 
    // return map of dates and related date wise bookings
    public static Map<string,List<Booking__c>> getCampDayPlaceholderBooking(set<string> teacherIds,Set<String> campDaysIds){
       
        Map<string,List<Booking__c>> mapOfCampDayBooking = new Map<string,List<Booking__c>>();
        List<Booking__c> listOfPlaceholderBooking = new List<Booking__c>();
        if(teacherIds != null && campDaysIds != null && campDaysIds.size() > 0 &&  teacherIds.size() > 0 ){
            List<Booking__c> listOfAllCampDayPlaceholderBooking =  getAllCampDayPlaceholderBooking(teacherIds,campDaysIds);
            if(listOfAllCampDayPlaceholderBooking != null && listOfAllCampDayPlaceholderBooking.size() > 0){
                for(Booking__c objBooking: listOfAllCampDayPlaceholderBooking){
                    listOfPlaceholderBooking = new List<Booking__c>();
                    if(mapOfCampDayBooking.containsKey(objBooking.Camp_Days__c)){
                        listOfPlaceholderBooking = mapOfCampDayBooking.get(objBooking.Camp_Days__c);
                    }
                    listOfPlaceholderBooking.add(objBooking);
                    mapOfCampDayBooking.put(objBooking.Camp_Days__c,listOfPlaceholderBooking);
                }
            }
        }   
       // system.debug('mapOfCampDayBooking'+mapOfCampDayBooking);
        return mapOfCampDayBooking;
    }

}