force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Is_fifth_booking__c.field-meta.xml
<CustomField>
    <fullName>Is_fifth_booking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is fifth booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to create lesson booking</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/classes/FifthBookingReminderSchedularTest.cls
/*
Name        :        FifthBookingReminderSchedularTest
Date        :        5 April 2019
Author      :        Karan Singh Soni
Description :        It is the test class of FifthBookingReminderSchedular.
*/
@istest
public class FifthBookingReminderSchedularTest {
    public static testMethod void invokeFifthBookingReminderSchedular(){
        Account objtchr=TestUtil.createAccount('Teacher',false,true);
        Account objCustmr=TestUtil.createAccount('Customer', True, true);
        Booking__c objBook=TestUtil.createBooking(objtchr.id,'Lesson','Regular', False);
        objBook.Is_fifth_booking__c=True;
        objBook.Student__c=objCustmr.id;
        objBook.Booking_Date__c=Date.today().addDays(10);
        insert objBook;
        FifthBookingReminderSchedular objFifthBookRem= new FifthBookingReminderSchedular();
        objFifthBookRem.execute(null);
     
    }
}