force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>(End_Time__c - Start_Time__c )/(60*1000)

/*IF( RecordType.Name = &apos;Facility&apos;, (End_Time__c - Start_Time__c )/(60*1000), If( ISPICKVAL( Package__r.Duration__c , &apos;Trial&apos;)  , value(&apos;30&apos;),  value(Text(Package__r.Duration__c))))
*/
/*Commented by Rajesh on 26th June 2019, To correct the actual duration for the studio booking

If( ISPICKVAL( Package__r.Duration__c , &apos;Trial&apos;)  , value(&apos;30&apos;),  value(Text(Package__r.Duration__c)))*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Durations in Minutes</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Is_fifth_booking__c.field-meta.xml
<CustomField>
    <fullName>Is_fifth_booking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is fifth booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
            <value>
                <fullName>Audition</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Group Class</fullName>
            </value>
            <value>
                <fullName>Group Lesson</fullName>
            </value>
            <value>
                <fullName>Piano Viewing</fullName>
            </value>
            <value>
                <fullName>Busy / Place holder</fullName>
                <isActive>false</isActive>
                <label>Busy / Place holder</label>
            </value>
            <value>
                <fullName>Notice</fullName>
                <isActive>false</isActive>
                <label>Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>From related Package
Used in Reports</description>
    <formula>TEXT( Package__r.Duration__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Next_Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Bill_Date__c</fullName>
    <formula>prepayment_period_end_date__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_To_Be_Change__c.field-meta.xml
<CustomField>
    <fullName>Package_To_Be_Change__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package To Be Change</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Enrolments (Package To Be Change)</relationshipLabel>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Promotional_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Period_End_Date__c</fullName>
    <label>Promotional Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type_of_Package__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Package__c</fullName>
    <description>From related Package</description>
    <formula>TEXT( Package__r.Type_of_package__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type of Package</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Session duration in minutes (Trial will be 30 min)</inlineHelpText>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Is_Promotion_Discount__c.field-meta.xml
<CustomField>
    <fullName>Is_Promotion_Discount__c</fullName>
    <formula>AND(
   NOT(ISBLANK(TEXT(Promotion_period_In_months__c))),
   Promotion_Discount__c &gt; 0,
   NOT(ISBLANK(Package_after_Promotion__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Promotion Discount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Package_after_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Package_after_Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package after Promotion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Package__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Lesson</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Promotion_Discount__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Discount__c</fullName>
    <label>Promotion Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Promotion_period_In_months__c.field-meta.xml
<CustomField>
    <fullName>Promotion_period_In_months__c</fullName>
    <label>Promotion period (In months)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Type_of_package__c.field-meta.xml
<CustomField>
    <fullName>Type_of_package__c</fullName>
    <label>Type of package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Promo</fullName>
            </value>
            <value>
                <fullName>Prepayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Next_Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Bill_Date__c</fullName>
    <label>Next Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PackageUpdateEnrolmentBatch.cls
/*
        Name        :    PackageUpdateEnrolmentBatch
        Date        :    02/04/2019
        Description :    This batch class is Update regular package on the Enrolments which are linked with the discounted package
*/
global class PackageUpdateEnrolmentBatch implements Database.Batchable<sObject>,database.stateful,Database.AllowsCallouts{
	
    global Database.QueryLocator start(Database.BatchableContext BC){
    	return Database.getQueryLocator([SELECT Id, Name, Package__c, Package_To_Be_Change__c, Promotional_Period_End_Date__c
                                         FROM Enrolment__c 
                                         WHERE Promotional_Period_End_Date__c <= TODAY AND Package_To_Be_Change__c != null 
                                         	   AND Package__r.Type_Of_Package__c IN ('Promo','Prepayment')]);
    }
    
    global void execute(Database.BatchableContext BC, List<Enrolment__c> enrList){
        
        if(enrList.size() > 0){
           
        	//Added by Rajesh: 25th June 2019, Updating promotional package with the regular package in the bookings
            List<Booking__c> bookUpdList = new List<Booking__c>();
            for(Booking__c objBooking : [SELECT Id,End_Time__c,Start_Time__c, Package__c, Enrolment__c, Enrolment__r.Package__c, Enrolment__r.Package_To_Be_Change__c, 
                                         		Enrolment__r.Promotional_Period_End_Date__c, Booking_Date__c 
                                         FROM Booking__c 
                                         WHERE RecordType.Name =: ConstantsClass.recordTypeLesson AND Booking_Date__c > TODAY AND Enrolment__c IN :enrList]){
                                              
                if(objBooking.Booking_Date__c > objBooking.Enrolment__r.Promotional_Period_End_Date__c && objBooking.Package__c == objBooking.Enrolment__r.Package__c){      
                    objBooking.Package__c = objBooking.Enrolment__r.Package_To_Be_Change__c;
                    bookUpdList.add(objBooking);
                }
            }
            
            if(bookUpdList.size() > 0)
                update bookUpdList;
            
            for(Enrolment__c enr : enrList){
            	enr.Package__c = enr.Package_To_Be_Change__c;       
                enr.Promotional_Period_End_Date__c = null;
            }
            update enrList;
        }
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
    /* 
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Added by rajesh, 25th June 2019- Added some promotinal package related fields for update enrolment and bookings with the new package
    	return Database.getQueryLocator([SELECT Id, Name, Next_Bill_Date__c, Enrolment__c, Enrolment__r.Package__c, Enrolment__r.Package__r.Promotion_period_In_months__c, Enrolment__r.Package_To_Be_Change__c, Enrolment__r.Promotional_Period_End_Date__c,
                                         Enrolment__r.Package__r.Promotion_Discount__c, Enrolment__r.Package__r.Package_after_Promotion__c, Enrolment__r.Package__r.Is_Promotion_Discount__c 
                                         FROM Subscription_Line_Item__c 
                                         WHERE Next_Bill_Date__c = NEXT_MONTH AND Enrolment__r.Package__r.Promotion_period_In_months__c != null
                                         	   AND Enrolment__r.Package__r.Promotion_Discount__c != null AND Enrolment__r.Package_To_Be_Change__c != null AND 
                                         	   Enrolment__r.Promotional_Period_End_Date__c != null AND Enrolment__r.Package__r.Is_Promotion_Discount__c = True]);
    }
    
    global void execute(Database.BatchableContext BC, List<Subscription_Line_Item__c> subLineItemList){
        List<Enrolment__c> updEnrList = new List<Enrolment__c>();
        
        //Added by Rajesh: 24th June 2019, processing subscription line items with the enrolment and populating regular package in the enrolment
        for(Subscription_Line_Item__c subLnItm : subLineItemList){
            updEnrList.add(new Enrolment__c(Id = subLnItm.Enrolment__c, 
                                            Package__c = subLnItm.Enrolment__r.Package_To_Be_Change__c));
        }
		
		        
        if(updEnrList.size() > 0){
            update updEnrList;
        	
            //Added by Rajesh: 25th June 2019, Updating promotional package with the regular package in the bookings
            List<Booking__c> bookUpdList = new List<Booking__c>();
            for(Booking__c objBooking : [SELECT Id,End_Time__c,Start_Time__c, Package__c, Package__r.Duration__c, Enrolment__c, Enrolment__r.Package__c, Enrolment__r.Promotional_Period_End_Date__c, Booking_Date__c FROM Booking__c WHERE RecordType.Name =: ConstantsClass.recordTypeLesson
                                            AND Enrolment__c IN :updEnrList AND Booking_Date__c >= today AND (Type__c =: ConstantsClass.typeRegular OR IS_Fifth_Booking__c = TRUE)
                                          AND Status__c !=: ConstantsClass.statusCanceled]){
                                              
                if(objBooking.Booking_Date__c > objBooking.Enrolment__r.Promotional_Period_End_Date__c){      
                    objBooking.Package__c = objBooking.Enrolment__r.Package__c;
                    bookUpdList.add(objBooking);
                }
            }
            
            if(bookUpdList.size() > 0)
                update bookUpdList;
        }
    }
    
    global void finish(Database.BatchableContext BC){
    } */   
}