force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Day__c.field-meta.xml
<CustomField>
    <fullName>Booking_Day__c</fullName>
    <formula>CASE(WEEKDAY( Booking_Date__c), 
1, &apos;Sun&apos;, 
2, &apos;Mon&apos;, 
3, &apos;Tue&apos;, 
4, &apos;Wed&apos;, 
5, &apos;Thu&apos;, 
6, &apos;Fri&apos;, 
&apos;Sat&apos;)</formula>
    <label>Booking Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Break</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Hours in-lieu</fullName>
            </value>
            <value>
                <fullName>Recital</fullName>
            </value>
            <value>
                <fullName>Contract Programme</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>5th Lesson</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Centre)</relationshipLabel>
    <relationshipName>CenterBooking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <description>This formula field is use for displaying name of center on booking object</description>
    <formula>Opportunity__r.Account.Name</formula>
    <label>Center Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Name__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Name__c</fullName>
    <formula>Teacher_Account__r.FirstName +&apos; &apos;+Teacher_Account__r.LastName</formula>
    <label>Teacher Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
            <value>
                <fullName>Audition</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Group Class</fullName>
            </value>
            <value>
                <fullName>Group Lesson</fullName>
            </value>
            <value>
                <fullName>Piano Viewing</fullName>
            </value>
            <value>
                <fullName>Busy / Place holder</fullName>
                <isActive>false</isActive>
                <label>Busy / Place holder</label>
            </value>
            <value>
                <fullName>Notice</fullName>
                <isActive>false</isActive>
                <label>Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to create lesson booking</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (Centre)</relationshipLabel>
    <relationshipName>Enrolments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>ABRSM</fullName>
            </value>
            <value>
                <fullName>Diploma/Grand</fullName>
            </value>
            <value>
                <fullName>比赛练习琴房</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/Teacher_Working_Hour__c.object-meta.xml
<CustomObject>
    <label>Teacher Working Hour</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Teacher Working Hour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Working Hours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teacher_Working_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Teacher_Name__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teacher Working Hours</relationshipLabel>
    <relationshipName>Teacher_Working_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Working_Day__c.field-meta.xml
<CustomField>
    <fullName>Working_Day__c</fullName>
    <label>Working Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
            <value>
                <fullName>Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TeacherWorkingHandler.cls
public class TeacherWorkingHandler {
    
    public static void createBooking(list<Teacher_Working_Hour__c> workingList){
        list<Booking__c> bkgList = new list<Booking__c>();
        Id bookingRecordType = Schema.SObjectType.booking__c.getRecordTypeInfosByName().get('Lesson').getRecordTypeId(); // Record type of Booking Record
        for(Teacher_Working_Hour__c twh:workingList){
            string startDay = twh.Working_Day__c;  
            date startDate  =system.today();
            Boolean IsDate  = true;
            while(IsDate){
                DateTime myCalDay = (DateTime) startDate;
                if(myCalDay.format('EEE') == startDay){
                    break;
                }
                startDate = startDate.addDays(1);
            }
            date endDate=startDate.addYears(1);    // End date of a year
            while(startDate <= endDate){
                DateTime myDateTime = (DateTime) startDate;
                if(myDateTime.format('EEE') == startDay){  //  Checking and Comparing the selected day 
                    booking__c bkng = new booking__c();
                    bkng.Center__c          = twh.Center_Name__c;
                    bkng.RecordTypeId 		= bookingRecordType;
                    bkng.Booking_Date__c	= startDate;
                    bkng.Teacher_Account__c = twh.Teacher_Name__c;
                    bkng.Start_Time__c 		= twh.Start_Time__c;
                    bkng.End_Time__c		= twh.End_Time__c;
                    bkng.Status__c 			= ConstantsClass.scheduledStatus;
                    bkng.Type__c			= 'Busy';
                    bkng.Category__c 		= 'Lunch';
                    bkng.Remarks__c			= 'Break hours'; 
                    bkgList.add(bkng);  //Added the list of Booking data for all the day in a year 
                }
                startDate=startDate.addDays(7);   
            }
        }
        if(bkgList.size()>0){
           insert bkgList;
        }
            	        
    }

    public static List<Booking__C> getAllEnrolledEnrolmentBookings(Set<string> centerIds,Set<string> resourceIds,map<String,string> teacherWorkingDays){
        Set<string> bookingType = new Set<string>{ConstantsClass.bookTypeRegular,ConstantsClass.typeMakeup,ConstantsClass.typeAdhoc,ConstantsClass.typeTrial};
        date currentDate = system.today();    
        String statusCanceled = ConstantsClass.statusCanceled;
        String enroledStatus = ConstantsClass.enroledStatus;
        String enrolRegularStatus = ConstantsClass.typeRegular;
        String online = ConstantsClass.Online;
         system.debug('centerIds'+centerIds);
        system.debug('resourceIds'+resourceIds);
        string query ='SELECT Id, Booking_Day__c, Resource__c,Start_Time__c ,End_Time__c,Enrolment__c,Teacher_Account__c,Center__c ';
        query += ' FROM Booking__c ';
        query += ' WHERE Enrolment__r.Type__c=:enrolRegularStatus';
        //query += ' And (Enrolment__r.Lesson_Mode__c !=: online Or Lesson_Type__c !=:  online) ';
        query += ' AND Enrolment__r.Stage__c=:enroledStatus';
        query += ' AND Type__c In:bookingType';
        query += ' AND Status__c!=:statusCanceled';
        query += ' AND Booking_date__c>=: currentDate';
        if(centerIds != Null && centerIds.size() > 0){
            query += ' AND Enrolment__r.Center__c In:centerIds';
        }
        if(resourceIds != Null && resourceIds.size() > 0){
            query += ' AND Enrolment__r.Resource__c In:resourceIds';
        }
        if(teacherWorkingDays != Null && teacherWorkingDays.size() > 0){
            List<string> workingDays = teacherWorkingDays.values();
            query += ' AND Booking_Day__c In:workingDays';
            Set<string> teacherIds = teacherWorkingDays.Keyset();
            query += ' AND Teacher_Account__c In:teacherIds';
            system.debug('workingDays'+workingDays);
            system.debug('teacherIds'+teacherIds);
        }
        system.debug('query'+query);
        List<Booking__C> listOfBookings = DataBase.query(query);
        system.debug('listOfBookings'+listOfBookings);
        return listOfBookings;
    }

    Public static void updateNewResourceAccordingToResource(Map<String,map<Id,Teacher_Working_Hour__c>> mapOfOldResourcesWithUpdatedTeachWorkHrs,Set<string> centerIds,map<String,string> teacherWorkingDays){
        if(mapOfOldResourcesWithUpdatedTeachWorkHrs != null && mapOfOldResourcesWithUpdatedTeachWorkHrs.size() > 0){
            List<Booking__C> listOfBookings = getAllEnrolledEnrolmentBookings(centerIds,mapOfOldResourcesWithUpdatedTeachWorkHrs.keySet(),teacherWorkingDays);
            map<id,Enrolment__c> mapOfEnrolment = new  map<id,Enrolment__c>();
            if(listOfBookings != null && listOfBookings.size() >0){
                for(Booking__C objBooking : listOfBookings){
                    if(mapOfOldResourcesWithUpdatedTeachWorkHrs.containsKey(objBooking.Resource__c)){
                        map<Id,Teacher_Working_Hour__c> mapOfUpdatedteachWorkHrs = mapOfOldResourcesWithUpdatedTeachWorkHrs.get(objBooking.Resource__c);
                        if(mapOfUpdatedteachWorkHrs != Null && mapOfUpdatedteachWorkHrs.size() > 0 ){
                            for(Teacher_Working_Hour__c objUpdatedteachWorkHrs : mapOfUpdatedteachWorkHrs.values()){
                                if(objBooking.Teacher_Account__c == objUpdatedteachWorkHrs.Teacher_Name__c &&
                                    objBooking.Booking_Day__c == objUpdatedteachWorkHrs.Working_Day__c &&
                                    objBooking.Start_Time__c >= objUpdatedteachWorkHrs.Start_Time__c
                                    && objBooking.End_Time__c <= objUpdatedteachWorkHrs.End_Time__c){
                                    objBooking.Resource__c = objUpdatedteachWorkHrs.Resource__c;
                                    mapOfEnrolment.put(objBooking.enrolment__C,new Enrolment__c (id= objBooking.enrolment__C,Resource__c = objUpdatedteachWorkHrs.Resource__c));
                                    system.debug('objBooking'+objBooking);
                                }
                            }
                        }   
                    }
                }
                update listOfBookings;
                system.debug('listOfBookings'+listOfBookings.size());
                system.debug('mapOfEnrolment'+mapOfEnrolment.size());
                if(mapOfEnrolment != null && mapOfEnrolment.size() > 0){
                    update mapOfEnrolment.values();
                    system.debug('mapOfEnrolment'+mapOfEnrolment);
                }
            }
        }
    }

    Public static void updateNewResourceAccordingToCenter(Map<String,map<Id,Teacher_Working_Hour__c>> mapOfCenterWithUpdatedTeachWorkHrs,map<String,string> teacherWorkingDays){
        if(mapOfCenterWithUpdatedTeachWorkHrs != null && mapOfCenterWithUpdatedTeachWorkHrs.size() >0){
            List<Booking__C> listOfBookings = getAllEnrolledEnrolmentBookings(mapOfCenterWithUpdatedTeachWorkHrs.keySet(),new Set<string>(),teacherWorkingDays);
            system.debug('listOfBookings'+listOfBookings);
            if(listOfBookings != null && listOfBookings.size() > 0){
                map<id,Enrolment__c> mapOfEnrolment = new  map<id,Enrolment__c>();
                for(Booking__C objBooking : listOfBookings){
                    if(mapOfCenterWithUpdatedTeachWorkHrs.containsKey(objBooking.Center__c)){
                        map<Id,Teacher_Working_Hour__c> mapOfUpdatedteachWorkHrs = mapOfCenterWithUpdatedTeachWorkHrs.get(objBooking.Center__c);
                         if(mapOfUpdatedteachWorkHrs != null && mapOfUpdatedteachWorkHrs.size() > 0){
                            for(Teacher_Working_Hour__c objUpdatedteachWorkHrs : mapOfUpdatedteachWorkHrs.values()){
                                if(objBooking.Teacher_Account__c == objUpdatedteachWorkHrs.Teacher_Name__c &&
                                    objBooking.Booking_Day__c == objUpdatedteachWorkHrs.Working_Day__c &&
                                    objBooking.Start_Time__c >= objUpdatedteachWorkHrs.Start_Time__c
                                    && objBooking.End_Time__c <= objUpdatedteachWorkHrs.End_Time__c){
                                    objBooking.Resource__c = objUpdatedteachWorkHrs.Resource__c;
                                    //system.debug('objBooking'+objBooking);
                                    mapOfEnrolment.put(objBooking.enrolment__C,new Enrolment__c (id= objBooking.enrolment__C,Resource__c = objUpdatedteachWorkHrs.Resource__c));
                                }
                            }
                            
                        }   
                    }
                }
                update listOfBookings;
                system.debug('listOfBookings'+listOfBookings.size());
                system.debug('mapOfEnrolment'+mapOfEnrolment.size());
                if(mapOfEnrolment != null && mapOfEnrolment.size() > 0){
                    system.debug('listOfEnrolment'+mapOfEnrolment);
                    update mapOfEnrolment.values();
                }
            }
        }
    }

    
}