force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Employee_Cost_Centre__c/Employee_Cost_Centre__c.object-meta.xml
<CustomObject>
    <label>Employee Cost Centre</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Cost Centre ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Cost Centre</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Cost_Centre__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Cost Centre (Centre)</relationshipLabel>
    <relationshipName>Employee_Cost_Centre1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Cost_Centre__c/fields/Cost_to_Centre__c.field-meta.xml
<CustomField>
    <fullName>Cost_to_Centre__c</fullName>
    <label>Cost % to Centre</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Employee_Cost_Centre__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Cost Centre</relationshipLabel>
    <relationshipName>Employee_Cost_Centre</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Cost_Centre__c/fields/Payout__c.field-meta.xml
<CustomField>
    <fullName>Payout__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payout</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payout__c.Employee_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Employee__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payout__c</referenceTo>
    <relationshipLabel>Employee Cost Centre</relationshipLabel>
    <relationshipName>Employee_Cost_Centre</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Cost_Centre__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <formula>Payout__r.Payout_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PayItem__c/PayItem__c.object-meta.xml
<CustomObject>
    <label>PayItem</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>PayItem No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PayItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PayItem__c/fields/Payitem__c.field-meta.xml
<CustomField>
    <fullName>Payitem__c</fullName>
    <label>Payitem</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payitem_Master__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payitem_Master__c</referenceTo>
    <relationshipLabel>PayItem</relationshipLabel>
    <relationshipName>Payitems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PayItem__c/fields/Payout__c.field-meta.xml
<CustomField>
    <fullName>Payout__c</fullName>
    <label>Payout</label>
    <referenceTo>Payout__c</referenceTo>
    <relationshipLabel>PayItem</relationshipLabel>
    <relationshipName>PayItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payout__c/Payout__c.object-meta.xml
<CustomObject>
    <label>Payout</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Pay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payout__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Payrolls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <formula>DATE(VALUE(TEXT(Year__c)),CASE(Month__c,&apos;January&apos;, 1,&apos;February&apos;,2,&apos;March&apos;,3,&apos;April&apos;,4,&apos;May&apos;,5,&apos;June&apos;,6,&apos;July&apos;,7,&apos;August&apos;,8,&apos;September&apos;,9,&apos;October&apos;,10,&apos;November&apos;,11,12),1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Future_Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rostering__c/Rostering__c.object-meta.xml
<CustomObject>
    <label>Rostering</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Rostering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rosterings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rostering__c/fields/Additional_Work_Day__c.field-meta.xml
<CustomField>
    <fullName>Additional_Work_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional Work Day</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rostering__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rosterings (Centre)</relationshipLabel>
    <relationshipName>RosteringCentre</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rostering__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rosterings</relationshipLabel>
    <relationshipName>Rosterings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rostering__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rostering__c/fields/PayItem__c.field-meta.xml
<CustomField>
    <fullName>PayItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PayItem</label>
    <referenceTo>PayItem__c</referenceTo>
    <relationshipLabel>Rosterings</relationshipLabel>
    <relationshipName>Rosterings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rostering__c/fields/Shift__c.field-meta.xml
<CustomField>
    <fullName>Shift__c</fullName>
    <label>Shift</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Regular Hours</fullName>
            </value>
            <value>
                <fullName>Opening Hours</fullName>
            </value>
            <value>
                <fullName>Closing Hours</fullName>
            </value>
            <value>
                <fullName>Exam Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rostering__c/fields/Work_Day__c.field-meta.xml
<CustomField>
    <fullName>Work_Day__c</fullName>
    <label>Work Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Day</fullName>
            </value>
            <value>
                <fullName>Half Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/Teacher_Working_Hour__c.object-meta.xml
<CustomObject>
    <label>Teacher Working Hour</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Teacher Working Hour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Working Hours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Break_Time__c.field-meta.xml
<CustomField>
    <fullName>Break_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select the checkbox to create a break schedule</inlineHelpText>
    <label>Break Time</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teacher_Working_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <formula>Center_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Centre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Teacher_Name__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teacher Working Hours</relationshipLabel>
    <relationshipName>Teacher_Working_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Working_Day__c.field-meta.xml
<CustomField>
    <fullName>Working_Day__c</fullName>
    <label>Working Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
            <value>
                <fullName>Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateEmployeeCostToCentreBatch.cls
global class GenerateEmployeeCostToCentreBatch implements Database.Batchable<sObject>, Database.Stateful{
    global Set<Id> accountIdSet = new Set<Id>();
    global Date batchProcessDate = system.today();
    global String mString;
    global String yString;
    global GenerateEmployeeCostToCentreBatch(){
        
    }
    
    global GenerateEmployeeCostToCentreBatch(Set<Id> accountIdSet){
        this.accountIdSet = accountIdSet;
    }
    global GenerateEmployeeCostToCentreBatch(Set<Id> accountIdSet, Date batchProcessDate ){
        this.accountIdSet = accountIdSet;
        this.batchProcessDate = batchProcessDate;    
    }
    
    global GenerateEmployeeCostToCentreBatch(Date batchProcessDate ){
        this.batchProcessDate = batchProcessDate ;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id FROM Account WHERE RecordType.Name IN (\'Employee\',\'Teacher\') ';
        if(accountIdSet != null && !accountIdSet.isEmpty()) query += ' AND Id IN : accountIdSet ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        Date startDate = date.newInstance(batchProcessDate.Year(),batchProcessDate.month(),1); 
        Date endDate = date.newInstance(batchProcessDate.Year(),batchProcessDate.month(),Date.DaysInMonth(batchProcessDate.Year(),batchProcessDate.month()));

        
        List<Account> accountList = (List<Account>) scope;
        
        system.debug('batchProcessDate==='+batchProcessDate);
        system.debug('accountList=='+accountList);
        
        // A wrapper class to combine cost data with employee or teacher
        Map<Id, CostCentre> costCentreMap = new Map<Id, CostCentre>();
        for(Payout__c pay : [SELECT Id, Employee_Name__c,Payout_Date__c,Month__c,Year__c  FROM Payout__c WHERE Employee_Name__c IN : accountList and Calendar_Month(Payout_Date__c)=:batchProcessDate.month() and Calendar_Year(Payout_Date__c)=:batchProcessDate.year()]){
            costCentreMap.put(pay.Employee_Name__c  , new CostCentre(pay));
            If(mstring==null || ystring==null){
                mString = pay.Month__c;
                ystring = pay.Year__c;
            }
        }
        
        // Employee Rostering
        for(Rostering__c rost : [SELECT Id, Name, Employee__c, Effective_Date__c, Centre__c, Additional_Work_Day__c, Shift__c, Notes__c, PayItem__c, Work_Day__c FROM Rostering__c WHERE Employee__c IN : accountList AND Effective_Date__c >=: startDate AND Effective_Date__c  <=: endDate]){
            if(costCentreMap.containsKey(rost.Employee__c)){
                CostCentre cost = costCentreMap.get(rost.Employee__c);
                
                // working time calculate
                Decimal workTime = 0;
                if(rost.Work_Day__c.equalsignorecase('Full Day')){
                    workTime = 1.00;
                }else if(rost.Work_Day__c.equalsignorecase('Half Day')){
                    workTime = 0.50;
                }
                cost.totalWorking += workTime;
                
                if(!cost.workingByCenreMap.containsKey(rost.Centre__c)) cost.workingByCenreMap.put(rost.Centre__c, 0.00);
                Decimal centreTime = cost.workingByCenreMap.get(rost.Centre__c);
                centreTime += workTime;
                cost.workingByCenreMap.put(rost.Centre__c, centreTime );
                
                costCentreMap.put(rost.Employee__c, cost );
            }
        }
        
        // Teacher_Working_Hour__c  
        for(Teacher_Working_Hour__c  twh : [SELECT Id, Teacher_Name__c, Working_Day__c, Active__c, Start_Time__c, End_Time__c, Remarks__c, Break_Time__c, Centre__c, Center_Name__c FROM Teacher_Working_Hour__c WHERE Teacher_Name__c IN : accountList AND Active__c = true AND Break_Time__c = false]){
            if(costCentreMap.containsKey(twh.Teacher_Name__c)){
                CostCentre cost = costCentreMap.get(twh.Teacher_Name__c);
                
                Decimal tWorkingTime = getTeacherWorkingTimeForMonth(twh);
                cost.totalWorking += tWorkingTime;
                system.debug('tWorkingTime  *** '+tWorkingTime );
                if(!cost.workingByCenreMap.containsKey(twh.Center_Name__c)) cost.workingByCenreMap.put(twh.Center_Name__c , 0.00);
                Decimal centreTime = cost.workingByCenreMap.get(twh.Center_Name__c);
                centreTime += tWorkingTime;
                cost.workingByCenreMap.put(twh.Center_Name__c, centreTime );
                
                costCentreMap.put(twh.Teacher_Name__c, cost );
            }
        }
        Map<String, Employee_Cost_Centre__c> existingCostCentreMap = getExistingEmployeeCostCentre();
        List<Employee_Cost_Centre__c> employeeCostCentreList = new List<Employee_Cost_Centre__c>();
        // setup cost centre data
        for(Id accountId : costCentreMap.keyset()){
            CostCentre cost = costCentreMap.get(accountId);
            for(Id centreId : cost.workingByCenreMap.keyset()){
                system.debug(cost.totalWorking + ' **** '+cost.workingByCenreMap.get(centreId));
                if(cost.totalWorking > 0 && cost.workingByCenreMap.get(centreId) > 0){
                    Decimal ctc = (cost.workingByCenreMap.get(centreId) * 100 )/cost.totalWorking ;
                    
                    Employee_Cost_Centre__c ecc = new Employee_Cost_Centre__c(
                        Centre__c = centreId,
                        Cost_to_Centre__c = ctc,
                        Employee__c = accountId,
                        Month__c = cost.payout.Month__c,
                        Year__c = cost.payout.Year__c,
                        Payout__c = cost.payout.Id
                    );
                    String key = ecc.Employee__c+''+ecc.Centre__c+''+ecc.Payout__c;
                    if(existingCostCentreMap.containsKey(key)){
                        ecc.Id = existingCostCentreMap.get(key).Id;
                        existingCostCentreMap.remove(key);
                    }
                    employeeCostCentreList.add(ecc);
                }
            }
            
        }
        if(!employeeCostCentreList.isEmpty()){
            upsert employeeCostCentreList;
        }
        // delete existing cost centre
        if(existingCostCentreMap != null && !existingCostCentreMap.values().isEmpty()){
            delete existingCostCentreMap.values();
        }
    }
    
    global Map<String, Employee_Cost_Centre__c> getExistingEmployeeCostCentre(){
        Map<String, Employee_Cost_Centre__c> eccMap = new Map<String, Employee_Cost_Centre__c>();
        for(Employee_Cost_Centre__c ecc : [SELECT Id, Year__c, Month__c, Payout__c, Cost_to_Centre__c, Centre__c, Employee__c, Name FROM Employee_Cost_Centre__c WHERE Year__c = : yString AND Month__c = : mString AND Employee__c IN: accountIdSet]){
            String key = ecc.Employee__c+''+ecc.Centre__c+''+ecc.Payout__c;
            eccMap.put(key, ecc);
        }
        return eccMap;
    }
    
    global Decimal getTeacherWorkingTimeForMonth(Teacher_Working_Hour__c  twh ){
        Decimal workingTimeMonth = 0;
        Decimal workingTimeDay = (twh.End_Time__c.hour() - twh.Start_Time__c.hour()) * 60;
        
        Date startDate = date.newInstance(batchProcessDate.Year(),batchProcessDate.month(),1); 
        Date endDate = date.newInstance(batchProcessDate.Year(),batchProcessDate.month(),Date.DaysInMonth(batchProcessDate.Year(),batchProcessDate.month()));
        
        workingTimeDay += twh.End_Time__c.minute() - twh.Start_Time__c.minute();
        system.debug('workingTimeDay  *** '+workingTimeDay  );
        system.debug('twh.Working_Day__c *** '+twh.Working_Day__c);
        system.debug('startDate *** '+startDate );
        system.debug('endDate *** '+endDate);
        //if(workingTimeDay < 0) workingTimeDay = workingTimeDay * -1;
        if(workingTimeDay > 0 && twh.Working_Day__c != null){
            while(startDate <= endDate){
                system.debug('startDate **'+startDate );
                DateTime dt = (DateTime) startDate ;
                String day = dt.format('EEE');
                if(day.equalsignorecase(twh.Working_Day__c)){
                    workingTimeMonth += workingTimeDay;
                    startDate = startDate.addDays(7);
                }else{
                    startDate = startDate.addDays(1);
                }
            }
        }
        system.debug('workingTimeMonth *** '+workingTimeMonth );
        return workingTimeMonth ;
    }
    
    global void finish(Database.BatchableContext BC){}
    
    global class CostCentre{
        global Payout__c payout ;
        global Decimal totalWorking ;
        global Map<Id, Decimal> workingByCenreMap ;
        
        global CostCentre(Payout__c payout){
            this.payout = payout;
            this.workingByCenreMap = new Map<Id, Decimal>();
            this.totalWorking = 0.00;
        }
    }
}