force-app/main/default/objects/Meeting_Feedback__c/Meeting_Feedback__c.object-meta.xml
<CustomObject>
    <label>Meeting Feedback</label>
    <nameField>
        <displayFormat>MF-{0000}</displayFormat>
        <label>Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Feedback__c/fields/Online_Lesson_Quality_Rating__c.field-meta.xml
<CustomField>
    <fullName>Online_Lesson_Quality_Rating__c</fullName>
    <label>Online Lesson Quality Rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting_Feedback__c/fields/Submitted_by__c.field-meta.xml
<CustomField>
    <fullName>Submitted_by__c</fullName>
    <label>Submitted by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PublicFeedbackApi.cls
@RestResource(urlMapping='/publicmeetingfeedback/*')

global class PublicFeedbackApi {  
    @HttpGet
    global static String createMeetingFeedback() {
        RestRequest req = RestContext.request;
        String personName = req.params.get('person_name');
        String roomName = req.params.get('room_name');
        String rating = req.params.get('rating');
        Meeting_Feedback__c meetingObj = new Meeting_Feedback__c();
        meetingObj.Submitted_by__c=personName;
        meetingObj.Room_Name__c=roomName;
        meetingObj.Online_Lesson_Quality_Rating__c=rating;
        Insert meetingObj;
        return meetingObj.Id;
    }   
}