force-app/main/default/objects/Account/fields/Admin_Fees__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fees__c</fullName>
    <label>Admin Fees %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MovedToSage__c.field-meta.xml
<CustomField>
    <fullName>MovedToSage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MovedToSage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Currency_Code_PI__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code_PI__c</fullName>
    <description>Global picklist in replace of Country Code(text)</description>
    <label>Currency Code PI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Admin_Fees__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fees__c</fullName>
    <label>Admin Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Center)</relationshipLabel>
    <relationshipName>Center_Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SageInvoiceKey__c.field-meta.xml
<CustomField>
    <fullName>SageInvoiceKey__c</fullName>
    <label>SageInvoiceKey</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Inv-Item-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>IF(ISBLANK( Subscription_Line_Item__c ), Booking__r.Center__r.Name+&apos; &apos;+ Booking__r.Center__r.LastName , Subscription_Line_Item__r.Enrolment__r.Center__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Organisations</relationshipLabel>
    <relationshipName>Organisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <formula>IF(Country__r.Tax_Rate__c &gt; 0, Country__r.Tax_Rate__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Location__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Type_of_package__c.field-meta.xml
<CustomField>
    <fullName>Type_of_package__c</fullName>
    <label>Type of package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Promo</fullName>
            </value>
            <value>
                <fullName>Prepayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Invoice__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/MovedToSage__c.field-meta.xml
<CustomField>
    <fullName>MovedToSage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MovedToSage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sage_GL_Account__c/Sage_GL_Account__c.object-meta.xml
<CustomObject>
    <label>Sage GL Account</label>
    <nameField>
        <label>Sage GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sage GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sage_GL_Account__c/fields/GL_Account_No__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_No__c</fullName>
    <label>GL Account No</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/Stripe_Payout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object will store the Payout logs whenever the payout is created in the stripe.</description>
    <label>Stripe Payout Log</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Stripe Payout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Payout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Stripe Payout Logs</relationshipLabel>
    <relationshipName>Stripe_Payout_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SageIntacctIntegrationUtilityTest.cls
/*
Name    :       SageIntacctIntegrationUtilityTest
Date    :       18 JULY 2019    
author  :       karan singh soni
*/
@isTest
public class SageIntacctIntegrationUtilityTest {
    @isTest
    private static void unitTest1(){
        
        Sage_Intacct_Credentials__c sic = new Sage_Intacct_Credentials__c();
        sic.Name='test';
        sic.Endpoint__c='https://api.intacct.com/ia/xml/xmlgw.phtml';
        insert sic;
        
        List<Sage_GL_Account__c> sgaList = new List<Sage_GL_Account__c>();
        for(integer i=0;i<=3;i++){
            Sage_GL_Account__c sga = new Sage_GL_Account__c();
            if(i==0){
                sga.Name='Merchandise Card Receivable';
            }
            else if(i==1){
                sga.Name='Accounts Payable'; 
                sga.GL_Account_No__c='qwerty';
            }
            else if(i==2){
                sga.Name='AGP Cash at Bank - OCBC';
            }
            else{
                sga.Name='Merchant Account Fees';
            }
            sgaList.add(sga) ;
        }
        insert sgaList;
        
        Stripe_Payout_Log__c spl = new Stripe_Payout_Log__c();
        insert spl;
        
        Country__c country = new Country__c();
        country.Name = 'IN';
        country.Country_Name__c = 'India';
        country.Tax_Rate__c = 7.0;
        country.Currency_Code__c = 'INR';
        country.Student_Policies_Template_Id__c = 'test';
        country.Stripe_Base_Url__c = 'www.test.com';
        country.Stripe_Publishable_Key__c = 'ABC';
        country.Stripe_Secret_Key__c = 'deede';
        country.Currency_Code_PI__c='SGD';
        insert country;
        
        Organisation__c org = new Organisation__c();
        org.Country__c = country.id;
        insert org;
        
        Account Centre = TestUtil.createAccount('Centre',TRUE,TRUE);
        Centre.Country__c=country.id;
        centre.Organisation__c=org.id;
        update Centre;
        
        Account cust = TestUtil.createAccount('Customer',TRUE,TRUE);
        
        Invoice__c objInv = TestUtil.createInvoice(cust.id,TRUE);
        objInv.Center__c = Centre.id;
        objInv.SageInvoiceKey__c='xyz';
        objInv.MovedToSage__c=false;
        objInv.Admin_Fees__c=10;
        update objInv;
        
        Program__C objProg=TestUtil.createProgram('Active','Piano',true);
        Package__c objPack=TestUtil.createPackage(objProg.id,Centre.id,'60',true);
        objPack.Type_of_package__c='Promo';
        objPack.Type__c='Individual';
        objPack.Sage_Revenue_Template__c='svt';
        update objPack;
        
        Invoice_Line_Item__c ili = TestUtil.createInvLineItem(objInv.id, TRUE);
        ili.Package__c=objPack.id;
        ili.GST_Amount__c=10;
        ili.Discount_Amount__c=5;
        
        update ili;
        Invoice_Line_Item__c ili2 = TestUtil.createInvLineItem(objInv.id, TRUE);
        ili2.Remarks__c = 'azx';
        ili2.Discount_Amount__c=10;
        ili2.Is_Deposit__c=false;
        ili2.Month__c=Date.today();
        ili2.GST_Amount__c=10;
        update ili2;
        
        Invoice_Line_Item__c ili3 = TestUtil.createInvLineItem(objInv.id, TRUE);
        ili3.Remarks__c = 'azx';
        ili3.Discount_Amount__c=10;
        ili3.Is_Deposit__c=true;
        ili3.Month__c=Date.today();
        ili3.GST_Amount__c=0;
        update ili3;
        
        Payment__c objPay = TestUtil.createPayment(cust.id,TRUE);
        Payment__c objPay1 = TestUtil.createPayment(cust.id,TRUE);
        objPay1.SagePaymentKey__c='zzxc';
        objPay1.Invoice__c=objInv.id;
        objPay1.Stripe_Payout_Id__c=spl.id;
        update objPay1;
        objPay.Payment_Date__c=system.today();
        objPay.Payment_Amount__c=-1;
        objPay.Invoice__c=objInv.id;
        objPay.MovedToSage__c=false;
        objPay.Parent_Payment__c=objPay1.id;
        objPay.Stripe_Payout_Id__c=spl.id;
        update objPay;
        
        Set<String> setOfInvIds = new Set<String>();
        setOfInvIds.add(objInv.Id);
        setOfInvIds.add('asdf');
        
        test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'<?xml version="1.0" encoding="UTF-8"?><response><control><status>success</status><senderid>Aureus Group</senderid><controlid>a0P0p000000AKnAEAW</controlid><uniqueid>false</uniqueid><dtdversion>3.0</dtdversion></control><operation><authentication><status>success</status><userid>ws_tek</userid><companyid>Aureus Group-imp</companyid><locationid>AGP</locationid><sessiontimestamp>2019-08-28T03:47:39-07:00</sessiontimestamp><sessiontimeout>2019-08-28T09:47:39-07:00</sessiontimeout></authentication><result><status>success</status><function>getAPISession</function><controlid>a0P0p000000AKnAEAW</controlid><data><api><sessionid>oSHwMnFypzWA7wmIPlLj332aNYHvCQ..</sessionid><endpoint>https://api.intacct.com/ia/xml/xmlgw.phtml</endpoint><locationid>AGP</locationid></api></data></result></operation></response>'));
        
        SageIntacctIntegrationUtility.sessionWrapper objnew = new SageIntacctIntegrationUtility.sessionWrapper();
        objnew.senderId='sdsd';
        objnew.senderPassword='csd';
        objnew.endPointUrl='sdd';
        objnew.sessionId='sds';
        objnew.errorMsg='dcsds';
        
        SageIntacctIntegrationUtility.getGlAccountCodes();
        SageIntacctIntegrationUtility.resultWrapper objnew2 = new SageIntacctIntegrationUtility.resultWrapper();
        SageIntacctIntegrationUtility.revRecWrapper objnew3 = new SageIntacctIntegrationUtility.revRecWrapper();
        SageIntacctIntegrationUtility.newEnrolment(cust.id,setOfInvIds);
        SageIntacctIntegrationUtility.newStudioRental(cust.id,objInv.Id,objPay.Id);
        SageIntacctIntegrationUtility.packageUpgrade(objInv.Id,objPay.Id);  
        SageIntacctIntegrationUtility.changeEnrolment(objInv.Id);
        SageIntacctIntegrationUtility.createCustomer(new SageIntacctIntegrationUtility.sessionWrapper(), Centre);
        SageIntacctIntegrationUtility.createInvoice(new SageIntacctIntegrationUtility.sessionWrapper(),new Invoice__c());
        SageIntacctIntegrationUtility.createPayment(new SageIntacctIntegrationUtility.sessionWrapper(), new Payment__c(), 'invoiceKey');
        SageIntacctIntegrationUtility.reverseInvoice(new SageIntacctIntegrationUtility.sessionWrapper(),objInv);
        SageIntacctIntegrationUtility.reversePayment(new SageIntacctIntegrationUtility.sessionWrapper(), objPay);
        SageIntacctIntegrationUtility.createAdjustmentJournalEntries(new SageIntacctIntegrationUtility.sessionWrapper(), objPay); 
        SageIntacctIntegrationUtility.getRevRecognitionSchedule(objnew, 'invoiceKey');
        SageIntacctIntegrationUtility.getRevRecognitionEntries(objnew, new set<string>{'zxc'});
        SageIntacctIntegrationUtility.updateRevRecEntries(objnew, new Map<string,string>{'updRevRecEntryMap'=>'updRevRecEntryMap'}, new Map<string,string>{'newRevRecEntryMap'=>'newRevRecEntryMap'});
        SageIntacctIntegrationUtility.createStripeJournalEntries(spl,new List<Payment__c>());
        SageIntacctIntegrationUtility.existingCustomerPrepayment(objInv.id,objPay.id);
        SageIntacctIntegrationUtility.voidInvoice(objInv.id);
        SageIntacctIntegrationUtility.refundPayment(objPay.id);
        SageIntacctIntegrationUtility.paynowInvoice(objPay.id);
        SageIntacctIntegrationUtility.americanClubInvoice(objInv.id);
        
        test.stopTest();
    }
    
    @isTest
    private static void unitTest2(){
        
        Sage_Intacct_Credentials__c sic = new Sage_Intacct_Credentials__c();
        sic.Name='test';
        sic.Endpoint__c='https://api.intacct.com/ia/xml/xmlgw.phtml';
        insert sic;
        
        List<Sage_GL_Account__c> sgaList = new List<Sage_GL_Account__c>();
        for(integer i=0;i<=3;i++){
            Sage_GL_Account__c sga = new Sage_GL_Account__c();
            if(i==0){
                sga.Name='Merchandise Card Receivable';
            }
            else if(i==1){
                sga.Name='Accounts Payable'; 
                sga.GL_Account_No__c='qwerty';
            }
            else if(i==2){
                sga.Name='AGP Cash at Bank - OCBC';
            }
            else{
                sga.Name='Merchant Account Fees';
            }
            sgaList.add(sga) ;
        }
        insert sgaList;
        
        Stripe_Payout_Log__c spl = new Stripe_Payout_Log__c();
        insert spl;
        
        Country__c country = new Country__c();
        country.Name = 'IN';
        country.Country_Name__c = 'India';
        country.Tax_Rate__c = -7.0;
        country.Currency_Code__c = 'INR';
        country.Student_Policies_Template_Id__c = 'test';
        country.Stripe_Base_Url__c = 'www.test.com';
        country.Stripe_Publishable_Key__c = 'ABC';
        country.Stripe_Secret_Key__c = 'deede';
        country.Currency_Code_PI__c='SGD';
        insert country;
        
        Organisation__c org = new Organisation__c();
        org.Country__c = country.id;
        insert org;
        
        Account Centre = TestUtil.createAccount('Centre',TRUE,TRUE);
        Centre.Country__c=country.id;
        centre.Organisation__c=org.id;
        update Centre;
        
        Account cust = TestUtil.createAccount('Customer',TRUE,TRUE);
        
        Invoice__c objInv = TestUtil.createInvoice(cust.id,TRUE);
        objInv.Center__c = Centre.id;
        objInv.SageInvoiceKey__c='xyz';
        objInv.MovedToSage__c=false;
        objInv.Admin_Fees__c=10;
        update objInv;
        
        Program__C objProg=TestUtil.createProgram('Active','Piano',true);
        Package__c objPack=TestUtil.createPackage(objProg.id,Centre.id,'60',true);
        objPack.Type_of_package__c='Promo';
        objPack.Type__c='Individual';
        objPack.Sage_Revenue_Template__c='svt';
        update objPack;
        
        Invoice_Line_Item__c ili = TestUtil.createInvLineItem(objInv.id, TRUE);
        ili.Package__c=objPack.id;
        ili.GST_Amount__c=10;
        ili.Discount_Amount__c=5;
        update ili;
        Invoice_Line_Item__c ili2 = TestUtil.createInvLineItem(objInv.id, TRUE);
        ili2.Remarks__c = 'azx';
        ili2.Discount_Amount__c=10;
        ili2.Is_Deposit__c=false;
        ili2.Month__c=Date.today();
        ili2.GST_Amount__c=10;
        update ili2; 
        
        Payment__c objPay = TestUtil.createPayment(cust.id,TRUE);
        Payment__c objPay1 = TestUtil.createPayment(cust.id,TRUE);
        objPay1.SagePaymentKey__c='zzxc';
        objPay1.Invoice__c=objInv.id;
        objPay1.Stripe_Payout_Id__c=spl.id;
        objPay1.Payment_Amount__c=1;
        objPay1.SagePaymentKey__c='spk';
        update objPay1;
        objPay.Payment_Date__c=system.today();
        objPay.Payment_Amount__c=-1;
        objPay.Invoice__c=objInv.id;
        objPay.MovedToSage__c=false;
        objPay.Parent_Payment__c=objPay1.id;
        objPay.Stripe_Payout_Id__c=spl.id;
        update objPay;
        
        Set<String> setOfInvIds = new Set<String>();
        setOfInvIds.add(objInv.Id);
        setOfInvIds.add('asdf');
        
        test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'<?xml version="1.0" encoding="UTF-8"?><response><control><status>success</status><senderid>Aureus Group</senderid><controlid>a0P0p000000AKnAEAW</controlid><uniqueid>false</uniqueid><dtdversion>3.0</dtdversion></control><operation><authentication><status>success</status><userid>ws_tek</userid><companyid>Aureus Group-imp</companyid><locationid>AGP</locationid><sessiontimestamp>2019-08-28T03:47:39-07:00</sessiontimestamp><sessiontimeout>2019-08-28T09:47:39-07:00</sessiontimeout></authentication><result><status>success</status><function>getAPISession</function><controlid>a0P0p000000AKnAEAW</controlid><data><api><sessionid>oSHwMnFypzWA7wmIPlLj332aNYHvCQ..</sessionid><endpoint>https://api.intacct.com/ia/xml/xmlgw.phtml</endpoint><locationid>AGP</locationid></api></data></result></operation></response>'));
        
        SageIntacctIntegrationUtility.sessionWrapper objnew = new SageIntacctIntegrationUtility.sessionWrapper();
        objnew.senderId='sdsd';
        objnew.senderPassword='csd';
        objnew.endPointUrl='sdd';
        objnew.sessionId='sds';
        objnew.errorMsg='dcsds';
        
        SageIntacctIntegrationUtility.getGlAccountCodes();
        SageIntacctIntegrationUtility.resultWrapper objnew2 = new SageIntacctIntegrationUtility.resultWrapper();
        SageIntacctIntegrationUtility.revRecWrapper objnew3 = new SageIntacctIntegrationUtility.revRecWrapper();
        SageIntacctIntegrationUtility.newEnrolment(cust.id,setOfInvIds);
        SageIntacctIntegrationUtility.newStudioRental(cust.id,objInv.Id,objPay.Id);
        SageIntacctIntegrationUtility.packageUpgrade(objInv.Id,objPay.Id);  
        SageIntacctIntegrationUtility.changeEnrolment(objInv.Id);
        SageIntacctIntegrationUtility.createCustomer(new SageIntacctIntegrationUtility.sessionWrapper(), Centre);
        SageIntacctIntegrationUtility.createInvoice(new SageIntacctIntegrationUtility.sessionWrapper(),new Invoice__c());
        SageIntacctIntegrationUtility.fetchARInvoiceKey(objnew,'invoiceKey');
        SageIntacctIntegrationUtility.fetchVATprocessStatus(objnew,'invoiceKey');
        SageIntacctIntegrationUtility.createPayment(new SageIntacctIntegrationUtility.sessionWrapper(), new Payment__c(), 'invoiceKey');
        SageIntacctIntegrationUtility.applyARPayment(objnew,objInv);
        SageIntacctIntegrationUtility.reverseInvoice(new SageIntacctIntegrationUtility.sessionWrapper(),objInv);
        SageIntacctIntegrationUtility.reversePayment(new SageIntacctIntegrationUtility.sessionWrapper(), objPay);
        SageIntacctIntegrationUtility.createAdjustmentJournalEntries(new SageIntacctIntegrationUtility.sessionWrapper(), objPay); 
        SageIntacctIntegrationUtility.getRevRecognitionSchedule(objnew, 'invoiceKey');
        SageIntacctIntegrationUtility.getRevRecognitionEntries(objnew, new set<string>{'zxc'});
        SageIntacctIntegrationUtility.updateRevRecEntries(objnew, new Map<string,string>{'updRevRecEntryMap'=>'updRevRecEntryMap'}, new Map<string,string>{'newRevRecEntryMap'=>'newRevRecEntryMap'});
        
        SageIntacctIntegrationUtility.createStripeJournalEntries(spl,new List<Payment__c>());
        SageIntacctIntegrationUtility.existingCustomerPrepayment(objInv.id,objPay.id);
        SageIntacctIntegrationUtility.voidInvoice(objInv.id);
        SageIntacctIntegrationUtility.refundPayment(objPay.id);
        SageIntacctIntegrationUtility.paynowInvoice(objPay.id);
        SageIntacctIntegrationUtility.americanClubInvoice(objInv.id);
        SageIntacctIntegrationUtility.adhocInvoice(objInv.id);
        
        test.stopTest();
    }
    
    @isTest
    private static void unitTest3(){
        Country__c country = new Country__c();
        country.Name = 'IN';
        country.Country_Name__c = 'India';
        country.Tax_Rate__c = 7.0;
        country.Currency_Code__c = 'INR';
        country.Student_Policies_Template_Id__c = 'test';
        country.Stripe_Base_Url__c = 'www.test.com';
        country.Stripe_Publishable_Key__c = 'ABC';
        country.Stripe_Secret_Key__c = 'deede';
        country.Currency_Code_PI__c='SGD';
        insert country;
        
        Organisation__c org = new Organisation__c();
        org.Country__c = country.id;
        org.Sage_Company__c = 'AGP';
        insert org;
        
        Account Centre = TestUtil.createAccount('Centre',TRUE,TRUE);
        Centre.Country__c=country.id;
        centre.Organisation__c=org.id;
        update Centre;
        
        Account cust = TestUtil.createAccount('Customer',TRUE,TRUE);
        
        Invoice__c objInv = TestUtil.createInvoice(cust.id,TRUE);
        objInv.Center__c = Centre.id;
        objInv.MovedToSage__c=true;
        objInv.SageOrderEntryKey__c = 'orderKey';
        objInv.Admin_Fees__c=10;
        update objInv;
        
        Program__C objProg=TestUtil.createProgram('Active','Piano',true);
        Package__c objPack=TestUtil.createPackage(objProg.id,Centre.id,'60',true);
        objPack.Type_of_package__c='Promo';
        objPack.Type__c='Individual';
        objPack.Sage_Revenue_Template__c='svt';
        update objPack;
        
        Invoice_Line_Item__c ili = TestUtil.createInvLineItem(objInv.id, TRUE);
        ili.Package__c=objPack.id;
        ili.GST_Amount__c=10;
        ili.Discount_Amount__c=5;
        update ili;
        Invoice_Line_Item__c ili2 = TestUtil.createInvLineItem(objInv.id, TRUE);
        ili2.Remarks__c = 'azx';
        ili2.Discount_Amount__c=10;
        ili2.Is_Deposit__c=false;
        ili2.Month__c=Date.today();
        ili2.GST_Amount__c=10;
        update ili2; 
        
        Payment__c objPay = TestUtil.createPayment(cust.id,TRUE);
        Payment__c objPay1 = TestUtil.createPayment(cust.id,TRUE);
        objPay1.SagePaymentKey__c='zzxc';
        objPay1.Invoice__c=objInv.id;
        objPay1.Payment_Amount__c=1;
        objPay1.SagePaymentKey__c='spk';
        update objPay1;
        objPay.Payment_Date__c=system.today();
        objPay.Payment_Amount__c=-1;
        objPay.Invoice__c=objInv.id;
        objPay.MovedToSage__c=false;
        objPay.Parent_Payment__c=objPay1.id;
        update objPay;
        
        database.executeBatch(new SageFetchARInvoiceKey(new set<string>{objInv.Id}),1);
        
        SchedulableContext sc;
        SageFetchARInvoiceKey sfk = new SageFetchARInvoiceKey();
        sfk.execute(sc);
        
    }
}