force-app/main/default/objects/Account/fields/Admin_Fees__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fees__c</fullName>
    <label>Admin Fees %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Admin_Fees_Required__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fees_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Fees Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FCM_Token__c.field-meta.xml
<CustomField>
    <fullName>FCM_Token__c</fullName>
    <label>FCM Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Paid_Notification__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Paid_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in Mobile Notification settings
Send this notification only if this field is checked</description>
    <label>Invoice Paid Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Ref_No__c</fullName>
    <label>Ref No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Admin_Fees__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fees__c</fullName>
    <label>Admin Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Center)</relationshipLabel>
    <relationshipName>Center_Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <summarizedField>Invoice_Line_Item__c.Discount_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Gross_Total__c.field-meta.xml
<CustomField>
    <fullName>Gross_Total__c</fullName>
    <description>Total Amount Excluding Deposits</description>
    <label>Gross Total</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Line_Item__c.Is_Deposit__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Internal_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Internal_Ref_No__c</fullName>
    <description>The purpose of this field is to store a running sequence of the invoices of each country which can be used by accounting and finance department for internal reference.</description>
    <label>Internal Ref No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvoiceTriggerHelper.cls
/*
Name        :    InvoiceTriggerHelper
Date        :    4/02/2019
Description :    Helper Class For Invoice Trigger 
*/
public class InvoiceTriggerHelper{
    
    /*
This method takes the set of Id's of the Invoices
and calculate the Admin fees according to percentage of admin fees of subtraction of discount amount from the grand total.
and update the invoice.
*/
    public static void getAdminFees(Set<String> invoiceSet){
        List<Invoice__c> listOfInvoices = new List<Invoice__c>();
        
        if(invoiceSet.size() > 0){
            List<Invoice__c> invoices = [SELECT Id, Admin_Fees__c, Gross_Total__c, Discount_Amount__c, Parent_Account__c, Parent_Account__r.Admin_Fees__c, Parent_Account__r.Admin_Fees_Required__c FROM Invoice__c WHERE Id IN :invoiceSet];
            Decimal dc = 0;
            if(invoices.size() > 0){
                for(Invoice__c invoiceObj : invoices){
                    dc = 0;
                    if(invoiceObj.Parent_Account__r.Admin_Fees_Required__c && String.isNotBlank(invoiceObj.Parent_Account__r.Admin_Fees__c)){
                        dc = ((invoiceObj.Gross_Total__c - invoiceObj.Discount_Amount__c) * Integer.valueOf(invoiceObj.Parent_Account__r.Admin_Fees__c)) / 100;
                        invoiceObj.Admin_Fees__c = BillingUtility.roundOffAmount(dc);
                        listOfInvoices.add(invoiceObj);
                    }
                }
                if(listOfInvoices.size() > 0){
                    update listOfInvoices;
                }
                
            }
        }
    }
    
    /*
This method takes the set of Id's of the Invoices where the total amount of invoice is less than 0
and create a task for the financial User(Baljit). Because it is a refund case.    
*/
    
    public static void createRefundTask(Set<String> invoiceSet){
        List<Task> taskList = new List<Task>();
        System.debug('invoiceSet'+invoiceSet);
        for(String invoiceId : invoiceSet){
            taskList.add(new Task(WhatId = invoiceId, 
                                  Priority = 'Normal', 
                                  Status = 'Open', 
                                  ActivityDate = System.today(), 
                                  OwnerId = Label.Financial_User));
        }
        
        if(taskList.size() > 0){
            insert taskList;
        }
        
    }
    
    
    //Insert the Invoice With the name = New Invoice Name 
    Public static void fillInvoiceName(List<Invoice__c> invoiceList){
        for(Invoice__c invoiceObj : invoiceList){
            invoiceObj.Name = 'New Invoice Name';
        }
    }
    
    //@Nishi (Date 26-7-2019), This process is used to proces Status invoice Notification.
    public static void procesStatusInvoice(Map<String,String> mapOfStatusInvoice){
        List<MobileNotificationWrapper> notifications = new List<MobileNotificationWrapper>();
        Map<String,String> parentTokens = new Map<String,String>();
        
        for(Account acc: [SELECT id,FCM_Token__c from Account 
                          where Id in: mapOfStatusInvoice.values() 
                          and Invoice_Paid_Notification__c = true AND FCM_Token__c !=null]){
                              parentTokens.put(acc.id,acc.FCM_Token__c );
                          }
        
        for(Invoice__c  invoiceObj : [SELECT id,Name,Parent_Account__c,Card_Type__c FROM Invoice__c  WHERE id in: mapOfStatusInvoice.keyset()]){
            try{
                if(parentTokens.containsKey(invoiceObj.Parent_Account__c)){
                    String to = parentTokens.get(invoiceObj.Parent_Account__c);
                    String title = invoiceObj.Name+' Paid';
                    String bodymsg = 'Please note '+invoiceObj.Name+' has been paid using '+invoiceObj.Card_Type__c+'. Click here to view the payment details.';
                    notifications.add(new MobileNotificationWrapper(invoiceObj.Parent_Account__c, to, title, bodymsg));
                }
            }catch(Exception e){}
        }
        if(notifications.size() > 0 && !System.isBatch() && !System.isFuture()) {
            Database.executeBatch(new SendMobileNotificationBatch(notifications),90);
        }
        
    }
    //@zakir  dated 22-10-2019, it is used to update the fields "Internal ref no SG" "Internal ref no HK" in Invoice Obj and "Ref No" field in Country Onj .
    public static void updateReferenceNo(list<Invoice__c> Invoice){
        List<Invoice__c> updInvList = new List<Invoice__c>();
        Map<Id,Country__c> mapCountryWithId = new Map<Id,Country__c>();
        
        for(Invoice__c inv: [SELECT Id, Name, Center__r.Country__c, Center__r.Country__r.Name, Center__r.Country__r.Ref_No__c 
                             FROM Invoice__c 
                             WHERE Id IN:Invoice AND Center__r.Country__c != null]){
                                 
            Country__c ci = new Country__c(Id = inv.Center__r.Country__c, Ref_No__c = inv.Center__r.Country__r.Ref_No__c);
            if(mapCountryWithId.containsKey(inv.Center__r.Country__c))
                ci = mapCountryWithId.get(inv.Center__r.Country__c);
                                 
            ci.Ref_No__c = ci.Ref_No__c!=null?(ci.Ref_No__c+1):1;
            mapCountryWithId.put(ci.Id, ci);
                                 
            String textNum = '';
            for(Integer i=String.valueOf(ci.Ref_No__c).length(); i < 5 ; i++)                     
                textNum += '0';
            textNum = textNum + ci.Ref_No__c;
                                 
        	if(inv.Center__r.Country__r.Name=='SG')
                textNum = 'SG-'+textNum;
            else if(inv.Center__r.Country__r.Name=='HK')
                textNum = 'HK-'+textNum;
            
            inv.Internal_Ref_No__c= textNum;
            updInvList.add(inv);                     
        }
            
        if(updInvList.size() > 0)
            update updInvList;
        
        if(mapCountryWithId.size() > 0) 
             update mapCountryWithId.values();
        /*set<id> centerIds = new set<id>(); 
        set<id> countryIds = new set<id>();
        List<Country__c> countryList = new List<Country__c>();
        
        for(Invoice__c inc : Invoice ){
            if(inc.Center__c!=null)
                centerIds.add(inc.Center__c);
        }
        System.debug('====centerIds===>>>'+centerIds);
        map<id,id> mapacctocountry = new map<id,id>();
        for(Account acnt : [Select id, Country__c from Account where Id in:centerIds]){
            if(acnt.Country__c!=null)
                mapacctocountry.put(acnt.id,acnt.Country__c);
            countryIds.add(acnt.Country__c);
        }
        map<id,Country__c> mapCountryWithId = new map<id,Country__c>([select id,Name, Ref_No__c from Country__c where id In: countryIds]);
        
        System.debug('====countryIds===>>>'+countryIds);
       List<Invoice__c> listInvoiceUpdate = new List<Invoice__c>();
        for(Invoice__c inv : Invoice){
            if(mapacctocountry.containskey(inv.Center__c)){
                Country__c ci = mapCountryWithId.get(mapacctocountry.get(inv.Center__c));
                ci.Ref_No__c = ci.Ref_No__c!=null?(ci.Ref_No__c+1):1;
                
                mapCountryWithId.put(mapacctocountry.get(inv.Center__c),ci);
                if(ci.Name=='HK'){
                    Invoice__c invv = new Invoice__c();
                    invv.Id = inv.Id;
                    invv.Internal_Ref_No_HK__c = ci.Ref_No__c;
                    listInvoiceUpdate.add(invv);
                }
                else if(ci.Name=='SG'){
                    Invoice__c invv = new Invoice__c();
                    invv.Id = inv.Id;
                    invv.Internal_Ref_No_SG__c = ci.Ref_No__c;
                    listInvoiceUpdate.add(invv);
                }
            }
        }
        if(listInvoiceUpdate.size() > 0) update listInvoiceUpdate ;
        
        if(mapCountryWithId.size() > 0) update mapCountryWithId.values();
        */
    }
}