force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK( PersonBirthdate ) ) ,
IF( DATE( 2000 , MONTH( PersonBirthdate) , DAY( PersonBirthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
YEAR (Today()) - YEAR ( PersonBirthdate ),
YEAR (Today()) - YEAR ( PersonBirthdate) -1 ),
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CDAC_Contribution__c.field-meta.xml
<CustomField>
    <fullName>CDAC_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDAC Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EUCF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>EUCF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EUCF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foreigner</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/MBMF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>MBMF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MBMF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Paid_By__c.field-meta.xml
<CustomField>
    <fullName>Paid_By__c</fullName>
    <label>Paid By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SINDA_Contribution__c.field-meta.xml
<CustomField>
    <fullName>SINDA_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SINDA Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Working_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_Working_Days__c</fullName>
    <label>Total Working Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payout__c/Payout__c.object-meta.xml
<CustomObject>
    <label>Payout</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Pay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payout__c/fields/CDAC_Contribution__c.field-meta.xml
<CustomField>
    <fullName>CDAC_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDAC Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/EUCF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>EUCF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EUCF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/MBMF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>MBMF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MBMF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/SINDA_Contribution__c.field-meta.xml
<CustomField>
    <fullName>SINDA_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SINDA Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/createPayItemForSalaryPayrollBatch.cls
/**
 * Name :createPayItemForSalaryPayrollBatch
 * Date: 4-May-2021
 * Author: Nishi
 * Description: for calculate teacher working hrs  and created payitem accordingly
 */
global without sharing class createPayItemForSalaryPayrollBatch implements Database.Batchable<sObject>, Database.stateful{
    Set<Id> empIdSet = new Set<Id>();
    Set<Id> payoutIdSet = new Set<Id>();
    date currentDate = system.today();
    Integer currYear = currentDate.Year();
    Integer currMonth = currentDate.month();
    Datetime dtm = (datetime) currentDate;
    string strCurrMonth = dtm.format('MMMM');
    Integer currDay = currentDate.day();
    Date startMonthDate = date.newInstance(currYear,currMonth,1); 
    Date lastMonthDate = date.newInstance(currYear,currMonth,Date.DaysInMonth(currYear,currMonth));
    public createPayItemForSalaryPayrollBatch(){
        createEmployeePayoutBatch.inFutureContext = false;
    }
    public createPayItemForSalaryPayrollBatch(Date processDate, set<Id>employeeIdSet,set<Id>payoutIdSet){
        createEmployeePayoutBatch.inFutureContext = false;
        empIdSet = employeeIdSet;
        currentDate = processDate;
        this.payoutIdSet =payoutIdSet;
        currentDate = processDate;
        currYear = currentDate.Year();
        currMonth = currentDate.month();
        dtm = (datetime) currentDate;
        strCurrMonth = dtm.format('MMMM');
        currDay = currentDate.day();
        startMonthDate = date.newInstance(currYear,currMonth,1); 
        lastMonthDate = date.newInstance(currYear,currMonth,Date.DaysInMonth(currYear,currMonth));
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        createEmployeePayoutBatch.inFutureContext = false;
        system.debug('empIdSet ** '+empIdSet);
        if(!empIdSet.isEmpty()){ 
            return Database.getQueryLocator([Select id,Total_Working_Days__c,Paid_By__c,Joining_Date__c,Issue_Date__c,ID_Type__c,PersonBirthdate,Age__c,Last_Working_Date__c,SINDA_Contribution__c,MBMF_Contribution__c,EUCF_Contribution__c,CDAC_Contribution__c from Account where Employee_Status__c in ('Probation','Confirm') and (recordType.Name='Teacher') and (Joining_Date__c=null or Joining_Date__c<=:lastMonthDate) and (Last_Working_Date__c=null or Last_Working_Date__c>=:startMonthDate) AND Id IN : empIdSet]);    
        }else{        
            return Database.getQueryLocator([Select id,Total_Working_Days__c,Paid_By__c,Joining_Date__c,Issue_Date__c,ID_Type__c,PersonBirthdate,Age__c,Last_Working_Date__c,SINDA_Contribution__c,MBMF_Contribution__c,EUCF_Contribution__c,CDAC_Contribution__c from Account where Employee_Status__c in ('Probation','Confirm') and (recordType.Name='Teacher') and (Joining_Date__c=null or Joining_Date__c<=:lastMonthDate) and (Last_Working_Date__c=null or Last_Working_Date__c>=:startMonthDate)]);    
        }
    }
    
    global void execute(Database.BatchableContext BC, List<Account> accounts){
        Set<Id> accIds = new Set<Id>();
        
        for(Account acc:accounts){
            accIds.add(acc.Id);
        }
        system.debug('payoutIdSet'+payoutIdSet);
        List<String> listOfpayoutIds = new List<String>();
        for(Id payoutId:payoutIdSet){
            listOfpayoutIds.add(payoutId);
        }
        Map<Id,Payout__c> mapOfPayout = AureusHRUtility.getEmployeePayout(listOfpayoutIds);
        Map<Id,Payout__c> mapOfaccToPayout = new Map<Id,Payout__c>();
        
        for(Payout__c pt: mapOfPayout.values()){            
               mapOfaccToPayout.put(pt.id,pt);
        }
        system.debug('accIds'+accIds);
        system.debug('accToPayoutMap'+mapOfaccToPayout);
       
        AureusHRManagementUtil.createPayItemForSalaryPayroll(accIds,currentDate,mapOfaccToPayout.keyset());

        AureusHRManagementUtil.calcualterPayoutCPFAmount(accounts,payoutIdSet,currentDate);
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
     
}