force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK( PersonBirthdate ) ) ,
IF( DATE( 2000 , MONTH( PersonBirthdate) , DAY( PersonBirthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
YEAR (Today()) - YEAR ( PersonBirthdate ),
YEAR (Today()) - YEAR ( PersonBirthdate) -1 ),
null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CDAC_Contribution__c.field-meta.xml
<CustomField>
    <fullName>CDAC_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDAC Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EUCF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>EUCF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EUCF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foreigner</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/MBMF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>MBMF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MBMF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Paid_By__c.field-meta.xml
<CustomField>
    <fullName>Paid_By__c</fullName>
    <label>Paid By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SINDA_Contribution__c.field-meta.xml
<CustomField>
    <fullName>SINDA_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SINDA Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Working_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_Working_Days__c</fullName>
    <label>Total Working Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/Employee_Work_Week__c.object-meta.xml
<CustomObject>
    <label>Employee Work Week</label>
    <nameField>
        <displayFormat>EW-{0000}</displayFormat>
        <label>Employee Work Week No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Work Week</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Work_Week__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee, Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Work Week</relationshipLabel>
    <relationshipName>Employee_Work_Week</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <label>Friday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <label>Monday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <label>Saturday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <label>Sunday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <label>Thursday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <label>Tuesday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <label>Wednesday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PayItem__c/PayItem__c.object-meta.xml
<CustomObject>
    <label>PayItem</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>PayItem No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PayItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PayItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Amount</fullName>
                <default>true</default>
                <label>Amount</label>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payitem_Master__c/Payitem_Master__c.object-meta.xml
<CustomObject>
    <label>Payitem Master</label>
    <nameField>
        <label>Payitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payitem Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payitem_Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition</fullName>
                <default>true</default>
                <label>Addition</label>
            </value>
            <value>
                <fullName>Deduction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payout__c/Payout__c.object-meta.xml
<CustomObject>
    <label>Payout</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Pay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payout__c/fields/CDAC_Contribution__c.field-meta.xml
<CustomField>
    <fullName>CDAC_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDAC Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Payrolls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/EUCF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>EUCF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EUCF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/MBMF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>MBMF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MBMF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Payroll_Batch__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payroll Batch</label>
    <referenceTo>Payroll_Batch__c</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/SINDA_Contribution__c.field-meta.xml
<CustomField>
    <fullName>SINDA_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SINDA Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payroll_Batch__c/Payroll_Batch__c.object-meta.xml
<CustomObject>
    <label>Payroll Batch</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Payroll Batch No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payroll Batch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payroll_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salary_Detail__c/Salary_Detail__c.object-meta.xml
<CustomObject>
    <label>Salary Detail</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>Salary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salary Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Salary_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salary_Detail__c/fields/Total_Salary__c.field-meta.xml
<CustomField>
    <fullName>Total_Salary__c</fullName>
    <formula>Basic_Salary__c +  Housing_Allowance__c +  Transport_Allowance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/createEmployeePayoutBatch.cls
global without sharing class createEmployeePayoutBatch implements Database.Batchable<sObject>, Database.stateful{
    date currentDate = system.today();
    Integer currYear = currentDate.Year();
    Integer currMonth = currentDate.month();
    Datetime dtm = (datetime) currentDate;
    string strCurrMonth = dtm.format('MMMM');
    Integer currDay = currentDate.day();
    Date startMonthDate = date.newInstance(currYear,currMonth,1); 
    Date lastMonthDate = date.newInstance(currYear,currMonth,Date.DaysInMonth(currYear,currMonth));
    Set<Id> empIdSet = new Set<Id>();
    global Set<Id> allEmpIdSet;
    global  Set<Id> allPayoutIdSet;
    global Payroll_Batch__c payrollBatch = new Payroll_Batch__c();
    public static boolean inFutureContext = true;
    public createEmployeePayoutBatch(){
        allEmpIdSet = new Set<Id>();
        allPayoutIdSet = new Set<Id>();
    }
    public createEmployeePayoutBatch(Date processDate, set<Id>employeeIdSet, Payroll_Batch__c payrollBth){
        allEmpIdSet = new Set<Id>();
        allPayoutIdSet = new Set<Id>();
        empIdSet = employeeIdSet;
        payrollBatch = payrollBth;
        currentDate = processDate;
        currYear = currentDate.Year();
        currMonth = currentDate.month();
        dtm = (datetime) currentDate;
        strCurrMonth = dtm.format('MMMM');
        currDay = currentDate.day();
        startMonthDate = date.newInstance(currYear,currMonth,1); 
        lastMonthDate = date.newInstance(currYear,currMonth,Date.DaysInMonth(currYear,currMonth));
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('empIdSet ** '+empIdSet);
        if(!empIdSet.isEmpty()){ 
            return Database.getQueryLocator([Select id,Total_Working_Days__c,Paid_By__c,Joining_Date__c,Issue_Date__c,ID_Type__c,PersonBirthdate,Age__c,Last_Working_Date__c,SINDA_Contribution__c,MBMF_Contribution__c,EUCF_Contribution__c,CDAC_Contribution__c from Account where Employee_Status__c in ('Probation','Confirm') and (recordType.Name='Employee' or recordType.Name='Teacher') and (Joining_Date__c=null or Joining_Date__c<=:lastMonthDate) and (Last_Working_Date__c=null or Last_Working_Date__c>=:startMonthDate) AND Id IN : empIdSet]);    
        }else{        
            return Database.getQueryLocator([Select id,Total_Working_Days__c,Paid_By__c,Joining_Date__c,Issue_Date__c,ID_Type__c,PersonBirthdate,Age__c,Last_Working_Date__c,SINDA_Contribution__c,MBMF_Contribution__c,EUCF_Contribution__c,CDAC_Contribution__c from Account where Employee_Status__c in ('Probation','Confirm') and (recordType.Name='Employee' or recordType.Name='Teacher') and (Joining_Date__c=null or Joining_Date__c<=:lastMonthDate) and (Last_Working_Date__c=null or Last_Working_Date__c>=:startMonthDate)]);    
        }
    }
    
    global void execute(Database.BatchableContext BC, List<Account> accounts){
        inFutureContext = false;
        Set<Id> accIds = new Set<Id>();
        for(Account acc:accounts){
            accIds.add(acc.Id);
        }
        system.debug('@@accIds'+accIds);
        Map<Id,List<Employee_Work_Week__c>> accToWorkWeekMap = new Map<Id,List<Employee_Work_Week__c>>();
        for(Employee_Work_Week__c eww: [Select id,Employee__c ,Effective_Date__c,Monday__c,Tuesday__c,Wednesday__c,Thursday__c,Friday__c,Saturday__c,Sunday__c from Employee_Work_Week__c 
                            where Employee__c in:accIds and Effective_Date__c!=null and Effective_Date__c<=:lastMonthDate order by Effective_Date__c desc]){
            List<Employee_Work_Week__c> tempList = new List<Employee_Work_Week__c>();
            if(accToWorkWeekMap.containsKey(eww.Employee__c)){
                tempList.addAll(accToWorkWeekMap.get(eww.Employee__c));
            }
            tempList.add(eww);
            
            accToWorkWeekMap.put(eww.Employee__c,tempList);
        }

        
        system.debug('@@accToWorkWeekMap'+accToWorkWeekMap);
        Map<Id,List<Salary_Detail__c>> accToSalaryMap = new Map<Id,List<Salary_Detail__c>>();
        for(Salary_Detail__c salDet: [select id,Total_Salary__c,Effective_Date__c,Employee_Name__c, Basic_Salary__c, Housing_Allowance__c, Transport_Allowance__c from Salary_Detail__c where Employee_Name__c in:accIds and Total_Salary__c>0 and Effective_Date__c!=null and Effective_Date__c<=:lastMonthDate and Status__c='Active' order by Effective_Date__c desc]){
            List<Salary_Detail__c> tempList = new List<Salary_Detail__c>();
            if(accToSalaryMap.containsKey(salDet.Employee_Name__c)){
                tempList.addAll(accToSalaryMap.get(salDet.Employee_Name__c));
            }
            tempList.add(salDet);
            accToSalaryMap.put(salDet.Employee_Name__c,tempList);
        }
        system.debug('@@accToSalaryMap'+accToSalaryMap);
        Map<Id,Payout__c> accToPayoutMap = new Map<Id,Payout__c>(); 
        
        for(Payout__c pt: [SELECT Id, Name, Month__c, Year__c, Salary__c, Total_Amount__c, Employee_CPF_Amount__c, Employer_CPF_Amount__c, 
                            Total_CPF__c, Employee_Name__c, CDAC__c, MBMF__c, SINDA__c, EUCF__c, SDL__c, Total_OW_Amount__c, Total_AW_Amount__c, 
                            Total_Non_CPF_Amount__c, Status__c, Payroll_Batch__c, No_of_working_days__c, Daily_Rate__c, Total_Payable__c, 
                            Monthly_Working_Days__c, Monthly_Salary__c, Basic_Salary__c, Housing_Allowance__c, Transport_Allowance__c from Payout__c where Employee_Name__c in:accIds and month__c=:strCurrMonth and year__c=:''+currYear+'']){            
               accToPayoutMap.put(pt.Employee_Name__c,pt);
        }
        system.debug('@@accToPayoutMap'+accToPayoutMap);
        List<Payout__c> payoutList = new List<Payout__c>();
        // CPF Details for calculate cpf data
        CalculatePayoutService.cpfDetailsMap = CalculatePayoutService.getEmpCPFDetails();
        CalculatePayoutService.employeeWeekMap = accToWorkWeekMap;
        CalculatePayoutService.employeeRecords  = accounts;
        CalculatePayoutService.setupEmployeeWeekData();
        List<Account> updateAccountList = new List<Account>();
        List<Payitem__c> payitemList = new List<Payitem__c>();
        Map<String,Id> payitemMasterMap = new Map<String,Id>();
        for(Payitem_Master__c pi : [SELECT Id,Name FROM Payitem_Master__c WHERE Name = 'Salary in Lieu (Employee)' OR Name = 'Salary in Lieu (Employer)']){
            if(pi.Name.indexOf('Employee') != -1) payitemMasterMap.put('Employee', pi.Id);
            if(pi.Name.indexOf('Employer') != -1) payitemMasterMap.put('Employer', pi.Id);
        }
         system.debug('@@payitemMasterMap'+payitemMasterMap);
        for(Account acc:accounts){
            decimal workingDays = 0;
            decimal empSalary = 0;
            Date startDate = startMonthDate;
            Date endDate = lastMonthDate;
            AureusHRUtility.workingDaysWrapper wd = new AureusHRUtility.workingDaysWrapper();
            if(accToWorkWeekMap.containsKey(acc.Id)){
                //Method to calculate employees working days in a month
                wd = AureusHRUtility.calcEmpWorkingDaysInaMonth(currYear,currMonth,startDate,endDate,accToWorkWeekMap.get(acc.Id));
                workingDays = wd.workingDays;
            }
            
            system.debug('WorkingDays==='+workingDays);
            AureusHRUtility.EmployeeSalaryWrapper sw = new AureusHRUtility.EmployeeSalaryWrapper();
            if(accToSalaryMap.containsKey(acc.Id)){
                sw = AureusHRUtility.calcEmployeeSalaryInaMonth(currYear,currMonth,startDate,endDate,accToSalaryMap.get(acc.Id),wd,acc.Joining_Date__c,acc.Last_Working_Date__c);    
            }
            
            Payout__c payout = new Payout__c();
            if(accToPayoutMap.containsKey(acc.Id)){
                //payout.Id =  accToPayoutMap.get(acc.Id).Id;   
                payout =  accToPayoutMap.get(acc.Id);   
            }else{
                payout.Employee_Name__c = acc.Id;
            }
            if(String.isBlank(payout.Id)){
                payout.SINDA_Contribution__c = acc.SINDA_Contribution__c;
                payout.MBMF_Contribution__c = acc.MBMF_Contribution__c;
                payout.EUCF_Contribution__c = acc.EUCF_Contribution__c ;
                payout.CDAC_Contribution__c = acc.CDAC_Contribution__c ;
            }
            If(sw.monthlySalary>0){
                payout.Monthly_Salary__c = sw.monthlySalary.setScale(2);
            }
            payout.Monthly_Working_Days__c = workingDays;
            
            if(sw.actualSalary>0){
                payout.Salary__c = sw.actualSalary.setScale(2);
            }else{
                payout.Salary__c = 0;
            }
            
            if(sw.basicSalary > 0){
                payout.Basic_Salary__c = sw.basicSalary.setScale(2);
            }else{
                payout.Basic_Salary__c = 0;
            }
            
            if(sw.housingAllowance > 0){
                payout.Housing_Allowance__c = sw.housingAllowance.setScale(2);
            }else{
                payout.Housing_Allowance__c = 0;
            }
            
            if(sw.transportAllowance  > 0){
                payout.Transport_Allowance__c = sw.transportAllowance .setScale(2);
            }else{
                payout.Transport_Allowance__c = 0;
            }
            
            payout.No_of_working_days__c = sw.actualWorkingDays;
            
            payout.Month__c = strCurrMonth;
            payout.Year__c = ''+currYear+'';
            
            payout.Employer_CPF_Amount__c = 0;
            payout.Employee_CPF_Amount__c = 0;
            // calculate CPF
            payout = CalculatePayoutService.calculateEmployeeCPF(acc,payout);
            if(!empIdSet.isEmpty()){
                payout.Payroll_Batch__c = payrollBatch.id;
                payout.Status__c = 'Processed';
            }
            payoutList.add(payout);
            
            // create new payitem, if account having information
            if(acc.Total_Working_Days__c != null){
                Id mId = null;
                if(payitemMasterMap.containsKey(acc.Paid_By__c)){
                    mId = payitemMasterMap.get(acc.Paid_By__c);
                }
                Payitem__c payItem = new PayItem__c(
                    Type__c = 'Days',
                    Value__c = acc.Total_Working_Days__c,
                    Payout__r = payout,
                    Payitem__c = mId 
                );
                payitemList.add(payItem);
                
                acc.Total_Working_Days__c = null; 
                updateAccountList.add(acc);             
           }
        } 
          system.debug('@@payoutList'+payoutList);
        upsert payoutList;
        if(!updateAccountList.isEmpty()){
            update updateAccountList;
        }
         system.debug('@@updateAccountList'+updateAccountList);
        if(!payitemList.isEmpty()){
            for(Payitem__c pi : payitemList){
                pi.Payout__c = pi.Payout__r.id;
            }
            insert payitemList;
        }
        system.debug('@@payitemList'+payitemList);
        //----------------
        //creating PayItems for approved leave requests for the Payouts - Start
        Set<Id> payoutIdSet = new Set<Id>();
        for(Payout__c payout: payoutList){
            payoutIdSet.add(payout.Id);
        }
        allEmpIdSet.addAll(accIds);
        allPayoutIdSet.addAll(payoutIdSet);
        system.debug('@@payoutIdSet'+payoutIdSet);
        AureusHRManagementUtil.createPayItemWithoutPLR(payoutIdSet, null, currentDate, null);
        AureusHRManagementUtil.calcLossAndCreatePayItemForUnpaidLeave(payoutIdSet, null, currentDate, null); 
         //creating PayItems for approved leave requests for the Payouts - End
    }
    
    global void finish(Database.BatchableContext BC){
        system.debug('accIds'+allEmpIdSet);
        system.debug('payoutIdSet'+allPayoutIdSet);
        ////Nishi : 9-Apr-2021:Acreating PayItems for approved working Hrs requests for the Payouts - Start
        //AureusHRManagementUtil.createPayItemForSalaryPayroll(accIds,currentDate,payoutIdSet);
        Database.executeBatch(new createPayItemForSalaryPayrollBatch(currentDate, allEmpIdSet,allPayoutIdSet),100);
         ////Nishi : 9-Apr-2021:Acreating PayItems for approved working Hrs requests for the Payouts - end
    }
     
}