force-app/main/default/objects/Account/fields/Also_a_Student__c.field-meta.xml
<CustomField>
    <fullName>Also_a_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Also a Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Time</fullName>
            </value>
            <value>
                <fullName>Part-Time</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Freelance</fullName>
            </value>
            <value>
                <fullName>Internship</fullName>
            </value>
            <value>
                <fullName>Overseas Staff</fullName>
            </value>
            <value>
                <fullName>Non-Employee Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Centre)</relationshipLabel>
    <relationshipName>CenterBooking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Is_fifth_booking__c.field-meta.xml
<CustomField>
    <fullName>Is_fifth_booking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is fifth booking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Parent)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FifthBookingReminderBatch.cls
/*
    Name          :    FifthBookingReminderBatch
    Date          :    11 March 2019
    Author        :    
    Description   :    This batch class is used for sending reminder email to parent for 5th booking. 
*/
global class FifthBookingReminderBatch implements Database.Batchable<sObject>,database.stateful{
    private Integer noOfDays;
    global DateTime startTime;
    global integer noOfRecords;
    global FifthBookingReminderBatch(Integer noOfDays){
        this.noOfDays = noOfDays;
        noOfRecords  = 0;
        startTime = system.now();
    } 
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        Date bookingDateToCheck= Date.today().addDays(noOfDays); 
        return Database.getQueryLocator([SELECT Id,Student__c,Student__r.parent__c,Student__r.personContactId,Student__r.parent__r.personContactId,
                                        Student__r.parent__r.Also_a_Student__c,Student__r.Also_a_Student__c,
                                        Teacher_Account__r.Engagement_Type__c,Center__r.Organisation__r.Name // added by nishi: 12-Oct-2020
                                        FROM Booking__c WHERE Booking_Date__c =:bookingDateToCheck 
                                        AND IS_fifth_Booking__c = TRUE
                                        AND RecordType.Name=: ConstantsClass.recordTypeLesson]);
    }
    global void execute(Database.BatchableContext BC,List<Booking__c> listOfBooking){
        noOfRecords += listOfBooking.size();
        Map<String,String> mapOfBookingWithContact = new Map<String,String>();
        Map<String,String> mapOfOssiaBookingWithContact = new Map<String,String>();
        map<string,EmailTemplate> templatemap= new map<string,EmailTemplate>();
        //added by nishi: 12-Oct-2020:start: for send email according to organisation
        for(EmailTemplate objEmailTemplate :[Select Id,DeveloperName from EmailTemplate 
									where DeveloperName = 'FifthBookingReminder' 
									or DeveloperName = 'Ossia_FifthBookingReminder' 
									]){
										templatemap.put(objEmailTemplate.DeveloperName,objEmailTemplate);
									}
        //List<EmailTemplate> templateList = [SELECT Id FROM EmailTemplate WHERE DeveloperName ='FifthBookingReminder'];
       //added by nishi: 12-Oct-2020:end: for send email according to organisation     
        for(Booking__c objBooking : listOfBooking){
            //boolean isReminderFifthlessonBooking = true;
            //added by nishi: 12-Oct-2020:start: for send email according to organisation
            if(string.isnotBlank(objBooking.Center__r.Organisation__r.Name) && objBooking.Center__r.Organisation__r.Name.equalsIgnoreCase(System.Label.Ossia_Organisation_Name)){
                if(string.isNotBlank(objBooking.Teacher_Account__r.Engagement_Type__c) && ConstantsClass.teacherPartTimeEngagementStatus.contains(objBooking.Teacher_Account__r.Engagement_Type__c)){
                   // isReminderFifthlessonBooking= false;
                }
                else{
                    if(String.isNotBlank(objBooking.Student__r.Parent__c)){
                        mapOfOssiaBookingWithContact.put(objBooking.Id,objBooking.Student__r.Parent__r.PersonContactId); 
                    }else if(objBooking.Student__r.Also_a_Student__c){
                        mapOfOssiaBookingWithContact.put(objBooking.Id,objBooking.Student__r.PersonContactId);
                    }
                }
            }else{
            //added by nishi: 12-Oct-2020:end: for send email according to organisation    
                if(String.isNotBlank(objBooking.Student__r.Parent__c)){
                    mapOfBookingWithContact.put(objBooking.Id,objBooking.Student__r.Parent__r.PersonContactId); 
                }else if(objBooking.Student__r.Also_a_Student__c){
                    mapOfBookingWithContact.put(objBooking.Id,objBooking.Student__r.PersonContactId);
                }
            }
        }
        if(mapOfBookingWithContact.size()> 0 && templatemap.size() > 0){
            List<Messaging.SingleEmailMessage> listOfemail = new List<Messaging.SingleEmailMessage>();
            for(String bookingId : mapOfBookingWithContact.keySet()){
                if(templateMap.containsKey('FifthBookingReminder')){
                    String contactId = mapOfBookingWithContact.get(bookingId);
                    Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(templatemap.get('FifthBookingReminder').Id, contactId, bookingId);
                    email.setTargetObjectId(contactId);
                    email.saveAsActivity = true;
                    //email.setWhatId(invoiceObj.Parent_Account__c);
                    listOfemail.add(email); 
                }
            } 
            if(listOfemail.size()>0){
                Messaging.sendEmail(listOfemail,False);   
            }
        }
        //added by nishi: 12-Oct-2020:start: for send email according to ossia organisation
        if(mapOfOssiaBookingWithContact.size()> 0 && templatemap.size() > 0){
            List<Messaging.SingleEmailMessage> listOfemail = new List<Messaging.SingleEmailMessage>();
            for(String bookingId : mapOfOssiaBookingWithContact.keySet()){
                if(templateMap.containsKey('Ossia_FifthBookingReminder')){
                    String contactId = mapOfOssiaBookingWithContact.get(bookingId);
                    Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(templatemap.get('Ossia_FifthBookingReminder').Id, contactId, bookingId);
                    email.setTargetObjectId(contactId);
                    email.saveAsActivity = true;
                    //email.setWhatId(invoiceObj.Parent_Account__c);
                    listOfemail.add(email); 
                }
            } 
            if(listOfemail.size()>0){
                Messaging.sendEmail(listOfemail,False);   
            }
        }
        //added by nishi: 12-Oct-2020:start: for send email according to ossia organisation
    }
    global void finish(Database.BatchableContext BC){
        BillingUtility.createBatchLog('Fifth Booking Reminder Batch',startTime,system.now(),noOfRecords);
    }
}