force-app/main/default/objects/Account/fields/American_club__c.field-meta.xml
<CustomField>
    <fullName>American_club__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>American club</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.LastName</field>
            <operation>contains</operation>
            <value>American club</value>
        </filterItems>
        <filterItems>
            <field>$Source.Membership_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Membership_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (American club)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <label>Membership Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>American Club</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <label>Stripe Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Centre)</relationshipLabel>
    <relationshipName>CenterBooking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Parent)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Studio_Booking_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Studio_Booking_Invoice_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Studio Booking Invoice Number</description>
    <label>Studio Booking Invoice Number</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>Select this record type to create facility booking</description>
    <label>Facility</label>
</RecordType>

force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Existing Bookings</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <description>To be used in reports
Booking: Package</description>
    <formula>Booking__r.Package__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (Centre)</relationshipLabel>
    <relationshipName>Enrolments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Center)</relationshipLabel>
    <relationshipName>Center_Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Inv-Item-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>IF(ISBLANK( Subscription_Line_Item__c ), Booking__r.Center__r.Name+&apos; &apos;+ Booking__r.Center__r.LastName , Subscription_Line_Item__r.Enrolment__r.Center__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <formula>Trim(text(Enrolment__r.Parent__r.Salutation ) + &quot; &quot; + Enrolment__r.Parent__r.FirstName + &quot; &quot; + Enrolment__r.Parent__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <description>Select this record type to setup package for Facility Rental</description>
    <label>Facility</label>
</RecordType>

force-app/main/default/classes/EnrolmentThankyouCntrlTest.cls
/*
Name        :        EnrolmentThankyouCntrlTest
Date        :        21 April 2019
Author      :        Karan Singh Soni
Description :        It is the test class of EnrolmentThankyouCntrl.
*/

@Istest
public class EnrolmentThankyouCntrlTest {
     @testSetup
    private static void createData() {
        AureusCalendarControllerTestHelper.createCalenderData();
    }
    
    public Static testMethod Void invokeEnrolmentThankyouCntrl(){
      /*  Account acc = testUtility.createAccount('Test','Customer',true);
        Invoice__c objinvoice = testUtility.createInvoice(acc.id, true);
        Invoice_Line_Item__c objInvLneItm=TestUtil.createInvLineItem(objinvoice.id,True);
        Case objCase=new Case();
        //objCase.Enrolment__c=ObjEnrol.id;
        objcase.RecordTypeId=Schema.SObjectType.case.getRecordTypeInfosByName().get('Sales Enquiry').getRecordTypeId();
        objCase.Status='New';
        objCase.Origin='Email';
        objCase.AccountId=acc.id;
        insert objCase;*/
        test.startTest();
        list<Invoice__c> invoicelist = [select id from Invoice__c];
        list<Booking__C> bookinglist = [select id,teacher_account__c,enrolment__c,parent__c,center__c,package__C from Booking__C];
        ApexPages.currentPage().getParameters().put('inv',invoicelist[0].id);
        EnrolmentThankyouCntrl objEnrolThank = new EnrolmentThankyouCntrl();
        
        pageReference pdfPage = Page.SubscriptionInvoicePdfClone;
        pdfPage.getParameters().put('inv',invoicelist[0].id);
       
        objEnrolThank.generateInvPdf();
        EnrolmentThankyouCntrl.fillAtt(Blob.valueOf('test pdf'), String.valueOf(invoicelist[0].id),'testpdf');
        
        //Insert booking
        Booking__C objBookForStudent=AureusCalendarControllerTestHelper.createBooking(bookinglist[0].teacher_account__c,bookinglist[0].enrolment__c,
                                                                                      bookinglist[0].parent__c,bookinglist[0].center__c,
                                                   bookinglist[0].package__C,date.today(),'Completed','Facility','Studio',false);
        objBookForStudent.Studio_Booking_Invoice_Number__c = invoicelist[0].Id;
        insert objBookForStudent;
        
        ApexPages.currentPage().getParameters().put('bookId',objBookForStudent.id);
        ApexPages.currentPage().getParameters().put('type','Studio');
        objEnrolThank.generateInvPdf();
       
        ApexPages.currentPage().getParameters().put('scId','test');
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'{"paid": true}'));
        objEnrolThank.updateInvoiceNumOnStripe(new set<string> {invoicelist[0].id});
         test.stopTest();
    }
    
    public Static testMethod Void invokeEnrolmentThankyouCntrl2(){
      /*  Account acc = testUtility.createAccount('Test','Customer',true);
        Invoice__c objinvoice = testUtility.createInvoice(acc.id, true);
        Invoice_Line_Item__c objInvLneItm=TestUtil.createInvLineItem(objinvoice.id,True);
        Case objCase=new Case();
        //objCase.Enrolment__c=ObjEnrol.id;
        objcase.RecordTypeId=Schema.SObjectType.case.getRecordTypeInfosByName().get('Sales Enquiry').getRecordTypeId();
        objCase.Status='New';
        objCase.Origin='Email';
        objCase.AccountId=acc.id;
        insert objCase;*/
        test.startTest();
        list<Invoice__c> invoicelist = [select id,Parent_Account__C from Invoice__c];
        list<Booking__C> bookinglist = [select id,teacher_account__c,enrolment__c,parent__c,center__c,package__C from Booking__C];
        ApexPages.currentPage().getParameters().put('inv',invoicelist[0].id);
        ApexPages.currentPage().getParameters().put('isOssia','true');
        EnrolmentThankyouCntrl objEnrolThank = new EnrolmentThankyouCntrl();
        Account obj1=new Account();
        obj1.LastName='American club';
        obj1.Membership_Type__c=ConstantsClass.amcClubMember;
        obj1.PersonEmail ='test@test.com';
        insert obj1;
        
        Account objAcc=new Account();
        objAcc.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        objAcc.Membership_Type__c=ConstantsClass.amcClubMember;
        objAcc.LastName='test cstmr';
        objAcc.Stripe_Customer_Id__c=NULL;
        objAcc.American_club__c=obj1.id;
        objAcc.Membership_Number__c= '90';
        objAcc.id= invoicelist[0].Parent_Account__c;
         objAcc.PersonEmail ='test@gmail.com';
        update objAcc;
        pageReference pdfPage = Page.SubscriptionInvoicePdfClone;
        pdfPage.getParameters().put('inv',invoicelist[0].id);
       
        objEnrolThank.isOssia = TRUE;
        objEnrolThank.generateInvPdf();
        EnrolmentThankyouCntrl.fillAtt(Blob.valueOf('test pdf'), String.valueOf(invoicelist[0].id),'testpdf');
        
        //Insert booking
        Booking__C objBookForStudent=AureusCalendarControllerTestHelper.createBooking(bookinglist[0].teacher_account__c,bookinglist[0].enrolment__c,
                                                                                      bookinglist[0].parent__c,bookinglist[0].center__c,
                                                   bookinglist[0].package__C,date.today(),'Completed','Facility','Studio',false);
        objBookForStudent.Studio_Booking_Invoice_Number__c = invoicelist[0].Id;
        insert objBookForStudent;
        
        ApexPages.currentPage().getParameters().put('bookId',objBookForStudent.id);
        ApexPages.currentPage().getParameters().put('type','Studio');
        objEnrolThank.generateInvPdf();
        ApexPages.currentPage().getParameters().put('scId','test');
     
         test.stopTest();
    }
   
}