force-app/main/default/objects/Account/fields/Available_Make_up_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_Units__c</fullName>
    <label>Available Make-up mins For Individual</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Time</fullName>
            </value>
            <value>
                <fullName>Part-Time</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Freelance</fullName>
            </value>
            <value>
                <fullName>Internship</fullName>
            </value>
            <value>
                <fullName>Overseas Staff</fullName>
            </value>
            <value>
                <fullName>Non-Employee Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>(End_Time__c - Start_Time__c )/(60*1000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store the teacher that whose teacher class is this.</description>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes (Account)</relationshipLabel>
    <relationshipName>Teacher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Available_Make_up_mins__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_mins__c</fullName>
    <description>this field for manage ossia Student Makeup Mins</description>
    <inlineHelpText>this field for manage ossia Organization Student Makeup Mins</inlineHelpText>
    <label>Available Make-up mins</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (Centre)</relationshipLabel>
    <relationshipName>Enrolments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>From related Package
Used in Reports</description>
    <formula>TEXT( Package__r.Duration__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Fifth_Lesson__c/Fifth_Lesson__c.object-meta.xml
<CustomObject>
    <label>Fifth Lesson</label>
    <nameField>
        <displayFormat>FL-{00000}</displayFormat>
        <label>Fifth Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fifth Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fifth_Lesson__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <description>This field stores booking date of fifth lesson</description>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this is lookup of account</description>
    <label>Center Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons</relationshipLabel>
    <relationshipName>Fifth_Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>it will  stores the time duration of fifth lesson</description>
    <formula>(End_Time__c - Start_Time__c )/(60*1000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It will store enrolment for the booking</description>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Fifth Lessons</relationshipLabel>
    <relationshipName>Fifth_Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will helps to describe that This Fifth lesson is active or not to show on calendar.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this is lookup field of account</description>
    <label>Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons (Parent)</relationshipLabel>
    <relationshipName>Fifth_Lessons1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FifthLessonReminderBatch.cls
/*
Name        :        FifthLessonReminderBatch
Date        :        24 Septmber 2019
Author      :        
Description :        It is FifthLessonReminderBatch class which send emails to the customer before 10 and fifteen days.
*/
global class FifthLessonReminderBatch implements Database.Batchable<sObject>, database.stateful{
    
    global Date BookingDate;
    global Integer numberOfDays;
    global DateTime startTime;
     global integer noOfRecords;
    global List <EmailTemplate> emailTemplateList;
    public FifthLessonReminderBatch (Date callingDate, Integer numberOfDays){
        emailTemplateList = new  List<EmailTemplate>();
        String emailTemplateName;

        noOfRecords  = 0;
        startTime = system.now();

        if(callingDate != NULL && numberOfDays != NULL && numberOfDays > 0){
            BookingDate = callingDate.addDays(numberOfDays);
            this.numberOfDays = numberOfDays;
            if(numberOfDays == 10){
                emailTemplateName = 'FifthLessonReminderFor10Days';
            }else if(numberOfDays == 15){
                emailTemplateName = 'FifthLessonReminderFor15Days';
            }
        }

        if(String.isNotBlank(emailTemplateName)){
            emailTemplateList = [SELECT Id, name FROM EmailTemplate WHERE developername = :emailTemplateName];
        }
        
    }
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator([SELECT Id,Booking_Date__c,Parent__r.Available_Make_up_Units__c, Duration__c, 
                                        Parent__r.PersonContactId,Enrolment__c ,Enrolment__r.Center__r.Location__c ,
                                        // added by nishi: 7-Sep-2020:for check organisation is ossia then we get makeup mins on enrolment and teacher type is part-time then we not send reminder 
                                        Enrolment__r.Available_Make_up_Mins__c,Enrolment__r.Center__r.Organisation__r.Name,Enrolment__r.teacher__r.Engagement_Type__c
                                        FROM Fifth_Lesson__c 
                                        WHERE Booking_Date__c = :BookingDate 
                                        AND IsActive__c = TRUE 
                                        AND Enrolment__c != NULL
                                        ]);
    }
    global void execute(Database.BatchableContext bc,List <Fifth_Lesson__c> FifthLessonReminderList){

        noOfRecords  += FifthLessonReminderList.size();
        List <Messaging.SingleEmailMessage> singleEmailList = new  List <Messaging.SingleEmailMessage>();

        if(emailTemplateList.size() > 0){
            
            for(Fifth_Lesson__c fl : FifthLessonReminderList){
                 //start: added by nishi: 7-Sep-2020:for check organisation is ossia then we get makeup mins on enrolment and teacher type is part-time then we not send reminder 
                 Boolean isSendNotification = true;
                Decimal availableMakeupUnits = 0;
                if(string.isNotBlank(fl.Enrolment__c) && string.isNotBlank(fl.Enrolment__r.Center__c) && string.isNotBlank(fl.Enrolment__r.Center__r.Organisation__c)
                 && string.isNotBlank(fl.Enrolment__r.Center__r.Organisation__r.Name) && fl.Enrolment__r.Center__r.Organisation__r.Name.equalsIgnoreCase(System.Label.Ossia_Organisation_Name)){
                    availableMakeupUnits = fl.Enrolment__r.Available_Make_up_Mins__c != null ? fl.Enrolment__r.Available_Make_up_Mins__c : 0;
                    if(string.isNotBlank(fl.Enrolment__c) && string.isNotBlank(fl.Enrolment__r.teacher__c) &&  string.isNotBlank(fl.Enrolment__r.teacher__r.Engagement_Type__c) && 
                        fl.Enrolment__r.Teacher__r.Engagement_Type__c.equalsIgnoreCase('Part-Time') ){
                            isSendNotification = false;        
                    }
                }else{
                    availableMakeupUnits = fl.Parent__r.Available_Make_up_Units__c != null ? fl.Parent__r.Available_Make_up_Units__c : 0;
                }
                 //end : added by nishi: 7-Sep-2020:for check organisation is ossia then we get makeup mins on enrolment and teacher type is part-time then we not send reminder 
                                       
                Decimal duration = fl.Duration__c != null ? fl.Duration__c : 0;
                system.debug('!!duration'+duration);
                 system.debug('!!availableMakeupUnits'+availableMakeupUnits);
                // 19-mar-2020:jatin: for check Available_Make_up_Units__c is less then then fifth_lesson_ Package_duration 
                //then we send email otherwise not
                if(duration > availableMakeupUnits && isSendNotification){
                     Messaging.SingleEmailMessage mail = AureusUtility.getSingleEmailMessage(emailTemplateList[0].Id,fl.Parent__r.PersonContactId,fl.Enrolment__c,fl.Enrolment__r.Center__r.Location__c);
                    singleEmailList.add(mail);
                    system.debug('!!Send email  ---  fl.Duration__c--'+fl.Duration__c);
                    system.debug('!!Send email  ----- fl.Parent__r.Available_Make_up_Units__c--'+fl.Parent__r.Available_Make_up_Units__c);
                }
            } 
        }
        system.debug('!!singleEmailList'+singleEmailList);
        if(singleEmailList.size()>0){
            Messaging.sendEmail(singleEmailList, FALSE);     
        }   
    }
    global void finish(Database.BatchableContext BC){
        BillingUtility.createBatchLog('Fifth Lesson Reminder',startTime,system.now(),noOfRecords);
     }
    
}