force-app/main/default/objects/Account/fields/Available_Make_up_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_Units__c</fullName>
    <label>Available Make-up mins For Individual</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>(End_Time__c - Start_Time__c )/(60*1000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store the teacher that whose teacher class is this.</description>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes (Account)</relationshipLabel>
    <relationshipName>Teacher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (Centre)</relationshipLabel>
    <relationshipName>Enrolments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Enrolments</relationshipLabel>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>From related Package
Used in Reports</description>
    <formula>TEXT( Package__r.Duration__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Lesson_Day__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Day__c</fullName>
    <description>Weekly Appointment Day</description>
    <label>Lesson Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Lesson_Start_time__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Start_time__c</fullName>
    <label>Lesson Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Lessons_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Lessons_Start_Date__c</fullName>
    <inlineHelpText>Enrolment first lesson date</inlineHelpText>
    <label>Lessons Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/New_Class__c.field-meta.xml
<CustomField>
    <fullName>New_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>select class Id is enrolment type is group</description>
    <label>New Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Enrolments (New Class)</relationshipLabel>
    <relationshipName>Enrolments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/New_Lesson_Day__c.field-meta.xml
<CustomField>
    <fullName>New_Lesson_Day__c</fullName>
    <label>New Lesson Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/New_Package_Id__c.field-meta.xml
<CustomField>
    <fullName>New_Package_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Package Id</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Enrolments (New Package Id)</relationshipLabel>
    <relationshipName>Enrolments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/New_Teacher__c.field-meta.xml
<CustomField>
    <fullName>New_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (New Teacher)</relationshipLabel>
    <relationshipName>Enrolments5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Next_Lesson_Start_time__c.field-meta.xml
<CustomField>
    <fullName>Next_Lesson_Start_time__c</fullName>
    <label>Next Lesson Start time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Request_Date__c</fullName>
    <label>Advance Action Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Status__c</fullName>
    <label>Advance Action Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Type__c</fullName>
    <label>Advance Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Enrolment Change</fullName>
            </value>
            <value>
                <fullName>Centre Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Session duration in minutes (Trial will be 30 min)</inlineHelpText>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PostInvoiceBatch.cls
/*
        Name        :    PostInvoiceBatch
        Date        :    06/28/2019
        Author      :  
        Description :    This batch class is used for the following:
                         1. Perform Advance Actions like:
                             A. Upgrade Enrolment
                             B. Downgrade Enrolment
                             C. Withdrawal of Enrolment
                             D. Change of Enrolment
                         2. creating 13th Month Bookings
        
*/
global class PostInvoiceBatch implements Database.Batchable<sObject>, database.stateful{
     global DateTime startTime;
     global integer noOfRecords;
     global String enroledStatus;
     global Set<String> enrolTypes;
     global String enrolRegularType;
     global Set<String> enrolmentIds;
     global PostInvoiceBatch(){
        enroledStatus = ConstantsClass.enroledStatus;
        enrolRegularType = ConstantsClass.enrolRegularStatus;
        noOfRecords  = 0;
        startTime = system.now();
         enrolTypes = New Set<String>{ConstantsClass.enrolRegularStatus,ConstantsClass.enrolGroupType};
        
     }
    public PostInvoiceBatch(Set<string> enrolIds){
        enrolmentIds = enrolIds;
        enroledStatus = ConstantsClass.enroledStatus;
        enrolRegularType = ConstantsClass.enrolRegularStatus;
        noOfRecords  = 0;
        startTime = system.now();
         enrolTypes = New Set<String>{ConstantsClass.enrolRegularStatus,ConstantsClass.enrolGroupType};
        
    }
     global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Student__c, Center__c, Center__r.Name, Teacher__c, Package__c,
                                          Lesson_Start_time__c, Package__r.Duration__c, Lesson_Day__c,
                                          Parent__c, Parent__r.Available_Make_up_Units__c,Student__r.Name,Parent__r.Name,
                                          Package_Process_Type__c, Package_Process_Request_Date__c, 
                                          New_Package_Id__c, Package_Process_Status__c, Effective_Date__c,
                                          New_Teacher__c, Next_Lesson_Start_time__c, New_Lesson_Day__c, Stage__c,
                                          //Commented by jatin: 9-jan-2020 : For manage  group class in enrolments
                                          Type__c, Class__c,New_Class__c 
                                          FROM Enrolment__c 
                                          WHERE Type__c In: enrolTypes AND
                                          //Commented by jatin: 9-jan-2020 : For manage regular and group type enrolments
                                          //Type__c = :enrolRegularType
                                          Stage__c =: enroledStatus AND 
                                          Lessons_Start_Date__c <= THIS_MONTH AND
                                          Id IN: enrolmentIds]);
     }
     
     global void execute(Database.BatchableContext BC, List<Enrolment__c> enrolmentList){
        noOfRecords  += enrolmentList.size();
        system.debug('enrolmentList'+enrolmentList);
        AureusUtility.postInvoiceJobOnEnrolment(enrolmentList);
     }
     
     global void finish(Database.BatchableContext BC){
        BillingUtility.createBatchLog('Post-Invoice Batch',startTime,system.now(),noOfRecords);
     }
}