force-app/main/default/objects/Account/fields/Available_Make_up_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_Units__c</fullName>
    <label>Available Make-up mins For Individual</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/Fifth_Lesson__c.object-meta.xml
<CustomObject>
    <label>Fifth Lesson</label>
    <nameField>
        <displayFormat>FL-{00000}</displayFormat>
        <label>Fifth Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fifth Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fifth_Lesson__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <description>This field stores booking date of fifth lesson</description>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this is lookup of account</description>
    <label>Center Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons</relationshipLabel>
    <relationshipName>Fifth_Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>it will  stores the time duration of fifth lesson</description>
    <formula>(End_Time__c - Start_Time__c )/(60*1000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>it is lookup of package</description>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Fifth Lessons</relationshipLabel>
    <relationshipName>Fifth_Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this is lookup field of account</description>
    <label>Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons (Parent)</relationshipLabel>
    <relationshipName>Fifth_Lessons1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>This fields holds starting time of fifth lesson</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this is lookup of account</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons (Student)</relationshipLabel>
    <relationshipName>Fifth_Lessons2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons (Teacher)</relationshipLabel>
    <relationshipName>Fifth_Lessons3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Session duration in minutes (Trial will be 30 min)</inlineHelpText>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to setup package for music lesson</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/classes/FifthLessonController.cls
public without Sharing class FifthLessonController {
   @RemoteAction
   Public Static AureusCalendarController.EventDetails fetchLessonDetails(String lessonId){
       List<Fifth_Lesson__c> fifthLessonList = new List<Fifth_Lesson__c>();
       AureusCalendarController.EventDetails eventDetail = new AureusCalendarController.EventDetails();
       if(String.isNotBlank(lessonId)){
            fifthLessonList = AureusCalendarControllerHelper.fetchFifthLessson(new Set<String>{lessonId});
            if(fifthLessonList.size() > 0){
                DateTime lessonDate;
                lessonDate = DateTime.newInstance(fifthLessonList[0].Booking_Date__c, fifthLessonList[0].Start_Time__c);
                eventDetail.Id = fifthLessonList[0].Id;
                eventDetail.name = fifthLessonList[0].Name;
                eventDetail.staffMember = fifthLessonList[0].Teacher_Account__r.FirstName + ' ' + fifthLessonList[0].Teacher_Account__r.LastName;
                eventDetail.staffMemberId = fifthLessonList[0].Teacher_Account__c;
                eventDetail.centerId = fifthLessonList[0].Center__c;
                eventDetail.centerName = fifthLessonList[0].Center__r.Name;
                eventDetail.dateAndTime = lessonDate.format('EEE, MMM dd YYYY');
                eventDetail.endDateTime = lessonDate.format('h:mm a');
                eventDetail.duration = fifthLessonList[0].Duration__c;
                eventDetail.parentFirstName = fifthLessonList[0].Parent__r.FirstName + ' ' + fifthLessonList[0].Parent__r.LastName;
                eventDetail.parentMobile = fifthLessonList[0].Parent__r.PersonMobilePhone;
                eventDetail.parentEmail = fifthLessonList[0].Parent__r.PersonEmail;
                eventDetail.studentFirstName = fifthLessonList[0].Student__r.FirstName + ' ' + fifthLessonList[0].Student__r.LastName;
                eventDetail.type = 'Fifth Lesson';
                eventDetail.studentId = fifthLessonList[0].Student__c;
                eventDetail.parentId = fifthLessonList[0].Parent__c;
                eventDetail.newPackage = fifthLessonList[0].Package__c; 
                eventDetail.newPackageName = fifthLessonList[0].Package__r.Name; 
                eventDetail.amm = fifthLessonList[0].Parent__r.Available_Make_up_Units__c;
            }
            
       }
       return eventDetail;
   }

   
   /*
    *   This Method Will Create the Placeholder with the same as 
    *   5th Lesson. And Delete the 5th Lesson Record through interface
    */
   @RemoteAction
   Public Static String bookingConvert(String lessonId, String caseId, String type, Boolean flag){
        String caseIdToReturn = '';
        IConvertFifthLesson convertTypeObj;
        if(type == 'placeholder'){
            convertTypeObj = new ConvertToPlaceholder(lessonId, caseId);
        }else if(type == 'makeup'){
            convertTypeObj = new ConvertToMakeup(lessonId, caseId, flag);
        }else if(type == 'adhoc'){
            convertTypeObj = new ConvertToAdhoc(lessonId, caseId, flag);
        }
        caseIdToReturn = convertTypeObj.convertFifthLesson();
        return caseIdToReturn;
   }
}