force-app/main/default/objects/Account/fields/Available_Make_up_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_Units__c</fullName>
    <label>Available Make-up mins For Individual</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Available_Make_up_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_Units__c</fullName>
    <label>Available Make-up mins.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Make_up_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Make_up_Expiry_Date__c</fullName>
    <inlineHelpText>Make-up expiry date set when a booking marked as Make-up</inlineHelpText>
    <label>Make-up Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to create lesson booking</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/classes/MakeupCreditsReminderSchedularTest.cls
/*
Name        :        MakeupCreditsReminderSchedularTest
Date        :        4 April 2019
Author      :        Karan Singh Soni
Description :        It is the test class of MakeupCreditsReminderSchedular.
*/
@isTest
public class MakeupCreditsReminderSchedularTest {
    public static testmethod void invokeMakeupCreditsReminderSchedular(){
        Account objteachr=TestUtil.createAccount('Teacher',false,true);
        Account objCustmr=TestUtil.createAccount('Customer',True,True);
        Booking__c objBook = TestUtil.createBooking(objteachr.id, 'Lesson','Regular',false);
        objBook.Make_up_Expiry_Date__c=date.today().addDays(-1);
        objbook.Available_Make_up_Units__c=30;
        objBook.Student__c=objCustmr.id;
        insert objBook;
        MakeupCreditsReminderSchedular objMakeCredit = new MakeupCreditsReminderSchedular();
        //every day at 23:00
        //string seh='0 0 23 * * ?';
        //system.schedule('Test Status Check',seh,objMakeCredit);
        
        //
         objMakeCredit.execute(Null);     
        MakeupCreditsReminderBatch batchObj = new MakeupCreditsReminderBatch(-1);
		Database.executeBatch(batchObj);
    }
}