force-app/main/default/objects/Account/fields/Available_Make_up_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_Units__c</fullName>
    <label>Available Make-up mins For Individual</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>(End_Time__c - Start_Time__c )/(60*1000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store the teacher that whose teacher class is this.</description>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes (Account)</relationshipLabel>
    <relationshipName>Teacher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (Centre)</relationshipLabel>
    <relationshipName>Enrolments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Enrolments</relationshipLabel>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>From related Package
Used in Reports</description>
    <formula>TEXT( Package__r.Duration__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Lesson_Day__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Day__c</fullName>
    <description>Weekly Appointment Day</description>
    <label>Lesson Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Lesson_Start_time__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Start_time__c</fullName>
    <label>Lesson Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/New_Centre__c.field-meta.xml
<CustomField>
    <fullName>New_Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for track new changed center id</description>
    <label>New Centre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (New Centre)</relationshipLabel>
    <relationshipName>Enrolments7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/New_Lesson_Day__c.field-meta.xml
<CustomField>
    <fullName>New_Lesson_Day__c</fullName>
    <label>New Lesson Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/New_Package_Id__c.field-meta.xml
<CustomField>
    <fullName>New_Package_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Package Id</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Enrolments (New Package Id)</relationshipLabel>
    <relationshipName>Enrolments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/New_Teacher__c.field-meta.xml
<CustomField>
    <fullName>New_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (New Teacher)</relationshipLabel>
    <relationshipName>Enrolments5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Next_Lesson_Start_time__c.field-meta.xml
<CustomField>
    <fullName>Next_Lesson_Start_time__c</fullName>
    <label>Next Lesson Start time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Request_Date__c</fullName>
    <label>Advance Action Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Status__c</fullName>
    <label>Advance Action Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Type__c</fullName>
    <label>Advance Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Enrolment Change</fullName>
            </value>
            <value>
                <fullName>Centre Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Session duration in minutes (Trial will be 30 min)</inlineHelpText>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/WaitingEnrolmentsBatch.cls
/*
    Name : WaitingEnrolmentsBatch
    date: 3-Feb-2021
    Author :  Nishi Jain
    Description:
    1.	 A scheduled process will run for all Waiting enrolments and check for the availability of the preferred time slot for the enrolment duration.
    2.	If a timeslot is found then an email notification will be send to Centre Admin and Customer to perform the necessary action. 

*/
global with sharing class WaitingEnrolmentsBatch implements Database.Batchable<sObject>,database.stateful {
    global Set<String> enrolTypes;
    global Set<String> enrolStatus;
    global String enroledStage;
    global WaitingEnrolmentsBatch (){
        enrolTypes = New Set<String>{ConstantsClass.enrolRegularStatus}; 
        enrolStatus =New Set<String>{ConstantsClass.enrolWaitingStatus};
        enroledStage = ConstantsClass.enroledStatus;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        string queryString = 'SELECT Id,Name,Student__c,Status__c,Preferred_End_time__c,Preferred_Start_Time__c,Preferred_Day__c,Preferred_Teacher__c ,Center__c, Center__r.Name, Teacher__c, Package__c,Lesson_Start_time__c, Package__r.Duration__c, Lesson_Day__c,Parent__c, Parent__r.Available_Make_up_Units__c,Student__r.Name,Parent__r.Name, ';
        queryString+= ' Package_Process_Type__c, Package_Process_Request_Date__c,New_Package_Id__c, Package_Process_Status__c, Effective_Date__c,New_Teacher__c, Next_Lesson_Start_time__c, New_Lesson_Day__c, Stage__c,New_Centre__c,';
        queryString+= ' Type__c, Class__c,New_Class__c  FROM Enrolment__c ';
        queryString+= ' WHERE Type__c In: enrolTypes ';
        queryString+= ' AND Status__c In: enrolStatus ';
        queryString+= ' AND Stage__c =: enroledStage ';
        queryString+= ' AND Preferred_Teacher__c != null ';
        queryString+= ' AND Preferred_End_time__c != null ';
        queryString+= ' AND Preferred_Start_Time__c != null ';
        queryString+= ' AND Preferred_Day__c != null ';
       return Database.getQueryLocator(queryString);                           
    }
    
    global void execute(Database.BatchableContext BC, List<Enrolment__c> listOfEnrolment){
       //System.debug('listOfEnrolment'+listOfEnrolment.size());
        Map<string,set<string>> preferredTeacherDays = new Map<string,set<string>>(); 
        Map<string,List<Enrolment__c>> preferredEnrolmentMap = new Map<string,List<Enrolment__c>>(); 
        List<Enrolment__c> listOfPreferredEnrolment = new List<Enrolment__c>();
        set<string> prefeWorkingDays = new set<string>();
        for(Enrolment__c objEnrolment: listOfEnrolment){
            prefeWorkingDays = new set<string>();
            listOfPreferredEnrolment = new List<Enrolment__c>();
            if(preferredTeacherDays.containsKey(objEnrolment.Preferred_Teacher__c)){
                prefeWorkingDays.addAll(preferredTeacherDays.get(objEnrolment.Preferred_Teacher__c));
            }
            if(preferredEnrolmentMap.containsKey(objEnrolment.Preferred_Day__c)){
                listOfPreferredEnrolment.addAll(preferredEnrolmentMap.get(objEnrolment.Preferred_Day__c));
            }
            prefeWorkingDays.add(objEnrolment.Preferred_Day__c);
            preferredTeacherDays.put(objEnrolment.Preferred_Teacher__c, prefeWorkingDays);
            listOfPreferredEnrolment.add(objEnrolment);
            preferredEnrolmentMap.put(objEnrolment.Preferred_Day__c,listOfPreferredEnrolment);
        }
      //System.debug('preferredEnrolmentMap'+preferredEnrolmentMap.keyset());
      //System.debug('preferredTeacherDays'+preferredTeacherDays.keyset());
        if(preferredTeacherDays != null && preferredTeacherDays.size() >0 && preferredEnrolmentMap != null && preferredEnrolmentMap.size() > 0){
            List<Enrolment__c> cancelledEnrolmentList = [SELECT Id,Name,Student__c,Status__c,Preferred_End_time__c,Preferred_Start_Time__c,Preferred_Day__c,Preferred_Teacher__c ,Center__c, Center__r.Name, 
                                                                Teacher__c, Package__c,Lesson_Start_time__c, Package__r.Duration__c, Lesson_Day__c,
                                                                Stage__c,Type__c, Class__c,New_Class__c  FROM Enrolment__c 
                                                                Where Stage__c =: ConstantsClass.enrollmentStageCancelled
                                                                And Teacher__c in: preferredTeacherDays.keyset()
                                                                and Lesson_Day__c in : preferredEnrolmentMap.keyset()];
                                                               //System.debug('cancelledEnrolmentList'+cancelledEnrolmentList);
            map<string,Set<string>> cancelEnrolmentDayTime = new map<string,Set<string>>();
            set<string> cancelEnrolmentTimeslots = new set<string>();
            set<string> peferredEnrolmentTimeslots = new set<string>();
            if(cancelledEnrolmentList != null && cancelledEnrolmentList.size() >0 ){
                for(Enrolment__c objCancelEnrolment: cancelledEnrolmentList){
                   //System.debug('objCancelEnrolment'+objCancelEnrolment); 
                    listOfPreferredEnrolment = new List<Enrolment__c>();
                    peferredEnrolmentTimeslots = new set<string>();
                    prefeWorkingDays = new set<string>();
                    cancelEnrolmentTimeSlots = new set<String>();
                    if(preferredTeacherDays.containsKey(objCancelEnrolment.Teacher__c)){
                        prefeWorkingDays  = preferredTeacherDays.get(objCancelEnrolment.Teacher__c);
                      //System.debug('prefeWorkingDays'+prefeWorkingDays);
                      //System.debug('objCancelEnrolment.Lesson_Day__c'+objCancelEnrolment.Lesson_Day__c);
                        if(string.isnotBlank(objCancelEnrolment.Lesson_Day__c) && 
                        (prefeWorkingDays != null && prefeWorkingDays.size() > 0 && prefeWorkingDays.contains(objCancelEnrolment.Lesson_Day__c)) 
                        && preferredEnrolmentMap.containsKey(objCancelEnrolment.Lesson_Day__c) ){
                            listOfPreferredEnrolment = preferredEnrolmentMap.get(objCancelEnrolment.Lesson_Day__c);
                           //System.debug('listOfPreferredEnrolment'+listOfPreferredEnrolment);
                            DateTime cancelEnrolmentstartTime = DateTime.newInstance(system.today(),  objCancelEnrolment.Lesson_Start_time__c);
                            DateTime cancelEnrolmentendTime = DateTime.newInstance(system.today(),  objCancelEnrolment.Lesson_Start_time__c.addMinutes(Integer.valueOf(objCancelEnrolment.Package__r.Duration__c)));
                            if(cancelEnrolmentstartTime != NULL && cancelEnrolmentendTime != NULL){
                                cancelEnrolmentTimeSlots = getFormatedTimeSlotList(cancelEnrolmentstartTime, cancelEnrolmentendTime);
                               //System.debug('cancelEnrolmentTimeSlots'+cancelEnrolmentTimeSlots);
                                                      
                                if(cancelEnrolmentTimeSlots != null && cancelEnrolmentTimeSlots.size() > 0){
                                    if(listOfPreferredEnrolment != null && listOfPreferredEnrolment.size() > 0){
                                        for( Enrolment__c objPreferredEnrolment : listOfPreferredEnrolment){
                                           //System.debug('objPreferredEnrolment'+objPreferredEnrolment); 
                                           //System.debug('objCancelEnrolment.Package__r.Duration__c'+objCancelEnrolment.Package__r.Duration__c); 
                                           //System.debug('objPreferredEnrolment.Package__r.Duration__c'+objPreferredEnrolment.Package__r.Duration__c); 
                                            DateTime peferredEnrolmentstartTime = DateTime.newInstance(system.today(),  objPreferredEnrolment.Preferred_Start_Time__c);
                                            DateTime peferredEnrolmentendime = DateTime.newInstance(system.today(),  objPreferredEnrolment.Preferred_End_time__c);
                                            if(peferredEnrolmentstartTime != NULL && peferredEnrolmentendime != NULL){
                                                peferredEnrolmentTimeslots = getFormatedTimeSlotList(peferredEnrolmentstartTime, peferredEnrolmentendime);
                                                if(peferredEnrolmentTimeslots.containsAll(cancelEnrolmentTimeSlots)){
                                                   //System.debug('peferredEnrolmentTimeslots'+peferredEnrolmentTimeslots);
                                                    if(objPreferredEnrolment.Package__r.Duration__c >= objCancelEnrolment.Package__r.Duration__c){
                                                        System.debug('objPreferredEnrolment'+objPreferredEnrolment.name); 
                                                        System.debug('objCancelEnrolment'+objCancelEnrolment.name); 
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
       
    }

    global void finish(Database.BatchableContext BC){
   
    }
    
    private static set<String> getFormatedTimeSlotList(DateTime startTime, DateTime endTime){
        set<String> timeSlots = new set<String>();
        if(startTime < endTime){
            while(startTime <= endTime){
                timeSlots.add(startTime.format('h:mm a'));
                startTime = startTime.addMinutes(15);
            }
        }
        return timeSlots;
    }
}