force-app/main/default/objects/Account/fields/Available_Make_up_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_Units__c</fullName>
    <label>Available Make-up mins For Individual</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <label>Instrument</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Instrument</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/App_Feeds__c/App_Feeds__c.object-meta.xml
<CustomObject>
    <label>App Feed</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Feeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Feeds__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>App Feeds (Center)</relationshipLabel>
    <relationshipName>Home_page_feeds3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/App_Feeds__c/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <label>Instrument</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/App_Feeds__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Home_page_feeds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/App_Feeds__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Home_page_feeds1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Available_Make_up_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Make_up_Units__c</fullName>
    <label>Available Make-up mins.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Day__c.field-meta.xml
<CustomField>
    <fullName>Booking_Day__c</fullName>
    <formula>CASE(WEEKDAY( Booking_Date__c), 
1, &apos;Sun&apos;, 
2, &apos;Mon&apos;, 
3, &apos;Tue&apos;, 
4, &apos;Wed&apos;, 
5, &apos;Thu&apos;, 
6, &apos;Fri&apos;, 
&apos;Sat&apos;)</formula>
    <label>Booking Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>(End_Time__c - Start_Time__c )/(60*1000)

/*IF( RecordType.Name = &apos;Facility&apos;, (End_Time__c - Start_Time__c )/(60*1000), If( ISPICKVAL( Package__r.Duration__c , &apos;Trial&apos;)  , value(&apos;30&apos;),  value(Text(Package__r.Duration__c))))
*/
/*Commented by Rajesh on 26th June 2019, To correct the actual duration for the studio booking

If( ISPICKVAL( Package__r.Duration__c , &apos;Trial&apos;)  , value(&apos;30&apos;),  value(Text(Package__r.Duration__c)))*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Durations in Minutes</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <formula>Text(Package__r.Program__r.Instrument__c)</formula>
    <label>Instrument</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>TEXT(Center__r.Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Parent)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to create lesson booking</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Fifth_Lesson__c/Fifth_Lesson__c.object-meta.xml
<CustomObject>
    <label>Fifth Lesson</label>
    <nameField>
        <displayFormat>FL-{00000}</displayFormat>
        <label>Fifth Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fifth Lessons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fifth_Lesson__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <description>This field stores booking date of fifth lesson</description>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Booking_Day__c.field-meta.xml
<CustomField>
    <fullName>Booking_Day__c</fullName>
    <formula>CASE(WEEKDAY( Booking_Date__c), 1, &quot;Sunday&quot;,2,&quot;Monday&quot;,3 ,&quot;Tuesday&quot;,4,&quot;Wednesday&quot;,5,&quot;Thursday&quot;,6,&quot;Friday&quot;,7,&quot;Saturday&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>it will  stores the time duration of fifth lesson</description>
    <formula>(End_Time__c - Start_Time__c )/(60*1000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>it is lookup of package</description>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Fifth Lessons</relationshipLabel>
    <relationshipName>Fifth_Lessons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this is lookup field of account</description>
    <label>Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons (Parent)</relationshipLabel>
    <relationshipName>Fifth_Lessons1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>This fields holds starting time of fifth lesson</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this is lookup of account</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons (Student)</relationshipLabel>
    <relationshipName>Fifth_Lessons2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fifth_Lesson__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fifth Lessons (Teacher)</relationshipLabel>
    <relationshipName>Fifth_Lessons3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Session duration in minutes (Trial will be 30 min)</inlineHelpText>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <formula>TEXT( Program__r.Instrument__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instrument</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Unit_Fee__c.field-meta.xml
<CustomField>
    <fullName>Unit_Fee__c</fullName>
    <inlineHelpText>One session fee</inlineHelpText>
    <label>Unit Fee</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to setup package for music lesson</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/classes/FifthLessonPageForPortalController.cls
public without sharing class FifthLessonPageForPortalController{
    public String fifthLessonId{get;set;}
    public Boolean isError{get;set;}
    public String  errorMsg{get;set;}
    public Fifth_Lesson__c fifthLesson{get;set;}
    public String startTime{get;set;} 
    public Decimal totalFee{get;set;} 
    public Decimal packageUnitFee{get;set;} 
    public Decimal taxRate{get;set;}  
    public String type{get;set;}    
    public boolean makeUpButtonDisaleFlag{get;set;}
    public boolean actionRequiredFlag{get;set;}
    public faq_link_for_portal__c faqlink{get;set;}
    public FifthLessonPageForPortalController(){
        faqlink = faq_link_for_portal__c.getValues('link_name');
        fifthLesson = new Fifth_Lesson__c();
        fifthLessonId = ApexPages.currentPage().getParameters().get('id');
        System.debug('@@@@'+fifthLessonId);
        if(String.isNotBlank(fifthLessonId)){
            List<Fifth_Lesson__c> fifthLessonList = [SELECT id,parent__r.Available_Make_up_Units__c,Booking_Day__c,Student__r.name,Booking_Date__c,Package__r.instrument__c,package__r.location__r.Country__r.tax_rate__c,package__r.Unit_Fee__c,Teacher_Account__r.Name,Start_Time__c,Duration__c,Center__r.Name FROM Fifth_Lesson__c WHERE id =: fifthLessonId AND  IsActive__c =: true];
            system.debug(' #### '+fifthLessonList);
            if(fifthLessonList.size() > 0){
                date cdate = Date.today();
                fifthLesson = fifthLessonList.get(0);                
                startTime = DateTime.newInstance(fifthLesson.Booking_Date__c, fifthLesson.Start_Time__c).format('h:mm a'); 
                packageUnitFee = BillingUtility.roundOffAmount(fifthLesson.package__r.unit_fee__c);                           
                taxRate = BillingUtility.roundOffAmount((fifthLesson.package__r.location__r.Country__r.tax_rate__c * fifthLesson.package__r.unit_fee__c)/100);
                totalFee = BillingUtility.roundOffAmount(taxRate + fifthLesson.package__r.unit_fee__c);
                if(fifthLesson.Booking_Date__c.month() == System.today().month() && fifthLesson.Booking_Date__c.year() == System.today().year()){
                    actionRequiredFlag = true;
                }else{
                    actionRequiredFlag = false;
                }
                system.debug('@@@@ '+fifthLesson);
                if(fifthLesson.duration__c <= fifthLesson.parent__r.Available_Make_up_Units__c){
                    makeUpButtonDisaleFlag = false;
                }else{
                    makeUpButtonDisaleFlag = true;
                }
            }else{
                errorMsg = 'Fifth Booking not found! Please contact your Center Admin.';
                isError = true;
            }    
        }else{
            errorMsg = 'Fifth Booking not found! Please contact your Center Admin.';
            isError = true;
        }
        
    }
    public void createBookingRecord(){
        System.debug('fifthLessonId = '+fifthLessonId);
        System.debug('type = '+type);
        if(String.isNotBlank(fifthLessonId) && String.isNotBlank(type)){
            String isLessonIdExist = FifthLessonController.bookingConvert(fifthLessonId,'',type,false);
            System.debug('isLessonIdExist = '+isLessonIdExist);
            //query booking id of newly created booking through fifthlesson and create app feed record
            if(String.isNotBlank(isLessonIdExist)){
                String newBookingId = getBookingIdOfFifthLesson(fifthLessonId);
                if(String.isNotBlank(newBookingId)){
                    List<booking__c> newCreatedBookingList = getNewlyCreatedBooking(newBookingId);
                    if(newCreatedBookingList.size() > 0){
                        createAppFeedRecord(newCreatedBookingList,type);      
                    }
                }
            }
            if(String.isNotBlank(isLessonIdExist) && type == 'placeholder'){
                errorMsg = 'Your 5th booking has been cancelled successfully!<br/> We are processing your request, you will be directed to lessons view in a few seconds!';
                isError = true;
            }else if(String.isNotBlank(isLessonIdExist) && type == 'makeup'){
                errorMsg = 'Your Make-up booking has been created successfully!<br/> We are processing your request, you will be directed to lessons view in a few seconds!';
                isError = true;
            }else if(String.isNotBlank(isLessonIdExist) && type == 'adhoc'){
                errorMsg = 'Your Ad-hoc booking has been created successfully!<br/> We are processing your request, you will be directed to lessons view in a few seconds!';
                isError = true;
            }            
        }
    }
    private String getBookingIdOfFifthLesson(String bookingId){
        List<fifth_lesson__c> fifthLessonList = [SELECT id,booking__c FROM fifth_lesson__c WHERE id =: bookingId];
        //if(fifthLessonList.size() > 0){
        return fifthLessonList.get(0).booking__c;
        //}
        //return '';
    }
    private List<booking__c> getNewlyCreatedBooking(String newBookingId){
        //if(String.isNotBlank(newBookingId)){
        List<booking__c> newBookingList = [SELECT id,Parent__c,Student__c,Center__r.Location__c,Teacher_Account__c,Instrument__c,Center__c,Booking_Date__c,Location__c,Start_Time__c FROM booking__c where id =: newBookingId];
        //}        
        return newBookingList;
        
    }
    private void createAppFeedRecord(List<booking__c> newCreatedBookingList,String type){
        Savepoint sp = Database.setSavepoint();
        try{
            String appFeedType;        
            if(type == 'placeholder'){
                appFeedType = '5th Lesson - CX';
            }else if(type == 'makeup'){
                appFeedType = '5th Lesson - MU';
            }else{
                appFeedType = '5th Lesson - AH';
            }
            List<App_Feeds__c> listOfApp_Feeds = new  List<App_Feeds__c>();
            for(Booking__c objBooking: newCreatedBookingList){
                String instrument;
                if(type == 'makeup'){
                    instrument = 'Make-up';
                }else if(type == 'adhoc'){
                    instrument = 'Ad-hoc';
                }else{
                    instrument = objBooking.instrument__c;
                }
                listOfApp_Feeds.add(new app_feeds__c(Parent__c = objBooking.Parent__c,
                                   Student__c = objBooking.Student__c,
                                   Teacher__c  =objBooking.Teacher_Account__c,
                                   Type__c = appFeedType,
                                   Instrument__c = instrument,
                                   Center__c = objBooking.Center__c,
                                   Booking_Id__c = objBooking.id,
                                   Booking_Date__c = objBooking.Booking_Date__c,
                                   Location__c = objBooking.Center__r.Location__c,
                                   Booking_Time__c = objBooking.Start_Time__c));
                if(listOfApp_Feeds.size() > 0){
                    insert listOfApp_Feeds;
                }                   
            }            
        }catch(Exception e){
            Database.rollback(sp);
            System.debug('Error:  '+e.getMessage());
            errorMsg = e.getMessage();
            isError = true; 
            return;           
        }   
    }
}