force-app/main/default/objects/Account/fields/Bank_Detail__c.field-meta.xml
<CustomField>
    <fullName>Bank_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Detail</label>
    <referenceTo>Bank_Master__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>C-Level</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Senior Management</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
                <isActive>false</isActive>
                <label>Director</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number__c</fullName>
    <label>Tax Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Master__c/Bank_Master__c.object-meta.xml
<CustomObject>
    <label>Bank Master</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Master__c/fields/Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>Bank_Code__c</fullName>
    <label>Bank Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Master__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/Expense_Claim__c.object-meta.xml
<CustomObject>
    <label>Expense Claim</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Claim__c/fields/Applied_Amount__c.field-meta.xml
<CustomField>
    <fullName>Applied_Amount__c</fullName>
    <label>Applied Amount</label>
    <summarizedField>Expense_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Expense_Item__c.Expense_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Amount__c</fullName>
    <label>Approved Amount</label>
    <summarizedField>Expense_Item__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Expense_Item__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Expense_Item__c.Expense_Claim__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Converted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Converted_Amount__c</fullName>
    <label>Converted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>Used to Submit Claims</description>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expense Claims</relationshipLabel>
    <relationshipName>Expense_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Exp_Bank_File_Generated__c.field-meta.xml
<CustomField>
    <fullName>Exp_Bank_File_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is set to true for Expense Claim records for which Expense Bank File is generated.</description>
    <label>Expense Bank File Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Expense Claims</relationshipLabel>
    <relationshipName>Expense_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Partial Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Submit_Date__c.field-meta.xml
<CustomField>
    <fullName>Submit_Date__c</fullName>
    <description>Updated from Approval Process on Claim Submission</description>
    <label>Submit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Submit_For_Approval_Expense_Claim__c.field-meta.xml
<CustomField>
    <fullName>Submit_For_Approval_Expense_Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used for submit expense claim record for approval</description>
    <label>Submit For Approval Expense Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BankExpenseFileController.cls
public class BankExpenseFileController{
    Public transient String fileName{get;set;}
    Public transient String strFile{get;set;}
    /*Public transient Integer month{get;set;}
    Public transient Integer year{get;set;}*/
    private Organisation__c organisation = null; 
    
    public BankExpenseFileController(){
    }
    
    public void generateFile(){
        String pOrg = Apexpages.currentPage().getParameters().get('org');
        string strUploadDate = Apexpages.currentPage().getParameters().get('uploadDate');
        
        date uploadDate = system.today().addDays(1);
        if(strUploadDate!=null && strUploadDate.trim().length()>0){
            try{
                uploadDate = Date.valueOf(strUploadDate);
            }catch(exception e){}
        }
        datetime uploadDatetime = Datetime.newInstance(uploadDate, Time.newInstance(0, 0, 0, 0));
        
        if(String.isNotBlank(pOrg)){
            List<Organisation__c > orgList = [SELECT Id, Name, Bank_Account_Number__c, Bank_Name__c, Branch_Code__c FROM Organisation__c WHERE Id = : pOrg];
            if(orgList.size() > 0) organisation = orgList.get(0);
        }
        
        fileName = 'Bank Expense File.txt';
        
        strFile = '';
        if(organisation != null){
            //Bank Name
            strFile += generateFormatedString(organisation.Bank_Name__c, false, 58, ' ');
            //Fillers (&)
            strFile += generateFormatedString('', false, 24, '&');
            
            // change header row
            strFile = strFile + '\r\n';
            
            //Bank Account
            strFile += generateFormatedString(organisation.Bank_Account_Number__c, false, 20, ' ');
            //Branch Code
            strFile += generateFormatedString(organisation.Branch_Code__c, false, 3, ' ');
            //Company Name
            strFile += generateFormatedString(organisation.Name, false, 20, ' ');
            //Today's Date
            strFile += generateFormatedString(uploadDatetime.format('yyyyMMdd'), false, 8, ' ');
            //Blanks
            strFile += generateFormatedString('', false, 31, ' ');
            
            // change sun header row
            strFile = strFile + '\r\n';
            
            //String mString = dateOfRecords.format('MMMM');
            //String yString = dateOfRecords.format('yyyy');
            Integer sequence = 50000;
            
            List<Expense_Claim__c> expClaimList = [SELECT Id, Department__c, Organisation__c, Employee__c, Remarks__c, Status__c, 
                Submit_Date__c, Submit_For_Approval_Expense_Claim__c, Applied_Amount__c, Approved_Amount__c, Exp_Bank_File_Generated__c, 
                Currency_Code__c, Name, Employee__r.Bank_Detail__r.Bank_Code__c, Employee__r.Bank_Detail__r.Branch_Code__c,Employee__r.Bank_Detail__c, 
                Employee__r.AccountNumber, Employee__r.Beneficiary_Name__c, Employee__r.Tax_Number__c,Converted_Amount__c FROM Expense_Claim__c 
                WHERE Organisation__c =: pOrg AND Exp_Bank_File_Generated__c = FALSE AND Status__c in ('Approved','Partial Approved') and Converted_Amount__c>0 and Employee__r.AccountNumber!=null 
                and Employee__r.Bank_Detail__c!=null];
            
            if(expClaimList != NULL && expClaimList.size()>0){
                Map<Id,List<Expense_Claim__c>> employeeToExpClaimMap = new Map<Id,List<Expense_Claim__c>>();
                for(Expense_Claim__c expClaim: expClaimList){
                    List<Expense_Claim__c> tempList= new List<Expense_Claim__c>();
                    If(employeeToExpClaimMap.containsKey(expClaim.Employee__c)){
                        tempList = employeeToExpClaimMap.get(expClaim.Employee__c);
                    }
                    tempList.add(expClaim);
                    employeeToExpClaimMap.put(expClaim.Employee__c,tempList);
                    expClaim.Exp_Bank_File_Generated__c = true;
                }
                for(Id empId : employeeToExpClaimMap.keyset()){
                    Expense_Claim__c expClaim = employeeToExpClaimMap.get(empId)[0];
                    String recordString = '';
                    //Sequence
                    recordString += generateFormatedString(sequence+'', false, 5, ' ');
                    //Bank Code
                    recordString += generateFormatedString(expClaim.Employee__r.Bank_Detail__r.Bank_Code__c, false, 4, ' ');
                    //Branch Code
                    recordString += generateFormatedString(expClaim.Employee__r.Bank_Detail__r.Branch_Code__c, false, 3, ' ');
                    //Account Numner
                    recordString += generateFormatedString(expClaim.Employee__r.AccountNumber, false, 11, ' ');
                    //Name
                    recordString += generateFormatedString(expClaim.Employee__r.Beneficiary_Name__c, false, 20, ' ');
                    //Number
                    recordString += generateFormatedString('21' , false, 5, ' ');
                    //NRIC Tax Number
                    recordString += generateFormatedString(expClaim.Employee__r.Tax_Number__c, false, 21, ' ');
                    //Amount
                    decimal totalAmount = 0;
                    for(Expense_Claim__c ec:employeeToExpClaimMap.get(empId)){
                        totalAmount += ec.Converted_Amount__c;
                    }
                    String temp = totalAmount!= null?totalAmount.setScale(2)+'' : '';
                    
                    recordString += generateFormatedString(temp , true, 11, '0');
                    //Blank
                    recordString += generateFormatedString('' , false, 2, ' ');
                    recordString = recordString + '\r\n';
                    
                    strFile += recordString;
                    
                    sequence = sequence + 1;
                }
            }
            
            if(expClaimList != NULL && !expClaimList.isEmpty()){
                update expClaimList;
            }
        }
    }
    
    public void TestgenerateFile(){
        /*String strmonth = Apexpages.currentPage().getParameters().get('month');
        String stryear = Apexpages.currentPage().getParameters().get('year');*/
        String pOrg = Apexpages.currentPage().getParameters().get('org');
        //year = system.today().year();
        //month = system.today().month();
        
        if(String.isNotBlank(pOrg)){
            List<Organisation__c > orgList = [SELECT Id, Name, Bank_Account_Number__c, Bank_Name__c, Branch_Code__c FROM Organisation__c WHERE Id = : pOrg];
            if(orgList.size() > 0) organisation = orgList.get(0);
        }
        
        /*if(strmonth!=null && strmonth.trim().length()>0){
            month = Integer.valueOf(strMonth);
        }
        if(stryear!=null && stryear.trim().length()>0){
            year = Integer.valueOf(stryear);
        }*/
        
        //Datetime dateOfRecords = datetime.newInstance(year,month,1,0,0,0);
        //fileName = 'Bank Expense File ('+dateOfRecords.format('MMMM')+'-'+dateOfRecords.format('YYYY')+').txt';
        fileName = 'Bank Expense File.txt';
        
        strFile = '';
        if(organisation != null){
            
            //Bank Name
            strFile += generateFormatedString(organisation.Bank_Name__c, false, 58, ' ');
            //Fillers (&)
            strFile += generateFormatedString('', false, 24, '&');
            
            // change header row
            strFile = strFile + '\r\n';
            
            //Bank Account
            strFile += generateFormatedString(organisation.Bank_Account_Number__c, false, 20, ' ');
            //Branch Code
            strFile += generateFormatedString(organisation.Branch_Code__c, false, 3, ' ');
            //Company Name
            strFile += generateFormatedString(organisation.Name, false, 20, ' ');
            //Today's Date
            strFile += generateFormatedString(DateTime.now().format('yyyyMMdd'), false, 8, ' ');
            //Blanks
            strFile += generateFormatedString('', false, 31, ' ');
            
            // change sun header row
            strFile = strFile + '\r\n';
            
            //String mString = dateOfRecords.format('MMMM');
            //String yString = dateOfRecords.format('YYYY');
            Integer sequence = 50000;
            
            List<Expense_Claim__c> expClaimList = [SELECT Id, Department__c, Organisation__c, Employee__c, Remarks__c, Status__c, 
                Submit_Date__c, Submit_For_Approval_Expense_Claim__c, Applied_Amount__c, Approved_Amount__c, Exp_Bank_File_Generated__c, 
                Currency_Code__c, Name, Employee__r.Bank_Detail__r.Bank_Code__c, Employee__r.Bank_Detail__r.Branch_Code__c, 
                Employee__r.AccountNumber, Employee__r.Beneficiary_Name__c, Employee__r.Tax_Number__c FROM Expense_Claim__c 
                WHERE Organisation__c =: pOrg AND Exp_Bank_File_Generated__c = FALSE AND Status__c = 'Approved'];
            
            if(expClaimList != NULL && expClaimList.size()>0){
                for(Expense_Claim__c expClaim: expClaimList){
                    String recordString = '';
                    //Sequence
                    recordString += generateFormatedString(sequence+'', false, 5, ' ');
                    //Bank Code
                    recordString += generateFormatedString(expClaim.Employee__r.Bank_Detail__r.Bank_Code__c, false, 4, ' ');
                    //Branch Code
                    recordString += generateFormatedString(expClaim.Employee__r.Bank_Detail__r.Branch_Code__c, false, 3, ' ');
                    //Account Numner
                    recordString += generateFormatedString(expClaim.Employee__r.AccountNumber, false, 11, ' ');
                    //Name
                    recordString += generateFormatedString(expClaim.Employee__r.Beneficiary_Name__c, false, 20, ' ');
                    //Number
                    recordString += generateFormatedString('22' , false, 5, ' ');
                    //NRIC Tax Number
                    recordString += generateFormatedString(expClaim.Employee__r.Tax_Number__c, false, 21, ' ');
                    //Amount
                    String temp = expClaim.Approved_Amount__c!= null ? expClaim.Approved_Amount__c.setScale(2)+'' : '';
                    recordString += generateFormatedString(temp , true, 11, '0');
                    //Blank
                    recordString += generateFormatedString('' , false, 2, ' ');
                    recordString = recordString + '\r\n';
                    
                    if(expClaim.Employee__c != null && String.isNotBlank(expClaim.Employee__r.Bank_Detail__r.Bank_Code__c) && 
                    String.isNotBlank(expClaim.Employee__r.Bank_Detail__r.Branch_Code__c) && 
                    String.isNotBlank(expClaim.Employee__r.AccountNumber) && 
                    String.isNotBlank(expClaim.Employee__r.Beneficiary_Name__c) && 
                    expClaim.Approved_Amount__c != null && expClaim.Approved_Amount__c > 0){
                        strFile += recordString;
                        expClaim.Exp_Bank_File_Generated__c = TRUE;
                    }
                }
                sequence = sequence + 1;
            }
            
            if(expClaimList != NULL && !expClaimList.isEmpty()){
                update expClaimList;
            }
        }
    }
    
    public String generateFormatedString(String str, Boolean isNumeric, Integer uptoChar, String paddedWith){
        if(str == null ) str = '';
        if(isNumeric){
            if(str.indexOf('.') != -1){
                str = str.remove('.');
            }
            str = str.leftPad(uptoChar, paddedWith);
        }else{
            Integer length = str.length();
            if(length > uptoChar) return str.substring(0,uptoChar);
            str = str.rightPad(uptoChar, paddedWith);
        }
        return str;
    }
    public pageReference redirectTo(){
        return new pageReference('/apex/GenerateExpenseBankFile');
    }
}