force-app/main/default/objects/Account/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CDAC_Contribution__c.field-meta.xml
<CustomField>
    <fullName>CDAC_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDAC Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CentreName_Cust__c.field-meta.xml
<CustomField>
    <fullName>CentreName_Cust__c</fullName>
    <label>CentreName Cust</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Duty_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Duty_Type__c</fullName>
    <label>Employee Duty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Duty</fullName>
            </value>
            <value>
                <fullName>Non-Duty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EUCF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>EUCF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EUCF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foreigner</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/MBMF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>MBMF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MBMF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SINDA_Contribution__c.field-meta.xml
<CustomField>
    <fullName>SINDA_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SINDA Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number__c</fullName>
    <label>Tax Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Teacher_Bio__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Bio__c</fullName>
    <inlineHelpText>Data enter here will be shown on Trial and Enrolment pages.</inlineHelpText>
    <label>Teacher Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>Branch_Code__c</fullName>
    <label>Branch Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payout__c/Payout__c.object-meta.xml
<CustomObject>
    <label>Payout</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Pay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payout__c/fields/CDAC_Contribution__c.field-meta.xml
<CustomField>
    <fullName>CDAC_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDAC Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Employee_CPF_Amount__c.field-meta.xml
<CustomField>
    <fullName>Employee_CPF_Amount__c</fullName>
    <label>Employee CPF Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Payrolls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Employer_CPF_Amount__c.field-meta.xml
<CustomField>
    <fullName>Employer_CPF_Amount__c</fullName>
    <label>Employer CPF Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/EUCF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>EUCF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EUCF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/MBMF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>MBMF_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MBMF Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/SINDA_Contribution__c.field-meta.xml
<CustomField>
    <fullName>SINDA_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SINDA Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Future_Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/BankFileControllerTest.cls
@isTest
public class BankFileControllerTest{
    
     @isTest
    public static void unitTest(){
        
        string empRecordType =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Employee').getRecordTypeId();
        Organisation__c org = new Organisation__c(
            Name = 'Test Org',
            Bank_Account_Number__c = '123456789',
            Bank_Name__c = 'Test Bank Name',
            Branch_Code__c = '001'
        );
        insert org;
        
        Account employee = new Account(
            RecordTypeId = empRecordType,
            LastName='testEmployee',
            Teacher_Bio__c='testbio',
            CentreName_Cust__c='testCenter',
            Status__c='Working',
            Employee_Status__c = 'Confirm',
            Joining_Date__c = Date.Today().addDays(-10),
            Last_Working_Date__c = Date.today().addDays(10),
            Issue_Date__c = Date.Today().addDays(-30),
            ID_Type__c = 'Permanent Resident',
            PersonBirthdate = date.today().addYears(-30),
            Tax_Number__c = 'G3107590X',
            Organisation__c = org.Id,
            Employee_Duty_Type__c = 'Duty'
        );
        insert employee;  
        Payout__c payout = new Payout__c(
            Salary__c = 200,
            Employee_Name__c = employee.Id,
            year__c = DateTime.Now().format('YYYY'),
            Month__c = DateTime.Now().format('MMMM'),
            Employee_CPF_Amount__c = 21,
            Employer_CPF_Amount__c = 31,
            CDAC_Contribution__c = true,
            EUCF_Contribution__c = true,
            MBMF_Contribution__c = true,
            SINDA_Contribution__c = true
        );
        insert payout ;
        
        Test.StartTest();
        Test.setCurrentPageReference(new PageReference('Page.BankFile')); 
        System.currentPageReference().getParameters().put('org', org.Id);
        BankFileController obj = new BankFileController();
        obj.redirectTo();
        Test.StopTest();
    }
}