force-app/main/default/objects/Account/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <label>Stripe Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Minimum_Rental_Commitment_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Rental_Commitment_Period__c</fullName>
    <description>this field for piano rental for manage customer Minimum rental commitment period,</description>
    <label>Minimum Rental Commitment Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <description>this field for piano rental for manage customer Termination reason</description>
    <label>Termination Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not needed anymore</fullName>
            </value>
            <value>
                <fullName>Moving out of SG</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerminationEnrolmentProcessController.cls
/*
Name: TerminationEnrolmentProcessController
Date: 23-jan-2020
Author: JATIN
Description :  this controller for Terminating Piano Rental  for get Terminating date and pickup date 
*/

//CH01 15 Oct 2020 Karan Singh : CHanging the minimum period and Terminate Notice Period for aureus Student.

public with sharing class TerminationEnrolmentProcessController {
    Public Enrolment__c objEnrolment{get;set;}
    Public String TerminationReasonName{get;set;}
    Public String rentalDateString{get;set;}
    Public Boolean isSendToButton{get;set;}
    Public Boolean isRentalNotFound{get;set;}
    Public String errorMessage{get;set;}
    
    public TerminationEnrolmentProcessController(ApexPages.StandardController st) {
        objEnrolment = (Enrolment__c)st.getRecord();
        if(string.isNotBlank(objEnrolment.id)){
            List<Enrolment__c> listOfEnrolment = PianoRentalHelperController.getRentalEnrolmentList(new Set<string>{objEnrolment.id});
            if(listOfEnrolment != null && listOfEnrolment.size() > 0 ){
                objEnrolment = listOfEnrolment[0];
            }
            
            //CH01 : Fetching other details of the enrolment to check if the student is existing or not. Similar exisitng aureus student logic as used in PIano Rental process where we check if the customer is existing or no
            //			CLass- > SearchInstrumentRental_IpadCntrl , exisitng logic used, search this loginc in the class : isAlreadyStripCstmr
            List< Enrolment__c > listofEnrolForAureusStruent = [ SELECT Id,Instrument_Type__c, Parent__r.Stripe_Customer_Id__c, Parent__r.Card_Number__c, Parent__r.Card_Type__c FROM Enrolment__c WHERE Id =: objEnrolment.id ];
            Boolean isMinimumPeriodApplicable = false;
            
            set< String > setInstrumentType = new set< String >();
            if( String.isNotBlank( Label.Instrument_Type_for_the_Existing_Aureus_Students ) ){
                
                if( Label.Instrument_Type_for_the_Existing_Aureus_Students.contains(',') ){
                    setInstrumentType.addAll( Label.Instrument_Type_for_the_Existing_Aureus_Students.split(',') );
                }else{
                    setInstrumentType.add( Label.Instrument_Type_for_the_Existing_Aureus_Students);
                }
            }
            if( setInstrumentType.contains( listofEnrolForAureusStruent[0].Instrument_Type__c ) 
               //Existing Aureus Student checking loginc - (isAlreadyStripCstmr) 
               && String.isNotBlank( listofEnrolForAureusStruent[0].Parent__r.Stripe_Customer_Id__c  ) 
               && String.isNotBlank( listofEnrolForAureusStruent[0].Parent__r.Card_Number__c  ) && String.isNotBlank( listofEnrolForAureusStruent[0].Parent__r.Card_Type__c  ) ){
                   isMinimumPeriodApplicable = true;
               }
            //CH01 END
            Date terminateDate = system.today().addMonths(2);
            
            //CH01 Start
            if(isMinimumPeriodApplicable && String.isNotBlank( Label.Min_Notice_Period_for_Instrument_Rental_Termination_For_Aureus_Students )) {
                terminateDate = system.today().addMonths( Integer.valueOf( Label.Min_Notice_Period_for_Instrument_Rental_Termination_For_Aureus_Students ) );
            }
            //CH01 END
            Date minCommitmentRentalDate;
            isSendToButton = true;
            //consider Terminating Piano Rental:
            //a.	Minimum commitment period – 6 months
            //b.	Minimum notice period – 2 months
            
            //CH01 : ALso consider this points for Terminating Piano Rental
            //c.	Minimum Commitment period for the Aureus Student will be 3 months for KeyBoard and drum only
            //d.	Minimum notice period for the Aureus Student will be 1 months for KeyBoard and drum only
            
            if(objEnrolment.Subscription_Line_Items__r != null && objEnrolment.Subscription_Line_Items__r.size() > 0){
                if(objEnrolment.Subscription_Line_Items__r[0].Subscription_Start_Date__c != null){
                    /* if(objEnrolment.Minimum_Rental_Commitment_Period__c != null){
minCommitmentRentalDate = objEnrolment.Minimum_Rental_Commitment_Period__c;
}else{*/
                    minCommitmentRentalDate = objEnrolment.Subscription_Line_Items__r[0].Subscription_Start_Date__c.AddMonths(6);
                    //}
                    
                    //CH01 Start
                    if(isMinimumPeriodApplicable && String.isNotBlank( Label.Min_Commitment_Duration_for_Instrument_Rental_For_Aureus_Students )) {
                        minCommitmentRentalDate = objEnrolment.Subscription_Line_Items__r[0].Subscription_Start_Date__c.AddMonths( Integer.valueOf( Label.Min_Commitment_Duration_for_Instrument_Rental_For_Aureus_Students ) );  
                    }
                    //CH01 END
                    
                    if(minCommitmentRentalDate > terminateDate){
                        terminateDate = terminateDate.addDays(terminateDate.daysBetween(minCommitmentRentalDate));
                    }
                    isRentalNotFound= true;
                }else{
                    isRentalNotFound= false;
                    errorMessage ='We cannot process your request at the moment Rental Date not found. Please centre admin for further assistance.';
                }
                // terminateDate = terminateDate.addDays(1);
                rentalDateString = terminateDate.month()+'/'+terminateDate.day()+'/'+terminateDate.year();
                if(objEnrolment.Stage__c =='Piano Termination In-Progress' || objEnrolment.Stage__c =='Piano Rental Terminated'){
                    isRentalNotFound = false;
                    errorMessage ='We cannot process your request at the moment Already instrument terminatation is proceed. Please centre admin for further assistance.';
                }
            }else{
                isRentalNotFound= false;
                errorMessage ='We cannot process your request at the moment. Please centre admin for further assistance.';
            }
        }
    }
    
    public  List<SelectOption> getTerminationReason(){
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeSobjectResult[] results = Schema.describeSObjects(new List<String>{'Enrolment__c'});
        Schema.DescribeFieldResult dfrList = results[0].fields.getMap().get('Termination_Reason__c').getDescribe();
        String type = String.valueOf(dfrList.getType());
        options.add(new SelectOption('','Select Termination Reason'));
        if(type.equalsIgnoreCase('PICKLIST')){
            for(Schema.PicklistEntry currentEntry : dfrList.getPicklistValues()){
                options.add(new SelectOption(currentEntry.getValue() ,currentEntry.getValue()));
            }
        }
        return options;
    }
    
}