force-app/main/default/objects/Account/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration__c.field-meta.xml
<CustomField>
    <fullName>Expiration__c</fullName>
    <description>Expiry Month + Expiry Year
01/22</description>
    <formula>IF( ISNULL(Expiry_Month__c) ,&quot;&quot;,

CASE( Expiry_Month__c , 
1,&quot;01&quot;,
2,&quot;02&quot;,
3,&quot;03&quot;,
4,&quot;04&quot;,
5,&quot;05&quot;,
6,&quot;06&quot;,
7,&quot;07&quot;,
8,&quot;08&quot;,
9,&quot;09&quot;,
10,&quot;10&quot;,
11,&quot;11&quot;,
12,&quot;12&quot;,
&quot;&quot;) 
&amp; &quot;/&quot; &amp;
 RIGHT(TEXT(Expiry_Year__c),2)
)</formula>
    <label>Expiration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FCM_Token__c.field-meta.xml
<CustomField>
    <fullName>FCM_Token__c</fullName>
    <label>FCM Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mobile_Notification__c/Mobile_Notification__c.object-meta.xml
<CustomObject>
    <label>Mobile Notification</label>
    <nameField>
        <displayFormat>N-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CCExpirationNotificationBatch.cls
/*
        Name        :    CCExpirationNotificationBatch 
        Date        :    02/Aug/2019
        Author      :  
        Description :    This batch class is used to send reminder parent card CC is expire
      
*/
global class CCExpirationNotificationBatch implements Database.Batchable<sObject>,database.stateful,Database.AllowsCallouts{
    private Integer noOfDays;
    public CCExpirationNotificationBatch (Integer days){
        this.noOfDays= days;
    } 
    global Database.QueryLocator start(Database.BatchableContext BC){
        Date preDate = system.today().addDays(noOfDays);
        String year = String.valueOf(preDate.year());
        String dateFormat = preDate.Month()+'/'+ year.substring(2,4);
        system.debug('dateFormat'+dateFormat);
        return Database.getQueryLocator([select id,name,Expiry_Date__c,FCM_Token__c,Card_Number__c,Card_Type__c 
                                        FROM Account
                                        WHERE Expiration__c=: dateFormat 
                                        AND Card_Number__c!=null 
                                        AND FCM_Token__c !=null 
                                        ]);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> accountList){
       system.debug('accountList'+accountList);
       List<Mobile_Notification__c> listOfMobileNotification = new List<Mobile_Notification__c>();
        for(Account accountObj: accountList){
                 String  title =  'Your Payment on file '+accountObj.Card_Type__c+' x ' +accountObj.Card_Number__c+' is expiring soon.';
                 String  bodymsg = 'Please update your billing details by going to your account and adding a new card.';
                 String to = accountObj.FCM_Token__c;
                Mobile_Notification__c log = FirebaseNotificationHelper.sendNotificationBatch(accountObj.id, to, title, bodymsg);
                if(log != null) listOfMobileNotification.add(log); 
              
               
        }
        system.debug('listOfMobileNotification'+listOfMobileNotification);
        if(listOfMobileNotification.size() > 0 && listOfMobileNotification!= Null){
            insert listOfMobileNotification;
        }
        
    }

    global void finish(Database.BatchableContext BC){
       
    }
    
}