force-app/main/default/objects/Account/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <label>Card Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CentreName_Cust__c.field-meta.xml
<CustomField>
    <fullName>CentreName_Cust__c</fullName>
    <label>CentreName Cust</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <label>Stripe Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Location__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Session duration in minutes (Trial will be 30 min)</inlineHelpText>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/of_Units__c.field-meta.xml
<CustomField>
    <fullName>of_Units__c</fullName>
    <label># of Units</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Package_after_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Package_after_Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package after Promotion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Package__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Lesson</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Promotion_Discount__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Discount__c</fullName>
    <label>Promotion Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Promotion_period_In_months__c.field-meta.xml
<CustomField>
    <fullName>Promotion_period_In_months__c</fullName>
    <label>Promotion period (In months)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Type_of_package__c.field-meta.xml
<CustomField>
    <fullName>Type_of_package__c</fullName>
    <label>Type of package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Promo</fullName>
            </value>
            <value>
                <fullName>Prepayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to setup package for music lesson</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <label>Billing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Following program type may not be used
1. Trial
2. Makeup
3. Adhoc</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/School__c/School__c.object-meta.xml
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Schools</relationshipLabel>
    <relationshipName>Schools</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EnrolmentProcessControllertest.cls
/*
Name        :        EnrolmentProcessControllertest
Date        :        21,22 April 2019,18 july 2019
Author      :        Karan Singh Soni
Description :        It is the test class of EnrolmentProcessController.
*/

@isTest
public class EnrolmentProcessControllertest {
    public static testMethod void invokeEnrolmentProcessController(){
        Country__c cntry = new Country__c();
        cntry.Name = 'SG';
        cntry.Country_Name__c ='Singapore';
        cntry.Currency_Code__c ='SGD';
        cntry.Tax_Rate__c = 7;
        cntry.Student_Policies_Template_Id__c= 'DLe9tWht6W9PNHEabs2ruT';
        cntry.Stripe_Base_Url__c ='https://api.stripe.com';
        cntry.Stripe_Publishable_Key__c ='pk_test_eGeu4Z0mLSfXmekcJcLt7TVH';
        cntry.Stripe_Secret_Key__c ='sk_test_M3pk8qvbMs03SWjDuf6m1bss';
        insert cntry;
        
        Map<string,string> entrdDataMap=TestUtil.createData(); 
        // ################################ Added By Karan Singh Soni on 26 June 2019 ###########################
        Account objCentr=new Account();
        objCentr.id=entrdDataMap.get('objCentr');
        objCentr.Name='Aureus 112 Katong'; // satisfying condition on LOC 294
        objCentr.CentreName_Cust__c='Aureus Academy - 112 Katong';
        objCentr.Country__c = cntry.Id;
        update objcentr;
        // ################################  END Added By Karan Singh Soni on 26 June 2019 ######################
        Account objCustmr=new Account();
        objCustmr.id=entrdDataMap.get('objCustmr');
        objCustmr.Stripe_Customer_Id__c='cus_EtBijt8zP1mTdc';
        objCustmr.Card_Number__c='4242';
        objCustmr.Card_Type__c='Visa';
        update objCustmr;
        
        School__c objSchool= new School__C();
        objschool.Name='Rosyth School';
        insert objSchool;
        
        Program__C objProgram= new Program__C();
        objProgram.Id=entrdDataMap.get('objProg');
        objProgram.Billing__c='Monthly';
        update objProgram; 
        
        
        Package__c objPack= new Package__c();
        objPack.Id=entrdDataMap.get('objPack');
        objPack.Duration__c='30';
        objpack.Type__c='Individual';
        objpack.Type_of_package__c = 'Normal';
        objPack.RecordTypeId=Schema.SObjectType.Package__c.getRecordTypeInfosByName().get('Lesson').getRecordTypeId();
        update objpack;
        
        
        ApexPages.currentPage().getParameters().put('Id',entrdDataMap.get('objEnrol'));
        
        EnrolmentProcessController objEPC=new EnrolmentProcessController();
        objEPC.getAccoungGenderPicklist();
        objEPC.getAccoungNationalityPicklist();
        objEPC.getAccoungBillCntryPicklist();
        objEPC.getSchoolPicklist(); 
        objEPC.saveStuAndLessonOnGrid();
        objEPC.thirdScreenFeeCalculation();
		
        test.startTest();
            objEpc.stripeToken='sk_test_BQokikJOvBiI2HlWgH4olfQ2';
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'{ "id":"cus_EmndZcxxpUhDzD", "object": "customer","paid": true, "account_balance": 0, "created": 1553840254, "currency": "usd", "default_source": null, "delinquent": false, "description": null, "discount": null, "email": null, "invoice_prefix": "98B2456", "invoice_settings": { "custom_fields": null, "footer": null }, "livemode": false, "metadata": {}, "shipping": null, "sources": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/sources" }, "subscriptions": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/subscriptions" }, "tax_info": null, "tax_info_verification": null }'));
            
            objEpc.base64SignImg='TestEnrolmentImage';
            objEpc.completeEnrolment();
            
            objEpc.selectedStudentIndex = 0;
            objEpc.selectedLessonIndex  = 0;
            objEpc.buttonType  = 'EditRowBtn';
            objEpc.editLesson();
            
            objEpc.refreshSlots();
        objEPC.addMoreLessons();
        objEPC.addMoreStudentsAndLessons();
        test.stopTest();
        
        /*
        //objEpc.lessonWrap.selectedPlan=entrdDataMap.get('objPack');
        
       objEPC.getAccoungGenderPicklist();
        objEPC.getAccoungNationalityPicklist();
        objEPC.getAccoungBillCntryPicklist();
        objEPC.getSchoolPicklist();
        objEPC.checkTrialAvl();
        objEPC.lessonWrap.selectedCenter=entrdDataMap.get('objCentr');
        objEPC.fetchPlans();  
        
        objEpc.fetchTeachers();
        
        
        objEpc.lessonWrap.selectedTeacher=entrdDataMap.get('objTchr');
        objEpc.lessonWrap.lessonSlctSlot='11:00';
        objEpc.fetchTimeSlot();  
        objEpc.saveStuAndLessonOnGrid();
        objEpc.thirdScreenFeeCalculation(); 
        test.startTest();
        objEpc.stripeToken='sk_test_BQokikJOvBiI2HlWgH4olfQ2';
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'{ "id":"cus_EmndZcxxpUhDzD", "object": "customer", "account_balance": 0, "created": 1553840254, "currency": "usd", "default_source": null, "delinquent": false, "description": null, "discount": null, "email": null, "invoice_prefix": "98B2456", "invoice_settings": { "custom_fields": null, "footer": null }, "livemode": false, "metadata": {}, "shipping": null, "sources": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/sources" }, "subscriptions": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/subscriptions" }, "tax_info": null, "tax_info_verification": null }'));
        objEpc.parentAccWrap.Email='testEmail@gmail.com';
        objEpc.parentAccWrap.lastname='ParentWrapperLastName';
        
        objEpc.isParAlsoAStudent=true;
        objEpc.base64SignImg='TestEnrolmentImage';
        objEpc.completeEnrolment();
        test.stopTest();
        
        */
    }
    public static testMethod void invokeEnrolmentProcessController2(){
        /*EnrolmentProcessController objEPC=new EnrolmentProcessController();
        objEPC.checkTrialAvl();
        objEPC.selectedStudentIndex =1;
        objEPC.deleteLesson();
        objEPC.addMoreStudentsAndLessons();
        objEPC.completeEnrolment();
        School__c objSchool= new School__C();
        objschool.Name='Other';
        insert objSchool;
        objEPC.getSchoolPicklist();
        objEPC.isFreeTrialOpp = true;
        objEPC.checkTrialAvl();
        objEPC.isAlreadyStripCstmr =False;
       objEPC.stripeToken = 'Token';
        test.startTest();
                    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'{ "id":"cus_EmndZcxxpUhDzD", "object": "customer", "account_balance": 0, "created": 1553840254, "currency": "usd", "default_source": null, "delinquent": false, "description": null, "discount": null, "email": null, "invoice_prefix": "98B2456", "invoice_settings": { "custom_fields": null, "footer": null }, "livemode": false, "metadata": {}, "shipping": null, "sources": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/sources" }, "subscriptions": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/subscriptions" }, "tax_info": null, "tax_info_verification": null }'));
        objEPC.completeEnrolment();
        test.stopTest();
        //objEPC.addMoreLessons();
        //
        */
        
        Country__c cntry = new Country__c();
        cntry.Name = 'SG';
        cntry.Country_Name__c ='Singapore';
        cntry.Currency_Code__c ='SGD';
        cntry.Tax_Rate__c = 7;
        cntry.Student_Policies_Template_Id__c= 'DLe9tWht6W9PNHEabs2ruT';
        cntry.Stripe_Base_Url__c ='https://api.stripe.com';
        cntry.Stripe_Publishable_Key__c ='pk_test_eGeu4Z0mLSfXmekcJcLt7TVH';
        cntry.Stripe_Secret_Key__c ='sk_test_M3pk8qvbMs03SWjDuf6m1bss';
        insert cntry;
        
        
        Map<string,string> entrdDataMap=TestUtil.createData(); 
        // ################################ Added By Karan Singh Soni on 26 June 2019 ###########################
        Account objCentr=new Account();
        objCentr.Country__c = cntry.Id;
        objCentr.id=entrdDataMap.get('objCentr');
        objCentr.Name='Aureus 112 Katong'; // satisfying condition on LOC 294
        objCentr.CentreName_Cust__c='Aureus Academy - 112 Katong';
        update objcentr;
        // ################################  END Added By Karan Singh Soni on 26 June 2019 ######################
        Account objCustmr=new Account();
        objCustmr.id=entrdDataMap.get('objCustmr');
        objCustmr.Stripe_Customer_Id__c='cus_EtBijt8zP1mTdc';
        objCustmr.Card_Number__c='4242';
        objCustmr.Card_Type__c='Visa';
        update objCustmr;
        
        School__c objSchool= new School__C();
        objschool.Name='Rosyth School';
        insert objSchool;
        
        Program__C objProgram= new Program__C();
        objProgram.Id=entrdDataMap.get('objProg');
        objProgram.Billing__c='Monthly';
        update objProgram; 
        
        Package__c objPacktemp =testutil.createPackage(objProgram.id, objcentr.id, '30', true);
        
        
        Package__c objPack= new Package__c();
        objPack.Id=entrdDataMap.get('objPack');
        objPack.Duration__c='30';
        objpack.Type__c='Individual';
        objpack.Type_of_package__c = 'Promo';
        objpack.Promotion_Discount__c = 99;
        objpack.Promotion_period_In_months__c = '2';
        objpack.Package_after_Promotion__c = objPacktemp.id;
        objpack.of_Units__c = 8;
        objPack.RecordTypeId=Schema.SObjectType.Package__c.getRecordTypeInfosByName().get('Lesson').getRecordTypeId();
        update objpack;
        
        
        ApexPages.currentPage().getParameters().put('Id',entrdDataMap.get('objEnrol'));
        
        EnrolmentProcessController objEPC=new EnrolmentProcessController();
        objEPC.getAccoungGenderPicklist();
        objEPC.getAccoungNationalityPicklist();
        objEPC.getAccoungBillCntryPicklist();
        objEPC.getSchoolPicklist(); 
         objEPC.lessonWrap.selectedPlan = objPack.id;
        objepc.fetchTimeSlot();
        objEPC.saveStuAndLessonOnGrid();
        objEPC.thirdScreenFeeCalculation();
		
        test.startTest();
       
        
            objEpc.stripeToken='sk_test_BQokikJOvBiI2HlWgH4olfQ2';
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'{ "id":"cus_EmndZcxxpUhDzD", "object": "customer", "paid": true, "account_balance": 0, "created": 1553840254, "currency": "usd", "default_source": null, "delinquent": false, "description": null, "discount": null, "email": null, "invoice_prefix": "98B2456", "invoice_settings": { "custom_fields": null, "footer": null }, "livemode": false, "metadata": {}, "shipping": null, "sources": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/sources" }, "subscriptions": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/subscriptions" }, "tax_info": null, "tax_info_verification": null }'));
            
            objEpc.base64SignImg='TestEnrolmentImage';
            objEpc.completeEnrolment();
            
            objEpc.selectedStudentIndex = 0;
            objEpc.selectedLessonIndex  = 0;
            objEpc.buttonType  = 'EditRowBtn';
            objEpc.editLesson();
            
            objEpc.refreshSlots();
        objEPC.addMoreLessons();
        objEPC.addMoreStudentsAndLessons();
        test.stopTest();
        
        /*
        //objEpc.lessonWrap.selectedPlan=entrdDataMap.get('objPack');
        
       objEPC.getAccoungGenderPicklist();
        objEPC.getAccoungNationalityPicklist();
        objEPC.getAccoungBillCntryPicklist();
        objEPC.getSchoolPicklist();
        objEPC.checkTrialAvl();
        objEPC.lessonWrap.selectedCenter=entrdDataMap.get('objCentr');
        objEPC.fetchPlans();  
        
        objEpc.fetchTeachers();
        
        
        objEpc.lessonWrap.selectedTeacher=entrdDataMap.get('objTchr');
        objEpc.lessonWrap.lessonSlctSlot='11:00';
        objEpc.fetchTimeSlot();  
        objEpc.saveStuAndLessonOnGrid();
        objEpc.thirdScreenFeeCalculation(); 
        test.startTest();
        objEpc.stripeToken='sk_test_BQokikJOvBiI2HlWgH4olfQ2';
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,'{ "id":"cus_EmndZcxxpUhDzD", "object": "customer", "account_balance": 0, "created": 1553840254, "currency": "usd", "default_source": null, "delinquent": false, "description": null, "discount": null, "email": null, "invoice_prefix": "98B2456", "invoice_settings": { "custom_fields": null, "footer": null }, "livemode": false, "metadata": {}, "shipping": null, "sources": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/sources" }, "subscriptions": { "object": "list", "data": [], "has_more": false, "total_count": 0, "url": "/v1/customers/cus_EmndZcxxpUhDzD/subscriptions" }, "tax_info": null, "tax_info_verification": null }'));
        objEpc.parentAccWrap.Email='testEmail@gmail.com';
        objEpc.parentAccWrap.lastname='ParentWrapperLastName';
        
        objEpc.isParAlsoAStudent=true;
        objEpc.base64SignImg='TestEnrolmentImage';
        objEpc.completeEnrolment();
        test.stopTest();
        
        */

    }
    
}