force-app/main/default/objects/Account/fields/CentreName_Cust__c.field-meta.xml
<CustomField>
    <fullName>CentreName_Cust__c</fullName>
    <label>CentreName Cust</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Duty_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Duty_Type__c</fullName>
    <label>Employee Duty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Duty</fullName>
            </value>
            <value>
                <fullName>Non-Duty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foreigner</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Teacher_Bio__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Bio__c</fullName>
    <inlineHelpText>Data enter here will be shown on Trial and Enrolment pages.</inlineHelpText>
    <label>Teacher Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payroll_Batch__c/Payroll_Batch__c.object-meta.xml
<CustomObject>
    <label>Payroll Batch</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Payroll Batch No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payroll Batch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payroll_Batch__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Month</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payroll_Batch__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Payroll Batch</relationshipLabel>
    <relationshipName>Payroll_Batch</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payroll_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payroll_Batch__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PayrollBatchSetupControllerTest.cls
@isTest
public class PayrollBatchSetupControllerTest{
    @isTest
    public static void newRecordUnitTestPayrollBatch(){
        Organisation__c org = new Organisation__c(Name = 'Test org');
        insert org;
        
        Payroll_Batch__c payBatchLastMonth = new Payroll_Batch__c(
            Month__c = DateTime.Now().addMonths(-1).format('MMMMM'),
            Organisation__c = org.id,
            Year__c = DateTime.Now().addMonths(-1).format('YYYY')
        );
        insert payBatchLastMonth ;
        
        Payroll_Batch__c payBatch = new Payroll_Batch__c(
            Month__c = DateTime.Now().format('MMMMM'),
            Organisation__c = org.id,
            Year__c = DateTime.Now().format('YYYY')
        );
        insert payBatch ;
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(new Payroll_Batch__c());
        PayrollBatchSetupController obj = new PayrollBatchSetupController(sc);
        
        PayrollBatchSetupController.getRunBatch(payBatchLastMonth.Id, org.Id, DateTime.Now().format('MMMMM'), DateTime.Now().format('YYYY'), '', payBatchLastMonth.Id);
        obj.reDirectTo();
        Test.stopTest();
    }
    
    @isTest
    public static void editRecordUnitTestPayrollBatch(){
        Organisation__c org = new Organisation__c(Name = 'Test org');
        insert org;
        
        Account objAcc = new Account();
        string s=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Employee').getRecordTypeId();
        objAcc.RecordTypeId =s; 
        objAcc.LastName='testEmployee';
        objAcc.Teacher_Bio__c='testbio';
        objAcc.CentreName_Cust__c='testCenter';
        objAcc.Status__c='Working';   
        objAcc.Employee_Status__c = 'Confirm';
        objAcc.Joining_Date__c = Date.Today().addDays(-10);
        objAcc.Last_Working_Date__c = Date.today().addDays(10);
        objAcc.Issue_Date__c = Date.Today().addDays(-30);
        objAcc.ID_Type__c = 'Permanent Resident';
        objAcc.PersonBirthdate = date.today().addYears(-30);
        objAcc.Organisation__c = org.Id;
        objAcc.Employee_Duty_Type__c = 'Duty';
        insert objAcc; 
        
        Payroll_Batch__c payBatchLastMonth = new Payroll_Batch__c(
            Month__c = DateTime.Now().addMonths(-1).format('MMMMM'),
            Organisation__c = org.id,
            Year__c = DateTime.Now().addMonths(-1).format('YYYY')
        );
        insert payBatchLastMonth ;
        
        Payroll_Batch__c payBatch = new Payroll_Batch__c(
            Month__c = DateTime.Now().format('MMMMM'),
            Organisation__c = org.id,
            Year__c = DateTime.Now().format('YYYY')
        );
        insert payBatch ;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(payBatch);
        PayrollBatchSetupController obj = new PayrollBatchSetupController(sc);
        
        
        // calling meethods
        obj.reDirectTo();
        List<SelectOption> option = obj.getMonths;
        option = obj.getYearPickListValuesIntoList;
        String values = obj.getPaymentModePickListValuesIntoList;
        option = obj.getOrganisations;
        PayrollBatchSetupController.getFilterRemoteResult(org.Id, DateTime.Now().format('MMMMM'), DateTime.Now().format('YYYY'), payBatchLastMonth.Id);
        PayrollBatchSetupController.getRunBatch('', org.Id, DateTime.Now().format('MMMMM'), DateTime.Now().format('YYYY'), '', payBatchLastMonth.Id);
        PayrollBatchSetupController.getRunBatch('', org.Id, DateTime.Now().addMonths(1).format('MMMMM'), DateTime.Now().addMonths(1).format('YYYY'), '', payBatchLastMonth.Id);
        Test.stopTest();
    }
}