force-app/main/default/objects/Account/fields/Center_Email__c.field-meta.xml
<CustomField>
    <fullName>Center_Email__c</fullName>
    <label>Centre Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Centre_Status__c.field-meta.xml
<CustomField>
    <fullName>Centre_Status__c</fullName>
    <description>This field is used to enable or disable centre on public pages</description>
    <label>Centre Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CentreName_Cust__c.field-meta.xml
<CustomField>
    <fullName>CentreName_Cust__c</fullName>
    <label>CentreName Cust</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foreigner</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Main_Centre__c.field-meta.xml
<CustomField>
    <fullName>Main_Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Centre</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Main Centre)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Teacher_Bio__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Bio__c</fullName>
    <inlineHelpText>Data enter here will be shown on Trial and Enrolment pages.</inlineHelpText>
    <label>Teacher Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>Travel_Time__c</fullName>
    <defaultValue>30</defaultValue>
    <description>Aureus at Home</description>
    <inlineHelpText>Applicable for the home lessons</inlineHelpText>
    <label>Travel Time(In Minutes)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/PayItem__c/PayItem__c.object-meta.xml
<CustomObject>
    <label>PayItem</label>
    <nameField>
        <displayFormat>PI-{0000000}</displayFormat>
        <label>PayItem No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PayItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PayItem__c/fields/No_of_Days__c.field-meta.xml
<CustomField>
    <fullName>No_of_Days__c</fullName>
    <label>No. of Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PayItem__c/fields/Payitem__c.field-meta.xml
<CustomField>
    <fullName>Payitem__c</fullName>
    <label>Payitem</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payitem_Master__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payitem_Master__c</referenceTo>
    <relationshipLabel>PayItem</relationshipLabel>
    <relationshipName>Payitems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PayItem__c/fields/Payout__c.field-meta.xml
<CustomField>
    <fullName>Payout__c</fullName>
    <label>Payout</label>
    <referenceTo>Payout__c</referenceTo>
    <relationshipLabel>PayItem</relationshipLabel>
    <relationshipName>PayItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payitem_Master__c/Payitem_Master__c.object-meta.xml
<CustomObject>
    <label>Payitem Master</label>
    <nameField>
        <label>Payitem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payitem Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payitem_Master__c/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPF</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payout__c/Payout__c.object-meta.xml
<CustomObject>
    <label>Payout</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Pay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PayItemTriggerTest.cls
@isTest
public class PayItemTriggerTest{
    @isTest
    public static void unitTest(){
        Account objAcc1 = new Account();
        string centerRecordType =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Centre').getRecordTypeId();
        objAcc1.name='testCenter';
        objAcc1.CentreName_Cust__c='testCenter'; 
        objAcc1.Travel_Time__c=60.00;
        objAcc1.Location__c='Aureus Forum';
        objAcc1.Center_Email__c='test@techmatrixconsulting.com';
        objAcc1.Centre_Status__c='Active';
        insert objAcc1;
        
        Account objAcc = new Account();
        string s=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Employee').getRecordTypeId();
        objAcc.RecordTypeId =s; 
        objAcc.LastName='testEmployee';
        objAcc.Teacher_Bio__c='testbio';
        objAcc.CentreName_Cust__c='testCenter';
        objAcc.Status__c='Working';   
        objAcc.Employee_Status__c = 'Confirm';
        objAcc.Main_Centre__c = objAcc1.Id;
        objAcc.Joining_Date__c = Date.Today().addDays(-10);
        objAcc.Last_Working_Date__c = Date.today().addDays(10);
        objAcc.Issue_Date__c = Date.Today().addDays(-30);
        objAcc.ID_Type__c = 'Permanent Resident';
        objAcc.PersonBirthdate = date.today().addYears(-30);
        insert objAcc;   
        
        
        Payitem_Master__c pim = new Payitem_Master__c(
            Active__c = true,
            CPF__c = 'Non-CPF',
            Name = 'NS Make-up Pay'
        );
        insert pim;
        Payout__c pay = new Payout__c();
        insert pay;
        Test.StartTest();
        PayItem__c pitm = new PayItem__c (
            Amount__c = 12,
            CPF__c = 'Non-CPF',
            No_of_Days__c = 1,
            Payitem__c = pim.Id,
            Payout__c = pay.Id
        );
        insert pitm ;
        Test.StopTest();
    }
}