force-app/main/default/objects/Account/fields/Center_Email__c.field-meta.xml
<CustomField>
    <fullName>Center_Email__c</fullName>
    <label>Centre Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Centre_Name__c.field-meta.xml
<CustomField>
    <fullName>Centre_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Update this field when an Active Enrolment is created in the system</description>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Centre Name)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FCM_Token__c.field-meta.xml
<CustomField>
    <fullName>FCM_Token__c</fullName>
    <label>FCM Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>TEXT(Center__r.Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
            <value>
                <fullName>Audition</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Group Class</fullName>
            </value>
            <value>
                <fullName>Group Lesson</fullName>
            </value>
            <value>
                <fullName>Piano Viewing</fullName>
            </value>
            <value>
                <fullName>Busy / Place holder</fullName>
                <isActive>false</isActive>
                <label>Busy / Place holder</label>
            </value>
            <value>
                <fullName>Notice</fullName>
                <isActive>false</isActive>
                <label>Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to create lesson booking</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Existing Bookings</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Centre_Name__c.field-meta.xml
<CustomField>
    <fullName>Centre_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Add &apos;Duplicate&apos; and &apos;Enquiry Lost&apos; on Nov 4th to capture more Statistic
These values will be used in Pardot going forward
Requested By: Alex and Yunshi</description>
    <label>Sales Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Trial Requested</fullName>
            </value>
            <value>
                <fullName>Trial Booked</fullName>
            </value>
            <value>
                <fullName>Trial Cancelled</fullName>
            </value>
            <value>
                <fullName>Trial No Show</fullName>
            </value>
            <value>
                <fullName>Trial Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Enquiry Lost</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Center_Email__c.field-meta.xml
<CustomField>
    <fullName>Center_Email__c</fullName>
    <formula>Center__r.Center_Email__c</formula>
    <label>Center Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Enrolments</relationshipLabel>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Center_Email__c.field-meta.xml
<CustomField>
    <fullName>Center_Email__c</fullName>
    <formula>Centre_Name__r.Center_Email__c</formula>
    <label>Center Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Centre_Name__c.field-meta.xml
<CustomField>
    <fullName>Centre_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Enrolment.recordType-meta.xml
<RecordType>
    <fullName>Enrolment</fullName>
    <active>true</active>
    <businessProcess>Enrolment</businessProcess>
    <label>Enrolment</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <businessProcess>Enrolment</businessProcess>
    <label>Lesson</label>
</RecordType>

force-app/main/default/classes/CaseTriggerHelper.cls
public class CaseTriggerHelper {
    private static string custRec=ConstantsClass.customerRecTypeName;
    Private static String CentreRec = ConstantsClass.centerRecTypeName;
    //@Ravi, This process is used to update Service Request Cases with the Location, Center and Contact if Person Account exist
    // else create person account and update the same 
    @future
    public static void UpdateCase(set<Id> CaseId){

        
        List<EmailMessage> messages= [select id, ParentId, FromName, FromAddress, ToAddress from EmailMessage where ParentId IN: CaseId];
        list<Case> CaseListing = new list<Case>([Select Id, OwnerId,IsDeleted, CaseNumber, ContactId, AccountId, AssetId, SourceId, BusinessHoursId, ParentId, SuppliedName, SuppliedEmail, SuppliedPhone, SuppliedCompany, Type, RecordTypeId, Status, Reason, Origin, Subject, Priority, Description From Case where id in :CaseId]);
        set<string> ids = new set<string>();
        List<Case> caseList= new List<Case>();
        List<EmailMessage> emailList= new List<EmailMessage>();
        List<Account> accnt= new List<Account>();
        List<Account> accntUpdate= new List<Account>();
        map<string,Account> maptoAccount= new map<string,account>();
        
        for(Case cs:CaseListing){
            if(cs.SuppliedEmail != null){
                ids.add(cs.SuppliedEmail);   
            }
        }
        Id customerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(custRec).getRecordTypeId();
        list<Account> acc=[Select id,Name,Location__c,(Select id From Contacts),PersonEmail From Account where RecordTypeId =:customerId and PersonEmail in :ids];
        if(acc.size()>0){
            String QueIds;
            String CustomersId;
            string centerLocation;
            if(messages.size()>0){
                Id centerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(CentreRec).getRecordTypeId();
                List<Account> center = [Select id,Name,Location__c,Center_Email__c From Account where RecordTypeId =:centerId and Center_Email__c =:messages[0].ToAddress limit 1];
                
                if(center.size()>0){
                    CustomersId=center[0].id;
                    centerLocation = center[0].Location__c;
                }
                
            }
            map<string,Account> mapToAccnt = new map<string,Account>();
            for(Account getAcc:acc){
                mapToAccnt.put(getAcc.PersonEmail,getAcc);
            }
            set<id> caseidSet= new set<id>();
            // Changes on 4th Oct by Ravi as Updated Account with center and Location
            for(Account accObjNew:acc){
                Account accObj = new Account();
                accObj.Id=accObjNew.Id;
                accObj.Location__c=centerLocation;
                accObj.Centre_Name__c=CustomersId;
                accntUpdate.add(accObj);
            }
            for(Case caseobj:CaseListing){
                Case caseRec = new Case();
                caseRec.id=caseobj.id;
                caseRec.ContactId=mapToAccnt.get(caseobj.SuppliedEmail).Contacts[0].id;
                caseRec.Location__c=centerLocation;
                caseRec.Centre_Name__c=CustomersId;
                caseidSet.add(caseRec.id);
                caseList.add(caseRec);
            }
            update caseList;
            if(accntUpdate.size()>0){
                update accntUpdate;
            }
            
        }else{
            for(Case cs:CaseListing){
                String[] SuppName=String.isNotBlank(cs.SuppliedName)?cs.SuppliedName.split(' ',2):new List<String>();
                
                if(SuppName.size()==2){
                    Account ac= new Account(FirstName=SuppName[0],LastName=SuppName[1],PersonEmail=cs.SuppliedEmail,RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get(custRec).getRecordTypeId(),OwnerId=UserInfo.getUserId());
                    maptoAccount.put(ac.PersonEmail,ac);
                    accnt.add(ac);
                }
            }
            if(accnt.size()!=null){
                insert accnt;
            }
            map<string,Contact> mapAccToContact = new map<string,Contact>();
            for(Contact getCon:[Select Email,id from Contact where AccountId in : accnt]){
                mapAccToContact.put(getCon.Email,getCon);
            }
            for(Case casobj:CaseListing){
                if(maptoAccount.containsKey(casobj.SuppliedEmail)){
                    
                    String QueIds;
                    String CustomersId;
                    string centerLocation;
                    if(messages.size()>0){
                        Id centerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(CentreRec).getRecordTypeId();
                        List<Account> center = [Select id,Name,Location__c,Center_Email__c From Account where RecordTypeId =:centerId and Center_Email__c =:messages[0].ToAddress limit 1];
                        if(center.size()>0){
                            CustomersId=center[0].id;
                            centerLocation = center[0].Location__c; 
                        }
                        
                    }
                    Case cscObj = new Case();
                    cscObj.id=casobj.id;
                    cscObj.AccountId=maptoAccount.get(casobj.SuppliedEmail).id;
                    cscObj.ContactId=mapAccToContact.get(casobj.SuppliedEmail).id;
                    //cscObj.RecordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Sales Enquiry').getRecordTypeId();
                    cscObj.Location__c=centerLocation;
                    cscObj.Centre_Name__c=CustomersId;
                    caseList.add(cscObj);
                     // Changes on 4th Oct by Ravi as Updated Account with center and Location
                    for(Account accObj:accnt){
                        accObj.Location__c=centerLocation;
                        accObj.Centre_Name__c=CustomersId;
                        accntUpdate.add(accObj);
                    }
                }
                
            }
            if(accntUpdate.size()>0){
                update accntUpdate;
            }
            if(caseList!=null){
                update caseList;   
            }
        }
    }
    
    //@Rajesh(Date 19-04-2019), Populate Booking Id on Case
    @future
    public static void updateBookingIdInCase(Map<Id, Id> caseEnrMap){
        //Filling Enromlent Booking map
        Map<Id, Id>   enrTrialbookMap = new Map<Id, Id>();
        String bookLessRecId =  Schema.SObjectType.Booking__c.getRecordTypeInfosByName().get('Lesson').getRecordTypeId();    
        for(Booking__c book : [SELECT Id, Name, Enrolment__c FROM Booking__c 
                               WHERE Enrolment__c IN: caseEnrMap.values() AND 
                               Type__c =: ConstantsClass.typeTrial AND RecordTypeId=:bookLessRecId]){
                                   if(!enrTrialbookMap.containsKey(book.Enrolment__c))
                                       enrTrialbookMap.put(book.Enrolment__c, book.Id);
                               }
        
        List<Case> cupdList = new List<Case>();
        for(Id caseId : caseEnrMap.keySet()){
            if(enrTrialbookMap.containsKey(caseEnrMap.get(caseId))){
                cupdList.add(new Case(Id = caseId, Booking__c = enrTrialbookMap.get(caseEnrMap.get(caseId))));
            }
        }
        if(cupdList.size() > 0)
            update cupdList;
        //if(enrTrialbookMap.containsKey(enrol.Id))
        //  salesEnqCase.Booking__c = enrTrialbookMap.get(enrol.Id);
    }
    
    
    //@Rajesh (Date 6-4-2019), This process is used to update contactId with the Parent contactId
    public static void updateContact(List<case> caseList){
        Map<Id, Account> accMap = new Map<Id, Account>();
        for(Case c: caseList){
            if(c.AccountId != null && c.ContactId == null)
                accMap.put(c.AccountId, null);
        }
        if(accMap.size() > 0){
            accMap = new Map<Id, Account>([Select Id, PersonContactId From Account Where Id IN: accMap.keySet()]);
            for(Case c: caseList){
                if(c.AccountId != null && c.ContactId == null && accMap.get(c.AccountId) != null)
                    c.ContactId = accMap.get(c.AccountId).PersonContactId;
            }
        }
    }
    //@Rajesh (Date 3-4-2019), This process is used to update Lead and Opportunity and Enrolment as lost when case Lost
    //Commented by Rajesh on (17-06-2020), need to build this functionality from enrolment as per discussion with Ashish or Alex
  /*  public static void processOnCaseLost(List<case> caseList, Map<Id, Case> caseOldMap){
        Id recorTypeId = Schema.SObjectType.case.getRecordTypeInfosByName().get(ConstantsClass.caseSalesEnqRecTypeName).getRecordTypeId();
        
        List<Lead> leadUpdList       = new List<Lead>();
        List<Opportunity> oppUpdList = new List<Opportunity>();
        List<Enrolment__c> enrUpdList= new List<Enrolment__c>();
        for(Case cs: caseList){
            if(cs.RecordTypeId == recorTypeId && cs.Stage__c == ConstantsClass.caseLost && cs.Stage__c != caseOldMap.get(cs.Id).Stage__c){
                
                if(cs.Lead__c != null)
                    leadUpdList.add(new Lead(Id = cs.Lead__c , Status = ConstantsClass.caseLost));  
                
                if(cs.Opportunity__c != null)
                    oppUpdList.add(new Opportunity(Id = cs.Opportunity__c, StageName = 'Closed Lost'));
                
                if(cs.Enrolment__c != null)
                    enrUpdList.add(new Enrolment__c(Id = cs.Enrolment__c, Stage__c = ConstantsClass.caseLost));      
            }
        }
        
        if(leadUpdList.size() > 0)
            update leadUpdList;
        
        if(oppUpdList.size() > 0)
            update oppUpdList;
        
        if(enrUpdList.size() > 0)
            update enrUpdList;   
    }*/
    
    
    //@Nishi (Date 22-7-2019), This process is used to Change Case status Notification.
    public static void processChangeCase(Map<String,String> changeStatusMap){
        List<MobileNotificationWrapper> notifications = new List<MobileNotificationWrapper>();
        
        Map<String,String> parentTokens = new Map<String,String>();
        
        for(Account acc: [SELECT id,FCM_Token__c from Account where Id in:changeStatusMap.values() AND FCM_Token__c !=null]){
            parentTokens.put(acc.id,acc.FCM_Token__c );
        }
        
        for(Case caseObj : [SELECT id,Status,CaseNumber,AccountId FROM Case WHERE id in: changeStatusMap.keyset()]){
            try{
            if(parentTokens.containsKey(caseObj.AccountId)){
                String to = parentTokens.get(caseObj.AccountId);
                String title = 'Ticket #'+caseObj.CaseNumber+' has been updated!';
                String bodymsg = 'Please note your ticket '+ caseObj.CaseNumber +' has been updated. Please check your email for our reply or check your tickets page for more information.';
                notifications.add(new MobileNotificationWrapper(caseObj.AccountId, to, title, bodymsg));
            }
            }catch(Exception e){}
        }
        if(notifications.size() > 0 && !System.isBatch() && !System.isFuture()) {
            Database.executeBatch(new SendMobileNotificationBatch(notifications),90);
        }
    }
}