force-app/main/default/objects/Account/fields/Center_Email__c.field-meta.xml
<CustomField>
    <fullName>Center_Email__c</fullName>
    <label>Centre Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Nationality__c.field-meta.xml
<CustomField>
    <fullName>Employee_Nationality__c</fullName>
    <label>Employee Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nationality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-Time</fullName>
            </value>
            <value>
                <fullName>Part-Time</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Freelance</fullName>
            </value>
            <value>
                <fullName>Internship</fullName>
            </value>
            <value>
                <fullName>Overseas Staff</fullName>
            </value>
            <value>
                <fullName>Non-Employee Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Location__c.field-meta.xml
<CustomField>
    <fullName>ID_Location__c</fullName>
    <label>ID Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foreigner</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Identification_Number__c</fullName>
    <label>Identification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Manager</fullName>
            </value>
            <value>
                <fullName>Chauffeur</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Operations Officer</fullName>
            </value>
            <value>
                <fullName>Cleaner</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Director of Operations</fullName>
            </value>
            <value>
                <fullName>Finance Executive</fullName>
            </value>
            <value>
                <fullName>HR Payroll Executive</fullName>
            </value>
            <value>
                <fullName>Head of Piano Department</fullName>
            </value>
            <value>
                <fullName>Human Resource Manager</fullName>
            </value>
            <value>
                <fullName>Instrument Technician</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Music Instructor</fullName>
            </value>
            <value>
                <fullName>Music Teacher</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
            <value>
                <fullName>Sales Executive</fullName>
            </value>
            <value>
                <fullName>Sales and Operations Executive</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Piano Technician</fullName>
            </value>
            <value>
                <fullName>Language Teacher</fullName>
            </value>
            <value>
                <fullName>HR Executive</fullName>
            </value>
            <value>
                <fullName>Assistant Director of Marketing</fullName>
                <isActive>false</isActive>
                <label>Assistant Director of Marketing</label>
            </value>
            <value>
                <fullName>Assistant Director of Product Management</fullName>
                <isActive>false</isActive>
                <label>Assistant Director of Product Management</label>
            </value>
            <value>
                <fullName>Associate Director of HR</fullName>
                <isActive>false</isActive>
                <label>Associate Director of HR</label>
            </value>
            <value>
                <fullName>Associate Director of IT and Operations</fullName>
                <isActive>false</isActive>
                <label>Associate Director of IT and Operations</label>
            </value>
            <value>
                <fullName>Director of Retail</fullName>
                <isActive>false</isActive>
                <label>Director of Retail</label>
            </value>
            <value>
                <fullName>Executive</fullName>
                <isActive>false</isActive>
                <label>Executive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_Stage__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Stage__c</fullName>
    <label>Onboarding Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Onboarding_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Email__c.field-meta.xml
<CustomField>
    <fullName>Person_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Backend field to populate Person account email to send email</description>
    <label>Personal Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Work_Location__c.field-meta.xml
<CustomField>
    <fullName>Work_Location__c</fullName>
    <label>Work Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Singapore</fullName>
                <default>true</default>
                <label>Singapore</label>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payout__c/Payout__c.object-meta.xml
<CustomObject>
    <label>Payout</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Pay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payout__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Payrolls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Future_Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rostering__c/Rostering__c.object-meta.xml
<CustomObject>
    <label>Rostering</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Rostering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rosterings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rostering__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rosterings (Centre)</relationshipLabel>
    <relationshipName>RosteringCentre</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rostering__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rosterings</relationshipLabel>
    <relationshipName>Rosterings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rostering__c/fields/Work_Day__c.field-meta.xml
<CustomField>
    <fullName>Work_Day__c</fullName>
    <label>Work Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Day</fullName>
            </value>
            <value>
                <fullName>Half Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestGenerateEmployeeCostToCentreBatch.cls
/*
 * 		Name 			: TestGenerateEmployeeCostToCentreBatch;
 * 		Date 			: Dec, 24 2019
 * 		Author 			:
 * 		Descriptions	: this is GenerateEmployeeCostCentreBatchTest class of GenerateEmployeeCostToCentreBatch this Test class used to coverd GenerateEmployeeCostToCentreBatch class..
 * 		
*/


@isTest
private class TestGenerateEmployeeCostToCentreBatch {
    
    
    @TestSetup
    private static void dataSetup(){
        
        
        List<Account>	accountsList = new List<Account>();
        
        Schema.DescribeSObjectResult accountRecordType = Account.SObjectType.getDescribe();
       	Map<String,Schema.RecordTypeInfo> rtMapByName = accountRecordType.getRecordTypeInfosByName();
        
       	Country__c country = new Country__c();
        country.Name = 'SGD';
        country.Country_Name__c = 'Singapore';
        country.Tax_Rate__c = 7.0;
        country.Currency_Code__c = 'SGD';
        country.Student_Policies_Template_Id__c = 'test';
        country.Stripe_Base_Url__c = 'www.test.com';
        country.Stripe_Publishable_Key__c = 'ABC';
        country.Stripe_Secret_Key__c = 'deede';
        
        insert country; 
        
        accountsList.add(new Account(LastName = 'Bhuttan', Employee_Status__c = 'Draft', Onboarding_Stage__c = 'In Process', Employee_Nationality__c = 'American', 
                                    Work_Location__c = 'Singapore', Engagement_Type__c = 'Full-Time', PersonDepartment = 'C-Level', Person_Email__c = 'Bhuttan123@gmail.com',
                                    Job_Title__c = 'Cleaner', ID_Type__c = 'Foreigner', Identification_Number__c = '1234', ID_Location__c = 'Singapore', RecordTypeId = rtMapByName.get('Employee').RecordTypeId,
                        			Country__c = country.Id));
        accountsList.add(new Account(Name = 'Aureus 112 katong', Location__c = 'Aureus 112 katong', Center_Email__c = 'bhutt23@gmail.com', RecordTypeId = rtMapByName.get('Centre').RecordTypeId,
                         Country__c = country.Id));
        accountsList.add(new Account(LastName = 'Bhuttan', Employee_Status__c = 'Draft', Onboarding_Stage__c = 'In Process', Employee_Nationality__c = 'American', 
                                    Work_Location__c = 'Singapore', Engagement_Type__c = 'Full-Time', PersonDepartment = 'C-Level', Person_Email__c = 'btun23@gmail.com',
                                    Job_Title__c = 'Cleaner', ID_Type__c = 'Foreigner', Identification_Number__c = '3013', ID_Location__c = 'Singapore', RecordTypeId = rtMapByName.get('Teacher').RecordTypeId,
                        Country__c = country.Id));
        
        
        if(!accountsList.isEmpty()){
            INSERT accountsList;
        }
        
        List<Payout__c>	payoutsList = new List<Payout__c>();
        
        payoutsList.add(new Payout__c (Employee_Name__c = accountsList[0].Id, Month__c = 'December', Year__c = '2019'));
        payoutsList.add(new Payout__c (Employee_Name__c = accountsList[2].Id, Month__c = 'December', Year__c = '2019'));
        
        if(!payoutsList.isEmpty()){
            INSERT payoutsList;
        }
        
        List<Rostering__c> rosteringsList = new List<Rostering__c>();
        
        rosteringsList.add(new Rostering__c(Employee__c = accountsList[0].Id, Work_Day__c = 'Full Day', Centre__c = accountsList[1].Id , Effective_Date__c = Date.newInstance(2019, 12, 9),
                                           Shift__c = 'Opening Hours'));
       
        
        if(!rosteringsList.isEmpty()){
            INSERT rosteringsList;
        }
        
        List<Teacher_Working_Hour__c>	teacherWrokingsList = new List<Teacher_Working_Hour__c>();
        teacherWrokingsList.add(new Teacher_Working_Hour__c(Active__c = true, Break_Time__c = false,  Center_Name__c = accountsList[1].Id, Teacher_Name__c = accountsList[2].Id,
                                                            Start_Time__c = Time.newInstance(2,23,45,55), End_Time__c = Time.newInstance(7,40,50,51) , Working_Day__c = 'mon'));
        
        if(!teacherWrokingsList.isEmpty()){
            INSERT teacherWrokingsList;
        }
        
    }
    Private static testMethod void processGenerateEmployeeCostToCentre(){
        
        Set<Id>	accountIdsSet = new Set<Id>();
        
        for(Account accountRecord : [SELECT Id, LastName, Employee_Status__c FROM Account]){
            if(accountRecord.Id != null){
                accountIdsSet.add(accountRecord.Id);
            }
        }
        Test.startTest();
        String CRON_EXP = '0 0 0 3 9 ? 2022';
		String jobId = System.schedule('GenerateEmployeeCostToCentreScheduler',CRON_EXP,new GenerateEmployeeCostToCentreScheduler());
        
        Test.stopTest();
        System.debug('hello accountIds --> '+accountIdsSet);
		GenerateEmployeeCostToCentreBatch  employeeObj1 = new GenerateEmployeeCostToCentreBatch();        
        GenerateEmployeeCostToCentreBatch  employeeObj2 = new GenerateEmployeeCostToCentreBatch(accountIdsSet);
        
        GenerateEmployeeCostToCentreBatch  employeeObj3 = new GenerateEmployeeCostToCentreBatch(accountIdsSet, Date.newInstance(2019, 12, 2));
        GenerateEmployeeCostToCentreBatch  employeeObj4 = new GenerateEmployeeCostToCentreBatch(Date.newInstance(2019, 12, 5));
        
        Database.executeBatch(new GenerateEmployeeCostToCentreBatch(accountIdsSet));
        Database.executeBatch(new GenerateEmployeeCostToCentreBatch(accountIdsSet));
        
    }
    
    

}