force-app/main/default/objects/Account/fields/CentreName_Cust__c.field-meta.xml
<CustomField>
    <fullName>CentreName_Cust__c</fullName>
    <label>CentreName Cust</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Duty_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Duty_Type__c</fullName>
    <label>Employee Duty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Duty</fullName>
            </value>
            <value>
                <fullName>Non-Duty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foreigner</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Main_Centre__c.field-meta.xml
<CustomField>
    <fullName>Main_Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Centre</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Main Centre)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number__c</fullName>
    <label>Tax Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Teacher_Bio__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Bio__c</fullName>
    <inlineHelpText>Data enter here will be shown on Trial and Enrolment pages.</inlineHelpText>
    <label>Teacher Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/Employee_Work_Week__c.object-meta.xml
<CustomObject>
    <label>Employee Work Week</label>
    <nameField>
        <displayFormat>EW-{0000}</displayFormat>
        <label>Employee Work Week No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Work Week</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Work_Week__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employee, Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Work Week</relationshipLabel>
    <relationshipName>Employee_Work_Week</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Friday__c.field-meta.xml
<CustomField>
    <fullName>Friday__c</fullName>
    <label>Friday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Friday_Centre__c.field-meta.xml
<CustomField>
    <fullName>Friday_Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Friday Centre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Work Week (Friday Centre)</relationshipLabel>
    <relationshipName>Employee_Work_Week7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Monday__c.field-meta.xml
<CustomField>
    <fullName>Monday__c</fullName>
    <label>Monday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Monday_Centre__c.field-meta.xml
<CustomField>
    <fullName>Monday_Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Monday Centre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Work Week (Monday Centre)</relationshipLabel>
    <relationshipName>Employee_Work_Week1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Saturday__c.field-meta.xml
<CustomField>
    <fullName>Saturday__c</fullName>
    <label>Saturday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Sunday__c.field-meta.xml
<CustomField>
    <fullName>Sunday__c</fullName>
    <label>Sunday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Thursday__c.field-meta.xml
<CustomField>
    <fullName>Thursday__c</fullName>
    <label>Thursday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Tuesday__c</fullName>
    <label>Tuesday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Work_Week__c/fields/Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Wednesday__c</fullName>
    <label>Wednesday</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shift_Per_Day</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Entitlement__c/Leave_Entitlement__c.object-meta.xml
<CustomObject>
    <label>Leave Entitlement</label>
    <nameField>
        <displayFormat>LE-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Entitlement</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Entitlement__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leave Entitlement</relationshipLabel>
    <relationshipName>Leave_Entitlement</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Organisations</relationshipLabel>
    <relationshipName>Organisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <formula>IF(Country__r.Tax_Rate__c &gt; 0, Country__r.Tax_Rate__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/EmployeeRosteringBatchTest.cls
@isTest
public class EmployeeRosteringBatchTest {
    @testSetup
    public static void createData(){
        string centerRecordType =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Centre').getRecordTypeId();
        Country__c cntry = new Country__c();
        cntry.Name = 'SG';
        cntry.Country_Name__c ='Singapore';
        cntry.Currency_Code__c ='SGD';
        cntry.Tax_Rate__c = 7;
        cntry.Student_Policies_Template_Id__c= 'DLe9tWht6W9PNHEabs2ruT';
        cntry.Stripe_Base_Url__c ='https://api.stripe.com';
        cntry.Stripe_Publishable_Key__c ='pk_test_eGeu4Z0mLSfXmekcJcLt7TVH';
        cntry.Stripe_Secret_Key__c ='sk_test_M3pk8qvbMs03SWjDuf6m1bss';
        insert cntry;
        Organisation__c org = new Organisation__c(Name='Test',Country__c=cntry.Id);
        insert org;
        Account centre=TestUtil.createAccount('Centre',False,false);
        centre.Country__c =cntry.Id;
        centre.Organisation__c=org.Id;
        insert centre;
        
        
        string empRecordType =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Employee').getRecordTypeId();
        Account employee = new Account(
            Main_Centre__c = centre.Id,
            RecordTypeId = empRecordType,
            LastName='testEmployee',
            Teacher_Bio__c='testbio',
            CentreName_Cust__c='testCenter',
            Status__c='Working',
            Employee_Status__c = 'Confirm',
            Joining_Date__c = Date.Today().addDays(-10),
            Last_Working_Date__c = Date.today().addDays(10),
            Issue_Date__c = Date.Today().addDays(-30),
            ID_Type__c = 'Permanent Resident',
            PersonBirthdate = date.today().addYears(-30),
            Tax_Number__c = 'G3107590X',
            Employee_Duty_Type__c = 'Duty',
            Organisation__c=org.Id
        );
        insert employee;  
        
        Leave_Entitlement__c le = new Leave_Entitlement__c(
            Employee__c = employee.Id,
            Start_Date__c = Date.Today().addMonths(-1),
            End_Date__c = Date.Today().addMonths(1)
        );
        insert le;
        
        Employee_Work_Week__c eww = new Employee_Work_Week__c(
            Effective_Date__c = Date.Today().addDays(3),
            Employee__c = employee.Id,
            Friday__c = 'Full Day',
            Monday__c = 'Full Day',
            Saturday__c = 'Half Day',
            Sunday__c = 'Rest Day',
            Thursday__c = 'Half Day',
            Tuesday__c = 'Full Day',
            Wednesday__c = 'Full Day'
        );
        eww.Friday_Centre__c = centre.id;
        eww.Monday_Centre__c = centre.id;
        eww.Saturday_Centre__c = centre.id;
        eww.Sunday_Centre__c = centre.id;
        eww.Thursday_Centre__c = centre.id;
        eww.Tuesday_Centre__c = centre.id;
        eww.Wednesday_Centre__c= centre.id;
        
        eww.Friday_Note__c = '9:00 to 10:00';
        eww.Monday_Note__c = '9:00 to 10:00';
        eww.Saturday_Note__c = '9:00 to 10:00';
        eww.Sunday_Note__c = '9:00 to 10:00';
        eww.Thursday_Note__c = '9:00 to 10:00';
        eww.Tuesday_Note__c = '9:00 to 10:00';
        eww.Wednesday_Note__c = '9:00 to 10:00';
        
        eww.Friday_Shift__c = 'Regular Hours';
        eww.Monday_Shift__c = 'Regular Hours';
        eww.Saturday_Shift__c = 'Closing Hours';
        eww.Sunday_Shift__c = 'Regular Hours';
        eww.Thursday_Shift__c = 'Regular Hours';
        eww.Tuesday_Shift__c = 'Opening Hours';
        eww.Wednesday_Shift__c = 'Regular Hours';
        insert eww;
    }
    @isTest
    public static void unitTest1(){
        Test.startTest();
        Id jobId = Database.executeBatch(new EmployeeRosteringBatch(), 200);
        Test.StopTest();
    }
    @isTest
    public static void unitTest2(){
        Test.startTest();
        Id jobId = Database.executeBatch(new EmployeeRosteringBatch(1), 200);
        Test.StopTest();
    }
    @isTest
    public static void unitTest3(){
        Account acc =[select id  from Account limit 1];
        Test.startTest();
        Id jobId = Database.executeBatch(new EmployeeRosteringBatch(new set<Id>{acc.id},Date.today(),1), 200);
        Test.StopTest();
    }
    @isTest
    public static void unitTest4(){
        Account acc =[select id  from Account limit 1];
        Test.startTest();
        Id jobId = Database.executeBatch(new EmployeeRosteringBatch(new set<Id>{acc.id}), 200);
        Test.StopTest();
    }
    @isTest
    public static void unitTest5(){
        Account acc =[select id  from Account limit 1];
        Test.startTest();
        Id jobId = Database.executeBatch(new EmployeeRosteringBatch(new set<Id>{acc.id},Date.today()), 200);
        Test.StopTest();
    }
    @isTest
    public static void unitTest6(){
        Account acc =[select id  from Account limit 1];
        Test.startTest();
        Id jobId = Database.executeBatch(new EmployeeRosteringBatch(new set<Id>{acc.id},1), 200);
        Test.StopTest();
    }
    @isTest
    public static void unitTest7(){
        // This test runs a scheduled job at midnight 1pm
        String CRON_EXP = '0 0 1 * * ? * ';
        // Schedule the test job
        String jobId = System.schedule('EmployeeRosteringSchedular', CRON_EXP, new EmployeeRosteringSchedular());
        // Get the information from the CronTrigger API object 
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        // Verify the job has not run 
        System.assertEquals(0, ct.TimesTriggered); 
        // Verify the next time the job will run 
        Datetime nextSchduletime = datetime.newInstance(DATE.today().year(), DATE.today().month(), DATE.today().addDays(1).day(),01,00,00);
        System.assertEquals(string.valueOf(nextSchduletime), String.valueOf(ct.NextFireTime));   
        
        EmployeeRosteringSchedular objTaskSchd= new EmployeeRosteringSchedular();
        objTaskSchd.execute(Null);
        
    }
}