force-app/main/default/objects/Account/fields/CentreName_Cust__c.field-meta.xml
<CustomField>
    <fullName>CentreName_Cust__c</fullName>
    <label>CentreName Cust</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ID_Type__c.field-meta.xml
<CustomField>
    <fullName>ID_Type__c</fullName>
    <label>ID Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foreigner</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Identification_Number__c</fullName>
    <label>Identification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <label>Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number__c</fullName>
    <label>Tax Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Teacher_Bio__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Bio__c</fullName>
    <inlineHelpText>Data enter here will be shown on Trial and Enrolment pages.</inlineHelpText>
    <label>Teacher Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EmployeeNRICValidationTest.cls
@isTest
public class EmployeeNRICValidationTest{
    @isTest
    public static void unitTest(){
        String empRecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Employee').getRecordTypeId();
        Account employee = new Account(
            RecordTypeId = empRecordTypeId,
            LastName='testEmployee',
            Teacher_Bio__c='testbio',
            CentreName_Cust__c='testCenter',
            Status__c='Working',
            Employee_Status__c = 'Confirm',
            Joining_Date__c = Date.Today().addDays(-10),
            Last_Working_Date__c = Date.today().addDays(10),
            Issue_Date__c = Date.Today().addDays(-30),
            ID_Type__c = 'Permanent Resident',
            PersonBirthdate = date.today().addYears(-30),
            Identification_Number__c = '121212',
            Tax_Number__c = '21342'
        );
        Test.StartTest();
        database.insert(employee,false);  
        Test.StopTest();
    }
}