force-app/main/default/objects/Account/fields/CentreName_Cust__c.field-meta.xml
<CustomField>
    <fullName>CentreName_Cust__c</fullName>
    <label>CentreName Cust</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Duty_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Duty_Type__c</fullName>
    <label>Employee Duty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Duty</fullName>
            </value>
            <value>
                <fullName>Non-Duty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Exit_Type__c.field-meta.xml
<CustomField>
    <fullName>Exit_Type__c</fullName>
    <label>Exit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Resignation</fullName>
            </value>
            <value>
                <fullName>Non-renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Working_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Working_Date__c</fullName>
    <label>Last Working Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Notice_Period__c.field-meta.xml
<CustomField>
    <fullName>Notice_Period__c</fullName>
    <label>Notice Period (In Month)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Teacher_Bio__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Bio__c</fullName>
    <inlineHelpText>Data enter here will be shown on Trial and Enrolment pages.</inlineHelpText>
    <label>Teacher Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>CI - {0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Item__c/fields/Checklist_Master__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Master__c</fullName>
    <label>Checklist Master</label>
    <referenceTo>Checklist_Master__c</referenceTo>
    <relationshipLabel>Checklist Item</relationshipLabel>
    <relationshipName>Checklist_Item</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Teacher, Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Checklist Item</relationshipLabel>
    <relationshipName>Checklist_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Master__c/Checklist_Master__c.object-meta.xml
<CustomObject>
    <label>Checklist Master</label>
    <nameField>
        <displayFormat>CM - {0000}</displayFormat>
        <label>Checklist Master No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Master__c/fields/Activity_Name__c.field-meta.xml
<CustomField>
    <fullName>Activity_Name__c</fullName>
    <label>Activity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Checklist_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_Master__c/fields/X_days_before_Joining_Exit_Date__c.field-meta.xml
<CustomField>
    <fullName>X_days_before_Joining_Exit_Date__c</fullName>
    <label>X days before Joining/Exit Date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding Process</fullName>
            </value>
            <value>
                <fullName>Exit Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_Template_Activity__c/Checklist_Template_Activity__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Activity</label>
    <nameField>
        <displayFormat>CTA-{00000}</displayFormat>
        <label>Template Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Template Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Template_Activity__c/fields/Checklist_Master__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Master__c</fullName>
    <label>Checklist Master</label>
    <referenceTo>Checklist_Master__c</referenceTo>
    <relationshipLabel>Checklist Template Activities</relationshipLabel>
    <relationshipName>Checklist_Template_Activities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Template_Activity__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklist Template Activities</relationshipLabel>
    <relationshipName>Checklist_Template_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Document Master</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Document__c/Employee_Document__c.object-meta.xml
<CustomObject>
    <label>Employee Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Document__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>Documents__c</referenceTo>
    <relationshipLabel>Employee Documents</relationshipLabel>
    <relationshipName>Employee_Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Document__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee Documents</relationshipLabel>
    <relationshipName>Employee_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Document__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Onboarding_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OnBoardActChecklistControllerTest.cls
@isTest
public class OnBoardActChecklistControllerTest{
    @testSetup static void methodName() {
        // Create Employee
        Account objAcc = new Account();
        string s=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Employee').getRecordTypeId();
        if(s!=null){
            objAcc.RecordTypeId =s; 
            objAcc.LastName='testEmployee';
            objAcc.Teacher_Bio__c='testbio';
            objAcc.CentreName_Cust__c='testCenter';
            objAcc.Status__c='Working';   
            objAcc.Employee_Status__c = 'Confirm';
            objAcc.Joining_Date__c = system.today();
            objAcc.Employee_Duty_Type__c = 'Duty';
        }
        insert objAcc;   
        
        //Checklist Master
        List<Checklist_Master__c> ckmList = new List<Checklist_Master__c>();
        Checklist_Master__c ob = new Checklist_Master__c(Activity_Name__c = 'Master' , Type__c = 'Onboarding Process', X_days_before_Joining_Exit_Date__c = 2);
        Checklist_Master__c ex = new Checklist_Master__c(Activity_Name__c = 'Master' , Type__c = 'Exit Process', X_days_before_Joining_Exit_Date__c = 2);
        ckmList.add(ob);
        ckmList.add(ex);
        insert ckmList;
        
        List<Checklist_Item__c > ckItemList = new List<Checklist_Item__c >();
        Checklist_Item__c ckItem1 = new Checklist_Item__c (Activity_Name__c = 'Act', Checklist_Master__c = ob.Id, Completed__c = true, Due_Date__c = Date.Today(), Employee__c = objAcc.Id , Type__c = 'Onboarding Process' );
        Checklist_Item__c ckItem2 = new Checklist_Item__c (Activity_Name__c = 'Act', Checklist_Master__c = ex.Id, Completed__c = true, Due_Date__c = Date.Today(), Employee__c = objAcc.Id , Type__c = 'Exit Process' );
        ckItemList.add(ckItem1);
        ckItemList.add(ckItem2);
        
        insert ckItemList;
        
        Checklist_Template__c ckLTemplate = new Checklist_Template__c(Type__c = 'Onboarding Process');
        insert ckLTemplate ;
        Checklist_Template_Activity__c  temp = new Checklist_Template_Activity__c (Checklist_Template__c = ckLTemplate.Id, Checklist_Master__c = ob.Id);
        insert temp;
        
        Documents__c doc = new Documents__c(Name = 'Employee Policy');
        insert doc;
        
        Employee_Document__c eDoc = new Employee_Document__c(Document__c = doc.Id, Name = 'Employee Policy', Employee__c = objAcc.Id, Required__c = false, Stage__c = 'In Process');
        insert eDoc;
    }
    
    @isTest
    public static void unitTest(){
        String employeeId = [SELECT Id FROM Account LIMIT 1].Id;
        
        OnboardingActivityChecklistController.getExistingOBCheckListItem(employeeId);
        OnboardingActivityChecklistController.getExistingExitCheckListItem(employeeId);
        
        OnboardingActivityChecklistController.getMasterCheckList(employeeId, DateTime.Now().format('YYYY-MM-dd'), false);
        
        String templateId = [SELECT Id FROM Checklist_Master__c LIMIT 1].Id;
        OnboardingActivityChecklistController.getMasterCheckListItemByTemplate(templateId);
        
        String ChkMasterId = [SELECT Id FROM Checklist_Master__c WHERE Type__c = 'Onboarding Process' LIMIT 1].Id;
        String ChkItemId = [SELECT Id FROM Checklist_Item__c WHERE Type__c = 'Onboarding Process' LIMIT 1].Id;
        String masterLists = '';
        masterLists += '[{';
            masterLists += '"checklist_Item": {';
                masterLists += '"Checklist_Master__c": "'+ChkMasterId+'",';
                masterLists += '"Activity_Name__c": "Apply for Visa",';
                masterLists += '"Due_Date__c": "'+DateTime.Now().format('YYYY-MM-dd')+'",';
                masterLists += '"Type__c": "Onboarding Process",';
                masterLists += '"Employee__c": "'+employeeId+'",';
                masterLists += '"Id": "'+ChkItemId+'"';
            masterLists += '},';
            masterLists += '"isChecked": true,';
            masterLists += '"master_check": {';
                masterLists += '"Id": "'+ChkMasterId+'",';
                masterLists += '"Activity_Name__c": "Apply for Visa",';
                masterLists += '"Name": "CM - 0002",';
                masterLists += '"Type__c": "Onboarding Process",';
                masterLists += '"X_days_before_Joining_Exit_Date__c": 10';
            masterLists += '},';
            masterLists += '"oldDate": "'+DateTime.Now().addDays(-1).format('YYYY-MM-dd')+'"';
        masterLists += '}]';
        
        String ChkMasterId2 = ChkMasterId;
        ChkMasterId = [SELECT Id FROM Checklist_Master__c WHERE Id != : ChkMasterId2 AND  Type__c = 'Exit Process' LIMIT 1].Id;
        
        String masterExitLists = '';
        masterExitLists += '[{';
            masterExitLists += '"checklist_Item": {';
                masterExitLists += '"Checklist_Master__c": "'+ChkMasterId+'",';
                masterExitLists += '"Activity_Name__c": "Apply for Visa",';
                masterExitLists += '"Due_Date__c": "'+DateTime.Now().format('YYYY-MM-dd')+'",';
                masterExitLists += '"Type__c": "Onboarding Process",';
                masterExitLists += '"Employee__c": "'+employeeId+'",';
                masterExitLists += '"Id": "'+ChkItemId+'"';
            masterExitLists += '},';
            masterExitLists += '"isChecked": false,';
            masterExitLists += '"master_check": {';
                masterExitLists += '"Id": "'+ChkMasterId+'",';
                masterExitLists += '"Activity_Name__c": "Apply for Visa",';
                masterExitLists += '"Name": "CM - 0002",';
                masterExitLists += '"Type__c": "Onboarding Process",';
                masterExitLists += '"X_days_before_Joining_Exit_Date__c": 10';
            masterExitLists += '},';
            masterExitLists += '"oldDate": "'+DateTime.Now().addDays(-1).format('YYYY-MM-dd')+'"';
        masterExitLists += '}]';
        Account Employee = [SELECT Id, Name,Status__c,Joining_Date__c,Last_Working_Date__c,Employee_Status__c, Contract_End_Date__c,Exit_Type__c,Notice_Period__c FROM Account WHERE Id =: employeeId LIMIT 1];
        
        String docId = [SELECT Id FROM Documents__c LIMIT 1].Id;
        String eDOcId = [SELECT Id FROM Employee_Document__c  LIMIT 1].Id;
        String masterDocumentLists = '';
        masterDocumentLists += '[{';
            masterDocumentLists += '"documentId": "'+docId+'",';
            masterDocumentLists += '"documentName": "Employee Policy",';
            masterDocumentLists += '"eDocumentId": "'+eDOcId+'",';
            masterDocumentLists += '"isChecked": true,';
            masterDocumentLists += '"isRequired": true,';
            masterDocumentLists += '"onBoardingStatge": "In Process"';
        masterDocumentLists += '}]';

        
        OnboardingActivityChecklistController.generateCheckListItems(masterLists, masterExitLists, employeeId, Employee , masterDocumentLists, true, 'Test Template', 'Onboarding Process');
    }
}