force-app/main/default/objects/Account/fields/CentreName_Cust__c.field-meta.xml
<CustomField>
    <fullName>CentreName_Cust__c</fullName>
    <label>CentreName Cust</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>Travel_Time__c</fullName>
    <defaultValue>30</defaultValue>
    <description>Aureus at Home</description>
    <inlineHelpText>Applicable for the home lessons</inlineHelpText>
    <label>Travel Time(In Minutes)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Camp__c/Camp__c.object-meta.xml
<CustomObject>
    <description>this object for manage camp class</description>
    <label>Camp</label>
    <nameField>
        <label>Camp  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp class for manage Location/Centre</description>
    <label>Location/Centre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camps</relationshipLabel>
    <relationshipName>Camps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/Camp_Days__c.object-meta.xml
<CustomObject>
    <description>this object  for manage camp days</description>
    <label>Camp Days</label>
    <nameField>
        <label>Camp day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camp Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Name__c.field-meta.xml
<CustomField>
    <fullName>Camp_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Camp Name</label>
    <referenceTo>Camp__c</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Camp_Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp days for manage Camp Teacher</description>
    <label>Camp Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Dates_Of_The_Camp__c.field-meta.xml
<CustomField>
    <fullName>Dates_Of_The_Camp__c</fullName>
    <description>this field for camp days for manage Dates Of The Camp</description>
    <label>Dates Of The Camp</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/URL_Parameters__mdt/URL_Parameters__mdt.object-meta.xml
<CustomObject>
    <label>URL Parameter</label>
    <pluralLabel>URL Parameter</pluralLabel>
</CustomObject>

force-app/main/default/objects/URL_Parameters__mdt/fields/Param_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_Name__c</fullName>
    <label>Param Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/URL_Parameters__mdt/fields/Param_SF_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_SF_Value__c</fullName>
    <label>Param SF Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AllCampEnrolmentMultiStudentsCtrl.cls
/**
 * Name: AllCampEnrolmentMultiStudentsCtrl
 * Author: jatin
 * Date : 29-Jan-2020
 * Description: this controller get all active camp according to center's
 */
public  class AllCampEnrolmentMultiStudentsCtrl {
    Public map<string,List<Camp__c>> mapOfCamp{get;set;}
    Public map<string,List<date>> mapOfCampDay{get;set;}
    //jatin: 19-feb-2020: for now we change requirement show all active camp according to center's
    //Public List<Camp__c> ListOfCamp{get;set;}  
    Public String centerId {get;set;} 
    Public String centerName {get;set;} 
    Public String enrolCampId {get;set;} 
    public Boolean showCampList{get;set;}
    public string countryCode{get;set;}
    public boolean isAureusAtHome{get;set;}
    public Integer trvlDuration{get;set;}
    Public String campId {get;set;} 
    Public String campName {get;set;}
    public boolean isOssia {get;set;}//Juneid 28 Aug 2020 for cheking org
    Public String currentCountry{get;set;}//Juneid 28 Aug 2020, Getting current country code
     Map<String, String> urlParamMetaMap;//Juneid 28 Aug 2020,store metadata value 
    string currentOrg;
    
    public AllCampEnrolmentMultiStudentsCtrl() {
        mapOfCampDay = new map<string,List<date>>();
        showCampList = false;
        isOssia = false;
        currentCountry = '';
           urlParamMetaMap = new Map<String, String>();
        currentOrg = '';
        //jatin: 18-feb-2020: for now we change requirement show all active camp according to center's
       /* centerId =    ApexPages.currentPage().getParameters().get('centerId');
        if(String.isNotBlank(centerId)){
        ListOfCamp = CampClassUtilityController.getCampList(centerId,'','',new set<string>());
            if(ListOfCamp != null && ListOfCamp.size() > 0){
                centerName = ListOfCamp[0].Centre__r.name;
                countryCode = ListOfCamp[0].Centre__r.Country__r.name;
            }   
            showCampList = true;  
            checkAtHome();            
        }*/ 
        
        //Juneid 28 Aug 2020, Getting metadata value of country and organization name
        for(URL_Parameters__mdt urlMdt : [SELECT Param_Name__c,Param_SF_Value__c FROM URL_Parameters__mdt]){
            urlParamMetaMap.put(urlMdt.Param_Name__c, urlMdt.Param_SF_Value__c);
        }
        system.debug('@@urlParamMetaMap'+urlParamMetaMap);
        //Juneid 28 Aug 2020 Orgnization wise logic as per new Requierment
        if(String.isNotBlank(ApexPages.currentPage().getParameters().get('org'))){
            isOssia = ApexPages.currentPage().getParameters().get('org').equalsIgnoreCase('ossia') ? true : false;
        }
         currentCountry = ApexPages.currentPage().getParameters().get('country');
        currentCountry = String.isNotBlank(currentCountry) ? currentCountry :  'SG';
        currentOrg = isOssia ? urlParamMetaMap.get('Ossia') : urlParamMetaMap.get(currentCountry.toUpperCase());
      
            
        mapOfCamp = new map<string,List<Camp__c>>();
        List<Camp__c> ListOfCamp = new List<Camp__c>();
        if(String.isNotBlank(currentOrg)){
            getActiveCamps(currentOrg);
        }
          
    }
    public void getActiveCamps(string currentOrg){
        mapOfCamp = new map<string,List<Camp__c>>();
        List<Camp__c> ListOfCamp = new List<Camp__c>();
        mapOfCampDay = new map<string,List<date>>();
        List<Camp__c> ListOfAllActiveCamp = CampClassUtilityController.getCampList('','','',new set<string>(),currentOrg);
        //List<Camp__c> ListOfAllActiveCamp =CampClassUtilityController.getCampList('','','',new set<string>());
        if(ListOfAllActiveCamp != null && ListOfAllActiveCamp.size() > 0 ){
            for(Camp__c objCamp : ListOfAllActiveCamp){
                ListOfCamp = new List<Camp__c>();
                if(string.isNotBlank(objCamp.Centre__r.name) && mapOfCamp.containsKey(objCamp.Centre__r.name)){
                    ListOfCamp = mapOfCamp.get(objCamp.Centre__r.name);
                }
                ListOfCamp.add(objCamp);
                mapOfCamp.put(objCamp.Centre__r.name,ListOfCamp);
                list<date> listOfCampDays= new list<date>();
                if(objCamp.Camp_Days__r != null && objCamp.Camp_Days__r.size() > 0){
                    listOfCampDays.add(objCamp.Camp_Days__r[0].Dates_Of_The_Camp__c);
                    listOfCampDays.add(objCamp.Camp_Days__r[objCamp.Camp_Days__r.size() - 1].Dates_Of_The_Camp__c);
                    mapOfCampDay.put(objCamp.id,listOfCampDays);
                }
            }
            showCampList = true;
        }
    }
    public void getCampId(){     
       // List<Camp__c>  ListOfCamp = CampClassUtilityController.getCampList('',enrolCampId,'',new set<string>());
        //if(ListOfCamp != null && ListOfCamp.size() > 0){
            //centerName = ListOfCamp[0].Centre__r.name;
            //countryCode = ListOfCamp[0].Centre__r.Country__r.name;
       // }
        system.debug('enrolCampId'+enrolCampId);
        // jatin : 18-Feb-2020: select any camp id  then we get centerid into page then we check centername is 'At-home'
        if(string.isNotBlank(centerId))
             checkAtHome(); 
    }


    // check center name in Aureus At Home then calculate travel duration 
      public void checkAtHome(){
        if(String.isNotBlank(centerId))
            isAureusAtHome = (centerId == Label.Aureus_at_Home_Id ? true : false);
        else
            isAureusAtHome = false;
        
        if(isAureusAtHome){
            for(Account acc: [SELECT Id,Name,CentreName_Cust__c,Travel_Time__c 
                              FROM Account 
                              WHERE Id =: centerId  LIMIT 1]){
                trvlDuration = acc.Travel_Time__c > 0 ? Integer.valueOf(acc.Travel_Time__c) : 30;
            }
        }
    }
    
}