force-app/main/default/objects/Account/fields/Centre_Name__c.field-meta.xml
<CustomField>
    <fullName>Centre_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Update this field when an Active Enrolment is created in the system</description>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Centre Name)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <label>Stripe Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateCustomerCardForPortalCntrlTest.cls
@isTest
public class UpdateCustomerCardForPortalCntrlTest {
    @testSetup static void initDataForTest(){
        Account objCustmr=TestUtil.createAccount('Customer',True,true);
       // Account objCentre=TestUtil.createAccount('Centre',True,true);
        invoice__c invoiceObj=TestUtil.createInvoice(objCustmr.id,true);
        
    }
    
    public static testMethod void test1(){
        new UpdateCustomerCardForPortalCntrl();
        
        UpdateCustomerCardForPortalCntrl updateCustomerCardForPortalCntrlObj2=new UpdateCustomerCardForPortalCntrl();
        
        Country__c cntry = new Country__c();
        cntry.Name = 'SG';
        cntry.Country_Name__c ='Singapore';
        cntry.Currency_Code__c ='SGD';
        cntry.Tax_Rate__c = 7;
        cntry.Student_Policies_Template_Id__c= 'DLe9tWht6W9PNHEabs2ruT';
        cntry.Stripe_Base_Url__c ='https://api.stripe.com';
        cntry.Stripe_Publishable_Key__c ='pk_test_eGeu4Z0mLSfXmekcJcLt7TVH';
        cntry.Stripe_Secret_Key__c ='sk_test_M3pk8qvbMs03SWjDuf6m1bss';
        insert cntry;        
        Account objCenter=TestUtil.createAccount('Centre',false,false);
        objCenter.Country__c = cntry.Id;
        insert objCenter;
        
        Account objCustmr =[Select id from Account where recordType.name='Customer' LIMIT 1];
        objCustmr.Centre_Name__c = objCenter.Id;
        update objCustmr;
        invoice__c invoiceObj=[Select id FROM Invoice__c];
        //PageReference pageRef = Page.knowYourCustomerPage; 
        //pageRef.getParameters().put('id', String.valueOf(objCustmr.Id));
        apexpages.currentpage().getparameters().put('id',objCustmr.Id);
       // Test.setCurrentPage(pageRef);
        UpdateCustomerCardForPortalCntrl updateCustomerCardForPortalCntrlObj=new UpdateCustomerCardForPortalCntrl();
        objCustmr.Stripe_Customer_Id__c='StripID';
        update objCustmr;
        new UpdateCustomerCardForPortalCntrl();
        
        updateCustomerCardForPortalCntrlObj.getYears();
        updateCustomerCardForPortalCntrlObj.updateCard();
        
        
        UpdateCustomerCardForPortalCntrl.sendInvoiceMail(invoiceObj.id);
        
        test.startTest();
        BillingUtility.cls_data objClsData = new BillingUtility.cls_data();
        objClsData.id='card_1EQSP8Jja9IPifcSD7uJtvTz';
        objClsData.brand='Visa';
        objClsData.country='US';
        objClsData.customer='cus_EuGxgjwNxGcLDd';
        objClsData.cvc_check='pass';
        objClsData.exp_month=4;
        objClsData.exp_year=2024;
        objClsData.fingerprint='DodUMgRQg0xbj77T';
        objClsData.funding='credit';
        objClsData.last4='4242';
        
        
        BillingUtility.cls_sources objClsSourc= new BillingUtility.cls_sources();
        objClsSourc.stripeData=new List<BillingUtility.cls_data>{objClsData} ;
        objClsSourc.has_more=true;
        objClsSourc.total_count=1;
        objClsSourc.url='/v1/customers/cus_EuGxgjwNxGcLDd/sources';
        
        BillingUtility.StripeError objStripeError=new BillingUtility.StripeError();
        objStripeError.charge='charge';
        objStripeError.stripeType='stripeType';
        objStripeError.param='param';
        objStripeError.message='message';
        objStripeError.code='code';
        objStripeError.decline_code='decline_code';
        
        BillingUtility.StripeCard objStripeCard=new BillingUtility.StripeCard();
        objStripeCard.stripeType='stripeType';
        objStripeCard.country='US';
        objStripeCard.exp_month=4;
        objStripeCard.fingerprint='DodUMgRQg0xbj77T';
        objStripeCard.exp_year=2024;
        objStripeCard.last4='4242';
        objStripeCard.stripeObject='stripeObject';
        objStripeCard.id='card_1EQSP8Jja9IPifcSD7uJtvTz';
        objStripeCard.name='name';
        objStripeCard.brand='Visa';
        objStripeCard.error=objStripeError;
        objStripeCard.customer_id=objCustmr.id;
        objStripeCard.statusCode=200;
        
        BillingUtility.CardList objCardList=new BillingUtility.CardList();
        objCardList.count=1;
        objCardList.url='/v1/customers/cus_EuGxgjwNxGcLDd/sources';
        objCardList.stripeData=new List< BillingUtility.StripeCard>{objStripeCard};
            
        BillingUtility.StripeCustomer objStripeCustomer=new BillingUtility.StripeCustomer();
        objStripeCustomer.created=1;
        objStripeCustomer.account_balance=1000;
        objStripeCustomer.description='description';
        objStripeCustomer.error=objStripeError;
        objStripeCustomer.livemode=true;
        objStripeCustomer.default_source='default_source';
        objStripeCustomer.token='123';
        objStripeCustomer.id='123';
        objStripeCustomer.metadata=new Map<String,String>{'test' =>'test'};
            objStripeCustomer.cards =objCardList;
        objStripeCustomer.default_card='default_card';
        objStripeCustomer.statusCode=200;
        objStripeCustomer.sources=objClsSourc;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200,JSON.serialize(objStripeCustomer)));  
        updateCustomerCardForPortalCntrlObj.selMonth='4';
        updateCustomerCardForPortalCntrlObj.selYear='2024';
        updateCustomerCardForPortalCntrlObj.updateCard();
        String error= UpdateCustomerCardForPortalCntrl.addCard('1233', objCustmr.id, false,'SG');
        
        UpdateCustomerCardForPortalCntrl.addCard('1233', objCustmr.id, true,'SG');
        //     '{  "id": "card_1Ec5R72eZvKYlo2CRjZBIqTG",  "object": "card",  "address_city": null,  "address_country": null,  "address_line1": null,  "address_line1_check": null,  "address_line2": null,  "address_state": null,  "address_zip": null,  "address_zip_check": null,  "brand": "Visa",  "country": "US",  "customer": "cus_F6I0JZYhhDqs6p",  "cvc_check": null,  "dynamic_last4": null,  "exp_month": 8,  "exp_year": 2020,  "fingerprint": "Xt5EWLLDS7FJjR1c",  "funding": "credit",  "last4": "4242",  "metadata": {},  "name": "Jenny Rosen",  "tokenization_method": null,"sources":{"last4":"1234","brand":"visa"}}'
        Test.stopTest();
        
    }
}