force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Camp_Days__c.field-meta.xml
<CustomField>
    <fullName>Camp_Days__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp class  for select customer Camp Day</description>
    <label>Camp Days</label>
    <referenceTo>Camp_Days__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp__c/Camp__c.object-meta.xml
<CustomObject>
    <description>this object for manage camp class</description>
    <label>Camp</label>
    <nameField>
        <label>Camp  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp class for manage Location/Centre</description>
    <label>Location/Centre</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Camps</relationshipLabel>
    <relationshipName>Camps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>this field for camp class for manage camp Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Available_Package__c/Camp_Available_Package__c.object-meta.xml
<CustomObject>
    <description>this object for camp class for manage Camp Available Package details</description>
    <label>Camp Available Package</label>
    <nameField>
        <label>Camp Available Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camp Available Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Available_Package__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this field for camp package for manage camp package  active or not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Camp_Available_Package__c/fields/Camp_Name__c.field-meta.xml
<CustomField>
    <fullName>Camp_Name__c</fullName>
    <description>this field for camp package for manage selected camp name</description>
    <label>Camp Name</label>
    <referenceTo>Camp__c</referenceTo>
    <relationshipLabel>Camp Available Packages</relationshipLabel>
    <relationshipName>Camp_Available_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Camp_Available_Package__c/fields/No_of_days__c.field-meta.xml
<CustomField>
    <fullName>No_of_days__c</fullName>
    <description>this field for camp package for manage camp package number or days</description>
    <label>No. of days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Camp_Available_Package__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for camp package for manage camp selected package</description>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Camp Available Packages</relationshipLabel>
    <relationshipName>Camp_Available_Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/Camp_Day_Teachers__c.object-meta.xml
<CustomObject>
    <description>this object manage Camp Days related Teachers</description>
    <label>Camp Day Teachers</label>
    <nameField>
        <displayFormat>CampDayTeacher-{0000}</displayFormat>
        <label>Camp Day Teachers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Camp Day Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>this field manage teacher camp end time</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <description>this field manage teacher camp start time</description>
    <label>Start time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Day_Teachers__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp_Days__c/Camp_Days__c.object-meta.xml
<CustomObject>
    <description>this object  for manage camp days</description>
    <label>Camp Days</label>
    <nameField>
        <label>Camp day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camp Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp_Days__c/fields/Camp_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Camp_End_Time__c</fullName>
    <description>this field for camp days for manage Camp End Time</description>
    <label>Camp End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Name__c.field-meta.xml
<CustomField>
    <fullName>Camp_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Camp Name</label>
    <referenceTo>Camp__c</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Camp_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Camp_Start_Time__c</fullName>
    <description>this field for camp days for manage Camp Start Time</description>
    <label>Camp Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Dates_Of_The_Camp__c.field-meta.xml
<CustomField>
    <fullName>Dates_Of_The_Camp__c</fullName>
    <description>this field for camp days for manage Dates Of The Camp</description>
    <label>Dates Of The Camp</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/No_of_Students_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>No_of_Students_Enrolled__c</fullName>
    <description>this field for camp days for manage camp No. of Students Enrolled</description>
    <label>No. of Students Enrolled</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Camp_Days__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>this field for camp days for manage camp Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Camp__c.field-meta.xml
<CustomField>
    <fullName>Camp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this field for Camp Class  for manage camp Id</description>
    <label>Camp</label>
    <referenceTo>Camp__c</referenceTo>
    <relationshipLabel>Enrolments</relationshipLabel>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Location__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CampClassUtilityControllerTest.cls
/**
* Name: CampClassUtilityControllerTest
* Author: Jatin
* Date : 14-March-2020
* Description: this class Used to test CampClassUtilityController controller class
*/
@isTest
public class CampClassUtilityControllerTest {
    
    @testSetup
    private static void createData() {
        CampEnrolmentTestHelper.createCampData();
    }
    private static testMethod  void test_CampClassUtilityControllerTest(){
         list<Camp__c> lstCamp= [SELECT Id,Centre__c,Centre__r.Country__r.Currency_Code__c, Name
                                FROM Camp__c
                                Where Status__c =:ConstantsClass.campActiveStatus];
        list<Camp_Available_Package__c> lstPackages = [SELECT Id, Name,No_of_days__c FROM Camp_Available_Package__c 
                                                       where Camp_Name__c =:lstCamp[0].id 
                                                       and Active__c= true  
                                                       Order by No_of_days__c DESC];
        
        list<Camp_Days__c> lstCampDays = [ SELECT id,Status__c, Camp_Name__c, Camp_Start_Time__c, Camp_End_Time__c, Dates_Of_The_Camp__c, No_of_Students_Enrolled__c 
                                          FROM Camp_Days__c 
                                          where Camp_Name__c =: lstCamp[0].id 
                                          and Status__c ='Active'
                                          Order by Dates_Of_The_Camp__c];
        List<Camp_Day_Teachers__c> listOfCamp_Day_Teachers = [Select id,Camp_Teacher__c,Camp_Day__c
                                                              from Camp_Day_Teachers__c
                                                              where Camp_Day__c=: lstCampDays[0].id];
        List<camp__c> ListOfCamp =CampClassUtilityController.getCampList(lstCamp[0].Centre__c,lstCamp[0].id,
                                                                         new set<string>{lstPackages[0].id},new set<string>{lstCampDays[0].id});
        
        ListOfCamp = CampClassUtilityController.getCampList(lstCamp[0].Centre__c,lstCamp[0].id,
                                                            lstPackages[0].id,new set<string>{string.valueOf(lstCampDays[0].id)});
        
        CampClassUtilityController.getPicklistValues('Camp__c','Status__c');
        CampClassUtilityController.getTeacherWorkingHoursList(new set<string>{listOfCamp_Day_Teachers[0].Camp_Teacher__c},new set<string>{listOfCamp_Day_Teachers[0].Camp_Day__c},lstCamp[0].Centre__c);
    	CampClassUtilityController.getCampDaysTeachers(new set<Id>{lstCampDays[0].id});
        List<Booking__C> listOfbooking = [select id,Student__c,Enrolment__c,Teacher_Account__c,Camp_Id__c,Camp_Days__c,Package__c,Center__c,Start_Time__c,
                                             End_Time__c,Booking_Date__c
                                             from Booking__C];
        
        CampClassUtilityController.createCampBooking(listOfbooking[0].Student__c,listOfbooking[0].Enrolment__c,listOfbooking[0].Booking_Date__c,
                                                     listOfbooking[0].End_Time__c,listOfbooking[0].Start_Time__c,listOfbooking[0].Center__c,
                                                     listOfbooking[0].Package__c,listOfbooking[0].Camp_Id__c,listOfbooking[0].Camp_Days__c,'');
    }

}