force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Duty_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Duty_Type__c</fullName>
    <label>Employee Duty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Duty</fullName>
            </value>
            <value>
                <fullName>Non-Duty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Break</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Hours in-lieu</fullName>
            </value>
            <value>
                <fullName>Recital</fullName>
            </value>
            <value>
                <fullName>Contract Programme</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>5th Lesson</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Centre)</relationshipLabel>
    <relationshipName>CenterBooking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <description>This formula field is use for displaying name of center on booking object</description>
    <formula>Opportunity__r.Account.Name</formula>
    <label>Center Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Name__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Name__c</fullName>
    <formula>Teacher_Account__r.FirstName +&apos; &apos;+Teacher_Account__r.LastName</formula>
    <label>Teacher Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
            <value>
                <fullName>Audition</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Group Class</fullName>
            </value>
            <value>
                <fullName>Group Lesson</fullName>
            </value>
            <value>
                <fullName>Piano Viewing</fullName>
            </value>
            <value>
                <fullName>Busy / Place holder</fullName>
                <isActive>false</isActive>
                <label>Busy / Place holder</label>
            </value>
            <value>
                <fullName>Notice</fullName>
                <isActive>false</isActive>
                <label>Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Organisations</relationshipLabel>
    <relationshipName>Organisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Public_Holiday__c/Public_Holiday__c.object-meta.xml
<CustomObject>
    <label>Public Holiday</label>
    <nameField>
        <label>Public Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Holiday__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Public Holidays</relationshipLabel>
    <relationshipName>Public_Holidays</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Public_Holiday__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Public Holidays</relationshipLabel>
    <relationshipName>Public_Holidays</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Public_Holiday__c/fields/Organisation_Status__c.field-meta.xml
<CustomField>
    <fullName>Organisation_Status__c</fullName>
    <label>Organisation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Public_Holiday__c/fields/Public_Holiday_Date__c.field-meta.xml
<CustomField>
    <fullName>Public_Holiday_Date__c</fullName>
    <label>Public Holiday Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Public_Holiday__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending for execution</fullName>
            </value>
            <value>
                <fullName>Execution completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/Teacher_Working_Hour__c.object-meta.xml
<CustomObject>
    <label>Teacher Working Hour</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Teacher Working Hour ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Working Hours</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Break_Time__c.field-meta.xml
<CustomField>
    <fullName>Break_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select the checkbox to create a break schedule</inlineHelpText>
    <label>Break Time</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teacher_Working_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Teacher_Name__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teacher Working Hours</relationshipLabel>
    <relationshipName>Teacher_Working_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hour__c/fields/Working_Day__c.field-meta.xml
<CustomField>
    <fullName>Working_Day__c</fullName>
    <label>Working Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
            <value>
                <fullName>Sun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublicHolidayHelper.cls
public class PublicHolidayHelper {
    //Added By ....Ravi this trigger create a Holiday Catgory for all teacher in various location as per teacher working hours
    public static void createdPlaceholderPublic(List<Public_Holiday__c> publicHolidayList){
         // defined to store the teacher record types
        string teacherTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Teacher').getRecordTypeId();
        // defined to stores the Holiday date list
        List<Date> dateList= new List<Date>();
        // defined to store the type of duty if teacher 
        set<string> dutyType = new set<String>();
        // defined to map the Date with Holiday Date
        map<Date,string> mapToHoliday = new map<Date,string>();
        // defined to update the status of Public holiday 
        List<Public_Holiday__c> updatePublicHolidayList = new List<Public_Holiday__c>();
        // defined  to map the PublicHoliday id with COuntry Id
        map<String,string> mapToPublicHoliday = new map<String,String>();
        // new Definde Value
        map<string,List<Account>> mapToTeacherOrganistion= new map<string,List<Account>>();
        set<String> dayStr = new set<String>();
        //  end Defined Value
        // defined to map to working hour
         map<string,string> mapToworkinghour = new map<string,string>();
        set<String> organisationId =  new set<String>();
        list<Booking__c> BookingLeaveList = new list<Booking__c>();
        for(Public_Holiday__c phObj:publicHolidayList){
            Datetime dt = DateTime.newInstance(phObj.Public_Holiday_Date__c, Time.newInstance(0, 0, 0, 0));
            String dayOfWeek=dt.format('E');
            dayStr.add(dayOfWeek);
            if(phObj.Public_Holiday_Date__c <> null && phObj.Organisation_Status__c =='Closed' && phObj.Status__c=='Pending for execution'){
                dateList.add(phObj.Public_Holiday_Date__c);
                dutyType.add('Duty');
                dutyType.add('Non-Duty');
                organisationId.add(phObj.Organisation__c);
                mapToHoliday.put(phObj.Public_Holiday_Date__c,phObj.Name);
            }else if(phObj.Public_Holiday_Date__c <> null && phObj.Status__c=='Pending for execution' && phObj.Organisation_Status__c =='Open') {
                dateList.add(phObj.Public_Holiday_Date__c);
                dutyType.add('Duty');
                mapToHoliday.put(phObj.Public_Holiday_Date__c,phObj.Name);
                 organisationId.add(phObj.Organisation__c);
            }
        }
        for(Public_Holiday__c publicHoliday:[select Id,Organisation__r.Country__c,Country__c from Public_Holiday__c where Id in:publicHolidayList]){
            mapToPublicHoliday.put(publicHoliday.Id,publicHoliday.Organisation__r.Country__c);
        }
        
        // New Code 
        for(Account teacherObj:[select Id,Name,Organisation__c,Employee_Duty_Type__c,(select Working_Day__c,Center_Name__c,Teacher_Name__c,Start_Time__c,End_Time__c from Teacher_Working_Schedules__r  where  Break_Time__c=false and Active__c =true and Working_Day__c in:dayStr) from Account where RecordTypeId=:teacherTypeId and Employee_Duty_Type__c in:dutyType and Organisation__c in:organisationId]){
            if(mapToTeacherOrganistion.containsKey(teacherObj.Organisation__c)){
                list<Account> accList= mapToTeacherOrganistion.get(teacherObj.Organisation__c);
                accList.add(teacherObj); 
                mapToTeacherOrganistion.put(teacherObj.Organisation__c,accList);     
            }else{
                List<Account> accList = new List<Account>(); 
                accList.add(teacherObj);
                mapToTeacherOrganistion.put(teacherObj.Organisation__c,accList);
            }
            for(Teacher_Working_Hour__c workInstance:teacherObj.Teacher_Working_Schedules__r){
                mapToworkinghour.put(workInstance.Teacher_Name__c +'/' + workInstance.Working_Day__c,workInstance.Start_Time__c + '/'+workInstance.End_Time__c + '/' + workInstance.Working_Day__c); 
            }
        }
        Time StartTime =Time.newInstance(08, 00, 00, 00);
        Time EndTime=Time.newInstance(20, 00, 00, 00);
        
        for(Public_Holiday__c publicObj:publicHolidayList){
            if(mapToTeacherOrganistion.containsKey(publicObj.Organisation__c)){
                for(Account accTr:mapToTeacherOrganistion.get(publicObj.Organisation__c)){
                    if(publicObj.Organisation_Status__c=='Closed' || (publicObj.Organisation_Status__c=='Open' && accTr.Employee_Duty_Type__c=='Duty') ){
                        for (Teacher_Working_Hour__c ar : accTr.Teacher_Working_Schedules__r)  {
                            // Date leaveDate=dateList[0];
                            // System.debug('Campaign ID' + ar.get('Center_Name__c'));
                            string CenterId =string.valueOf(ar.Center_Name__c);
                            string teacherId =string.valueOf(ar.Teacher_Name__c);
                            system.debug('teacherId'+teacherId + 'CenterId'+CenterId);
                            
                                Datetime dt = DateTime.newInstance(publicObj.Public_Holiday_Date__c, Time.newInstance(0, 0, 0, 0));
                                String dayOfWeek=dt.format('E');
                                string KeyId=teacherId+'/'+dayOfWeek;
                                // system.debug('mapToworkinghour'+  mapToworkinghour.get(KeyId).split('/')[2] +'teacherId'+teacherId);
                                if(mapToworkinghour.containsKey(KeyId) && mapToworkinghour.get(KeyId).split('/')[2]==dayOfWeek ){
                                    integer hr=integer.valueOf(mapToworkinghour.get(KeyId).split('/')[0].split(':')[0]);
                                    integer min=integer.valueOf(mapToworkinghour.get(KeyId).split('/')[0].split(':')[1]);
                                    StartTime=Time.newInstance(hr,min,00,00);
                                    integer Ehr=integer.valueOf(mapToworkinghour.get(KeyId).split('/')[1].split(':')[0]);
                                    integer Emin=integer.valueOf(mapToworkinghour.get(KeyId).split('/')[1].split(':')[1]);
                                    EndTime=Time.newInstance(Ehr,Emin,00,00);
                                    String RemarkforTeacherLeave='Public Holiday';// Defining the remark for the Teacher Leave reason  
                                    
                                    if(mapToHoliday.containsKey(publicObj.Public_Holiday_Date__c)){
                                        RemarkforTeacherLeave =mapToHoliday.get(publicObj.Public_Holiday_Date__c) +' Public Holiday';
                                    }
                                    
                                    Booking__c bkgLeaveObj = new Booking__c(End_Time__c=EndTime,Start_Time__c=StartTime,Status__c='Scheduled',Type__c='Busy',Category__c='Holiday',Center__c=CenterId,Teacher_Account__c=teacherId,Booking_Date__c=publicObj.Public_Holiday_Date__c,Remarks__c=RemarkforTeacherLeave);
                                    BookingLeaveList.add(bkgLeaveObj);  
                                }
                        }
                    }
                    
                }  
            }
          
            
        }
        system.debug('BookingLeaveList'+BookingLeaveList.size());
        // check for the Leave availability
        if(BookingLeaveList.size()>0){
            insert BookingLeaveList;
        }
         // Updating the Public holiday Country on basis of Orgainistaion 
        for(Public_Holiday__c phObject:publicHolidayList){
            if(mapToPublicHoliday.containsKey(phObject.Id) && (phObject.Status__c =='Draft' || phObject.Status__c =='Pending for execution')){
                Public_Holiday__c phObjct = new Public_Holiday__c(Id=phObject.Id,Country__c=mapToPublicHoliday.get(phObject.Id));
                updatePublicHolidayList.add(phObjct); 
            }
        }
        
        
        if(updatePublicHolidayList.size()>0){
            update updatePublicHolidayList;
        }
    }

}