force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <label>Stripe Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrolments (Centre)</relationshipLabel>
    <relationshipName>Enrolments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Lesson_Day__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Day__c</fullName>
    <description>Weekly Appointment Day</description>
    <label>Lesson Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Promotional_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Period_End_Date__c</fullName>
    <label>Promotional Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Termination_request_date__c.field-meta.xml
<CustomField>
    <fullName>Termination_request_date__c</fullName>
    <description>this field for piano rental for manage customer Termination requested date</description>
    <label>Termination request date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Firebase_Settings__c/Firebase_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Firebase Settings</label>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Center)</relationshipLabel>
    <relationshipName>Center_Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Location__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Unit_Fee__c.field-meta.xml
<CustomField>
    <fullName>Unit_Fee__c</fullName>
    <inlineHelpText>One session fee</inlineHelpText>
    <label>Unit Fee</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Subscription_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Subscription_Line_Item__c.Subscription__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions (Centre)</relationshipLabel>
    <relationshipName>Subscriptions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Center__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Subscription__r.Center__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegularInvoiceHandlerTest.cls
/*
Name        :        RegularInvoiceHandlerTest
Date        :        8 April 2019
Author      :        Karan Singh Soni
Description :        It is the test class of RegularInvoiceHandler.
*/

@isTest
public class RegularInvoiceHandlerTest {
    
    public static testMethod void invokeRegularInvoiceHandler(){
        List<Enrolment__c> enrolmentList = new List<Enrolment__c>();
        Date firstDate, lastDate;
        firstDate = Date.newInstance(System.today().year(), System.today().month(), 05);
        lastDate = firstDate.addDays(10);
        Account objCustmr = TestUtil.createAccount('Customer',TRUE,FALSE);
        objCustmr.Stripe_Customer_Id__c='ch_1AxWbTFytruJp2FXW6iuRd1X';
        INSERT objCustmr;
        Firebase_Settings__c objSetting = new Firebase_Settings__c();
        objSetting.Name = 'setting';
        objSetting.Enable_Notifications__c = false;
        insert objSetting;
        Country__c country = new Country__c(); 
        country.Name = 'IN'; 
        country.Country_Name__c = 'India';
        country.Tax_Rate__c = 7.0; 
        country.Currency_Code__c = 'INR'; 
        country.Student_Policies_Template_Id__c = 'test'; 
        country.Stripe_Base_Url__c = 'www.test.com'; 
        country.Stripe_Publishable_Key__c = 'ABC';
        country.Stripe_Secret_Key__c = 'deede'; 
        insert country;
        
        Account objCentr = TestUtil.createAccount('Centre',TRUE,FALSE);
        objCentr.Country__c = country.Id;
        INSERT objCentr;
        
        Account objTeachr = TestUtil.createAccount('Teacher',TRUE,TRUE);
        
        Program__c objProg = TestUtil.createProgram('Active','Piano', TRUE);
        Package__c objPack = TestUtil.createPackage(objProg.Id, objCentr.Id,'30',True);
        
        Enrolment__c objENrol=TestUtil.createEnrolment(objCentr.Id,objTeachr.Id,objCustmr.Id,objPack.id,false);
        objENrol.Lesson_Day__c = 'Monday';
        objENrol.Promotional_Period_End_Date__c = lastDate.addDays(-3);
        Enrolment__c objENrol2=TestUtil.createEnrolment(objCentr.Id,objTeachr.Id,objCustmr.Id,objPack.id,false);
        objENrol2.Lesson_Day__c = 'Tuesday';
        objENrol2.Promotional_Period_End_Date__c = lastDate.addDays(-3);
        Enrolment__c objENrol3=TestUtil.createEnrolment(objCentr.Id,objTeachr.Id,objCustmr.Id,objPack.id,false);
        objENrol3.Lesson_Day__c = 'Wednesday';
        objENrol3.Promotional_Period_End_Date__c = lastDate.addDays(-3);
        Enrolment__c objENrol4=TestUtil.createEnrolment(objCentr.Id,objTeachr.Id,objCustmr.Id,objPack.id,false);
        objENrol4.Lesson_Day__c = 'Thursday';
        objENrol4.Promotional_Period_End_Date__c = lastDate.addDays(-3);
        Enrolment__c objENrol5=TestUtil.createEnrolment(objCentr.Id,objTeachr.Id,objCustmr.Id,objPack.id,false);
        objENrol5.Lesson_Day__c = 'Friday';
        objENrol5.Promotional_Period_End_Date__c = lastDate.addDays(-3);
        Enrolment__c objENrol6=TestUtil.createEnrolment(objCentr.Id,objTeachr.Id,objCustmr.Id,objPack.id,false);
        objENrol6.Lesson_Day__c = 'Saturday';
        objENrol6.Promotional_Period_End_Date__c = lastDate.addDays(-3);
        Enrolment__c objENrol7=TestUtil.createEnrolment(objCentr.Id,objTeachr.Id,objCustmr.Id,objPack.id,false);
        objENrol7.Lesson_Day__c = 'Sunday';
        objENrol7.Promotional_Period_End_Date__c = lastDate.addDays(-3);
        
        insert objENrol;
        
        Subscription__C objSub=TestUtil.createSubscription(objCustmr.id,true);
        Subscription_Line_Item__c objSubLine=TestUtil.createSubscriptionLineItem(objSub.id	,false);
        objSubLine.Enrolment__c = objENrol.Id;
        insert objSubLine;
        Invoice__C objInv=TestUtil.createInvoice(objCustmr.id, true);
        Map<String,List<Date>> mapOfDates= new Map<String,List<Date>>();
        DateTime startDt, endDt;
        startDt = DateTime.newInstance(Date.newInstance(System.today().year(), System.today().Month(), 01), Time.newInstance(0, 0, 0, 0));
        endDt =  DateTime.newInstance(startDt.date().addMonths(1).addDays(-1), Time.newInstance(0, 0, 0, 0));
        while(startDt != endDt){
            if(startDt.format('EEEE') == 'Monday'){
                if(mapOfDates.containsKey(startDt.format('EEEE'))){
                    List<Date> dates = mapOfDates.get(startDt.format('EEEE'));
                    dates.add(startDt.date());
                    mapOfDates.put(startDt.format('EEEE'), dates);
                }else{
                    mapOfDates.put(startDt.format('EEEE'),new List<Date> {startDt.date()});                    
                }
                
            }
            startDt =  startDt.addDays(1);                                                    
        }
        
        objSubLine = [SELECT Id,Enrolment__r.recordtype.Name,Enrolment__r.Center__c,Enrolment__r.Center__r.Country__c,Enrolment__r.Center__r.Country__r.Tax_Rate__c,
                      Enrolment__r.Promotional_Period_End_Date__c, Enrolment__r.Lesson_Day__c, 
                      Enrolment__r.Package__r.Unit_Fee__c, Enrolment__r.Package__c, Enrolment__r.Teacher__c 
                      FROM Subscription_Line_Item__c WHERE Id =: objSubLine.Id LIMIT 1];
        RegularInvoiceHandler objRegINV= new RegularInvoiceHandler(objSubLine, firstDate, lastDate);
        
        objRegINV.createInvoiceLineItem(objInv,mapOfDates);
    }
    // added by jatin: 18-mar-2020: for  Paino rental enrolment testing 
    public static testMethod void invokeRegularInvoiceHandlerPainoRental(){
        ClassEditControllerTestHelper.createGroupClassData();
        Date firstDate, lastDate;
        firstDate = Date.newInstance(System.today().year(), System.today().month(), 05);
        lastDate = firstDate.addDays(10);
        List<Invoice__C> listOfInvoice = [select id from invoice__C];
        List<Subscription_Line_Item__c> listOfSubLine = [SELECT Id,Enrolment__r.recordtype.Name,Enrolment__r.Center__c,Enrolment__r.Center__r.Country__c,Enrolment__r.Center__r.Country__r.Tax_Rate__c,
                                      Enrolment__r.Promotional_Period_End_Date__c, Enrolment__r.Lesson_Day__c,Amount__c, 
                                      Enrolment__r.Package__r.Unit_Fee__c, Enrolment__r.Package__c, Enrolment__r.Teacher__c 
                                      FROM Subscription_Line_Item__c LIMIT 1];
        Map<String,List<Date>> mapOfDates= new Map<String,List<Date>>();
        DateTime startDt, endDt;
        startDt = DateTime.newInstance(Date.newInstance(System.today().year(), System.today().Month(), 01), Time.newInstance(0, 0, 0, 0));
        endDt =  DateTime.newInstance(startDt.date().addMonths(1).addDays(-1), Time.newInstance(0, 0, 0, 0));
        while(startDt != endDt){
            if(startDt.format('EEEE') == 'Monday'){
                if(mapOfDates.containsKey(startDt.format('EEEE'))){
                    List<Date> dates = mapOfDates.get(startDt.format('EEEE'));
                    dates.add(startDt.date());
                    mapOfDates.put(startDt.format('EEEE'), dates);
                }else{
                    mapOfDates.put(startDt.format('EEEE'),new List<Date> {startDt.date()});                    
                }
                
            }
            startDt =  startDt.addDays(1);                                                    
        }
        RegularInvoiceHandler objRegINV= new RegularInvoiceHandler(listOfSubLine[0], firstDate, lastDate);
         objRegINV.createInvoiceLineItem(listOfInvoice[0],mapOfDates);
        
    }
    
    public static testMethod void invokeRegularInvoiceHandlerPainoRental2(){
        PianoRentalTestHelper.createPianoRentalData();
        Date firstDate, lastDate;
        firstDate = Date.newInstance(System.today().year(), System.today().month(), 05);
        lastDate = firstDate.addDays(10);
        List<Invoice__C> listOfInvoice = [select id from invoice__C];
        List<Subscription_Line_Item__c> listOfSubLine = [SELECT Id,Enrolment__r.recordtype.Name,Enrolment__r.Center__c,Enrolment__r.Center__r.Country__c,Enrolment__r.Center__r.Country__r.Tax_Rate__c,
                                      Enrolment__r.Promotional_Period_End_Date__c, Enrolment__r.Lesson_Day__c,Amount__c,Enrolment__r.Termination_request_date__c ,
                                      Enrolment__r.Package__r.Unit_Fee__c, Enrolment__r.Package__c, Enrolment__r.Teacher__c 
                                      FROM Subscription_Line_Item__c LIMIT 1];
        Map<String,List<Date>> mapOfDates= new Map<String,List<Date>>();
        DateTime startDt, endDt;
        startDt = DateTime.newInstance(Date.newInstance(System.today().year(), System.today().Month(), 01), Time.newInstance(0, 0, 0, 0));
        endDt =  DateTime.newInstance(startDt.date().addMonths(1).addDays(-1), Time.newInstance(0, 0, 0, 0));
        while(startDt != endDt){
            if(startDt.format('EEEE') == 'Monday'){
                if(mapOfDates.containsKey(startDt.format('EEEE'))){
                    List<Date> dates = mapOfDates.get(startDt.format('EEEE'));
                    dates.add(startDt.date());
                    mapOfDates.put(startDt.format('EEEE'), dates);
                }else{
                    mapOfDates.put(startDt.format('EEEE'),new List<Date> {startDt.date()});                    
                }
                
            }
            startDt =  startDt.addDays(1);                                                    
        }
        RegularInvoiceHandler objRegINV= new RegularInvoiceHandler(listOfSubLine[0], firstDate, lastDate);
         objRegINV.createInvoiceLineItem(listOfInvoice[0],mapOfDates);
    }
    
    
}