force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Next_Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Bill_Date__c</fullName>
    <formula>prepayment_period_end_date__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Location__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Center__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Subscription__r.Center__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Next_Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Bill_Date__c</fullName>
    <label>Next Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Plan_Package__c.field-meta.xml
<CustomField>
    <fullName>Plan_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan/Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subscription_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SubscriptionMonthlySchedularTest.cls
/*
Name        :        SubscriptionMonthlySchedularTest
Date        :        8 April 2019
Author      :        Karan Singh Soni
Description :        It is the test class of SubscriptionMonthlySchedular.
*/

@isTest
public class SubscriptionMonthlySchedularTest {
    public static testmethod void invokeSubscriptionMonthlySchedular(){
        
        Country__c country = new Country__c();
        country.Name = 'SG';
        country.Country_Name__c = 'Singapore';
        country.Tax_Rate__c = 7.0;
        country.Currency_Code__c = 'SGD';
        country.Student_Policies_Template_Id__c = 'test';
        country.Stripe_Base_Url__c = 'www.test.com';
        country.Stripe_Publishable_Key__c = 'ABC';
        country.Stripe_Secret_Key__c = 'deede';
        insert country;
        Account objCustmr=TestUtil.createAccount('Customer',True,True);
        
        Account objCentr=TestUtil.createAccount('Centre',False,FALSE);
        objCentr.Country__c = country.Id;
        INSERT objCentr;
        Account objtechr=TestUtil.createAccount('Teacher',False,true);
        Program__C objProg=TestUtil.createProgram('Active','Piano',true);
        Package__c objPack=testUtil.createPackage(objProg.id,objCentr.id,'60',true);        
        Enrolment__c objENrol=TestUtil.createEnrolment(objCentr.Id,objTechr.Id,objCustmr.Id,objPack.id,True); 
        
        Subscription__C objSubs=TestUtil.createSubscription(objCustmr.Id,False);
        objSubs.Status__c='Active';
        objSubs.Subscription_Start_Date__c=date.today().adddays(-5);
        objSubs.Next_Bill_Date__c=date.today().adddays(-5);
        insert objSubs;
        
        Subscription_Line_Item__c objSubsLine=TestUtil.createSubscriptionLineItem(objSubs.Id,False);
        objSubsLine.Enrolment__c=objEnrol.id;
        objSubsLine.Plan_Package__c=objPack.id;
        objSubsLine.Status__c='Active';
        objSubsLine.Next_Bill_Date__c=date.today().adddays(-5);
        insert objSubsLine; 
        
        SubscriptionMonthlySchedular objSubMonSch= new SubscriptionMonthlySchedular();
        objSubMonSch.execute(Null);
    }
}