force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balance_Amount__c</fullName>
    <formula>Total_Amount__c - Paid_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Center)</relationshipLabel>
    <relationshipName>Center_Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Method_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Method_of_Payment__c</fullName>
    <label>Method of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>NETS</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Offline Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Parent_Payment__c.field-meta.xml
<CustomField>
    <fullName>Parent_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Refund_Id__c.field-meta.xml
<CustomField>
    <fullName>Refund_Id__c</fullName>
    <description>This Field is Use to store the refund Id of the Stripe. If Refund request has been submitted by the customer.</description>
    <label>Refund Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeRefundController.cls
/*
    Name            :   StripeRefundController
    Date            :   30th May 2019
    Author          :   
    Description     :   
*/
public class StripeRefundController {
    @AuraEnabled
    public static String initiateRefund(String amount,String recId,String remark){
        String msg = 'success';
        Boolean isSuccess = FALSE;
        Decimal amountToRefund =  BillingUtility.roundOffAmount(Decimal.valueOf(amount));
        Payment__c objPay = [SELECT Id,Payment_Amount__c,Transaction_Id__c,remarks__c,Invoice__c,Parent_Account__c, Invoice__r.Center__r.Country__r.Id,  
                             Invoice__r.Center__r.Country__r.Stripe_Base_Url__c, Invoice__r.Center__r.Country__r.Stripe_Secret_Key__c ,
                             //commented by @nishi 14 sep 2020,Organisation wise charge as per new logic
                             Invoice__r.Center__r.Organisation__r.name,Payment_Date__c,method_of_payment__c,
                             Invoice__r.Center__r.Organisation__r.Stripe_Base_Url__c, Invoice__r.Center__r.Organisation__r.Stripe_Secret_Key__c
                             FROM Payment__c WHERE Id=:recId LIMIT 1];
        
        /* //commented by @nishi 14 sep 2020,Organisation wise charge as per new logic
        if(String.isNotBlank(objPay.Invoice__r.Center__r.Country__r.Id) && String.isNotBlank(objPay.Invoice__r.Center__r.Country__r.Stripe_Base_Url__c) && 
           String.isNotBlank(objPay.Invoice__r.Center__r.Country__r.Stripe_Secret_Key__c)){
            isSuccess = TRUE;
        }*/
        if(String.isNotBlank(objPay.Invoice__r.Center__r.Organisation__r.Id) && String.isNotBlank(objPay.Invoice__r.Center__r.Organisation__r.Stripe_Base_Url__c) && 
        String.isNotBlank(objPay.Invoice__r.Center__r.Organisation__r.Stripe_Secret_Key__c)){
         isSuccess = TRUE;
     }
        if(amountToRefund > 0 && objPay.Payment_Amount__c >= amountToRefund && String.isNotBlank(objPay.Transaction_Id__c) && isSuccess){
            // //commented by @nishi 14 sep 2020,Organisation wise charge as per new logic
            //BillingUtility.StripeRefund  refundObj = BillingUtility.createRefundForCharge(objPay.Transaction_Id__c,amountToRefund, objPay.Invoice__r.Center__r.Country__r.Stripe_Base_Url__c, objPay.Invoice__r.Center__r.Country__r.Stripe_Secret_Key__c);
            
            BillingUtility.StripeRefund  refundObj = BillingUtility.createRefundForCharge(objPay.Transaction_Id__c,amountToRefund,
                 objPay.Invoice__r.Center__r.Organisation__r.Stripe_Base_Url__c, objPay.Invoice__r.Center__r.Organisation__r.Stripe_Secret_Key__c);
            
            if(refundObj.statusCode == 200 && refundObj.status == 'succeeded'){
                Payment__c newPayment = BillingUtility.fillPayment(objPay.Parent_Account__c, objPay.Invoice__c, -1*amountToRefund, 'Success');
                newPayment.refund_Id__c = refundObj.id;
                newPayment.remarks__c = remark;
                newPayment.Parent_Payment__c = objPay.Id;
                newPayment.method_of_payment__c = ConstantsClass.cardModeType;  // added by @nishi 14 sep 2020,as per new requirement for netsuit we added payment method
                 //added by nishi: 14-Sep-2020:Payment date for Pending payments should be updated to the date of application in the subsequent invoice. Same should also be changed at the time of Refunds
                objPay.Payment_Date__c = System.today();
                //paymentList.add(newPayment);
                Insert newPayment;
                SageIntacctIntegrationUtility.refundPayment(newPayment.id);	 
             
                if(String.isNotBlank(objPay.invoice__c)){
                    Invoice__c objInv = [SELECT Id,Balance_Amount__c,Status__c FROM Invoice__c WHERE Id=: objPay.invoice__c];
                    //System.debug('objInv '+objInv);
                    if(objInv.Balance_Amount__c > 0){
                        objInv.Status__c = ConstantsClass.dueStatus;
                        UPDATE objInv;
                    }
                }
            }else{
                if(refundObj.error != null){
                    msg = refundObj.error.message;
                }
            }
        }else{
            msg = 'Amount can not be more then payment amount.';
        }
        return msg;
    }
}