force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Parent)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
            <value>
                <fullName>Audition</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Group Class</fullName>
            </value>
            <value>
                <fullName>Group Lesson</fullName>
            </value>
            <value>
                <fullName>Piano Viewing</fullName>
            </value>
            <value>
                <fullName>Busy / Place holder</fullName>
                <isActive>false</isActive>
                <label>Busy / Place holder</label>
            </value>
            <value>
                <fullName>Notice</fullName>
                <isActive>false</isActive>
                <label>Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to create lesson booking</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <inlineHelpText>Its used for Panda doc student policy Template Id</inlineHelpText>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Organisations</relationshipLabel>
    <relationshipName>Organisations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Base_Url__c</fullName>
    <label>Stripe Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publishable_Key__c</fullName>
    <label>Stripe Publishable Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Stripe_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Key__c</fullName>
    <label>Stripe Secret Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Student_Policies_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Policies_Template_Id__c</fullName>
    <label>Student Policies Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <formula>IF(Country__r.Tax_Rate__c &gt; 0, Country__r.Tax_Rate__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Location__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to setup package for music lesson</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Following program type may not be used
1. Trial
2. Makeup
3. Adhoc</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Program_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/MakeAppointmentForPortalControllerTest.cls
/**
* @File Name : MakeAppointmentForPortalControllerTest
* @Class Name : MakeAppointmentForPortalController
* @Description : Test class for MakeAppointmentForPortalController
* @Author : Karan Singh Soni
* @Last Modified By : Karan Singh Soni
* @Last Modified On : 12 Aug 2019
* @Modification Log : 
*==============================================================================
* Ver Date Author Modification
*==============================================================================
* 1.0 09 Aug 2019 Initial Version	(41%)
* 1.1 12 Aug 2019					(82%)
**/

@isTest
public class MakeAppointmentForPortalControllerTest {

     //------------------------------- Initialization of test data -------------------------------------------
    @testSetup static void initDataForTest(){
        Country__c cntry = new Country__c();
        cntry.Name = 'SG';
        cntry.Country_Name__c ='Singapore';
        cntry.Currency_Code__c ='SGD';
        cntry.Tax_Rate__c = 7;
        cntry.Student_Policies_Template_Id__c= 'DLe9tWht6W9PNHEabs2ruT';
        cntry.Stripe_Base_Url__c ='https://api.stripe.com';
        cntry.Stripe_Publishable_Key__c ='pk_test_eGeu4Z0mLSfXmekcJcLt7TVH';
        cntry.Stripe_Secret_Key__c ='sk_test_M3pk8qvbMs03SWjDuf6m1bss';
        insert cntry;
        
        Organisation__c org = new Organisation__c(Name='Test',Country__c=cntry.Id);
        insert org;
        Account objCentr=TestUtil.createAccount('Centre',false,false);
        objCentr.Country__c =cntry.Id;
        objCentr.Organisation__c=org.Id;
        insert objCentr;
        Account objTeachr=testUtil.createAccount('Teacher',false,true);
        Account objCustmr=TestUtil.createAccount('Customer',True,true);
        Booking__c objBook = TestUtil.createBooking(objTeachr.id,'Lesson','Regular',true);
        Program__C objProg=TestUtil.createProgram('Active','Piano',true);
        Package__c objPack=testUtil.createPackage(objProg.id,objCentr.id,'45',false); 
        objPack.Type__c = 'Makeup';
        insert objPack;
         package__c objPackNew = testUtil.createPackage(objProg.id,objCentr.id,'45',false); 
        objPackNew.Type__c = 'Makeup';
        insert objPackNew;
        Enrolment__c objENrol=TestUtil.createEnrolment(objCentr.Id,objTeachr.Id,objCustmr.Id,objPack.id,false);
        objENrol.Parent__c = objCustmr.id;
        objENrol.Type__c = ConstantsClass.typeRegular;
        objENrol.Stage__c = ConstantsClass.enroledStatus;
        objENrol.Student__c = objCustmr.id;
        insert objENrol;
        List <Teacher_Working_Hour__c> listTWH=TestUtil.createTeacher_Working_Hour(objTeachr.id,objCentr.Id,True,False,7);
        list<Center_Working_Hours__c> listCwh=TestUtil.createCenter_Working_Hours(objCentr.id, True,7);
    }
    
    //--------------------------------- for valid Appointment procedure --------------------------------------------
    public static testMethod void validAppointment(){
        
        //-------------------------------- fetching data to method ------------------------------------------------
        Account objCustmr = [SELECT Id FROM Account WHERE RecordType.Name = 'Customer' LIMIT 1 ];
        Account objTeacher = [SELECT Id FROM Account WHERE RecordType.Name = 'Teacher' LIMIT 1 ];
        Account objCenter = [SELECT Id FROM Account WHERE RecordType.Name = 'Centre' LIMIT 1 ];
        system.debug('objCustmr'+objCustmr);
        Package__c objPack = [SELECT id FROM Package__c LIMIT 1];
        Enrolment__c objENrol = [SELECT id FROM Enrolment__c  LIMIT 1];
        Booking__c objBook = [ SELECT Id FROM Booking__c LIMIT 1 ];
        
        
        //-------------------------------- Changes in Enrolment ---------------------------------------------------
        
        system.debug('@@@@'+[select Student__r.Name from Enrolment__c where Id =: objENrol.Id ].Student__r.Name);
        ApexPages.currentPage().getParameters().put('id',objCustmr.Id);
        MakeAppointmentForPortalController objMakeAppnt = new MakeAppointmentForPortalController();
        objMakeAppnt.enrollmentId = objENrol.id;
        objMakeAppnt.assignFlagValue = true;
        objMakeAppnt.updateFlagValue();
        //objMakeAppnt.prcType = 'Any Times Available';
        
        //-------------------------------- changes in Account ----------------------------------------------------
        objCustmr.Available_Make_up_Units__c = 30;
        update objCustmr;
        
        //-------------------------------- Changes in Booking -------------------------------------------------
        objBook.RecordTypeId = Schema.SObjectType.Booking__c.getRecordTypeInfosByName().get('Lesson').getRecordTypeId();
        objBook.Booking_Date__c = System.today();
        objBook.Start_Time__c = Time.newInstance(11, 11, 11, 11);
        objBook.End_Time__c = Time.newInstance(11, 11, 11, 11);
        objBook.Status__c = 'Scheduled';
		objBook.Type__c = 'Regular';
        objBook.Teacher_Account__c = objTeacher.id;
        update objBook;
        
        //-------------------------------- Inserting a new Teacher Working hour --------------------------------
        	String currDay = DateTime.now().format('E');
        	Teacher_Working_Hour__c tw = new Teacher_Working_Hour__c();
            tw.Active__c = true;
            tw.Break_Time__c = False;
            tw.Teacher_Name__c = objTeacher.id;
            tw.Center_Name__c = objCenter.Id;
            tw.Working_Day__c = currDay.toLowerCase();
            tw.Start_Time__c=Time.newInstance(7,0,0,0);
            tw.End_Time__c=Time.newInstance(23,0,0,0);
        	insert tw;
        
        
       //-------------------------------- select Student -------------------------------------------------------
        objMakeAppnt.selectedStudent();
        
        //@commented as per rajesh sir  will call end of SaveBooking(9 aug 2019 1:30 pm)
        //system.debug('objMakeAppnt'+objMakeAppnt.newModelList);
        //-------------------------------- saveCurrentRecord -----------------------------------------------------
        //objMakeAppnt.saveCurrentRecord();   
        //--------------------------------- backSecondScreen ---------------------------------------------------
        //objMakeAppnt.backSecondScreen();    @commented as per rajesh sir
        //@commented as per rajesh sir
        
        
        //--------------------------------- checkAvlMakeup,Refresh Summary ----------------------------------------------------
        objMakeAppnt.slcPkgdDuration = 30;
        objMakeAppnt.checkAvlMakeup();
        objMakeAppnt.slcdSlot = '11:00';
        objMakeAppnt.refreshSummary();
        

        //-------------------------------- Changes in newModelList -------------------------------------------
        objMakeAppnt.newModelList[0].selectedPackageId = objPack.id;	//selecting a package by the user
        
        //--------------------------------- Fetching Time Slot ------------------------------------------------
        objMakeAppnt.fetchTimeSlot();
        
        //--------------------------------- Save Booking --------------------------------------------------------
        objMakeAppnt.saveBooking();
        
        //--------------------------------- Fetching Teacher -----------------------------------------------------
        objMakeAppnt.getTeachersForSelectedLesson();
        
        //--------------------------------- Changing teacher --------------------------------------------------
        objMakeAppnt.changeTchr();		//will empty the selected package id;	
        
        //--------------------------------- Saving Current record ----------------------------------------------
        //objMakeAppnt.indexNo = 0;
        //objMakeAppnt.saveCurrentRecord(); 
        
        
        
    }
    
    //------------------------------- For inValid Appointment (Error msg's) ----------------------------------------------
    public static testMethod void inValidAppointment(){
        
        //------------------------------ Parent Account not Found --------------------------------------
        {
            ApexPages.currentPage().getParameters().put('id',Null);
            MakeAppointmentForPortalController objMakeAppnt = new MakeAppointmentForPortalController();
        }
        {
             ApexPages.currentPage().getParameters().put('id','DummyId');
            MakeAppointmentForPortalController objMakeAppnt = new MakeAppointmentForPortalController();
            
        }
        
        //---------------------------- checkAvlMakeup ---------------------------------------------------------
        {
            ApexPages.currentPage().getParameters().put('id','DummyId');
            MakeAppointmentForPortalController objMakeAppnt = new MakeAppointmentForPortalController();
            objMakeAppnt.checkAvlMakeup();
        }
        
    }
    
}