force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Field_1__c.field-meta.xml
<CustomField>
    <fullName>Field_1__c</fullName>
    <label>Field 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CMN-{0000}</displayFormat>
        <label>Credit Memo Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/Amount_Exl_tax_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Amount_Exl_tax_Rollup__c</fullName>
    <label>Amount(Exl Tax)</label>
    <summarizedField>Credit_memo_line_item__c.Amount__c</summarizedField>
    <summaryForeignKey>Credit_memo_line_item__c.Credit_Memo_Number__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Memos (Center)</relationshipLabel>
    <relationshipName>Credit_Memos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Cheque_Date__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Date__c</fullName>
    <label>Cheque Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Cheque_No__c.field-meta.xml
<CustomField>
    <fullName>Cheque_No__c</fullName>
    <label>Cheque No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Credit_Memo_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo_Date__c</fullName>
    <label>Credit Memo Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Center__r.Organisation__r.Country__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Number</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/NETS_Code__c.field-meta.xml
<CustomField>
    <fullName>NETS_Code__c</fullName>
    <label>NETS Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Organisations_Name__c.field-meta.xml
<CustomField>
    <fullName>Organisations_Name__c</fullName>
    <formula>Parent_Account__r.Centre_Name__r.Organisation__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Organisation Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>NETS</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Offline Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Refund_ID__c.field-meta.xml
<CustomField>
    <fullName>Refund_ID__c</fullName>
    <label>Refund ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Stripe_Fee__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Fee__c</fullName>
    <label>Stripe Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Stripe_Payout_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Payout Id</label>
    <referenceTo>Stripe_Payout_Log__c</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Tax_Amount_Rollup__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Rollup__c</fullName>
    <label>Tax Amount</label>
    <summarizedField>Credit_memo_line_item__c.Tax_Amount__c</summarizedField>
    <summaryForeignKey>Credit_memo_line_item__c.Credit_Memo_Number__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Amount_Exl_tax_Rollup__c +  Tax_Amount_Rollup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_memo_line_item__c/Credit_memo_line_item__c.object-meta.xml
<CustomObject>
    <label>Credit Memo Line Item</label>
    <nameField>
        <displayFormat>CMLI-{0000}</displayFormat>
        <label>Cedit Memo Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_memo_line_item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount(Excl Tax)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit_memo_line_item__c/fields/Field_1__c.field-meta.xml
<CustomField>
    <fullName>Field_1__c</fullName>
    <label>Field 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>/*Sub_Total__c + GST_Tax_Amount__c + Deposit__c*/
Sub_Total__c + New_GST_Amount_Admin_Fee__c + Deposit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Sub Total + GST/Tax Amount + Deposit</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Inv-Item-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>Location__r.Currency_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubscriptionCreditMemoDetailsController.cls
Public without sharing class SubscriptionCreditMemoDetailsController{
    public Credit_Memo__c creditMemo{get;set;}
    public centerInfo center {get;set;}
    public Invoice__c invoice {get;set;}
    public String invoiceNo{get;set;}
    public Invoice__c frominvoice {get;set;}
    public String frominvoiceNo{get;set;}
    //By Ravi
    public String InvoiceStatus{get;set;}
    Public string customLabelValue{get;set;}
    Public String InvoiceId{get;set;}
    public boolean displayUpdate{get;set;}
    public boolean isOssia{get;set;}
    public string ParentAccId{get;set;}
    public Decimal subTotal{get;set;}
    public Decimal discountAmount{get;set;}
    public Decimal totalAmount{get;set;}
    //By Ravi
    public SubscriptionCreditMemoDetailsController(){
        String paymentAsDeposit = ConstantsClass.paymentAsDepositRecordType;
        creditMemo = new Credit_Memo__c();
        center = new centerInfo();
        invoiceNo = '';
        isOssia = false;
        subTotal=0;
        totalAmount =0;
        string invId = Apexpages.currentPage().getParameters().get('Id');
        // string invId ='a1k1m000001dpW1AAI';// for temp used
        system.debug('@@invId'+invId);
        
        List<Credit_Memo__c> creditMemoList = [SELECT From_Invoice__c, Field_1__c, Parent_Account__c, Organisations_Name__c, Comments__c, Currency_Code__c, Total_Amount__c, Payment_Method__c,Invoice_Number__c, Credit_Memo_Date__c, Status__c, Refund_ID__c, Stripe_Payout_Id__c, Stripe_Fee__c, Cheque_Date__c, Cheque_No__c, Bank_Name__c, NETS_Code__c, Amount_Exl_tax_Rollup__c, Tax_Amount_Rollup__c, Center__c, Netsuite_Payment_Method__c, Id, Name,
                                               (SELECT Transaction_ID__c, Credit_Memo_Number__c, Enrolment__c, Amount__c, Netsuite_GST_Code__c, Tax_Amount__c,Enrolment__r.Teacher__r.Name,
                                                Enrolment__r.Student__r.Name,Package__r.Type__c,
                                                Month__c, Remarks__c, Package__c, Is_Deposit__c, Is_Discount__c, Field_1__c, Invoice_Line_Item__c, Package_Name__c, Netsuite_Product_Name__c, Name, Id 
                                                FROM Credit_memo_line_items__r ORDER BY Month__c Asc), Center__r.Organisation__r.Name,
                                               Parent_Account__r.Card_Number__c,Parent_Account__r.Name, Parent_Account__r.Admin_Fees__c, 
                                               Parent_Account__r.Billingstreet,Parent_Account__r.BillingCity,Parent_Account__r.BillingState,Parent_Account__r.personEmail,
                                               Parent_Account__r.personMobilePhone,Parent_Account__r.BillingPostalcode,Parent_Account__r.BillingCountry,
                                               Center__r.Name,Center__r.PersonEmail,Center__r.PersonMobilePhone,Center__r.Billingstreet,Center__r.BillingCity,
                                               Center__r.BillingState,Center__r.BillingPostalcode,Center__r.GST_Number__c, Center__r.Phone, Center__r.Center_Email__c, Center__r.Website,
                                               Center__r.country__r.Id,Center__r.Organisation__r.Tax_Rate__c, Center__r.country__r.Tax_Rate__c,
                                               Invoice_Number__r.Status__c,Invoice_Number__r.Name,Invoice_Number__r.createdDate,createdDate,
                                               From_Invoice__r.Status__c,From_Invoice__r.Name,From_Invoice__r.createdDate
                                               FROM Credit_Memo__c  
                                               WHERE id=:invId Limit 1 ];
        system.debug('creditMemoList--->'+creditMemoList);
        if(creditMemoList.size()>0){
            
            creditMemo = creditMemoList[0];
            // added by nishi: 18-Aug-2020: for show Ossia Logo
            if(String.isNotBlank(creditMemoList[0].Center__c) && 
               String.isNotBlank(creditMemoList[0].Center__r.Organisation__c) && 
               String.isNotBlank(creditMemoList[0].Center__r.Organisation__r.Name) && 
               creditMemoList[0].Center__r.Organisation__r.Name.equalsIgnoreCase(System.Label.Ossia_Organisation_Name)){
                   isOssia= true;  
               }
            discountAmount =0;
            subTotal =0;
            if(creditMemo.Credit_memo_line_items__r != null && creditMemo.Credit_memo_line_items__r.size() > 0){
                for(Credit_memo_line_item__c objlineitem : creditMemo.Credit_memo_line_items__r){
                    if(objlineitem.Is_Discount__c){
                        discountAmount+=objlineitem.Amount__c;   
                    }else{
                        subTotal+=objlineitem.Amount__c;
                    }
                    
                }
            }
            if(discountAmount != 0){
                discountAmount = BillingUtility.roundOffAmount(discountAmount);
            }
            if(subTotal != 0){
                subTotal = BillingUtility.roundOffAmount(subTotal);
            }
            
            // By Ravi
            ParentAccId= creditMemo.Parent_Account__c;
            if(String.isNotBlank(creditMemo.Status__c))
                InvoiceStatus = creditMemo.Status__c;
            InvoiceId=creditMemo.Id;
            customLabelValue = System.Label.Aureus_Site;
            if(String.isNotBlank(creditMemo.Parent_Account__r.Card_Number__c))
                displayUpdate = true;
            else
                displayUpdate = false;
            // By Ravi
            if(String.isNotBlank(creditMemo.Center__r.Name))
                center.name = creditMemo.Center__r.Name;
            if(creditMemo.Center__r.Phone != null){
                center.phone = creditMemo.Center__r.Phone;
            }   
            if(creditMemo.Center__r.Center_Email__c != null){
                center.email = creditMemo.Center__r.Center_Email__c;
            }  
            if(creditMemo.Center__r.Website != null){
                center.website  = creditMemo.Center__r.Website;
            }
            center.address = creditMemo.Center__r.Billingstreet != null? creditMemo.Center__r.Billingstreet:'';
            center.address += creditMemo.Center__r.BillingCity != null ? ' '+creditMemo.Center__r.BillingCity : '';
            center.address += creditMemo.Center__r.BillingState != null ? ' '+creditMemo.Center__r.BillingState : '';
            center.address += creditMemo.Center__r.BillingPostalcode != null ? ' '+creditMemo.Center__r.BillingPostalcode : '';
            invoice = creditMemo.Invoice_Number__r;
            if(String.isNotBlank(creditMemo.Invoice_Number__c)){
                invoiceNo = creditMemo.Invoice_Number__r.Name;
            }
            frominvoice = creditMemo.From_Invoice__r;
            if(String.isNotBlank(creditMemo.From_Invoice__c)){
                frominvoiceNo = creditMemo.From_Invoice__r.Name;
            }
        }
    }
    public class centerInfo{
        public string phone {get;set;}
        public string email {get;set;}
        public string name {get;set;}
        public string address {get;set;}
        public string website {get;set;}
    }
    
}