force-app/main/default/objects/Account/fields/Employee_Duty_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Duty_Type__c</fullName>
    <label>Employee Duty Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Duty</fullName>
            </value>
            <value>
                <fullName>Non-Duty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Probation</fullName>
            </value>
            <value>
                <fullName>Confirm</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Manager</fullName>
            </value>
            <value>
                <fullName>Chauffeur</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Operations Officer</fullName>
            </value>
            <value>
                <fullName>Cleaner</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Director of Operations</fullName>
            </value>
            <value>
                <fullName>Finance Executive</fullName>
            </value>
            <value>
                <fullName>HR Payroll Executive</fullName>
            </value>
            <value>
                <fullName>Head of Piano Department</fullName>
            </value>
            <value>
                <fullName>Human Resource Manager</fullName>
            </value>
            <value>
                <fullName>Instrument Technician</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Music Instructor</fullName>
            </value>
            <value>
                <fullName>Music Teacher</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Teacher</fullName>
            </value>
            <value>
                <fullName>Sales Executive</fullName>
            </value>
            <value>
                <fullName>Sales and Operations Executive</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Piano Technician</fullName>
            </value>
            <value>
                <fullName>Language Teacher</fullName>
            </value>
            <value>
                <fullName>HR Executive</fullName>
            </value>
            <value>
                <fullName>Assistant Director of Marketing</fullName>
                <isActive>false</isActive>
                <label>Assistant Director of Marketing</label>
            </value>
            <value>
                <fullName>Assistant Director of Product Management</fullName>
                <isActive>false</isActive>
                <label>Assistant Director of Product Management</label>
            </value>
            <value>
                <fullName>Associate Director of HR</fullName>
                <isActive>false</isActive>
                <label>Associate Director of HR</label>
            </value>
            <value>
                <fullName>Associate Director of IT and Operations</fullName>
                <isActive>false</isActive>
                <label>Associate Director of IT and Operations</label>
            </value>
            <value>
                <fullName>Director of Retail</fullName>
                <isActive>false</isActive>
                <label>Director of Retail</label>
            </value>
            <value>
                <fullName>Executive</fullName>
                <isActive>false</isActive>
                <label>Executive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Joining_Date__c.field-meta.xml
<CustomField>
    <fullName>Joining_Date__c</fullName>
    <label>Joining Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_Stage__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Stage__c</fullName>
    <label>Onboarding Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Onboarding_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {
    
    public static testMethod void testMethod1(){
        List<User> uList = [SELECT Id,Name FROM User Where id =: Label.B2BMA_Integration_UserId];
        if(uList.size() > 0){
            System.runAs(uList.get(0)){
                Account objCustmr=TestUtil.createAccount('Customer',True,True);
                objCustmr.PI_to_SF_Sync__pc = 'true';
                update objCustmr;
            }
        }
    }
    @isTest
    Private static void unitTest2(){
        Account objCustmr=TestUtil.createAccount('Customer',true,False);
        objCustmr.Employee_Status__c = 'Probation';
        objCustmr.Joining_Date__c = system.today();
        objCustmr.Employee_Duty_Type__c ='Duty';
        objCustmr.Job_Title__c = 'Chauffeur';
        insert objCustmr;
    }
    @isTest
    Private static void unitTest3(){
        try{
            Account objCustmr=TestUtil.createAccount('Customer',true,False);
            objCustmr.Employee_Status__c = 'Probation';
            insert objCustmr;
        }catch(exception e){
            
        }
    }
    @isTest
    Private static void unitTest4(){
        try{
            Account objCustmr=TestUtil.createAccount('Customer',true,False);
            objCustmr.Employee_Status__c = 'Probation';
            objCustmr.Joining_Date__c = system.today();
            insert objCustmr;
            objCustmr.Employee_Status__c = 'Confirm';
            update objCustmr;
        }catch(exception e){
            
        }
    }
    @isTest
    Private static void unitTest5(){
        try{
            Account objCustmr=TestUtil.createAccount('Customer',true,False);
            objCustmr.Employee_Status__c = 'Draft';
            objCustmr.Joining_Date__c = system.today();
            insert objCustmr;
            objCustmr.Employee_Status__c = 'Confirm';
            update objCustmr;
        }catch(exception e){
            
        }
    }
    
    @isTest
    Private static void unitTest6(){
        try{
            Account objCustmr=TestUtil.createAccount('Customer',true,False);
            objCustmr.Employee_Status__c = 'Draft';
            objCustmr.Joining_Date__c = system.today();
            objCustmr.Onboarding_Stage__c ='In Process';
            insert objCustmr;
            objCustmr.Onboarding_Stage__c = 'Completed';
            update objCustmr;
        }catch(exception e){
            
        }
    }
    
    @isTest
    Private static void unitTest7(){
        try{
            Account objCustmr=TestUtil.createAccount('Customer',true,False);
            objCustmr.Employee_Status__c = 'Draft';
            objCustmr.Joining_Date__c = system.today();
            objCustmr.Onboarding_Stage__c ='In Process';
            insert objCustmr;
            objCustmr.Onboarding_Stage__c = 'Completed';
            objCustmr.Employee_Duty_Type__c = 'Duty';
            update objCustmr;
        }catch(exception e){
            
        }
    }
    
    
}