force-app/main/default/objects/Account/fields/Field_1__c.field-meta.xml
<CustomField>
    <fullName>Field_1__c</fullName>
    <label>Field 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Gender</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Learning_Style__c.field-meta.xml
<CustomField>
    <fullName>Learning_Style__c</fullName>
    <label>Learning Style</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fun</fullName>
            </value>
            <value>
                <fullName>Exam</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Field_1__c.field-meta.xml
<CustomField>
    <fullName>Field_1__c</fullName>
    <label>Field 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Parent)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Make-up</fullName>
            </value>
            <value>
                <fullName>Audition</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Group Class</fullName>
            </value>
            <value>
                <fullName>Group Lesson</fullName>
            </value>
            <value>
                <fullName>Piano Viewing</fullName>
            </value>
            <value>
                <fullName>Busy / Place holder</fullName>
                <isActive>false</isActive>
                <label>Busy / Place holder</label>
            </value>
            <value>
                <fullName>Notice</fullName>
                <isActive>false</isActive>
                <label>Notice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking_Note__c/Booking_Note__c.object-meta.xml
<CustomObject>
    <label>Booking Note</label>
    <nameField>
        <displayFormat>BN-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Note__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Notes</relationshipLabel>
    <relationshipName>Booking_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Note__c/fields/Note_Created_By__c.field-meta.xml
<CustomField>
    <fullName>Note_Created_By__c</fullName>
    <label>Note Created By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Note__c/fields/Note_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Note_Created_Date__c</fullName>
    <label>Note Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Previous_Experience_if_any__c.field-meta.xml
<CustomField>
    <fullName>Previous_Experience_if_any__c</fullName>
    <label>Previous Experience (if any)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Pending Enrolment</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Booked</fullName>
            </value>
            <value>
                <fullName>Piano Viewing Completed</fullName>
            </value>
            <value>
                <fullName>Piano Rental Active</fullName>
            </value>
            <value>
                <fullName>Piano Termination In-Progress</fullName>
            </value>
            <value>
                <fullName>Piano Rental Terminated</fullName>
            </value>
            <value>
                <fullName>Piano Sold</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Enrolments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Instrument</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookingNotesBatch.cls
global class BookingNotesBatch implements Database.Batchable<sObject>{
    /*This class  creates notes   for all the Bookings with Type 'Trial' ANd Enrolment Type is Trial and enrolment Stage Booked And Requested */
 global Database.QueryLocator start(Database.BatchableContext bc){ 
     set<String> stage = new set<String>{'Requested','Booked'};
        String query = 'select Id,Student__r.PersonBirthdate,Booking_Date__c,Parent__r.Owner.Name,(select Id from ContentDocumentLinks ),(select Id from Booking_Notes__r ),Student__r.Gender__c,Enrolment__r.Previous_Experience_if_any__c,Student__r.Description,Enrolment__r.Learning_Style__c from Booking__c where Type__c=\'Trial\' And  Enrolment__r.Type__c = \'Trial\' And Enrolment__r.Stage__c in:stage limit 10';
        return Database.getQueryLocator(query); 
    }
    global void execute (Database.BatchableContext bc ,List<Booking__c> bookList){
        //system.debug('----'+bookList);
        //system.debug('----'+bookList[0].Booking_Notes__r);
        list<Booking__c> UpdateBookList = new list<Booking__c>();
        List<ContentDocumentLink> noteList = new list<ContentDocumentLink>();
        // For Portal: Booking Note Create List
        List<Booking_Note__c> BookingNoteList = new List<Booking_Note__c>();
        
        Map<Id,ContentNote> contentnote2insertmap = new Map<Id,ContentNote>();
        for(Booking__c bkObj :bookList){
            if(bkObj.ContentDocumentLinks.size() < 1){
                ContentNote cnt = new ContentNote();
                cnt.Content = Blob.valueof('Gender: '+ string.valueOf(bkObj.Student__r.Gender__c) +'<br>Birthday: '+ string.valueOf(bkObj.Student__r.PersonBirthdate) + '<br>Comments:' +string.valueOf(bkObj.Student__r.Description) +'<br>Previous Experience: '+ string.valueOf(bkObj.Enrolment__r.Previous_Experience_if_any__c)+ '<br>Learning Style: '+ string.valueOf(bkObj.Enrolment__r.Learning_Style__c) );
                cnt.Title = 'Initial Student Notes';
                contentnote2insertmap.put(bkObj.id,cnt);
            }
            if(bkObj.Booking_Notes__r.size() < 1){
                Booking_Note__c bkgObj = new Booking_Note__c(Booking__c=bkObj.Id,Note_Created_Date__c=bkObj.Booking_Date__c,Title__c='Initial Student Notes', Note_Created_By__c=bkObj.Parent__r.Owner.Name,
                                                             Description__c='Gender: '+ string.valueOf(bkObj.Student__r.Gender__c) +'<br>Birthday: '+ string.valueOf(bkObj.Student__r.PersonBirthdate) + '<br>Comments:' +string.valueOf(bkObj.Student__r.Description) +'<br>Previous Experience: '+ string.valueOf(bkObj.Enrolment__r.Previous_Experience_if_any__c)+ '<br>Learning Style: '+ string.valueOf(bkObj.Enrolment__r.Learning_Style__c)
                                                             );
				BookingNoteList.add(bkgObj);              
            }
        }
        
        if(contentnote2insertmap.values().size()>0)
            insert contentnote2insertmap.values();
        
        
       // system.debug('BookingNoteList'+BookingNoteList);
        for(Booking__c bkobj :bookList){
            //system.debug('bkobj.Id'+bkobj.Id);
            if(contentnote2insertmap.containskey(bkobj.id)){
                system.debug('----'+bkobj.id);
                ContentDocumentLink  clnk = new ContentDocumentLink();
                clnk.LinkedEntityId = bkobj.Id;
                clnk.ContentDocumentId = contentnote2insertmap.get(bkobj.id).Id;
                clnk.ShareType = 'I';
                noteList.add(clnk);
                bkobj.Field_1__c='Note Created on Trial Booking';
                UpdateBookList.add(bkobj);
            }
    }
        if(BookingNoteList.size()>0)
            insert BookingNoteList;
        //system.debug('BookingNoteList'+BookingNoteList[0].Id);
        if(noteList.size()>0){
            insert noteList;
            update UpdateBookList;
        }
    
}
    global void finish(Database.BatchableContext bc){
        System.debug('----Finish');
    }
}