force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Gender</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Camp__c/Camp__c.object-meta.xml
<CustomObject>
    <description>this object for manage camp class</description>
    <label>Camp</label>
    <nameField>
        <label>Camp  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Camp__c/fields/Early_Bird_Discount__c.field-meta.xml
<CustomField>
    <fullName>Early_Bird_Discount__c</fullName>
    <description>this field for manage discount if any user enrolled middle of Early Birds dates</description>
    <label>Early Bird Discount %</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Camp__c/fields/Early_Bird_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Early_Bird_End_Date__c</fullName>
    <description>this field for manage discount if any user enrolled date is less then this field</description>
    <label>Early Bird End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Camp__c/fields/Early_Bird_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Early_Bird_Start_Date__c</fullName>
    <description>this field for manage discount if any user enrolled date is greater then this field</description>
    <label>Early Bird Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CampPackagesDetailCtrl.cls
/**
 * name: CampPackagesDetailCtrl
 * date: 1-Feb-2020
 * Autho : jatin
 * desctiption: this controller show camp package details according to seleted camp Id
 * 
 */
public class CampPackagesDetailCtrl {
    Public String campId {get;set;} 
    public Account accountStudentObj{get;set;}
    public string stuPreExperience{get;set;}
    public string birthDate{get;set;}
    public boolean showDiscountAlert{get;set;}
    //Arpit/Junied 27-Aug-2020
    public boolean isOssia {get;set;}
    
    public CampPackagesDetailCtrl() {
        accountStudentObj = new Account();
        system.debug('is ossia -->'+ ApexPages.currentPage().getParameters().get('org'));
        //Arpit/Junied 27-Aug-2020
        isOssia = false;
        //Juneid 28 Aug 2020 Orgnization wise logic as per new Requierment
        if(String.isNotBlank(ApexPages.currentPage().getParameters().get('org'))){
            isOssia = ApexPages.currentPage().getParameters().get('org').equalsIgnoreCase('ossia') ? true : false;
        }
    }
    public Camp__c getCampDetails(){
        Camp__c campObj = new Camp__c ();
        system.debug('campId'+campId);
        showDiscountAlert = false;
        if(String.isNotBlank(campId)){
            List<Camp__c> listOfCamp = CampClassUtilityController.getCampList('',campId,'',new set<string>());
            if(listOfCamp != null && listOfCamp.size() > 0){
                campObj = listOfCamp[0];
                /*start : jatin: 4-mar-2020: When registerring for the camp, there should be a text above the packages for the early bird discount 
                                    then show alert. However, when the early bird discount does not apply, the text should not be appearing.*/
                if(system.today() >= campObj.Early_Bird_Start_Date__c && system.today() <= campObj.Early_Bird_End_Date__c 
                && campObj.Early_Bird_Discount__c != null &&  campObj.Early_Bird_Discount__c  > 0){
                    showDiscountAlert = true;
                } 
                /*end : jatin: 4-mar-2020: When registerring for the camp, there should be a text above the packages for the early bird discount 
                                    then show alert. However, when the early bird discount does not apply, the text should not be appearing.*/
            }
            
        }
        return campObj;
    }
    // get gender picklist
    public List<SelectOption> getAccoungGenderPicklist(){     
        return CampClassUtilityController.getPicklistValues('Account','Gender__c');
    }
   
}