force-app/main/default/objects/Account/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <label>Instrument</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Instrument</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holidays</fullName>
            </value>
            <value>
                <fullName>School trip</fullName>
            </value>
            <value>
                <fullName>Exams</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>Personal Reason</fullName>
            </value>
            <value>
                <fullName>Teacher MC</fullName>
            </value>
            <value>
                <fullName>Teacher Leave</fullName>
            </value>
            <value>
                <fullName>Admin Mistake</fullName>
                <isActive>false</isActive>
                <label>Admin Mistake</label>
            </value>
            <value>
                <fullName>Away</fullName>
                <isActive>false</isActive>
                <label>Away</label>
            </value>
            <value>
                <fullName>Cancelled Less than 24 hours</fullName>
                <isActive>false</isActive>
                <label>Cancelled Less than 24 hours</label>
            </value>
            <value>
                <fullName>No Show</fullName>
                <isActive>false</isActive>
                <label>No Show</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Centre)</relationshipLabel>
    <relationshipName>CenterBooking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <formula>Text(Package__r.Program__r.Instrument__c)</formula>
    <label>Instrument</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Parent)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to create lesson booking</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Existing Bookings</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <formula>TEXT( DAY(  Booking__r.Booking_Date__c  ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking Calendar Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <label>Instrument</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Instrument</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <description>To be used in reports
Booking: Package</description>
    <formula>Booking__r.Package__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/X24_hrs_cancellation_approved_Reject_by__c.field-meta.xml
<CustomField>
    <fullName>X24_hrs_cancellation_approved_Reject_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will indicate the name of the user that approved 24 hrs cancellation request</description>
    <label>24 hrs cancellation approved/Rejected by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/X24_Hrs_Cancellation_Request__c.field-meta.xml
<CustomField>
    <fullName>X24_Hrs_Cancellation_Request__c</fullName>
    <label>24 Hrs Cancellation Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <formula>TEXT( Program__r.Instrument__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instrument</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package__c/recordTypes/Lesson.recordType-meta.xml
<RecordType>
    <fullName>Lesson</fullName>
    <active>true</active>
    <description>Select this record type to setup package for music lesson</description>
    <label>Lesson</label>
</RecordType>

force-app/main/default/classes/ServiceRequestCancellationClass.cls
public class ServiceRequestCancellationClass {
    
    
    /*
    Name        :        ServiceRequestCancellationClass
    Author      :        Ravi Gupta
    Description :        It is the  class of .ServiceRequestCancellation
    */
    private static string serviceEnquiryRecordType=ConstantsClass.caseServiceEnqRecTypeName;
    
	@AuraEnabled
    public static list<Case> findCase(string searchKey){
         Id recorId = Schema.SObjectType.case.getRecordTypeInfosByName().get(serviceEnquiryRecordType).getRecordTypeId();
        list<Case> caseList =[SELECT Id,X24_Hrs_Cancellation_Request__c,Booking__c,Booking__r.Teacher_Account__r.Name,Booking__r.Teacher_Account__c,Booking__r.Start_Time__c,RecordTypeId,Booking__r.Name,Booking__r.Booking_Date__c,Booking__r.Parent__r.Name,Booking__r.Student__r.Name,Booking__r.Package__r.Name,Booking__r.Center__r.Name,Booking__r.Instrument__c,Booking__r.Status__c,Booking__r.Cancellation_Reason__c   FROM Case where Id=:searchKey AND RecordTypeId=:recorId AND (Subject='Lesson Cancellation within 24 hrs' OR Subject='Lesson Cancel within 24 hrs') AND Type='Lesson Cancel' AND Booking__c != null ];
        return caseList;
     
    }
    
    @AuraEnabled
    public static void updateCaseRequest(string actVal,string casId){
          list<Case> caseList = new list<Case>();
        
        if(actVal =='Confirm'){
            for(Case casobj:[SELECT Id,X24_Hrs_Cancellation_Request__c FROM Case WHERE Id=:casId ]){
                casobj.X24_Hrs_Cancellation_Request__c='Approved';
                casobj.X24_hrs_cancellation_approved_Reject_by__c=UserInfo.getUserId();
                caseList.add(casobj);                              
            }
            
        }else{
            for(Case casobj:[SELECT Id,X24_Hrs_Cancellation_Request__c FROM Case WHERE Id=:casId ]){
                casobj.X24_Hrs_Cancellation_Request__c='Rejected';
                casobj.X24_hrs_cancellation_approved_Reject_by__c=UserInfo.getUserId();
                caseList.add(casobj);                              
            }
        }
        if(caseList.size()>0){
            update caseList;   
        }
        
    }
}