force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holidays</fullName>
            </value>
            <value>
                <fullName>School trip</fullName>
            </value>
            <value>
                <fullName>Exams</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>Personal Reason</fullName>
            </value>
            <value>
                <fullName>Teacher MC</fullName>
            </value>
            <value>
                <fullName>Teacher Leave</fullName>
            </value>
            <value>
                <fullName>Admin Mistake</fullName>
                <isActive>false</isActive>
                <label>Admin Mistake</label>
            </value>
            <value>
                <fullName>Away</fullName>
                <isActive>false</isActive>
                <label>Away</label>
            </value>
            <value>
                <fullName>Cancelled Less than 24 hours</fullName>
                <isActive>false</isActive>
                <label>Cancelled Less than 24 hours</label>
            </value>
            <value>
                <fullName>No Show</fullName>
                <isActive>false</isActive>
                <label>No Show</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centre</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Centre)</relationshipLabel>
    <relationshipName>CenterBooking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>TEXT(Center__r.Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Parent)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>No-show</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Make-up</fullName>
                <isActive>false</isActive>
                <label>Make-up</label>
            </value>
            <value>
                <fullName>Makeup Pending</fullName>
                <isActive>false</isActive>
                <label>Makeup Pending</label>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
                <isActive>false</isActive>
                <label>Rescheduled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Teacher_Account__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher,Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leave Requests</relationshipLabel>
    <relationshipName>Leave_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TeacherLeaveReminder.cls
global class TeacherLeaveReminder implements Database.Batchable<sObject>{
    private Date  reqDate=system.today().addDays(7);
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'Select Id,Leave_Start_Date__c,Leave_End_Date__c,Employee__c From Leave_Request__c where Leave_Start_Date__c<=:reqDate AND Leave_End_Date__c >=:reqDate';
        return Database.getQueryLocator(query); 
      
    }
    global void execute (Database.BatchableContext bc ,List<sObject> recordsList){
        list<Booking__c> BookingList = new list<Booking__c>();
        set<String> cancellationReason = new set<String>{'Teacher MC','Teacher Leave'};
        system.debug('----'+recordsList);
        set<Date> leaveStartDate = new set<Date>();
        set<Date> leaveEndDate = new set<Date>();
        list<Leave_Request__c> leaveReqList =(list<Leave_Request__c>)recordsList;
        // store teacher Id with start  date  and end date
        Map<ID,Date> mapToTeacher = new  Map<Id,Date>();
        list<EmailTemplate> templateList= new list<EmailTemplate>();
        for(Leave_Request__c leavReqObj:leaveReqList){
            mapToTeacher.put(leavReqObj.Employee__c,reqDate);
            leaveStartDate.add(reqDate);
        }
        string templateId='';
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        templateList = [Select Id from EmailTemplate where name = 'Teacher Leave Reminder' limit 1];
        if(templateList[0].Id != null){
            templateId = templateList[0].Id;  
        }
        BookingList=[Select Id,Name,Teacher_Account__r.Name,Parent__r.PersonContactId,Center__r.Location__c,Parent__r.PersonEmail,Booking_Date__c,Teacher_Account__c from Booking__c where Teacher_Account__c =:mapToTeacher.keySet() and Status__c='Canceled' and Cancellation_Reason__c in:cancellationReason and  Booking_Date__c =: leaveStartDate];
        //system.debug('===---'+BookingList);
        for(Booking__c bkgList:BookingList){
            if(bkgList.Booking_Date__c == mapToTeacher.get(bkgList.Teacher_Account__c) && mapToTeacher.containsKey(bkgList.Teacher_Account__c) ){
                if(String.isNotBlank(templateId) && bkgList.Parent__r.PersonContactId != null && bkgList.Parent__r.PersonEmail != null){
                    Messaging.SingleEmailMessage mail = AureusUtility.getSingleEmailMessage(templateId, bkgList.Parent__r.PersonContactId, bkgList.Id, bkgList.Center__r.Location__c);
                    emailList.add(mail);
                }
            } 
        }
        
        if(emailList.size()>0){
            for(Messaging.SendEmailResult results :Messaging.sendEmail(emailList,false)){
                if(!results.isSuccess())
                    system.debug(results.getErrors());
            }  
            //Messaging.sendEmail(emailList); 
        }
        
    }
    global void finish(Database.BatchableContext bc){
        System.debug('----Finish');
    }
}