force-app/main/default/objects/Account/fields/MovedToSage__c.field-meta.xml
<CustomField>
    <fullName>MovedToSage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MovedToSage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <summarizedField>Invoice__c.Total_Invoice_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice__c.Status__c</field>
        <operation>equals</operation>
        <value>Due, Paid</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice__c.Parent_Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SageCustomerPushBatchTest.cls
/*
 * By Shalini Singh
 */
@istest
public class SageCustomerPushBatchTest {
    
     @isTest
    public static void test2(){
        //Invoice__c inv = SageIntacctIntegrationUtility.createInvoice(new SageIntacctIntegrationUtility.sessionWrapper(),new Invoice__c());
        Account acc=new Account();
        acc.LastName='XYZ';
        acc.RecordTypeId=schema.SObjectType.Account.getRecordTypeInfosByName().get(ConstantsClass.customerRecTypeName).getRecordTypeId();
        acc.MovedToSage__c=false;
        insert acc;
        Account acc2= new Account();
        acc2.LastName='PQR';
        insert acc2;
        
        Invoice__c inv = new Invoice__c();
        inv.Total_Invoice_Amount__c = 100;
        inv.Parent_Account__c = acc.id;
        inv.Status__c ='Due';
        insert inv;
        
        set<String> accidSet=new Set<String>();
        accidSet.add(acc.id);
        accidSet.add(acc2.id);
  
        Test.startTest();
        SageCustomerPushBatch obj = new SageCustomerPushBatch(accidSet);
        SageCustomerPushBatch obj1 = new SageCustomerPushBatch();
        ID batchprocessid = Database.executeBatch(obj);
        ID batchprocessid1 = Database.executeBatch(obj1);
        test.stopTest();
    }
  
   
}