force-app/main/default/objects/Account/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Sage_Company__c.field-meta.xml
<CustomField>
    <fullName>Sage_Company__c</fullName>
    <label>Sage Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGP</fullName>
            </value>
            <value>
                <fullName>AGH</fullName>
            </value>
            <value>
                <fullName>OMS</fullName>
            </value>
            <value>
                <fullName>ACP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Stripe_Payout_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Payout Id</label>
    <referenceTo>Stripe_Payout_Log__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sage_GL_Account__c/Sage_GL_Account__c.object-meta.xml
<CustomObject>
    <label>Sage GL Account</label>
    <nameField>
        <label>Sage GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sage GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sage_GL_Account__c/fields/GL_Account_No__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_No__c</fullName>
    <label>GL Account No</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sage_Intacct_Credentials__c/Sage_Intacct_Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Sage intacct credentials</description>
    <label>Sage Intacct Credentials</label>
</CustomObject>

force-app/main/default/objects/Stripe_Payout_Log__c/Stripe_Payout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object will store the Payout logs whenever the payout is created in the stripe.</description>
    <label>Stripe Payout Log</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Stripe Payout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Payout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Stripe Payout Logs</relationshipLabel>
    <relationshipName>Stripe_Payout_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This Field will store the Status of the payout object in stripe.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unprocessed</fullName>
                <default>true</default>
                <label>Unprocessed</label>
            </value>
            <value>
                <fullName>Processed in SF</fullName>
            </value>
            <value>
                <fullName>Posted in Sage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Stripe_Payout_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Id__c</fullName>
    <description>This Field will store the Stripe Payout Id from the Stripe</description>
    <label>Stripe Payout Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SageStripePayoutPushBatchTest.cls
@isTest
public class SageStripePayoutPushBatchTest {

    @isTest
      public static void test1(){

  
        Test.startTest();
        SageStripePayoutPushBatch obj = new SageStripePayoutPushBatch();
        ID batchprocessid = Database.executeBatch(obj);
        test.stopTest();
    }
    
     @isTest
    public static void test2(){
		Sage_Intacct_Credentials__c sic = new Sage_Intacct_Credentials__c();
        sic.Name='test';
        sic.Endpoint__c='https://api.intacct.com/ia/xml/xmlgw.phtml';
        insert sic;
        
        List<Sage_GL_Account__c> sgaList = new List<Sage_GL_Account__c>();
        for(integer i=0;i<=3;i++){
            Sage_GL_Account__c sga = new Sage_GL_Account__c();
            if(i==0){
                sga.Name='Merchandise Card Receivable';
            }
            else if(i==1){
                sga.Name='Accounts Payable'; 
                sga.GL_Account_No__c='qwerty';
            }
            else if(i==2){
                sga.Name='AGP Cash at Bank - OCBC';
            }
            else{
                sga.Name='Merchant Account Fees';
            }
            sga.GL_Account_No__c=''+i;
            sgaList.add(sga) ;
        }
        insert sgaList;
       
        Organisation__c org = new Organisation__c();
        org.Sage_Company__c = 'AGP';
        insert org;
        Stripe_Payout_Log__c spl = new Stripe_Payout_Log__c();
        spl.Status__c = 'Processed in SF';
        spl.Organisation__c= org.id;
        insert spl;
        Account cust = TestUtil.createAccount('Customer',TRUE,TRUE);
        Payment__c pay = new Payment__c();
        pay.Parent_Account__c = cust.id;
        pay.Payment_Status__c ='Success';
        pay.Payment_Amount__c = 105;
        pay.Stripe_Payout_Id__c = spl.Id;
        insert pay;
        
        set<Id> invidSet=new Set<Id>();
        invidSet.add(spl.id);
  
        Test.startTest();
        SageStripePayoutPushBatch obj = new SageStripePayoutPushBatch(invidSet);
        ID batchprocessid = Database.executeBatch(obj);
  
         Database.executeBatch(new SageStripePayoutPushBatch());
        test.stopTest();
    }
  
}