force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceReminderSchedularTest.cls
/*
Name        :        InvoiceReminderSchedularTest
Date        :        2 April 2019
Author      :        Karan Singh Soni
Description :        It is the test class of InvoiceReminderSchedular.
*/
@isTest
public class InvoiceReminderSchedularTest {

    public static testmethod void invokeInvoiceReminderSchedular(){
        Account objCustmr=TestUtil.createAccount('Customer',True,True);
        Invoice__C objINV=TestUtil.createInvoice(objCustmr.Id,False);
        objINV.Due_Date__c=Date.today().addDays(-3);
        objINV.Status__c='Due';
        insert objINV;
        InvoiceReminderSchedular objIRS=new InvoiceReminderSchedular();
        //string seh='0 0 23 *h * ?';
        //system.schedule('Test Status Check', seh,objIRS);
              
       // it will directly call schedular execute method to invoke batch class without cron expression
        objIRS.execute(null);
      
    }
}