force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/Expense_Claim__c.object-meta.xml
<CustomObject>
    <label>Expense Claim</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Claim__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expense Claims</relationshipLabel>
    <relationshipName>Expense_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Partial Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/Expense_Item__c.object-meta.xml
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>EI-{00000}</displayFormat>
        <label>Expense Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Total Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Expense_Claim__c.field-meta.xml
<CustomField>
    <fullName>Expense_Claim__c</fullName>
    <label>Expense Claim</label>
    <referenceTo>Expense_Claim__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <referenceTo>Expense_Type__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Types</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Type__c/Expense_Type__c.object-meta.xml
<CustomObject>
    <label>Expense Type</label>
    <nameField>
        <label>Expense Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Type</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomExpenseItemPageControllerTest.cls
/*
    Name : CustomExpenseItemPageControllerTest
    Date : 07 October 2019
    Author :
    Description: 
*/

@isTest
public class CustomExpenseItemPageControllerTest{
    @isTest
    public static void validateCustomExpenseItemPageController(){
        Account acc = new Account(LastName = 'test');
        insert acc;
        
        Expense_Type__c expType = new Expense_Type__c(Name = 'Test');
        insert expType;
        
        Expense_Claim__c expClaim = new Expense_Claim__c(Employee__c = acc.id, Status__c = 'Pending');
        insert expClaim;
        
        Expense_Item__c expItem = new Expense_Item__c(Expense_Claim__c = expClaim.Id, Expense_Type__c = expType.Id, Status__c = 'Pending', Amount__c = 100);
        insert expItem;
        
        Expense_Item__c expItem2 = new Expense_Item__c(Expense_Claim__c = expClaim.Id, Expense_Type__c = expType.Id, Status__c = 'Pending', Amount__c = 200);
        insert expItem2;
        
        PageReference pageRef = Page.CustomExpenseItemPage;
        pageRef.getparameters().put('id', expClaim.id);  
        Test.setCurrentPage(pageRef);
        
        Apexpages.StandardController sc = new Apexpages.StandardController(expClaim);
        CustomExpenseItemPageController ext = new  CustomExpenseItemPageController(sc);      
        ext.fetchExpItems();
        ext.getIsCurrentUserApprover();
        
        Integer i = 0;
        for(CustomExpenseItemPageController.ExpItem expItmWrapperObj: ext.expItemList){
            if(i==0)
                expItmWrapperObj.approvalAction = true;
            else
                expItmWrapperObj.approvalAction = false;
            i++;
        }
        
        ext.saveChanges();
        
        Expense_Item__c expItem3 = new Expense_Item__c(Expense_Claim__c = expClaim.Id, Expense_Type__c = expType.Id, Status__c = 'Pending');
        insert expItem3;
        
        expClaim.Status__c = 'Approved';
        update expClaim;
        
        expClaim.Status__c = 'Rejected';
        update expClaim;
        ext.getExpenseTypePL();
        ext.getSupplierPL();
        ext.saveChanges();
    }
    
}