force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Not-working</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Centre.recordType-meta.xml
<RecordType>
    <fullName>Centre</fullName>
    <active>true</active>
    <description>Select this record type to create a Centre</description>
    <label>Centre</label>
</RecordType>

force-app/main/default/objects/Enrolment__c/Enrolment__c.object-meta.xml
<CustomObject>
    <label>Enrolment</label>
    <nameField>
        <label>Enrolment No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrolments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrolment__c/fields/Next_Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Bill_Date__c</fullName>
    <formula>prepayment_period_end_date__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipName>Enrolments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Status__c</fullName>
    <label>Advance Action Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrolment__c/fields/Package_Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Package_Process_Type__c</fullName>
    <label>Advance Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Enrolment Change</fullName>
            </value>
            <value>
                <fullName>Centre Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrolment__c.field-meta.xml
<CustomField>
    <fullName>Enrolment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrolment</label>
    <referenceTo>Enrolment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Next_Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Bill_Date__c</fullName>
    <label>Next Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Plan_Package__c.field-meta.xml
<CustomField>
    <fullName>Plan_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan/Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subscription_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PackageProcessHandlerTest.cls
/*
Name        :        PackageProcessHandlerTest
Date        :        8 April 2019
Remodified  :		 24 June 2019
Author      :        Karan Singh Soni
Description :        It is the test class of PackageProcessHandler.
*/

@isTest
public class PackageProcessHandlerTest {
    
    public static testmethod void invokePackageProcessHandler(){
        Account objCustmr=TestUtil.createAccount('Customer',True,True);
        Account objCentr=TestUtil.createAccount('Centre',False,true);
        Account objtechr=TestUtil.createAccount('Teacher',False,true);
        Program__C objProg=TestUtil.createProgram('Active','Piano',true);
        Package__c objPack=testUtil.createPackage(objProg.id,objCentr.id,'60',true);        
        Enrolment__c objENrol=TestUtil.createEnrolment(objCentr.Id,objTechr.Id,objCustmr.Id,objPack.id,false);
        objENrol.Package_Process_Status__c='Pending';
        objENrol.Package_Process_Type__c='Downgrade';
        objENrol.Effective_Date__c=date.today();
        insert objENrol;
        
        Subscription__C objSubs=TestUtil.createSubscription(objCustmr.Id,False);
        objSubs.Status__c='Active';
        objSubs.Subscription_Start_Date__c=date.today().adddays(-5);
        objSubs.Next_Bill_Date__c=date.today().adddays(-5);
        insert objSubs;
        
        Subscription_Line_Item__c objSubsLine=TestUtil.createSubscriptionLineItem(objSubs.Id,False);
        objSubsLine.Enrolment__c=objEnrol.id;
        objSubsLine.Plan_Package__c=objPack.id;
        objSubsLine.Status__c='Active';
        objSubsLine.Next_Bill_Date__c=date.today().adddays(-5);
        insert objSubsLine;
        
        List<Subscription_Line_Item__c> listOfSubLineItems=[SELECT Id,ENrolment__c,Enrolment__r.Package_Process_type__c,
                                                            Enrolment__r.Package_Process_Status__c,
                                                            Enrolment__r.effective_date__c
                                                            FROM Subscription_Line_Item__c];
            
            //new List<Subscription_Line_Item__c>();
       // listOfSubLineItems.add(objSubsLine);
        
        Invoice__C objInv=Testutil.createInvoice(objCustmr.Id,true);
        
        PackageProcessHandler objPackProcess=new PackageProcessHandler(objInv,listOfSubLineItems,date.today(),date.today());
        
        objENrol.Package_Process_Type__c='Upgrade';
        update objENrol;
        
        listOfSubLineItems=[SELECT Id,ENrolment__c,Enrolment__r.Package_Process_type__c,
                                                            Enrolment__r.Package_Process_Status__c,
                                                            Enrolment__r.effective_date__c
                                                            FROM Subscription_Line_Item__c];
        PackageProcessHandler objPackProcess2=new PackageProcessHandler(objInv,listOfSubLineItems,date.today(),date.today());
        objENrol.Package_Process_Type__c='Cancellation';
        update objENrol;
        listOfSubLineItems=[SELECT Id,ENrolment__c,Enrolment__r.Package_Process_type__c,
                                                            Enrolment__r.Package_Process_Status__c,
                                                            Enrolment__r.effective_date__c
                                                            FROM Subscription_Line_Item__c];
        PackageProcessHandler objPackProcess3=new PackageProcessHandler(objInv,listOfSubLineItems,date.today(),date.today());
        
    }
}