force-app/main/default/objects/Account/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <label>Stripe Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceAttachmentBatchTest.cls
/*
Name        :        InvoiceAttachmentBatchTest
Date        :        31st May 2019
Description :        It is the test class of InvoiceAttachmentBatch.
*/
@isTest
public class InvoiceAttachmentBatchTest {
    @isTest
    public static void invokeInvoiceAttachmentBatch(){
        Account objCustmr=TestUtil.createAccount('Customer',True,false); 
        objCustmr.personEmail = 'test@tmc.com';
        objCustmr.Stripe_Customer_Id__c='ch_1AxWbTFytruJp2FXW6iuRd1X';
        INSERT objCustmr;
        
        Invoice__c invoiceObj = TestUtil.createInvoice(objCustmr.Id, true);
        Set<String> invoices = new Set<String>();
        invoices.add(invoiceObj.Id);
        InvoiceAttachmentBatch obj = new InvoiceAttachmentBatch(invoices);
        Database.executeBatch(obj,200);
        
    }
    
}