force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>Sub-Item-{0000}</displayFormat>
        <label>Subscription Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subscription_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/subscriptionLineItemTriggerHelper.cls
public class subscriptionLineItemTriggerHelper{
    
    public static void checkStatus(Set<ID> subscriptionIDSet){
        Map<String, List<Subscription_Line_Item__c>> mapOfSubLineItem = new Map<String,List<Subscription_Line_Item__c>>();
        List<Subscription__c> listOfSubsToUpd = new List<Subscription__c>();
       for(Subscription_Line_Item__c objSubLineItem : [SELECT Id,Subscription__c FROM Subscription_Line_Item__c WHERE Subscription__c IN:subscriptionIDSet 
                                                        AND Status__c !=: ConstantsClass.statusInActive]){
            List<Subscription_Line_Item__c> listOfLineItems = mapOfSubLineItem.containsKey(objSubLineItem.Subscription__c) ? 
                                                                mapOfSubLineItem.get(objSubLineItem.Subscription__c) : new List<Subscription_Line_Item__c>();    
            listOfLineItems.add(objSubLineItem);
            mapOfSubLineItem.put(objSubLineItem.Subscription__c,listOfLineItems);    
        }
        System.debug('subscriptionIDSet'+subscriptionIDSet);
        System.debug('mapOfSubLineItem'+mapOfSubLineItem);
        for(String subsId : subscriptionIDSet){
            if(!mapOfSubLineItem.containsKey(subsId)){
                listOfSubsToUpd.add(new Subscription__c(Id= subsId,Status__c = ConstantsClass.statusInActive));        
            }else{
                listOfSubsToUpd.add(new Subscription__c(Id= subsId,Status__c = ConstantsClass.activeStatus));        
            }
        }
        if(listOfSubsToUpd.size() > 0){
            UPDATE listOfSubsToUpd;
        }
        
    }
}