force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount__c</fullName>
    <description>This field is used to store amount received against the invoice</description>
    <inlineHelpText>Amount received</inlineHelpText>
    <label>Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Stripe_fees__c.field-meta.xml
<CustomField>
    <fullName>Stripe_fees__c</fullName>
    <label>Stripe fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Stripe_Payout_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Payout Id</label>
    <referenceTo>Stripe_Payout_Log__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/Stripe_Payout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object will store the Payout logs whenever the payout is created in the stripe.</description>
    <label>Stripe Payout Log</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Stripe Payout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Payout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Stripe_Fee_charged__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Fee_charged__c</fullName>
    <description>This Field will store the Total Stripe Fee charged by the Stripe per payout.</description>
    <label>Stripe Fee charged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Stripe_Payout_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Id__c</fullName>
    <description>This Field will store the Stripe Payout Id from the Stripe</description>
    <label>Stripe Payout Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentTriggerHandler.cls
/**
 * Name         :       PaymentTriggerHandler
 * Date         :       21 June 2019
 * Author       :       
 * Description  :       To Updaet Invoice Paid Amount from Payment whose record type os PaymentAsCredit or PaymentAs Deposit
*/
public Class PaymentTriggerHandler{
    public static void transferToInvoice( List<Payment__c> payments ){
        List<Invoice__c> paymentInvoice = new List<Invoice__c>();
        Set<Id> listInvoiceIds = new Set<Id>();
        Id paymentDepositId = Schema.SObjectType.Payment__c.getRecordTypeInfosByName().get(ConstantsClass.paymentAsDepositRecordType).getRecordTypeId();
        Id paymentCreditId = Schema.SObjectType.Payment__c.getRecordTypeInfosByName().get(ConstantsClass.paymentAsCredit).getRecordTypeId();
        Id paymentTransactionId = Schema.SObjectType.Payment__c.getRecordTypeInfosByName().get(ConstantsClass.paymentTransactionRecType).getRecordTypeId();
        for( Payment__c payment : payments ){
            if( ( payment.RecordTypeId == paymentDepositId || payment.RecordTypeId == paymentCreditId || 
                  payment.RecordTypeId == paymentTransactionId ) && 
                payment.Invoice__c != NULL){
                listInvoiceIds.add(payment.Invoice__c); 
            }
        }
        system.debug('listInvoiceIds'+listInvoiceIds);
        if( listInvoiceIds != NULL && listInvoiceIds.size() > 0 ){
            for( AggregateResult aggRes : [ SELECT Invoice__c, SUM(Payment_Amount__c) total FROM Payment__c WHERE Invoice__c IN: listInvoiceIds GROUP BY invoice__c ] ){
                Invoice__c invoice = new Invoice__c( Id = (Id)aggRes.get('Invoice__c') );
                invoice.Paid_Amount__c = aggRes.get('total') != NULL ? (Decimal)aggRes.get('total') : 0;
                paymentInvoice.add( invoice );
                listInvoiceIds.remove( (Id)aggRes.get('Invoice__c') );
            }  
            //if invoice has left with no payment record then set paid amount to 0
            for( Id invoiceId : listInvoiceIds){
                paymentInvoice.add( new Invoice__c( Id = invoiceId, Paid_Amount__c = 0 ) );
            }
            system.debug('paymentInvoice'+paymentInvoice);
            if( paymentInvoice != NULL && paymentInvoice.size() > 0 ){
                
                UPDATE paymentInvoice;
            }
        }
    }

    //@Jatin 10/22/2019, Add the work due to stripe payout log
    public static void rollUpStripePayoutFees(Set<String> stripePayoutIds){
        List<Stripe_Payout_Log__c> payoutLogList = new List<Stripe_Payout_Log__c>();
        if(stripePayoutIds.size() > 0){

            List<AggregateResult> paymentAggregateList = [SELECT SUM(Stripe_fees__c) fees, Stripe_Payout_Id__c FROM Payment__c WHERE Stripe_Payout_Id__c IN :stripePayoutIds GROUP BY Stripe_Payout_Id__c];
			system.debug('paymentAggregateList'+paymentAggregateList);
            for(AggregateResult paymentAggregate : paymentAggregateList){
                payoutLogList.add(new Stripe_Payout_Log__c(Id = String.valueOf(paymentAggregate.get('Stripe_Payout_Id__c')), Stripe_Fee_charged__c = Double.valueOf(paymentAggregate.get('fees'))));
            }
        }
        system.debug('payoutLogList'+payoutLogList);
        if(payoutLogList.size() > 0){
            UPDATE payoutLogList;
        }
    }
}