force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Inv-Item-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddCreditMemoController.cls
public with sharing class AddCreditMemoController {
  @AuraEnabled(cacheable=true)
  public static creditMemoWrap getCreditMemoDetails(Id invId) {
    system.debug('invId --> ' + invId);
    creditMemoWrap objCreditMemoWrap = new creditMemoWrap();

    // prettier-ignore
    if ( String.isBlank(invId) || invId.getSobjectType() != Schema.Invoice__c.SObjectType) {

    objCreditMemoWrap.isError = 'Invalid Invoice Id';
    return objCreditMemoWrap;

  } else {

    // prettier-ignore
    for (Invoice__c objInv : [ SELECT Id,Status__c, 
                    (SELECT ID, Amount__c FROM Invoice_Line_Items__r WHERE Amount__c > 0) 
                    FROM Invoice__c 
                    WHERE ID = :invId ]) {
                      
                      objCreditMemoWrap.invoiceStatus = objInv.Status__c;
                      objCreditMemoWrap.objInvoice = objInv;
                      if( objInv.Invoice_Line_Items__r.size() > 0 ){
                        
                        for( Invoice_Line_Item__c objInvLine : objInv.Invoice_Line_Items__r ){

                          system.debug('objInvLine.Amount__c --> ' + objInvLine.Amount__c);
                          objCreditMemoWrap.invoiceAmount += objInvLine.Amount__c;
                        }
                        
                      }
                    }
                    system.debug('objCreditMemoWrap.invoiceAmount --> ' + objCreditMemoWrap.invoiceAmount );
  }
    return objCreditMemoWrap;
  }

  @AuraEnabled(cacheable=true)
  public static String createCreditMemo(
    String userAmount,
    creditMemoWrap creditWrap,
    String creditMode,
    String remarks
  ) {
    if (creditMode == 'Refund Memo') {
      //will call the stripe after confimation
    } else if (creditMode == 'Credit Memo (Future Adj)') {
      if (creditWrap.invoiceAmount == Decimal.valueOf(userAmount)) {
      } else {
      }
    } else if (creditMode == 'Credit Memo (Invoice Cancellation)') {
      if (creditWrap.invoiceAmount == Decimal.valueOf(userAmount)) {
      } else {
      }
    }

    return 'success';
  }
  public class creditMemoWrap {
    @AuraEnabled
    public Decimal invoiceAmount;
    @AuraEnabled
    public Decimal existCreditAmount;

    @AuraEnabled
    public String invoiceStatus;
    @AuraEnabled
    public Invoice__c objInvoice;
    @AuraEnabled
    public String isError;

    public creditMemoWrap() {
      invoiceAmount = 0;
      existCreditAmount = 0;
      objInvoice = new Invoice__c();
      isError = '';
      invoiceStatus = '';
    }
  }
}