force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Center)</relationshipLabel>
    <relationshipName>Center_Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <summarizedField>Invoice_Line_Item__c.Discount_Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Inv-Item-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>IF(ISBLANK( Subscription_Line_Item__c ), Booking__r.Center__r.Name+&apos; &apos;+ Booking__r.Center__r.LastName , Subscription_Line_Item__r.Enrolment__r.Center__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <description>This Field is used to manage Gst on invoice line item individually</description>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>Invoice__r.Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Is_Deposit__c.field-meta.xml
<CustomField>
    <fullName>Is_Deposit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deposit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TempUpdateGstAmtInLnitmRecords.cls
global class TempUpdateGstAmtInLnitmRecords implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc){ 
        //
        String query = 'SELECT id,name,invoice_date__c,Amount__c,Discount_Amount__c,Is_Deposit__c,Field_1__c'+ 
                                     ' FROM invoice_Line_item__c '+
                                     ' WHERE invoice__r.Center__r.Country__r.name = \'SG\' '+
                                     ' AND Is_Deposit__c = False AND Amount__c != null '+
                                     ' AND invoice_date__c >= 2019-07-01 order by Id';
        return Database.getQueryLocator(query); 
    }
    global void execute (Database.BatchableContext bc ,List<invoice_Line_item__c> invList){
        Decimal tempGstPrcntg = 7;
        for(invoice_Line_item__c invLnItm: invList){
            Decimal tempTotAmt = invLnItm.Amount__c; 
            tempTotAmt = invLnItm.Discount_Amount__c > 0 ? (tempTotAmt-invLnItm.Discount_Amount__c): tempTotAmt; 
            invLnItm.GST_Amount__c = BillingUtility.roundOffAmount(tempTotAmt != 0 ? ((tempTotAmt * tempGstPrcntg) / 100):0);
            invLnItm.Field_1__c = invLnItm.Field_1__c +'-- updated Gst Amount on '+System.today()+'.';
        }
        
        update invList;
    }
    global void finish(Database.BatchableContext bc){
        System.debug('----Finish');
    }
}