force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/voidInvoicecontrollerTest.cls
/*
    Name            :   voidInvoicecontrollerTest
    Date            :   22 May 2019
    Author          :   Karan Singh Soni
    Description     :   This test class is used for void and delete process of invoice.
*/
@isTest
public class voidInvoicecontrollerTest {
    public static TestMethod void invokevoidInvoicecontroller(){
        Invoice__c objInv = new Invoice__c();
        objInv.Parent_Account__c=TestUtil.createAccount('Customer', True, True).id;
        insert objInv;
        
        VoidInvoiceController.processInvoice(objInv.Id, 'void','Test');
    }
    public static TestMethod void invokevoidInvoicecontroller2(){
        Invoice__c objInv = new Invoice__c();
        objInv.Parent_Account__c=TestUtil.createAccount('Customer', True, True).id;
        insert objInv;
        
        VoidInvoiceController.processInvoice(objInv.Id, 'delete','');
    }
}