force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Payout_Log__c/Stripe_Payout_Log__c.object-meta.xml
<CustomObject>
    <description>This Object will store the Payout logs whenever the payout is created in the stripe.</description>
    <label>Stripe Payout Log</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Stripe Payout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Payout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Stripe Payout Logs</relationshipLabel>
    <relationshipName>Stripe_Payout_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This Field will store the Status of the payout object in stripe.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unprocessed</fullName>
                <default>true</default>
                <label>Unprocessed</label>
            </value>
            <value>
                <fullName>Processed in SF</fullName>
            </value>
            <value>
                <fullName>Posted in Sage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Stripe_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_Amount__c</fullName>
    <description>This Field will Store the Payout Amount of the Stripe(Not in cents).</description>
    <label>Stripe Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Stripe_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Date__c</fullName>
    <description>This Field will store the Payout Date and Time on which payout is created on the Stripe</description>
    <label>Stripe Payout Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stripe_Payout_Log__c/fields/Stripe_Payout_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payout_Id__c</fullName>
    <description>This Field will store the Stripe Payout Id from the Stripe</description>
    <label>Stripe Payout Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PayoutWebhookWrapper.cls
/*
        Name        :   PayoutWebhookWrapper
        Author      :   Jatin
        Create Date :   10/02/2019
        Description :   This is a Wrapper Class for storing the webhook response from the stripe.
*/
public class PayoutWebhookWrapper {

    
	public Payoutdata data;

	class Payoutdata {
		public PayoutObject object_c;
	}

	class PayoutObject {
		public String id;	
		public String object_c;	
		public Double amount;	
		public Integer arrival_date;	
		public boolean automatic;
		public String balance_transaction;	
		public Long created;	
		public String currency_c;	
		public String description;	
		public String destination;	
		public String method;	
		public String source_type;
		public String status;	
		public String type;	
	}

	public static PayoutWebhookWrapper parse(String json){
        if(String.isNotBlank(json)){
            json = json.replaceAll('object', 'object_c');
            json = json.replaceAll('currency', 'currency_c');
        }
		return (PayoutWebhookWrapper) System.JSON.deserialize(json, PayoutWebhookWrapper.class);
	}

    public static Stripe_Payout_Log__c parseToStripePayoutLog(PayoutWebhookWrapper payoutObject, Boolean isDML,String organisationId){
        Stripe_Payout_Log__c payoutLogObject = new Stripe_Payout_Log__c();
        if(String.isNotBlank(payoutObject.data.object_c.id)){
            payoutLogObject.Stripe_Payout_Id__c = payoutObject.data.object_c.id;
            if(payoutObject.data.object_c.created > 0 && payoutObject.data.object_c.created != NULL){
                payoutLogObject.Stripe_Payout_Date__c = DateTime.newInstance(payoutObject.data.object_c.created * 1000);
            }
            if(payoutObject.data.object_c.amount > 0 && payoutObject.data.object_c.amount != NULL){
               payoutLogObject.Stripe_Payment_Amount__c = payoutObject.data.object_c.amount / 100;
            }
            payoutLogObject.Status__c = ConstantsClass.payoutStatusUnprocessed;
            //@@ Jatin :1-nov-2019: for add Organization Id 
            payoutLogObject.Organisation__c =organisationId;
        }
        if(isDML){
            try{
                INSERT payoutLogObject;
            }catch(exception e){
                RestContext.response.statusCode = 500;
            }
        }
        return payoutLogObject;
    }

}