force-app/main/default/objects/Home_Carousel__c/Home_Carousel__c.object-meta.xml
<CustomObject>
    <description>Used in Customer Portal and Mobile App 
To manage Home Page Events, Promotions etc.</description>
    <label>Home Carousel</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Home Carousel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Home_Carousel__c/fields/Sr_No__c.field-meta.xml
<CustomField>
    <fullName>Sr_No__c</fullName>
    <label>Sr. No</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>-None-</fullName>
                <default>true</default>
                <label>-None-</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Login</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomeCarouselUploadControllerTest.cls
@isTest
public class HomeCarouselUploadControllerTest {
	@isTest
    private static void test() {
        Home_Carousel__c newHomeCarouselObj = new Home_Carousel__c(Sr_No__c='1');
        insert newHomeCarouselObj;
        
        insertContentVersion('Title','test',Blob.valueOf('Unit Test Attachment Body'),TRUE);
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');
		ContentVersion objContent = insertContentVersion('content title','path',beforeblob,TRUE);
        insertContentDocumentLink(newHomeCarouselObj.id,objContent.ContentDocumentId,'V','AllUsers',TRUE);
        
        
        ContentVersion converObj = [SELECT id, ContentDocumentId FROM ContentVersion Limit 1];
        
        ContentDocumentlink ContentObj = new ContentDocumentlink(LinkedEntityId = newHomeCarouselObj.Id,ShareType = 'V',ContentDocumentId = converObj.ContentDocumentId);
        insert ContentObj;
        
        ContentDistribution ConDistObj = new ContentDistribution(Name = 'document',ContentVersionId = converObj.Id);
        insert ConDistObj;
                   	
        HomeCarouselUploadController.createProfileImage(newHomeCarouselObj.id,'Name',objContent.contentDocumentId);                             
    }
    
    public static ContentVersion insertContentVersion(String title , String clientPath, Blob versionData, Boolean isDML){
        ContentVersion cv = new ContentVersion(title = title,PathOnClient =clientPath,
                                               VersionData =versionData );
        if(isDML){
            try{
                insert cv;    
                cv = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
            }catch(Exception e){
                System.debug(e.getMessage());
            }
            
        }
        return cv;  
    }
    
     public static ContentDocumentLink insertContentDocumentLink(String parentId,String documentId, String shareType,String visibility,Boolean isDML){
        ContentDocumentLink objDocLink = new ContentDocumentLink(LinkedEntityId = parentId,ContentDocumentId=documentId,
                                                                 ShareType = shareType,Visibility = visibility);
        try{
            if(isDML){
                insert objDocLink;
            }   
        }catch(Exception e){
            System.debug('in catch');
            System.debug(e.getMessage());
        }
        return objDocLink;
    }
    
}