force-app/main/default/objects/ReferAFriendEmail__mdt/ReferAFriendEmail__mdt.object-meta.xml
<CustomObject>
    <label>ReferAFriendEmail</label>
    <pluralLabel>ReferAFriendEmails</pluralLabel>
</CustomObject>

force-app/main/default/objects/ReferAFriendEmail__mdt/fields/EmailBody__c.field-meta.xml
<CustomField>
    <fullName>EmailBody__c</fullName>
    <label>EmailBody</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ReferAFriendEmail__mdt/fields/EmailSubject__c.field-meta.xml
<CustomField>
    <fullName>EmailSubject__c</fullName>
    <label>EmailSubject</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RAFEmailContentAPI.cls
@RestResource(urlMapping='/rafemailcontentservice/*')

global class RAFEmailContentAPI {  
    @HttpGet
    global static ReferAFriendEmail__mdt getRAFEmailContent() {
        RestRequest req = RestContext.request;
        ReferAFriendEmail__mdt rafEmail = [SELECT EmailBody__c, EmailSubject__c from ReferAFriendEmail__mdt WHERE MasterLabel =: 'Email'][0];
        //RestResponse res = RestContext.response;
       // res.responseBody =  Blob.valueOf(JSON.serialize(attachmentData));
        return rafEmail;
    }   
}