force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RecallLeaveRequestOnCancelTest.cls
@isTest
private class RecallLeaveRequestOnCancelTest {

    private static testMethod void doTest() {
        
        Test.startTest();
        String recordTypeId = Schema.SObjectType.Leave_Request__c.getRecordTypeInfosByName().get('Paid Leave').getRecordTypeId();
        Date startDate = Date.newInstance(2020, 01, 13);
        Date endDate = Date.newInstance(2020, 01, 15);
        Leave_Request__c leaveReqObj = new Leave_Request__c(Leave_Start_Date__c = startDate,Leave_End_Date__c = endDate,status__c = 'Draft',recordtypeid = recordTypeId);
        insert leaveReqObj;
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();  
        req.setComments('Submitting approval request using in test');        
        req.setObjectId(leaveReqObj.id);        
        Approval.ProcessResult result = Approval.process(req);  
        List<String> leaveIds = new List<String>();
        leaveIds.add(leaveReqObj.id);
        RecallLeaveRequestOnCancel.recallLeaveRequest(leaveIds);
        //Leave_Request__c updateLeave = new Leave_Request__c(id=leaveReqObj.id,status__c='Cancelled');
        //update updateLeave;        
        //System.assert(updateLeave.status__c=='Cancelled');
        Test.stopTest();

    }
}