force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Calendar_Update_Process__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Update_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Calendar Update Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher,Employee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leave Requests</relationshipLabel>
    <relationshipName>Leave_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_End_Date__c</fullName>
    <label>Leave End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Leave_Start_Date__c</fullName>
    <label>Leave Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Sick_leave_start_Time__c.field-meta.xml
<CustomField>
    <fullName>Sick_leave_start_Time__c</fullName>
    <label>Sick leave start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Request__c/recordTypes/Child_Care_Leave.recordType-meta.xml
<RecordType>
    <fullName>Child_Care_Leave</fullName>
    <active>true</active>
    <label>Child Care Leave</label>
</RecordType>

force-app/main/default/objects/Leave_Request__c/recordTypes/Extended_Child_Care_Leave.recordType-meta.xml
<RecordType>
    <fullName>Extended_Child_Care_Leave</fullName>
    <active>true</active>
    <label>Extended Child Care Leave</label>
</RecordType>

force-app/main/default/objects/Leave_Request__c/recordTypes/NSMen_Leave.recordType-meta.xml
<RecordType>
    <fullName>NSMen_Leave</fullName>
    <active>true</active>
    <label>NSMen Leave</label>
</RecordType>

force-app/main/default/objects/Leave_Request__c/recordTypes/Other_Leave.recordType-meta.xml
<RecordType>
    <fullName>Other_Leave</fullName>
    <active>true</active>
    <label>Other Leave</label>
</RecordType>

force-app/main/default/objects/Leave_Request__c/recordTypes/Paid_Leave.recordType-meta.xml
<RecordType>
    <fullName>Paid_Leave</fullName>
    <active>true</active>
    <label>Paid Leave</label>
</RecordType>

force-app/main/default/classes/LeaveRequestScheduler.cls
global class LeaveRequestScheduler implements Schedulable {
    // Scheduler is called basically when leave start date is either less than 35 or is 35 and recordtype is any of the (Paid_Leave,Child_Care_Leave,Extended_Child_Care_Leave,Other_Leave,NSMen_Leave) 
   global void execute(SchedulableContext sc) {
       Id paidRecordTypeId = Schema.SObjectType.Leave_Request__c.getRecordTypeInfosByDeveloperName().get('Paid_Leave').getRecordTypeId();
       Id childkRecordTypeId = Schema.SObjectType.Leave_Request__c.getRecordTypeInfosByDeveloperName().get('Child_Care_Leave').getRecordTypeId();
       Id extendedRecordTypeId = Schema.SObjectType.Leave_Request__c.getRecordTypeInfosByDeveloperName().get('Extended_Child_Care_Leave').getRecordTypeId();    
       Id otherRecordTypeId = Schema.SObjectType.Leave_Request__c.getRecordTypeInfosByDeveloperName().get('Other_Leave').getRecordTypeId();
       Id nationalServiceRecord = Schema.SObjectType.Leave_Request__c.getRecordTypeInfosByDeveloperName().get('NSMen_Leave').getRecordTypeId();
       List<Leave_Request__c> leaveReqList = new List<Leave_Request__c>();
       for(Leave_Request__c leaveObj : [SELECT Id,Leave_End_Date__c,Sick_leave_start_Time__c,Employee__c,Calendar_Update_Process__c,Status__c,Leave_Start_Date__c,RecordTypeId FROM Leave_Request__c where Status__c ='Approved' and Calendar_Update_Process__c =false and Leave_Start_Date__c>=today order by Leave_Start_Date__c Asc]){ 
         
           if(System.today().daysBetween(leaveObj.Leave_Start_Date__c) <=  Integer.valueOf(Label.Leave_Minimum_Due_No)  && (leaveObj.RecordTypeId==nationalServiceRecord || leaveObj.RecordTypeId==paidRecordTypeId || 
                                                                                  leaveObj.RecordTypeId==childkRecordTypeId || leaveObj.RecordTypeId==extendedRecordTypeId ||
                                                 								  leaveObj.RecordTypeId==otherRecordTypeId)){
               leaveReqList.add(leaveObj);
			   break;
           } 
       }
       if(leaveReqList.size()>0){
          LeaveRequestHelper.sickLeave(leaveReqList); 
       }
   }
}